### ISSUE TITLE
Clang support

### ISSUE THREAD

**Issue by letmaik** [microsoft/onnxruntime#1025]
Is there interest to add official support for Clang? Adding it to the CI build matrix would be useful to keep track of any Clang-related issues.

**Comment by pranavsharma** [comment]
There are no plans currently to add clang support. If there is enough interest we can reconsider this. Thanks!

**Comment by xkszltl** [comment]
@pranavsharma 
++interest

**Comment by letmaik** [comment]
For what it's worth, ONNX RT compiles just fine with Clang (`CC=clang CXX=clang++`) so this is mostly a matter of adding it to CI and making sure not to introduce breaks.

**Comment by xkszltl** [comment]
@letmaik
A few question about your setup:
  1. Which linker, ld or lld (-fuse-ld=lld)?
  2. libc++ or libstdc++?
  3. Which version of llvm?

Thanks

**Comment by letmaik** [comment]
ld, libc++, llvm 7

**Comment by xkszltl** [comment]
> ld, libstdc++, llvm 7

Thanks for the quick response

**Comment by zahiraam** [comment]
@letmaik, @xkszltl 
This is not quite the experience I had. 
On Linux when building shared libraries using this command:

./build.sh --config RelWithDebInfo --build_shared_lib --use_dnnl

With clang 15.0.0 , I got a build error:

onnxruntime-new/onnxruntime/include/onnxruntime/core/common/make_string.h:46:3: note: in instantiation of function template specialization 'onnxruntime::detail::MakeStringImpl<const char *, unsigned long, const char *, long, const char *, gsl::span<long>>' requested here
  MakeStringImpl(ss, args...);
  ^
onnxruntime-new/onnxruntime/include/onnxruntime/core/common/make_string.h:93:18: note: in instantiation of function template specialization 'onnxruntime::detail::MakeStringImpl<const char *, unsigned long, const char *, long, const char *, gsl::span<long>>' requested here
  return detail::MakeStringImpl(detail::if_char_array_make_ptr_t<Args const&>(args)...);
                 ^
onnxruntime-new/onnxruntime/onnxruntime/core/providers/dnnl/subgraph/dnnl_reduce.cc:276:11: note: in instantiation of function template specialization 'onnxruntime::MakeString<char[20], unsigned long, char[23], long, char[9], gsl::span<long>>' requested here
          ORT_ENFORCE(src_dims[i] == 1, "Dimension of input ", i, " must be 1 instead of ", src_dims[i],
          ^
onnxruntime-new/onnxruntime/include/onnxruntime/core/common/common.h:182:64: note: expanded from macro 'ORT_ENFORCE'
                                                ::onnxruntime::MakeString(__VA_ARGS__)); \
                                                               ^
onnxruntime-new/onnxruntime/onnxruntime/core/providers/dnnl/subgraph/dnnl_subgraph_primitive.h:130:22: note: 'operator<<' should be declared prior to the call site or in namespace 'gsl'
inline std::ostream& operator<<(std::ostream& os, const gsl::span<int64_t>& span) {
                     ^
1 error generated.

This issue is related to unqualified lookup templates. This is a common issue documented here: [Language Compatibility (llvm.org)](https://clang.llvm.org/compatibility.html#dep_lookup) It describes invalid code that GCC allows but not clang. It also offers two solutions which I adapted to onnxruntime. 

Making this change:

diff --git a/onnxruntime/core/providers/dnnl/subgraph/dnnl_subgraph_primitive.h b/onnxruntime/core/providers/dnnl/subgraph/dnnl_subgraph_primitive.h
--- a/onnxruntime/core/providers/dnnl/subgraph/dnnl_subgraph_primitive.h
+++ b/onnxruntime/core/providers/dnnl/subgraph/dnnl_subgraph_primitive.h
@@ -127,10 +127,13 @@ inline std::ostream& operator<<(std::ostream& os, const gsl::span<const int64_t>
   return os;
 }
 
+}  // namespace onnxruntime
+
+namespace gsl {
 inline std::ostream& operator<<(std::ostream& os, const gsl::span<int64_t>& span) {
   std::copy(span.cbegin(), span.cend(), std::ostream_iterator<int64_t>(os, " "));
   return os;
 }
 
-}  // namespace onnxruntime
+}  // namespace gsl

Fixes the issue. With clang onnxruntime is building and running.

Is MS willing to make changes to the code in order to fix build errors with other compilers? The above change is certainly offering a more valid code.

We also have encountered several issues with the Intel compiler that are all related to implicit instantiation of function templates. Adding explicit instantiation of these functions fixed the issues. 
The difference of behavior between the Intel compiler and other compilers for these function templates is that they are being inlined with the Intel compiler (and therefore their definitions are discarded and any reference to them will result into undefined symbols at link time). Other compilers might not be inlining these functions and are therefore not encountering the link errors.
Has anyone seen these issues? Any comments welcome.
Thanks.

**Comment by zahiraam** [comment]
@[pranavsharma](https://github.com/pranavsharma)

**Comment by DaydreamCoding** [comment]
#include "core/framework/tensor_shape.h"

at first line of dnnl_reduce.cc file
