### ISSUE TITLE
what is the right way to convert `ortValue`  to `torch.tensor` for GPU?

### ISSUE THREAD

**Issue by Ki6an** [microsoft/onnxruntime#10327]
Hi, I'm working on making [fastT5](https://github.com/Ki6an/fastT5) support GPU, the library implements huggingface's `generate()` method to produce the output tokens. so most of this pipeline is in PyTorch (you can look into [this file](https://github.com/Ki6an/fastT5/blob/master/fastT5/onnx_models.py) to know how it's done for CPU).  I'm using `io-binding` to avoid copying data btw CPU and GPU for running the model on onnxruntime with CUDA EP.  

The inputs to ort are provided as torch tensors so binding them is fast and easy as `io_binding.bind_input()`  takes `tensor.data_ptr()` as input and also the input shapes are known. 

for outputs, I used `io_binding.bind_output()` and provided only the `name` and `device` since we don't know the output shape or data_ptr. we can pre-create tensors (by precalculating the tensor shape ) to store output but it can become cumbersome as t5 creates large numbers of outputs with different shapes.

so I chose `io_binding.get_outputs()` to get the outputs, now, the outputs are provided as `outvalues`, in order to convert them to tensor we have to first convert them to numpy,  using `torch.from_numpy(ort_output.numpy()).to(device)`. this conversion process is affecting the inference speed significantly as there are lots of outputs to work with and also in a loop.

```js
tt to ort.run:1730.759693000664 ms, tt ortValue to torch tensor:2520.3441690007367 ms, total time:4882.381090000081 ms   
```
as you can see the conversion process is taking a lot of time, is there a better and more efficient way to convert outvalues to torch tensor?
maybe not using numpy as an intermediate step?

any help would be appreciated

**Comment by yuslepukhin** [comment]
Since you can not pre-allocate tensor on GPU ahead of time, you will need to deal with GPU memory that ORT allocates on output. To gain access to that memory, call `data_ptr()` on the corresponding output OrtValue which would be a pointer to that buffer on a GPU device.  You can obtain the shape by calling `shape()`. You can then decide what to do with it.

**Comment by Ki6an** [comment]
thank you for the response, ik this is not related to onnxruntime but do you know how to create a torch tensor from a data pointer. 

after some searching, I found that using [dlpack ](https://github.com/microsoft/onnxruntime/issues/4162) is a plausible workaround.

https://github.com/microsoft/onnxruntime/blob/50ae97a8bd5184915f2bb2e81727f05770d74d9f/orttraining/orttraining/python/training/ortmodule/_utils.py#L13-L18

I think it is available only in the `onnxruntime-training` library. are there any plans on including it in the `onnxruntime-gpu`?

**Comment by brevity2021** [comment]
Hi @Ki6an, thanks for the question & answer. I am facing the same issue (`torch.from_numpy(ort_output.numpy()` is too slow) and wonder whether the dlpack workaround still works. I'm using Onnxruntime 1.11.1 and it seems that `OrtValue` does not have the `to_dlpack` API. Thanks!

**Comment by brevity2021** [comment]
> Hi @Ki6an, thanks for the question & answer. I am facing the same issue (`torch.from_numpy(ort_output.numpy()` is too slow) and wonder whether the dlpack workaround above still works. I'm using Onnxruntime 1.11.1 and it seems that `OrtValue` does not have the `to_dlpack` API. Thanks!

I was able to use the following code:
Install the package: `pip install onnxruntime-training==1.11.1` 

```from onnxruntime.training.ortmodule._utils import _ortvalue_to_torch_tensor
# x is an ortvalue
device=torch.device('cuda')
a =_ortvalue_to_torch_tensor( x._ortvalue,  device)```
Is that the way you used it?

However, in my case the running/conversion time ratio seems not as big as yours, the running time/conversion time is 1000:1 in my case (when using `torch.from_numpy`. using the _ortvalue_to_torch_tensor reduces the conversion time to 1/5).

**Comment by Ki6an** [comment]
@brevity2021  if you are able to use both `onnxruntime-gpu` and `onnxruntime-training` libraries at the same time after installing them from pip?  

then yes, import it as `from onnxruntime.training.ortmodule._utils import _ortvalue_to_torch_tensor` and use it as you've shown.

> However, in my case the running/conversion time ratio seems not as big as yours, the running time/conversion time is 1000:1 in my case (when using torch.from_numpy. using the _ortvalue_to_torch_tensor reduces the conversion time to 1/5).

glad you were able to reduce the conversion time,
re: running/conversion ratio: I think it depends on the model you are running. That was for the t5 model, and  I was converting the pkvs (around 24 large tensors) to torch.tensors.

**Comment by rajhans** [comment]
Are there any updates on the ability to convert from OrtValue to torch.Tensor (presumably via dlpack) during inference? I am running into the same issue when running a T5 model while trying to avoid a copy to the CPU. Using ONNXRuntime with conversion to numpy (using HF's optimum since [this PR](https://github.com/huggingface/optimum/pull/199) is merged) is 2x slower than just vanilla HF transformer on a v100 gpu.

I tried the suggestion here, but installing from source is not an ideal experience for deployment and is brittle: https://github.com/microsoft/onnxruntime/issues/10286#issuecomment-1013477686

**Comment by brevity2021** [comment]
Unfortunately, even the `_ortvalue_to_torch_tensor` is no longer in the onnxruntime-training package. This has been moved to OnnxRuntime but `to_dlpack` is only exposed when training is enabled.[[link](https://github.com/microsoft/onnxruntime/blob/86c5c07ea419b935541d0abd2a16bf204e19c6ed/onnxruntime/python/onnxruntime_pybind_ortvalue.cc#L282)]. Is there any plan to expose this at the inference time also?

**Comment by baijumeswani** [comment]
`ortvalues_to_torch_tensor` is still [available in `onnxruntime-training`](https://github.com/microsoft/onnxruntime/blob/86c5c07ea419b935541d0abd2a16bf204e19c6ed/orttraining/orttraining/python/training/ortmodule/_utils.py#L66).

Example on how to use it can be found [here](https://github.com/microsoft/onnxruntime/blob/86c5c07ea419b935541d0abd2a16bf204e19c6ed/orttraining/orttraining/python/training/ortmodule/_training_manager.py#L166).

**Comment by brevity2021** [comment]
thanks @baijumeswani . But the above requires `OrtValueVector` instead of `OrtValue`. They seem very similar, wonder why we can only use `OrtValueVector`.

**Comment by baijumeswani** [comment]
`OrtValueVector` is a vector of `OrtValue`s. Definition can be found here: https://github.com/microsoft/onnxruntime/blob/86c5c07ea419b935541d0abd2a16bf204e19c6ed/onnxruntime/python/onnxruntime_pybind_ortvalue.cc#L307.

If you only care about single `OrtValue`, just add a single value to the vector, and call `_ortvalues_to_torch_tensor` above.

**Comment by brevity2021** [comment]
Thank you @baijumeswani ! I know we can create a vector, but am just trying to understand the reason of not being able to use `OrtValue`. It sounds like just an additional API exposure.
I have this need to convert the IOBinding output (which is an `OrtValue`) to tensor for speeding up the inference, so hopefully, I can have as few additional steps as possible. 
So just trying to understand whether this is intentional (some reason behind it), or this is something we could expect to fix in the future. Thanks!

**Comment by baijumeswani** [comment]
@brevity for training purposes, we never had the explicit requirement to convert a single ortvalue to tensor. We had to work with converting an unknown number of torch tensors to and from ortvalues. We initially performed this conversion one tensor at a time by looping over the torch tensors and calling `_ortvalue_to_torch_tensor` on them.

But after PR #11176, we removed this function and started using `_ortvalues_to_torch_tensor`. This is intentional.

For the functionality you're looking for (to convert a single `OrtValue`), I am not sure if that is in the works. In his PR, @xadupre asks this question:
> Second item which I leave open for discussion: should we also enable the implementation of DLPack protocol in onnxruntime and not only in onnxruntime-training? Since November last year, numpy implements DLPack protocol. It was introduced in 0.22.

I am not sure if he found any answer to this question yet.

For the time being, please use `_ortvalues_to_torch_tensor`.

**Comment by brevity2021** [comment]
Thank you for the explanation. I believe for the original [post](https://github.com/microsoft/onnxruntime/issues/10327#issue-1108641603) and this [reply](https://github.com/microsoft/onnxruntime/issues/10327#issuecomment-1205657944) we are all more interested in the use case that converts the IOBinding output OrtValue to tensor, not training.

The reason we need this: especially for text generation models, we need to call onnxruntime inference multiple times for the autoregressive decoding process. This is typically run on GPU and we would like the tensor to stay there. Generally the previous call's output will be the next call's input. If OrtValue needs to be converted to CPU then converted back for the next inference call (for the next step of generation), it will be very slow. We need a way to convert to the tensor on GPU, without copying to CPU due to numpy.

Installing both `onnxruntime-gpu` and `onnxruntime-training` can have issues. I've seen the same error as described in this [issue](https://github.com/microsoft/onnxruntime/issues/9754), after installing both `onnxruntime-gpu` and `onnxruntime-training` by pip. (these two replies [1](https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-978198118) [2](https://github.com/microsoft/onnxruntime/issues/9754#issuecomment-1098097912) report the same thing). Plus for the inference we don't really need `onnxruntime-training` except for this function. This creates concerns when using onnxruntime in production for this instability. Ideally, we only want one library for our inference code.

I believe moving OrtValue->torch.Tensor to Onnxruntime will benefit people with such use cases and save people time to seek workarounds or alternatives. @baijumeswani @xadupre can we consider that?

**Comment by xadupre** [comment]
numpy implemented the dlpack protocol: https://numpy.org/devdocs/reference/generated/numpy.from_dlpack.html#numpy.from_dlpack. It will be released in 1.24, probably at the end of this year. I guess it makes sense to enable it in onnxruntime.

**Comment by pranavsharma** [comment]
There's no reason to do any conversion. Please look for "You can also bind inputs and outputs directly to a PyTorch tensor." on this page https://onnxruntime.ai/docs/api/python/api_summary.html.

**Comment by xadupre** [comment]
We could but dlpack is also about transferring the ownership of the data. So when a torch tensor is created through the dlpack protocol, torch becomes responsible for its deletion as well. Without the protocol, the buffer hosting the data needs to remain alive. The user has to be aware of that. The data may stay in memory longer than needed.

**Comment by baijumeswani** [comment]
Closing this issue now. Thanks for the inputs @pranavsharma, @xadupre, @brevity2021

**Comment by vadimkantorov** [comment]
@justinchuby Is there a plan for providing direct `_ort_value_from_dlpack` as well?

This would allow to drop going through NumPy in `torch.onnx` in:
 
https://github.com/pytorch/pytorch/blob/ff83f53486e2b9f94b2ed7039efe22f80a25e009/torch/onnx/_internal/exporter/_onnx_program.py#L153-L154

- https://github.com/pytorch/pytorch/pull/159177

**Comment by vadimkantorov** [comment]
It also appears that bool dtype was added to dlpack: https://github.com/dmlc/dlpack/pull/114

https://github.com/microsoft/onnxruntime/blob/ff83f53486e2b9f94b2ed7039efe22f80a25e009/onnxruntime/core/dlpack/dlpack_converter.cc#L45-L49

**Comment by vadimkantorov** [comment]
Or is it now available under `OrtValue.from_dlpack(...)`?

https://github.com/microsoft/onnxruntime/blob/ecc358f069488a79c5abc16c5ddfbc4bd5b3c771/onnxruntime/python/onnxruntime_pybind_ortvalue.cc#L406

**Comment by justinchuby** [comment]
@snnn is working on a renewed dlpack support. Do you have anything to share? Thanks @snnn
