### ISSUE TITLE
call for Vulkan support

### ISSUE THREAD

**Issue by znsoftm** [microsoft/onnxruntime#10603]
For the most of OSs, vulkan can support acceleration of computing operations, the best choice of EP is vulakn. So any possibility?

**Is your feature request related to a problem? Please describe.**
just a new feature.

**System information**
- ONNX Runtime version (you are using):

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
For the most of OSs, vulkan can support acceleration of computing operations, the best choice of EP is vulakn. So any possibility?

**Comment by fuhengwu2021** [comment]
What do you mean `the best choice of EP is vulakn`? @znsoftm

**Comment by hariharans29** [comment]
Dupe of https://github.com/microsoft/onnxruntime/issues/8295.

**Comment by hariharans29** [comment]
Hi @znsoftm

Just for our education, can you expand on what value a Vulkan EP will add alongside the existing GPU EPs in ORT:

1) CUDA EP and TensorRT EP (for Nvidia cards)
2) ROCM EP and MiGraphix EP (for AMD cards)
3) DirectML EP for the Windows platform

**Comment by pranavsharma** [comment]
cc @manashgoswami

**Comment by siegelaaron94** [comment]
@hariharans29 Because of macOS (via MoltenVK) we are currently using CoreML and Apple is just too slow to add features and it is limiting us. They are constantly breaking CoreML with the macOS 12.3 update they broke permute on 6-D tensors (using to get around the lack of pixel unshuffle) but only on M1 (x64 and macOS < 12.3 are fine). I wouldn't mind putting in some of the leg work to get this feature started.

**Comment by znsoftm** [comment]
Thanks for all of your replies.

In a special situation, there is no Windows ( no directML),  no Nvidia (no CUDA), no AMD (no ROCM), but there is a GPU other than listed above and can support vulkan,  if it supports vulkan, such as macos/ios  it can be accelerated by a  GPU.

**Comment by znsoftm** [comment]
Thanks for all of your replies.

In a special situation, there is no Windows ( no directML),  no Nvidia (no CUDA), no AMD (no ROCM), but there is a GPU other than listed above and can support vulkan,  if it supports vulkan, such as macos/ios  it can be accelerated by a  GPU.

**Comment by DavidDohmen** [comment]
Just to add to this: 
Running linux with a Intel CPU/GPU, a Vulkan backend would also be highly appreciated! None of the existing options (CUDA/ROCM/DirectML) work here.

**Comment by OrsoEric** [comment]
It's 2026, and still I can't run ONNX runtime with Vulkan acceleration on 760m iGPU

AMD ROCm acceleration is still not available and mostly experimental

Vulkan acceleration is fairly competent

**Comment by jeffrey-cochran** [comment]
> It's 2026, and still I can't run ONNX runtime with Vulkan acceleration on 780m iGPU
> 
> AMD ROCm acceleration is still not available and mostly experimental
> 
> Vulkan acceleration is fairly competent

The first person who used my ONNX-based application made the exact same request for the exact same reason.

Would be very cool to support Vulkan as an EP.

**Comment by partizanna** [comment]
ML on Vulkan got really great, often rivaling ROCm, while avoiding 25GB of ROCm packages in docker images.  
Also providing support for many Vulkan capable HW platforms which are neglected by direct manufacturer driver support, while also allowing for easy cross HW vendor support - under Vulkan its easy to run a mix of GPUs like Intel + NV + AMD.

**Comment by inonitz** [comment]
Sorry for necroing a somewhat dead thread.
I took a quick look at the work people have done on WebGPU - I'm aware that this the effective replacement for vulkan, but I still think a dedicated Execution Provider for vulkan would perform better & would be widely used, especially on low-end hardware that doesn't have access to the greatest & latest compute software & hardware respectively. llama.cpp is a good example of this.

I'd love to work on a Vulkan EP but honestly don't know where to look / help. I can fill many gaps in my knowledge using existing documentation & LLM's but I am not even sure where to begin. Would love some pointers or references to work people have already began.

**Comment by OrsoEric** [comment]
> I'm aware that this the effective replacement for vulkan

It isn't, I spent weeks on it, to no avail. WebGPU falls back to low performance DirectX, or worse WebGL or OpenGL, or worse CPU under windows. Perhaps under Linux they work better, but last time I checked, Windows was made by... Microsoft... And it's another abstraction layer on top of all other abstraction layers, making it more likely the function you need isn't accelerated or has low preformance generics. It doesn't help ONNX models arent common, and most of what you find aren't well made. Like for LLMs the KV cache should be inside the ONNX graph to have better chance at being accelerated and not swapping to RAM like crazy. 

> I'd love to work on a Vulkan EP but honestly don't know where to look / help.

I reckon it's more value adding to contribute to [llama.cpp/Vulkan,](https://github.com/ggml-org/llama.cpp) and more recently, [sd.cpp/Vulkan. ](https://github.com/leejet/stable-diffusion.cpp)Those are direct bindings from models to Vulkan runtime, avoiding the additional abstraction layers.

Probably the ONLY scenarios where those runtime are slower is for CUDA/Nvidia, because CUDA is the GOAT. And for devices for which Vulkan is outdated or bound hapazardly to the underlying ALUs.

The degree to which Vulkan outperforms other runtimes is cartoonish... 

The selling point of ONNX is that it avoids the ludicrous pytorch dependencies and at times all the extra files gguf and safetensor at time needs. But the performance you give up for that portability makes it a non starter. 

The ONLY way ONNX becomes widespread, is if Microsoft makes proper ONNX/Vulkan bindings, and takes ccare to release high performance ONNX models of open source text, image, audio and 3D models as they come out.

The opposite is happening. E.g. Microsoft has the great Trellis 2, and it's dependencies are so deeply baked with pytorch/CUDA that it's nearly impossible to run it on even bare CPU. Microsoft didn't care enough to release Trellis 2 ONNX.

And if Microsoft isn't releasing first party open models on that, the ONNX runtime is dead and gone.

**Comment by inonitz** [comment]
> I reckon it's more value adding to contribute to [llama.cpp/Vulkan,](https://github.com/ggml-org/llama.cpp) and more recently, [sd.cpp/Vulkan. ](https://github.com/leejet/stable-diffusion.cpp)Those are direct bindings from models to Vulkan runtime, avoiding the additional abstraction layers.

Sure, but that was not my use-case - I'm well aware of these and have already found plenty of use for them, see the LocalLLama subreddit for instance. Essentially I needed to run YOLO26 Nano Models with C++ & ROS2 for a pretty constrained low-end laptop & inside a pretty big system. Honestly converting an ultralytics model from `.pt` => `.onnx` was painless & using [YOLOs-CPP](https://github.com/Geekgineer/YOLOs-CPP) was the exact solution to my problem. Of course, I'm now stuck with Onnxruntime until I find a better alternative, which is unfortunately not trivial to come by. Its almost as if people have requested this feature for years to no avail...
