### ISSUE TITLE
C++ inference with DirectML: ERROR: Dimensions of the View are invalid.

### ISSUE THREAD

**Issue by wojtuss** [microsoft/onnxruntime#10708]
**Describe the bug**
Following the issue https://github.com/microsoft/onnxruntime/issues/10279 and the sanity test app there (https://github.com/microsoft/onnxruntime/issues/10279#issuecomment-1018928665) I wrote an app, which runs inference on a given onnx model. For most of my models it works fine. However, for some of them I get the following error:
```
D3D12 ERROR: ID3D12Device::CreateUnorderedAccessView: The Dimensions of the View are invalid due to at least one of the following conditions. Assuming StructureByeStride 4, FirstElement (value = 935854080) must be between 0 and the maximum offset of the Buffer, 1073741823, inclusively. With the current FirstElement, NumElements (value = 267386880) must be between 1 and 137887744, inclusively, in order that the View fit on the Buffer. [ STATE_CREATION ERROR #345: CREATEUNORDEREDACCESSVIEW_INVALIDDIMENSIONS]
```

Sometimes an fp16 model converted from fp32 (using `convert_float_to_float16` from `onnxmltools.utils.float16_converter`) runs fine without the above error, while the fp32 model throws the error.
Sometimes the same model with smaller input [1, 3, 1080, 1920] works fine, but with input [1, 3, 2160, 3840] fails as above.

Narrowing down I came to the point where
```
m_bindingTable->BindTemporaryResource(&tempBindingDesc);
```
in `onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\FusedGraphKernel.cpp` throws the above error. I couldn't go deeper without debug symbols.

Could you please give me some hints, where the problem can be and how to fix it?

**Urgency**
High, this issue impedes progress in optimizing a product.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro
- ONNX Runtime installed from (source or binary): source, (0d9030e79888d1d5828730b254fedc53c7b640c1) with changes from https://github.com/microsoft/onnxruntime/commit/e1012a8662585b730ba1973450f1c7e0911735d5.
- ONNX Runtime version:  v1.10.1
- Python version: 3.8.10
- Visual Studio version (if applicable): Community 2019, Version 16.11.9
- GCC/Compiler version (if compiling from source): MSVC 14.29.30133, x64
- CUDA/cuDNN version: - 
- GPU model and memory: AMD Radeon RX 6800 XT, 16GB
- Windows SDK version 10.0.20348.0

**To Reproduce**
The application is based on the code https://github.com/microsoft/onnxruntime/issues/10279#issuecomment-1018928665 by @fdwr 

**Expected behavior**
Execution without errors.

**Comment by fdwr** [comment]
@wojtuss I don't have the answer (asking some teammates more familiar with D3D UAV limits and the graph code...), but it seems the graph is trying to coalesce tensors and allocate more than a 1GB of GPU memory in a single view. Thanks for the D3D debug layer output, which helps.

In the meantime, since you are building from source, if you temporarily hack `AbiCustomRegistry::RegisterOperatorKernel()` `supportsGraph=false` or split the graph by setting one of the operators used in the graph to `DmlGraphSupport::Supported` in OperatorRegistration.cpp, does the issue still repro for you? (to be clear, that's *not* a fix, and it will hinder perf, but it's useful for the data point)

**Comment by fdwr** [comment]
Does this happen only when the debug layer is on, or when disabled too? There was an issue with the D3D debug layer on older Windows (<=2019-03-06) rejecting >4GB tensors, but actually it worked fine if you disabled the debug layer or suppressed that specific debug layer error.

**Comment by wojtuss** [comment]
@fdwr 
Thank you. The error occurs even when debug layer is off.
To supplement the description, my models accepts three inputs of size [1, 3, h, w], and outputs one tensor [1, 3, h, w]. When hxw is 4K, for some models the error occurs, and for others do not, still with fp32 data type. For 4K size VRAM utilization is around 15 GB, for FHD there is plenty of free memory.

I have forcefully set `supportsGraph=false` in `AbiCustomRegistry::RegisterOperatorKernel()` and the previously failing models started to run OK.

**Comment by fdwr** [comment]
>for 4K input size VRAM utilization is around 15 GB
If your Radeon RX 6800 XT only has 16GB, and other processes need GPU memory too, including the DWM (Desktop Window Manager) and other open apps (particularly web browsers), which on my machine is about 200MB's, then when combined with possible memory fragmentation, that's concerningly near the edge. :/

Looking at `ExecuteReusableCommandList`, I'm surprised it even reaches the `BindTemporaryResource` rather than failing earlier at `contextWrapper.AllocateTemporaryData(...)` (which calls `BucketizedBufferAllocator::Alloc` and ultimately `m_device->CreateCommittedResource`), if there was a memory allocation issue. Do you recall the `execBindingProps.TemporaryResourceSize` value? Was it huge?

> Indeed, the patch affected the performance, latencies have doubled, at least.
Yeah, each ORT graph node's operator is called separately in that case rather than being fused into a single large DML_GRAPH node which can apply optimizations (e.g. eliminate redundant copies, remove identities, slice/join directly in place...). So not a solution, but thank for you the confirmation.

I presume this is a proprietary model that cannot be shared, but if you have other non-proprietary models that repro the issue or with zeroed weights that don't expose IP (e.g. [this tool](https://github.com/fdwr/ConvertOnnxModel/) `ConvertOnnxModel -zeromodelvalues input.onnx output.onnx`), that would be helpful.

**Comment by wojtuss** [comment]
> Do you recall the `execBindingProps.TemporaryResourceSize` value? Was it huge?
Yes, it was 2,281,725,696 at the point where `m_bindingTable->BindTemporaryResource(&tempBindingDesc);` was called
![image](https://user-images.githubusercontent.com/19307410/156534734-6c0b3fbd-25e8-4adf-869f-788505476675.png)

> I presume this is a proprietary model that cannot be shared, but if you have other non-proprietary models that repro the issue or with zeroed weights that don't expose IP (e.g. [this tool](https://github.com/fdwr/ConvertOnnxModel/) `ConvertOnnxModel -zeromodelvalues input.onnx output.onnx`), that would be helpful.

True. I will look for another model with reproduction.

**Comment by wojtuss** [comment]
@fdwr , do you have any idea about where the problem can be?

**Comment by fdwr** [comment]
@wotjuss: Sorry, without a repro, I cannot know for sure. GPU VA memory fragmentation still seems a likely issue (or we could also have a latent bug overflowing a uint32 somewhere 🤔).

**Comment by fdwr** [comment]
We have some pending changes for DML 1.9 (expecting release ~next week https://www.nuget.org/packages/Microsoft.AI.DirectML/) that hopefully address your private model, finding a few spots using uint32 rather than uint64. 🤞

**Comment by nums11** [comment]
Closing as resolved.
