### ISSUE TITLE
Why onnxruntime does not support parallel execution mode of CUDA?

### ISSUE THREAD

**Issue by ZinuoCai** [microsoft/onnxruntime#10730]
Hello everyone! I wonder why onnxruntime does not support parallel execution mode of CUDA. There seems no bug when I allow kernels to execute in parallel.

**Comment by RyanUnderhill** [comment]
It can deadlock when running and since common big OPs are typically internally parallel (especially with CUDA) there's not a real benefit to running multiple OPs in parallel. Some specially parallel crafted models did show some noticeable gains but it was more worth it for us to improve of individual ops so far.
