### ISSUE TITLE
Unstable behavior in CUDA EP

### ISSUE THREAD

**Issue by rakib-hasan** [microsoft/onnxruntime#10955]
**Describe the bug**
ORT CUDA EP produces different results for the same input.

**Urgency**
Hopefully before ORT 1.11.0 is released since the issue seems to be present in rel-1.11.0 branch.

**System information**
- TensorRT 22.02 docker container on an Ubuntu 18.04 system.
- ONNX Runtime installed from: Source.
- ONNX Runtime version: 1.11.0 (still in development)
- Python version: 3.8.10
- GCC/Compiler version (if compiling from source): gcc 9.3.0
- CUDA/cuDNN version: CUDA 11.6
- GPU model and memory: NVIDIA TITAN V (V100) 12GB

**To Reproduce**

1. Put the attached executable and the onnx model in some directory e.g. $HOME/testing
2. Start a TensorRT docker container from that directory (i.e. $HOME/testing): `docker run --gpus all -it --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -v${PWD}:/workspace/onnx-stateful nvcr.io/nvidia/tensorrt:22.02-py3`
3. Build the onnxruntime commit id: `0f5d0a091a37db48593905c33a834597338288e8` (Feb 5, 2022) and install it to e.g. `/workspace/ort-0f5d0a0`
4. Build the onnxruntime commit id: `769aa8363dd7ac0e6601e55481f7a9938ebc7c5a` (Mar 8, 2022) and install it to e.g. `/workspace/ort-769aa83`
5. Set the LD_LIBRARY_PATH to **first ORT binaries** e.g. `export LD_LIBRARY_PATH=/workspace/ort-0f5d0a0/lib:$LD_LIBRARY_PATH`
6. Run the attached executable from the mounted directory: `cd /workspace/onnx-stateful && ./onnx_stateful_gtest` . It will run two identical tests and both should pass.
```
Running main() from /workspace/onnx-stateful/testing/build-0f5d0a0/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 2 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from DebugConfig/OnnxModelRunnerTest
[ RUN      ] DebugConfig/OnnxModelRunnerTest.TestCorrectness/0_0_64_1_CUDA_FP16_16b
[       OK ] DebugConfig/OnnxModelRunnerTest.TestCorrectness/0_0_64_1_CUDA_FP16_16b (718 ms)
[----------] 1 test from DebugConfig/OnnxModelRunnerTest (718 ms total)
[----------] 1 test from Debug1Config/OnnxModelRunnerTest
[ RUN      ] Debug1Config/OnnxModelRunnerTest.TestCorrectness/0_0_64_1_CUDA_FP16_16b
[       OK ] Debug1Config/OnnxModelRunnerTest.TestCorrectness/0_0_64_1_CUDA_FP16_16b (6 ms)
[----------] 1 test from Debug1Config/OnnxModelRunnerTest (6 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 2 test suites ran. (744 ms total)
[  PASSED  ] 2 tests.
```

7. Set the LD_LIBRARY_PATH to **second ORT binaries** e.g. `export LD_LIBRARY_PATH=/workspace/ort-769aa83/lib:$LD_LIBRARY_PATH`
8. Run the attached executable from the mounted directory: `cd /workspace/onnx-stateful && ./onnx_stateful_gtest` . It will run two identical tests but this time the first test passes and the second one fails due to different output.
```
Running main() from /workspace/onnx-stateful/testing/build-0f5d0a0/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 2 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from DebugConfig/OnnxModelRunnerTest
[ RUN      ] DebugConfig/OnnxModelRunnerTest.TestCorrectness/0_0_64_1_CUDA_FP16_16b
[       OK ] DebugConfig/OnnxModelRunnerTest.TestCorrectness/0_0_64_1_CUDA_FP16_16b (716 ms)
[----------] 1 test from DebugConfig/OnnxModelRunnerTest (716 ms total)
[----------] 1 test from Debug1Config/OnnxModelRunnerTest
[ RUN      ] Debug1Config/OnnxModelRunnerTest.TestCorrectness/0_0_64_1_CUDA_FP16_16b
Output Tensor: 0 Index: 0
-7.21497 vs. 0,
Output Tensor: 0 Index: 1
0.881882 vs. 0,
Output Tensor: 0 Index: 2
-17.4532 vs. 0,
Output Tensor: 0 Index: 3
7.16027 vs. 0,
Output Tensor: 0 Index: 4
13.2091 vs. 0,
/workspace/onnx-stateful/testing/tests/gtests/onnx_model_runner_test.cpp:168: Failure
Expected equality of these values:
  0
  m_ModelRunner.check_output(tasks_cpu, tasks_gpu, m_ModelRunner.m_UseFP16 ? 6e-2f : 1e-4f)
    Which is: 5
[  FAILED  ] Debug1Config/OnnxModelRunnerTest.TestCorrectness/0_0_64_1_CUDA_FP16_16b, where GetParam() = (0, 64, 1, false, true, true) (3 ms)
[----------] 1 test from Debug1Config/OnnxModelRunnerTest (3 ms total)
[----------] Global test environment tear-down
[==========] 2 tests from 2 test suites ran. (732 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Debug1Config/OnnxModelRunnerTest.TestCorrectness/0_0_64_1_CUDA_FP16_16b, where GetParam() = (0, 64, 1, false, true, true)
 1 FAILED TEST
```

**Expected behavior**
The output for the same input should always be same. In this case, it seems after the first inference the ORT CUDA is left in an unstable state and causing the second identical inference request to produce different results.

**Additional context**
In both cases, the test is running an inference of batch size=1 with CPU first, then with CUDA EP and then compares the results to see if the test passed or not. Both tests share the same ORT ENV variable but they create their own ORT Session and destroys the session objects at the end of the tests. I also tried not sharing the ORT ENV but still the same issue. I also tried an earlier commit (`a7f6442c45ede16e92205e9d4c7068819eef37ae`) from March 1 where the issue is also present. So it seems the issue was introduced sometime between Feb 5 and Mar 1.

[ORT_CUDA_issue.zip](https://github.com/microsoft/onnxruntime/files/8310759/ORT_CUDA_issue.zip)

**Comment by snnn** [comment]
Why /workspace/ort-769aa83/lib was added to LD_LIBRARY_PATH, why is it needed?

**Comment by rakib-hasan** [comment]
With the steps 3-4 above, you should have two different ORT installs. Steps 5 and 7 are just trying to set up which binaries to use. Step 6 is using the libs from Step 5 and Step 8 is using the libs from Step 7.

**Comment by RandySheriffH** [comment]
@rakib-hasan : thanks for reporting this, but have u ever tried on other cuda version?

**Comment by rakib-hasan** [comment]
@RandySheriffH Apologies for the late reply. Not seeing your other comment anymore but here is my (possibly outdated) response: I tried the faulty commit on TRT 21.08 container which has cuda-11.4 and still ran into the same issue.

**Comment by rakib-hasan** [comment]
According to @jywu-msft , it seems the issue is due to a recent commit (d07a237) that enforces Ort::Env object to be created only once in a process and only destroyed when ORT is not needed anymore (e.g. process exits). Closing this issue based on that but please feel free to reopen if there is any follow up needed.

**Comment by snnn** [comment]
Add some background: (I write it here in case I will forget it too)

In provider_host_api.h you can see each pluggable provider must implement a Shutdown() function. Please onnxruntime::Provider represent a  DLL(or shared library), it is not an EP.  The shutdown function is called when OrtEnv is closed, so that we can ensure the all the dynamically loaded EP will be unloaded before the core framework is unloaded from the system. It makes sense, because EP depends on the core framework, not vice versa. If the EP dll didn't have any global variable that depends on the ORT core framework, then we don't need to worry about it. But it is too ideal.  

On windows we say an executable file links to (or loads) a DLL in one of two ways:

1. Implicit linking, where the operating system loads the DLL at the same time as the executable that uses it. The client executable calls the exported functions of the DLL the same way as if the functions were statically linked and contained within the executable. Implicit linking is sometimes referred to as static load or load-time dynamic linking.

2. Explicit linking, where the operating system loads the DLL on demand at runtime. An executable that uses a DLL by explicit linking **must explicitly load and unload the DLL.** It must also set up a function pointer to access each function it uses from the DLL. Unlike calls to functions in a statically linked library or an implicitly linked DLL, the client executable must call the exported functions in an explicitly linked DLL through function pointers. Explicit linking is sometimes referred to as dynamic load or run-time dynamic linking.

When Implicit linking is used, operating system knows the dependency relationship, it can help handle it. It won't unload DLLs in wrong order.  But, in our case if we want to use Implicit linking we will need to extract the core framework to a  separated DLL like onnxruntime_framework.dll. And it has a limitation that EP's code can't be in the main executable binary. i.e. EP must be compiled as a DLL, instead of being part of an EXE. When we developed the EP API, we couldn't foresee if there would be such a need.

So we went to the "explicit linking" road. Not only we must explicitly load EP DLLs, we also need to explicitly clean their global variables and unload them. Thus we added the shutdown function. However, there could be a mismatch between how many times load/unload happens and how many times Provider::Shutdown() was called.  For two reasons:
1. People may forget to delete ort env. In this case all DLLs will still be unloaded but it will be done in a wrong order and could crash.
2.  Sometimes when you call dlclose() , the shared lib won't be unloaded immediately. Because the refcount hasn't reached to 0 yet, or the shared library was built with "-Wl,-z,nodelete", or simply because [it uses "inline" keyword](https://bugzilla.redhat.com/show_bug.cgi?id=1215452). 

So there would be a chance that:
1. A global variable is initialized when the DLL is loaded
2. Then it get cleaned when  Provider::Shutdown() is called. But the DLL is not unloaded
3. Then someone tries to use the DLL and the global variable again, You will find the global variable is not initialized (because it has been cleaned)

The old ONNX Runtime code works because every time when it tries to access CUDA EP's kernel registry, it tests if the registry is initialized or not. If it is not initialized, do it now. However, such code is not thread-safe.  In order to make it thread-safe, we need to acquire a mutex before testing if the registry is initialized. Luckily OrtMutex doesn't have a constructor/destructor. So it is possible to add such a check at the beginning of Provider::Shutdown()'s function body. At least we can tell people if Provider::Shutdown()  was invoked more than once.
