### ISSUE TITLE
high memory occupy when quantization with big calibrate dataset

### ISSUE THREAD

**Issue by ArtyZe** [microsoft/onnxruntime#11020]
[]I notice that quantization output collect code is like:
![image](https://user-images.githubusercontent.com/32027268/160350896-ae73f585-8f0a-48c5-bb98-a8d7a7779e2c.png)

but if my model is complex with many tensors and my calibrate dataset chanced to be big, memory with runs out,
why designed like that instead of update histogram each step

**Comment by chilo-ms** [comment]
We provide examples showing how to split the large dataset for calibration to prevent OOM:

- https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/object_detection/trt/yolov3/e2e_user_yolov3_example.py#L88

- https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/nlp/bert/trt/e2e_tensorrt_bert_example.py#L249

We want to give users the flexibility to decide how they want to deal with the dataset. Collect all the raw data first can give you the best performance, but if the dataset is large, we also support read in dataset stride by stride. 
Thanks for bringing it up, we could document better so that user can understand how to use it.
