### ISSUE TITLE
python 3.10 release ETA?

### ISSUE THREAD

**Issue by mharvey-jt** [microsoft/onnxruntime#11117]
Hi, do you have any ETA for a release supporting Python 3.10? Are there any blockers that need resolving? Cheers, M

**Comment by pranavsharma** [comment]
@snnn - can you comment?

**Comment by snnn** [comment]
It will be in onnxruntime 1.12.  We haven't set a date for it yet.

**Comment by faxu** [comment]
This should already be updated in the master branch so you can get dev builds from https://test.pypi.org/project/ort-nightly/

**Comment by AuracleTech** [comment]
Waiting for update

**Comment by bconstanzo** [comment]
I have just installed ort-nightly on Python 3.10 under Windows 10 64 bits and it's importing, and it seems to work, though I can't get skl2onnx to install (because it tries to remove nightly and go to the previous stable). I'll be installing another environment for training and seeing if it works fine later on.

**Comment by omega7379** [comment]
So there's 2 ways to get around this issue for now (while it does suck that is hasn't been released yet afaik).

$ curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3.9 get-pip.py

this installs pip for python 3.9 which is then accessible via pip3.9

The other option as mentioned previously-
$pip install ort-nightly

both seem to work (program dependant), and up to the user's preference.
