### ISSUE TITLE
[Documentation Request]

### ISSUE THREAD

**Issue by vishwas1234567** [microsoft/onnxruntime#11400]
[Enter feedback here]

---
#### Document Details
* Title: Python
* Page: [https://onnxruntime.ai/docs/get-started/with-python.html](https://onnxruntime.ai/docs/get-started/with-python.html)
* Page Source: with-python.md

Code not working for the new version of the tf2onnx

**Comment by hariharans29** [comment]
Can you provide a detailed request ? What is it that you are trying to achieve ? What have you tried so far ?

**Comment by hariharans29** [comment]
Please re-open the issue after you fill in the Github issue template:

**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.
