### ISSUE TITLE
onnxruntime cannot used in a subgraph an output created in the main graph

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#11536]
**Describe the bug**

onnxruntime cannot load a mode due to the following error: ``Graph output (one) does not exist in the graph``. This resul created with operator Constant is returned by a subgraph linked to a branch of an operator If.

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): >indows
- ONNX Runtime installed from (source or binary): soucrce
- ONNX Runtime version: 1.12
- Python version: 3.9

**To Reproduce**

Load the following file: [switch_axes.inlined.onnx.zip](https://github.com/microsoft/onnxruntime/files/8700040/switch_axes.inlined.onnx.zip).

```python
from onnxruntime import InferenceSession
InferenceSession("...attached file")
```

**Expected behavior**
It should load the model without any error.

**Comment by hariharans29** [comment]
Is it similar to this: https://github.com/microsoft/onnxruntime/issues/5991 ?

**Comment by skottmckay** [comment]
The problem is that an outer scope value is being directly returned by a subgraph and the ORT code doesn't allow for that when creating the Graph instance (it expects all outputs to be created within the subgraph). It's not until later that we build all the connections to validate outer scope value usage.

In theory we can check if the value exists in an ancestor graph and allow it, however we would need to create a NodeArg in the subgraph for the value. This is consistent with how other outer scope values are treated and maintains a condition that there's a NodeArg for all values in the Graph, be they local or outer scope.

e.g.
https://github.com/microsoft/onnxruntime/blob/48efeca66cbc7eada72a0c59a87476a75b36aa14/onnxruntime/core/graph/graph.cc#L1199

All good in theory, but next would be that the BuildConnections logic is not aware of an outer scope value directly providing a subgraph output. Cuurently that means the outer scope value doesn't make it into the implicit inputs for the subgraph, and type/shape inferencing wouldn't be aware of it. The current logic only does this resolution for node inputs:

https://github.com/microsoft/onnxruntime/blob/48efeca66cbc7eada72a0c59a87476a75b36aa14/onnxruntime/core/graph/graph.cc#L1647-L1658

We could add another step to BuildConnections for this, but there may also be allocation planning issues with this sort of setup (haven't looked into that). 

The question at this point is whether it's worth all this complexity for an edge case that the ONNX spec doesn't clearly state is allowed. The only relevant statement I could find was in the [Loop spec](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Loop), where it says

> Values from the enclosing scope (i.e. variable "a" here) are in scope and can be referenced in the inputs of the loop.

It does not say anything about an outer scope value being able to be directly returned as a subgraph output.

Given all that, I think it's easier to require an Identity node to pass through an outer scope value as a subgraph output. 

Side note: Looking at the model it may be possible to use a Where node instead of an If given the subgraphs are simply choosing a value and not doing any other processing.

**Comment by xadupre** [comment]
Can we display a better error message if this case happens?
