### ISSUE TITLE
Unable to load DLL 'onnxruntime.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by sethjuarez** [Microsoft/onnxruntime#116]
**Describe the bug**
After installing Nuget package and attempting to create a session I get the following error in a WinForms app on .NET Framework version 4.6.1:

`Unable to load DLL 'onnxruntime.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

at line 33 in `Microsoft.ML.OnnxRuntime.SessionOptions`:

```csharp
public SessionOptions()
{
     _nativeOption = new NativeOnnxObjectHandle(NativeMethods.ONNXRuntimeCreateSessionOptions());
}
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows**
- ONNX Runtime installed from (source or binary): **Nuget Installed Microsoft.ML.OnnxRuntime in VS17**
- ONNX Runtime version: **0.1.5**

**To Reproduce**
Added Nuget package and attempted the following code with a valid onnx file:
```csharp
var options = SessionOptions.Default;
options.AppendExecutionProvider(ExecutionProvider.Cpu);
_session = new InferenceSession(file, options);
```
I tried running from Visual Studio on x64

**Expected behavior**
The dll should load and the session should start.

**Note**
I am sure this is a silly error on my part but maybe others will run into it.

**Comment by pranavsharma** [comment]
@shahasad @jignparm can one of you take a look? thanks!

**Comment by rjoganah** [comment]
Same error here, but for me the reason seems to be that i'm using windows 8.1, it seems that it's only compatible with windows 10 and I'm using windows 8.1 Enterprise.
I copied microsoft.ml.onnxruntime\0.1.5\runtimes\win10-x64\native\onnxruntime.dll in the \lib\netstandard1.1\ path 
But now i get an error when loading the onnx model : System.AccessViolationException. But as it's a targeted dll for win10 I think that it's expected to fail.

**Comment by shahasad** [comment]
Current build is supported for windows 10, x64 CPU only. Support for other platforms are coming in subsequent releases. Meanwhile, please feel free to build from the source.

**Comment by sethjuarez** [comment]
I built from source but could not find the dll. I’m also running Windows 10 x64.

**Comment by jignparm** [comment]
The problem is due to the Visual Studio not copying the dependent dlls (onnxruntime.dll and mkldnn.dll )to the \x64\Debug directory. After copying both these files, the project runs successfully.

**Comment by sethjuarez** [comment]
That is correct! Also the onnx model I exported from the current version of the PyTorch ONNX export uses a version of Gemm in the export that is not compatible.

**Comment by n8allan** [comment]
I don't understand why this is closed.  Shouldn't the nuget package copy the native file automatically?

**Comment by tkcrown** [comment]
Same issue here.

**Comment by shahasad** [comment]
Should have been fixed in the later versions. Plz try v0.5

**Comment by Ajk4** [comment]
I got the same thing on 0.5

**Comment by jbrownkramer** [comment]
I have the same thing on 1.1.0

**Comment by y2kbugger** [comment]
You have to set your cpu type to either x86 or x64.

@shahasad @jignparm Perhaps this could be made clearer, maybe build should fail if cpu type is not correctly setup in Visual Studio.

**Comment by jignparm** [comment]
> You have to set your cpu type to either x86 or x64.

> I have the same thing on 1.1.0

That should not be the case -- it should work for x86, x64 as well as AnyCPU, depending on which architecture applies to the project (i.e. native C++, .Net Core or .Net Framework). 

The package ships with the appropriate targets files, so you should not need to copy any DLLs (the original issue was created prior to the package fixes.)

Can you  post a way to reproduce the error?

**Comment by y2kbugger** [comment]
To be honest I haven't tried to reproduce since the 0.4 era, I only pinged you because I saw someone saying they had it with 1.1.0. I still do leave mine configured with x86 regardless of whether my code is managed or not. If I have time I'll experiment.

**Comment by jbrownkramer** [comment]
I believe one issue was fixed by changing the platform, but I have not tried to replicate the problem. 

One thing I know for sure: I have a project - project A -  that uses onnxruntime as a nuget package.  I have another project - project B - that references project A.  Unless onnxtruntime is explicitly added as a Nuget package to project B, onnxtruntime.dll doesn't get copied into the bin folder.  I think this is a property of Nuget more generally, and not onnxruntime per se.

**Comment by sacha-broute** [comment]
It happens to me also, and without a way to reproduce it for now

**Comment by sacha-c** [comment]
I figured out my issue!

I am using _paket_ as a package manager, instead of VS nuget manager. So my project doesn't have a packages.config, which is why onnxruntime.dll is never copied

props.xml has the following conditions:
 ` <ItemGroup Condition="Exists('packages.config') OR
                        Exists('$(MSBuildProjectName).packages.config') OR
                        Exists('packages.$(MSBuildProjectName).config')"> `

I will be creating a new issue for this

**Comment by aleksandar-lazic** [comment]
I've had this error with Microsoft.ML.OnnxRuntime.Gpu 1.3.0

Turns out, I've accidently removed "NVIDIA GPU Computing Toolkit" from the path.

**Comment by devnet123** [comment]
i'm having the same issue on 1.4.2
any suggestion ?

**Comment by n8allan** [comment]
I struggled with this until I fired up "Depends" and discovered that it requires the [VC runtime](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by ChaseRoth** [comment]
@devnet123 I get the same error on both 1.5.1 and 1.52 versions.

**Comment by Grayda** [comment]
I was facing this issue (or possibly a similar issue), and I ended up installing https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/1.5.2?_src=template which resolved the issue for me.

**Comment by nelemans1971** [comment]
I've had similar problems with onnxruntime.dll when deploying my application on other computers.

In the end it came down to installing "Visual C++ Redistributable for Visual Studio"  (VC_redist.x64.exe & VC_redist.x86.exe). After installing these libraries the problem was resolved and onnxruntime.dll  loaded without problems.

**Comment by Aida-Enna** [comment]
Having the same issue using AnyCPU - It doesn't download/install the 32bit DLLs and so it fails with `System.BadImageFormatException: 'Could not load file or assembly 'Aspose.OCR, Version=21.1.2.0, Culture=neutral, PublicKeyToken=716fcc553a201e56' or one of its dependencies. An attempt was made to load a program with an incorrect format.'`.

I downloaded the x86 release zip and was able to place onnxruntime.dll in the right directory to (assumedly, since I can't run it) fix it, but I'm not able to find pre-compiled x86 versions of mklml.dll and libiomp5md.dll to see if this would fix it for them as well.

**Comment by ChaseRoth** [comment]
> 
> 
> Having the same issue using AnyCPU - It doesn't download/install the 32bit DLLs and so the project I'm trying to use it fails with `System.BadImageFormatException: 'Could not load file or assembly 'Aspose.OCR, Version=21.1.2.0, Culture=neutral, PublicKeyToken=716fcc553a201e56' or one of its dependencies. An attempt was made to load a program with an incorrect format.'` (because it loads the 64 bit DLLs)
> 
> I downloaded the x86 release zip and was able to place onnxruntime.dll in the right directory (`\packages\Microsoft.ML.OnnxRuntime.MKLML.1.4.0\runtimes\win-x86\native\`) to (assumedly, since I can't run it) fix it, but I'm not able to find pre-compiled x86 versions of mklml.dll and libiomp5md.dll to see if this would fix it for them as well.

I did some digging to see if I could find a solution to your issue but was unable to locate any x86 binaries. I think your best bet might be to download the source code from [Microsoft.ML source code](https://github.com/dotnet/machinelearning/releases) and try to build your desired x86 libs. 

Keep in mind not all functionalities when running x86 are supported, specifically TensorFlow and LightGBM. This is stated in the [github for ML](https://github.com/dotnet/machinelearning#operating-systems-and-processor-architectures-supported-by-mlnet). Another reference to x86 not being supported [here](https://devblogs.microsoft.com/dotnet/announcing-ml-net-0-7-machine-learning-net/). Who knows what issues might arise when trying to build the lib with your setup so I would suggest migrating your project to x64 if possible.

**Comment by mcicat** [comment]
> I struggled with this until I fired up "Depends" and discovered that it requires the [VC runtime](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

Thank You for this, You saved me hours.

**Comment by lxmou666** [comment]
> 我一直在努力解决这个问题，直到我启动了"Depends"并发现它需要[VC运行时](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)。

I solved it in this way

**Comment by benquan** [comment]
I was having same problem with VS2022 and deploying to windows x86.

If I install on develepment computer, it all runs fine, but if it's a clean Win10 computer (recently installed), I will get the error. The error got solved by installing "Visual C++ Redistributable for Visual Studio" as @nelemans1971 suggested. Why is it not included in the nuget dependencies?
