### ISSUE TITLE
Missing packages of ort-nightly on TestPyPI for some environments

### ISSUE THREAD

**Issue by jcwchen** [microsoft/onnxruntime#11613]
**Describe the bug**
https://test.pypi.org/project/ort-nightly/1.12.0.dev20220523004/#files This is the only version of ort-nightly on TestPyPI. There are missing packages for some environments. For instance, Mac only has Python 3.7 wheel. I guess there might be CI failures so the wheels were not uploaded somehow. ONNX repo uses ort-nightly to run some simple tests so currently some release CIs there are failing because of missing ort-nightly packages.

Here is my question: Does ort-nightly only keep one version for now? If so, could we make it keep a few versions at least? In that case, we can prevent possible CI failures every day. I hope at least every platform can have one runnable ort-nightly package. Thank you!

**Urgency**
ONNX 1.12 release is coming and therefore ONNX will run release CIs intensively these days. We can skip testing ort-nightly in the CIs for now, but I hope that ort-nightly can always reliable.

**To Reproduce**
Run
```
python -m pip install -q -i https://test.pypi.org/simple/ ort-nightly
```
in some environments and it will complain `ERROR: No matching distribution found for ort-nightly`.

**Expected behavior**
Ideally ort-nightly should be always downloadable.

**Comment by snnn** [comment]
testpypi is only used for testing how to publish a package, it is not a place for hosting nightly package. I do not recommend anyone uses pip to fetch ORT package there, because it has a high risk of supply chain security issue. 

Sorry I won't fix it. Please build ORT from source if you really need to use a nightly package. Or, please contact my PM. 

At this moment, due to Microsoft security polices, I don't have a solution for this except directly publishing the nightly packages to pypi.org.
