### ISSUE TITLE
Error when loading with C#: An unhandled exception of type 'System.AccessViolationException' occurred in Microsoft.ML.OnnxRuntime.dll

### ISSUE THREAD

**Issue by oohlala1204** [microsoft/onnxruntime#1174]
I have loaded and run my model with python API, and it works, but when I try to load the onnx model with C#, an error occurs.
I just use the code in the sample:

```
var session = new InferenceSession(modelPath,options)
```

An error occurs:
```
Exception thrown: 'System.AccessViolationException' in Microsoft.ML.OnnxRuntime.dll
An unhandled exception of type 'System.AccessViolationException' occurred in Microsoft.ML.OnnxRuntime.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```
The Call Stack is as follows:
![image](https://user-images.githubusercontent.com/32919349/59019234-3fd7b680-887a-11e9-8c15-97d188fb9091.png)

Any help would be appreciated!

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows10
- ONNX Runtime installed from (source or binary):binary
- ONNX Runtime version:0.4.0
- Python version:
- Visual Studio version (if applicable): VS2017
-.NET Framework 4.6.1

**Comment by jannavarro** [comment]
@oohlala1204 why was this closed? How did you solve it? I am encountering the same error so hope you could share how to solve it.

**Comment by oohlala1204** [comment]
> @oohlala1204 why was this closed? How did you solve it? I am encountering the same error so hope you could share how to solve it.

I change the configuration from "for any CPU" to "x64" and the problem is solved. Hope it helps.

**Comment by linehammer** [comment]
An access violation occurs in unmanaged or unsafe code when the code attempts to read or write to memory that has not been allocated, or to which it does not have access. This usually occurs because a pointer has a bad value.  These Corrupted State Exceptions (CSE) are not allowed to be caught by your standard managed code.

There are a few ways to get around this:

- Recompile as a [.NET](http://net-informations.com/faq/default.htm) 3.5 assembly and run it in .NET 4.0.
- Add a line to your application's config file under the configuration/runtime element: <legacyCorruptedStateExceptionsPolicy enabled="true|false"/>
- Decorate the methods you want to catch these exceptions in with the HandleProcessCorruptedStateExceptions attribute.
-
