### ISSUE TITLE
ORT nightly build is not discoverable on Google

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxruntime#11791]
A google search for "onnxruntime nightly" doesn't yield ways to install the nightly builds.

**Comment by snnn** [comment]
We do not provide nightly packages.  Though we have a pipeline that runs daily and publishes ort python packages to test pypi, but it is only for testing if the package is acceptable by pypi, and we delete the package soon after it gets published. pypi and test pypi do not provide enough storage space for us to host nightly packages. I have to manually delete old packages every week. I don't like the job.

**Comment by justinchuby** [comment]
@snnn I know we have https://download.onnxruntime.ai/onnxruntime_nightly_cu114.html, can we just link it from the onnxruntime website so that it gets indexed?

**Comment by snnn** [comment]
@askhade , what do you think? My understanding is that training python packages are only designed for being used in PTC containers. If it true, then we don't have much needs for them being indexed.

**Comment by justinchuby** [comment]
(Reopening to keep the discussion)

**Comment by natke** [comment]
Do we not publish nightly packages? We say we do: https://onnxruntime.ai/docs/install/#inference-install-table-for-all-languages

**Comment by snnn** [comment]
Then I think we should stop publishing packages to test pypi to ease the confusion. 

From security & compliance perspective, without doubt pypi.org is a good place for hosting packages for open source projects like onnxruntime. The others, like testpypi or Azure Devops, need evaluation. This is very different than Microsoft 1st-party usages. A non-opensource project can create a private Azure Devops feed to host all python package they need there. They can  create a daily pipeline to build onnxruntime from source and publish onnxruntime nightly package to their private Azure devops feed. They can also do the same thing for their software. It is under a condition that the feed is private, which means the onnxruntime nightly package is also private. Because if the feed is public, they will need to evaluate if they can redistribute onnxruntime's dependent packages. Generally speaking, from copyright perspective the answer is no. If we have a feed that only contains onnxruntime python package without the dependent packages that we don't own, then it may suffer supply chain attack. For example, we publish nuget packages to https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly, but I can't recommend anyone to use it. Most of the packages only have zero downloads. And I can't publish these nuget packages to nuget.org, because nuget.org's policy doesn't allow so. 
So, if any of you need a nightly package, I can only recommend building onnxruntime from source by yourself.  You can setup a nightly pipeline and publish the package to any non-public place.

**Comment by natke** [comment]
Adding @faxu
