### ISSUE TITLE
Scan performs worse than LSTM for CUDA EP

### ISSUE THREAD

**Issue by rakib-hasan** [microsoft/onnxruntime#11986]
A scan model seems to run slower than an equivalent LSTM model even though the scan is supposed to be doing less amount of computation than LSTM.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime installed from (source or binary): Binary
- ONNX Runtime version: ORT-1.11.1
- Python version: 3.8
- CUDA/cuDNN version: cuda-11.6
- GPU model and memory: T4, 16GB

**To Reproduce**
1. Start a TRT container (just to compare how TRT behaves for the same models): `docker run --gpus all -it --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -v /home:/home nvcr.io/nvidia/tensorrt:22.04-py3`
2. Install onnxruntime: `python3 -m pip install onnxruntime-gpu`
3. Run the script with the attached models in the same directory:

```
import numpy as np
import onnxruntime as ort
import time

ort.set_default_logger_severity(3)

max_iters = 200
sequence = 500
batches = [64,128]
models = ["LSTM.onnx", "Scan.onnx"]
providers = ["CUDAExecutionProvider", "TensorrtExecutionProvider"]

for ep in providers:
  for model in models:
    # all the setup
    dt = np.float32
    trt_opts = {}
    trt_opts = {"trt_max_workspace_size": "4294967296"}
    ep_w_opts = ()
    if "Tensorrt" in ep:
      ep_w_opts = (ep, trt_opts)
    else:
      ep_w_opts = ep # just cuda ep name

    # now create an ORT session
    sess = ort.InferenceSession(model, providers=[ep_w_opts])
    for batch in batches:
      print(f"{max_iters},{sequence},{batch},{ep},{model}", end='', flush=True)
      inputs = {}
      inputs["input"] = np.zeros((sequence, batch, 64), dtype=dt)
      # do a warm-up run first
      r = sess.run(None, inputs)
      start_time = time.time()
      for iter in range(max_iters):
        r = sess.run(None, inputs)

      print(f",{((time.time() - start_time)/max_iters)}")
    sess = None
```

**Expected behavior**
Scan model is supposed to be running faster than LSTM models (as it does for TRT EP). But you can see that for CUDA EP, it runs about 6x slower.
The performance comparison on my end:
![image](https://user-images.githubusercontent.com/1003393/175697893-6896f2eb-4775-4c0d-bba3-ea6ceaaaf02c.png)
[LSTM_vs_Scan_models.zip](https://github.com/microsoft/onnxruntime/files/8981694/LSTM_vs_Scan_models.zip)

**Comment by skottmckay** [comment]
LSTM is implemented as a single kernel. Scan is implemented by calling the subgraph in the Scan node sequentially for each input. i.e. you can think of LSTM as calling one big function that does all the work, and Scan as calling one function per node in the subgraph, and repeating that for each value in the input sequence. Due to this the amount of optimization and parallelism in the implementation of LSTM is going to be significantly better.

TensorRT is potentially able to create a compiled version of the Scan if all nodes in the subgraph are supported by the TensorRT execution provider. I would guess this is the case with your test model, and the compiled version can do a lot more optimizations and execute more operations in parallel.

Note that it's non-trivial to correctly handle calling the subgraph in parallel as there can be state variables which may change between each iteration. We could potentially optimize to execute a Scan node with no state variables in parallel, however doing so would have implications on memory usage.
