### ISSUE TITLE
C# Session.Run ONNX FP16 type result is strange, using Python is normal

### ISSUE THREAD

**Issue by chunweihuangya** [microsoft/onnxruntime#12401]
**Describe the bug**
C# session run onnx FP32 two classes model is normal, but when using FP16 model, images predict result always return [0, 15360].
*Python using same FP16 model predict result is normal.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- ONNX Runtime installed from (source or binary): NuGet
- ONNX Runtime version: Microsoft.ML.OnnxRuntime.Gpu 1.11.0
- Python version:
- Visual Studio version (if applicable): VS 2022
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2 / 8.1.0
- GPU model and memory: RTX3070 8G

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18112635/182099990-87dc1750-0c03-4b96-9229-52142ffcf147.png)

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by yuslepukhin** [comment]
What model would you like us to try this on?
What python package are you using? Is it `onnxruntime` or `onnxruntime-gpu`? Assuming the same version. Having that script would also be helpful.

**Comment by chunweihuangya** [comment]
Python using onnxruntime-gpu 1.10.0.
Model link:
https://drive.google.com/drive/folders/1KsXtYCinJFObbSZ-gY2wO9lIWVgQcorj?usp=sharing

**Comment by yuslepukhin** [comment]
Would you care to share a python script you used and a piece of C# code? The latter is especially interesting.

**Comment by chunweihuangya** [comment]
> Would you care to share a python script you used and a piece of C# code? The latter is especially interesting.

Upload .cs, .py and test image file at the following link:
https://drive.google.com/drive/folders/1KsXtYCinJFObbSZ-gY2wO9lIWVgQcorj?usp=sharing

**Comment by tianleiwu** [comment]
@chunweihuangya,
Here is an example of Float16 inference:
https://github.com/microsoft/onnxruntime/blob/466b2d9f3daeb35132a637f5cc8420636e636ed2/csharp/test/Microsoft.ML.OnnxRuntime.Tests.Common/InferenceTest.cs#L1236-L1255
You might notice that Float16 tensor use some integers (not float) to initialize.

Float16 is stored as unsigned short. Since NamedOnnxValue will point to a memory buffer, the buffer shall have values of unsigned shorts. You will need some conversion function (like [this](https://gist.github.com/vermorel/1d5c0212752b3e611faf84771ad4ff0d)) to convert between float and unsigned short. 

I recommend use float in inputs and outputs if you need read the value. That might have better performance than doing the conversion by yourself. You can set [keep_io_types=True](https://github.com/microsoft/onnxconverter-common/blob/744f6e95fbaf952c20e12c1113a9935d34cfa1a7/onnxconverter_common/float16.py#L90) in conversion.

**Comment by yuslepukhin** [comment]
As @tianleiwu pointed out, you cannot just cast float to Float16 type, it requires conversion. It might be helpful to read a bit about `float16` format. While its bits commonly stored as 16 bit integer, it is not an integer and casting to it (unless you defined a cast operator) would simply take float's integer part. Our C# API does not provide such conversion. Typically, clients who want to use float16 already have input as float16.

**Comment by chunweihuangya** [comment]
Thank you for your reply! I convert float to half first, and then convert to Float16 type, the inference result is normaly.

**Comment by zishui-wu** [comment]
@chunweihuangya Is the performance improved with fp16 and C api? Because there is traversal conversion fp16，my result of the performance is lower than fp32; @yuslepukhin Please give some guidance on the performance of fp16，Thank you very much！！！

**Comment by yuslepukhin** [comment]
While there is not many details you are giving, fp16 is generally for saving memory, but operations on it, except some trivial ones such as checking for zero, require conversion to fp32 and back. For this reason, you can't have both space savings and performance. CUDA has some efficient implementations, but in general it is what is it. You might want to take my suggestion and read about fp16 format and its purpose.
