### ISSUE TITLE
install onnxruntime 1.11.0 on Jetson Nano - protobuf requires Python '>=3.7' but the running Python is 3.6.9

### ISSUE THREAD

**Issue by luckingof** [microsoft/onnxruntime#12523]
HI! I want to install ONNXRuntime on my Jetson Nano but i run into the following error:

protobuf requires Python '>=3.7' but the running Python is 3.6.9

I followed the installation Method from https://elinux.org/Jetson_Zoo#ONNX_Runtime and selected an Python 3.6 pip wheel but it still fails while collecting protobuff (from onnxruntime-gpu==1.11.0).

# Download pip wheel from location mentioned above
$ wget https://nvidia.box.com/shared/static/jy7nqva7l88mq9i8bw3g3sklzf4kccn2.whl -O onnxruntime_gpu-1.10.0-cp36-cp36m-linux_aarch64.whl
# Install pip wheel
$ pip3 install onnxruntime_gpu-1.10.0-cp36-cp36m-linux_aarch64.whl

I hope somebody have a quick fix. Thank you!

**Comment by luckingof** [comment]
I run protobuf version 3,18,0

**Comment by snnn** [comment]
The latest ORT has stopped supporting python 3.6. If possible, please update your python to a newer version.  
We can't add new features to ORT 1.11, since it has been replaced by ORT 1.12. We can't resolve this issue is ORT 1.11. 

When you install pip, you can specify which version you want.  Like
```
pip3 install protobuf==3.18.1
```
In such a way, you might be able to find a version that works good with python 3.6.

**Comment by ameer-alwadiya** [comment]
I tried to install onnxruntime without dependencies and it works:

pip install --no-deps onnxruntime_gpu-1.10.0-cp36-cp36m-linux_aarch64.whl

And before installing it, I already have protobuf-3.8.0 installed on my device on Jetson Nano
