### ISSUE TITLE
Some QlinearConv can't dequantize its int8 weight with ORT1.12

### ISSUE THREAD

**Issue by mengniwang95** [microsoft/onnxruntime#12800]
**Describe the bug**
In the same model, some QlinearConv can't dequantize its int8 weight with below error:
[E:onnxruntime:, sequential_executor.cc:368 Execute] Non-zero status code returned while running DequantizeLinear node. Name:'onnx::Conv_608_quantized_Deq
uantizeLinear' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/quantization/quantize_linear.cc:33 void onnxruntime::PrepareForQDQ(const onnxruntime::TensorShape&, const
 onnxruntime::Tensor&, const onnxruntime::Tensor*, int64_t, int64_t&, int64_t&, int64_t&) scale.Shape().NumDimensions() == 1 && scale.Shape()[0] == broadcast_dim was false. scale must
be 1D tensor with size 1024
![image](https://user-images.githubusercontent.com/65003808/187592005-e8ebf403-9604-4a79-abc2-234bcad0ff21.png)
The perm of Transpose is [1,0,2,3]

Further I try to remove the first Transpose, but it still fails with the same error.

It will not fail with ORT1.11, so I wonder is it a new feature or a bug?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):binary
- ONNX Runtime version:1.12
- Python version:3.8.10

**To Reproduce**
insert dquant node for the weight of conv:
```python
        pre_transpose_node = onnx.helper.make_node(
                                 'Transpose',
                                 inputs=[tensor_name],
                                 outputs=[tensor_name + '_transposed'],
                                 perm=(1,0,2,3),
                                 name=tensor_name + '_pre_transpose')
        dequantize_node = onnx.helper.make_node(
                                 'DequantizeLinear', 
                                 [tensor_name + '_transposed', 
                                  scale_tensor.name, 
                                  zo_tensor.name], 
                                 [tensor_name + '_DequantizeLinear'], 
                                 name=tensor_name + '_DequantizeLinear')
        post_transpose_node = onnx.helper.make_node(
                                 'Transpose',
                                 inputs=[tensor_name + '_DequantizeLinear'],
                                 outputs=[tensor_name + '_output'],
                                 perm=(1,0,2,3),
                                 name=tensor_name + '_post_transpose')
```
I test part of convs and find Conv_7_quant, Conv_69_quant will fail, Conv_78_quant can run successfully.
[int8.zip](https://github.com/microsoft/onnxruntime/files/9458418/int8.zip)

**Comment by skottmckay** [comment]
Can you please share either the edited model that fails, or the complete set of steps to make changes to the model you've shared?

**Comment by mengniwang95** [comment]
Uploaded the edited model

**Comment by mengniwang95** [comment]
[int8.zip](https://github.com/microsoft/onnxruntime/files/9495038/int8.zip)

**Comment by skottmckay** [comment]
I believe this was fixed in 1.12.1. Can you please try with that?

https://github.com/microsoft/onnxruntime/pull/12218/files#diff-aa4a843a7b36def2173c1867700edc5655e4829f3be6f2a32a9040060202c45dR2004-R2006

**Comment by yihonglyu** [comment]
Could you update the opset ai.onnx from v12 to v13 in your model? In opset 13, DequantizeLinear has attribute axis and works fine with the enhanced optimization.

**Comment by skottmckay** [comment]
Actually that change doesn't apply due to the model opset. Whilst it does work with the latest code it doesn't hit PrepareForQDQ at all (which seems correct as those aren't QDQ node groups involved) in my testing. 

What's more important is that your model seems to be invalid. The ONNX spec for opset 12 DequantizeLinear does not allow for per-channel zero point and scale values. That was added in opset 13. The transpose optimizer is (validly) assuming that if the opset is 12 it doesn't need to do anything special like update the 'axis' attribute when moving a Transpose past a DequantizeLinear.

https://github.com/onnx/onnx/blob/main/docs/Changelog.md#dequantizelinear-10 says 
> 'x_scale' and 'x_zero_point' are both scalars. 

But the DQ nodes in your model do not have a single value for those inputs.

**Comment by mengniwang95** [comment]
But why ORT1.11.0 can work but ORT1.12 can't? @skottmckay I try 1.12.1 and it doesn't work

**Comment by skottmckay** [comment]
The transpose optimizer didn't have a second pass in 1.11 where it flipped the DQ and Transpose (largely for QDQ reasons but also more performant to do the Transpose on quantized data). That means we never moved a Transpose node across a DQ node where the 'axis' attribute had to be updated for it to work. 

Additionally the ORT DQ implementation doesn't explicitly check the opset and will happily work with an invalid node from a model with opset < 13. We assume that the ONNX checks have validated the node against the spec, but they are missing a check for the zp and scale being scalar (largely due to ONNX schema not having an explicit way to require something to be a scalar). The only 'fix' on the ORT side would be to add that check and fail your model due to that.

Either way, your model is invalid for ONNX opset 12. You could try using the onnx opset updater, but it may fail if it expects a DQ node to have scalar zp and scale. 

https://onnxruntime.ai/docs/reference/mobile/helpers.html#onnx-model-opset-updater
