### ISSUE TITLE
[Documentation] How to register custom operator in onnxruntime

### ISSUE THREAD

**Issue by debda018** [microsoft/onnxruntime#12896]
### Describe the documentation issue

I have written custom operator in Onnx C Api and want to register it in onnxruntime for inferencing. I have followed this tutorial in the link and as mentioned in step 1 I have written the custom operator and registered it in pytorch succesfully. 
The same C++ operator is written in ONNX Runtime C++ API and cmake is used to build the custom operator with all the required dependencies. The built directory is not generating any shared object which can be loaded by `register_custom_ops_library(<path_to_object_file>)` of `SessionOptions`. I am able to export the model with custom operator. But when i try to create an `InferenceSession` in python onnxruntime library I am getting the following error:
```
Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from model_resnet_custom.onnx failed:Fatal error: com.microsoft:Reduction_dd(-1) is not a registered function/op
```
 It would be great idf someone could advice me on how to register the operator in onnxruntime in python and provide some information regading this error.

 

### Page / URL

https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/README.md

**Comment by skottmckay** [comment]
> The built directory is not generating any shared object which can be loaded by register_custom_ops_library(<path_to_object_file>) of SessionOptions

Is there a specific error message you're getting?

**Comment by debda018** [comment]
> > The built directory is not generating any shared object which can be loaded by register_custom_ops_library(<path_to_object_file>) of SessionOptions
> 
> Is there a specific error message you're getting?

As the shared object is not being generated I can't post any error message regarding that but I have posted an error message when i am trying to run the inference of the custom operator in python's onnxruntime. Do you have any idea on how to register a custom operator written in C++ Api in python's onnxruntime?

**Comment by skottmckay** [comment]
The tutorial seems to be setup so with the custom op implementation being built into an executable along with ORT, so it's used directly instead of by registering a separate library. To create a standalone library the cmake setup would need to be changed, and you'd need to call RegisterCustomOpsLibrary like [this](https://github.com/microsoft/onnxruntime/blob/1e34440c370d40085fad5fd1b1002b4a04c5991d/onnxruntime/test/shared_lib/test_inference.cc#L122-L125 ) example.

That probably won't fix anything if you're currently adding an Ort::CustomOpDomain instance to the SessionOptions.

> com.microsoft:Reduction_dd

Make sure the domain string and op name match exactly. I would not recommend using the existing 'com.microsoft' domain though - for a custom op it's safer to use a custom domain name so there's no potential clash with existing things.

**Comment by skottmckay** [comment]
If it fails to get the symbol that would imply the library is not exporting it correctly. ORT will load the shared library and do symbol lookup using `dlsym`. Can you check what is exported? e.g. https://www.baeldung.com/linux/shared-library-exported-functions

I believe an empty string is doing the same due to how linux behaves. dlopen with an empty string returns the handle for the main program, which also won't have a RegisterCustomOps symbol exported. We could explicitly check for an empty string and provide a better error though.

**Comment by debda018** [comment]
@skottmckay Thank you for your help. I realized I was not exporting anything in my code and that was the root cause of the problem. Everything works now and I can successfully run the session in python's onnxruntime.
