### ISSUE TITLE
Improve Test Data Compression

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#1306]
Test data is getting really large and I think we should improve the compression at least to reduce network traffic.

Here's the current statistics:
```
4.2G (4321892)    20181210.zip
19G (19019224)    20190419         # Extracted data
17G (17408196)    20190419.txz     # From tar -cv 20190419 | xz -ceT36 > 20190419.txz
19G (19014084)    20190419.zip     # The zip you offered, which does almost no compression.
```

**System information**
- ONNX Runtime version (you are using): master

**Describe the solution you'd like**

Create 2 pkgs.
`.txz` for Linux, better `.zip` for windows.

Besides, in general, it's a bad practice to have several items (opset7/opset8/opset9) directly in a zip/tarball without a root dir.

**Describe alternatives you've considered**

At least get a high compression ratio zip.

**Comment by snnn** [comment]
I did it in purpose. Because increasing compression level will slow down data downloading. Our network speed is even faster than local disk, which is much faster than any data compression algorithm.  I saw no value here to waste cpu time just for saving 10% bandwidth. As I pointed before, on our build machines, the downloading only takes 2 minutes. So even you can optimize it to 1min 48sec without extra cost, It's not worth for me . Because the whole build takes more than 1 hour. A few seconds improvement is not observable.

**Comment by xkszltl** [comment]
Interesting.
I also noticed that unzip is slow.
However, since xz is a streaming algorithm, you can do an equivalence of `curl $url | xz -cdT$(nproc) | tar -x` on Linux/macOS.
This hides the extraction time and it's even multi-theaded.

**Comment by xkszltl** [comment]
The total download time for me in Redmond is ~20min so 10% is definitely noticeable, and for other geo location I tried, 10% is several hours.

For me I can accept creating a mirror server or republish it somewhere else, since I have the infrastructure to do so and I can make the first successful download.
But for the broader open source community this can be quite frustrating.

**Comment by snnn** [comment]
It's a one time thing. You don't need to do it repeatly. Once you get it on one machine, you can transfer it to another, without bothering Azure. If you need to frequently download it, please let me know. Because this is the easiest way to get us bankrupted.  Network bandwidth is expensive (but it's free if both of the hosts are in the same Azure region). 

My suggestion is: 
If the downloading happens in Azure, it's fast, network is free. Don't setup local disk cache, it's not worth to.
Else, use a cache please.

**Comment by snnn** [comment]
And, for all the cloud storage, don't compress the data by yourself. The storage layer and network layer will handle it for you.

**Comment by snnn** [comment]
Won't do it as I can't see much benefit from it.

**Comment by xkszltl** [comment]
> It's a one time thing. You don't need to do it repeatly. Once you get it on one machine, you can transfer it to another, without bothering Azure. If you need to frequently download it, please let me know. Because this is the easiest way to get us bankrupted. Network bandwidth is expensive (but it's free if both of the hosts are in the same Azure region).
> 
> My suggestion is:
> If the downloading happens in Azure, it's fast, network is free. Don't setup local disk cache, it's not worth to.
> Else, use a cache please.

Haha!

On Windows, for production build, we start from a clean set up dir to ensure reproducibility. I did implement a local cache.
On Linux, we're building docker, so everytime we start from scratch and there's no cache at all if it's build in Azure or Corpnet. If it is build in China I use a local file server to host the cache.

**Comment by xkszltl** [comment]
> And, for all the cloud storage, don't compress the data by yourself. The storage layer and network layer will handle it for you.

It's limited to gzip by HTTP.
