### ISSUE TITLE
Falling back to CPU when DirectML not ready.

### ISSUE THREAD

**Issue by vpenades** [microsoft/onnxruntime#13276]
### Describe the issue

I have some models that load and run fine in my machine, where GetAvailableProviders reports DML and CPU are available. I run the models using DML.

We also have a CI machine that also runs some unit tests, it also reports DML and CPU as available, but DML crashes when trying to load the models.

I suspect GetAvailableProviders just give the list of runtimes linked into the program.

What I would like is some method or property somewhere that would tell me if a given provider is ready to run, so if it is not ready, I could fall back to CPU

### To reproduce

Try to load a model using DML in a machine with no graphics card.

### Urgency

I just forced the models to load on CPU when unit testing, but it's a hack

### Platform

Windows

### OS Version

Win10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

DirectML

**Comment by fdwr** [comment]
> but DML crashes when trying to load the models.

Do you have the error message or any more details?

> Try to load a model using DML in a machine with no graphics card.

Interesting. Does it have no GPU at all, or an older one that doesn't support compute shaders? That would make a difference for potential recommendations.

> I suspect GetAvailableProviders just give the list of runtimes linked into the program.

That's what it sounds like in the documentation: 'Queries all the execution providers supported in the native onnxruntime shared library'.

**Comment by vpenades** [comment]
The stacktrace of the exception is:
```
Microsoft.ML.OnnxRuntime.OnnxRuntimeException : [ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\providers\dml\dml_provider_factory.cc(124)\onnxruntime.DLL!00007FFE04385AFA: (caller: 00007FFE04385B47) Exception(1) tid(25c0) 80070057 The parameter is incorrect.

   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_DML(Int32 deviceId)
   at Tests.GlobalSetup._ConfigureWindowsSafe(SessionOptions options) in C:\TeamCity\buildAgent\work\ccecdcadfce654f7\tests\Rehametrics.BlazePose.ONNX.Tests\_RegisterOnnx.cs:line 40
   at Microsoft.ML.OnnxRuntime.SessionOptionsContainer.ApplyConfiguration(SessionOptions options, String configuration, Boolean useDefaultAsFallback)
   at Microsoft.ML.OnnxRuntime.SessionOptionsContainer.Create(String configuration, Boolean useDefaultAsFallback)
```

So it's throwing the exception when it calls AppendExecutionProvider_DML ....  so I guess the obvious solution would by to wrap the code with a try-catch  and do the fallback just there.

But, given that AppendExecutionProvider_DML would likely fail, then it should not be listed as an available provider?

Changing the behavior of GetAvailableProviders  would be controversial, so I would suggest a `GetAvailableProviders(bool all | readyProvidersOnly);` overload

Anyway, I think it's worth to clarify the provider fallback best practices, because OnnxRuntime is beginning to be used in end user products, and developers might not have access to all possible hardwares that would require testing.

Regarding the machine where we run the unit tests, it's a normal desktop machine. It has an integrated graphics card, most probably a basic IntelHD. What's probably different is that it runs Windows Server Essentials as operating system.

**Comment by fdwr** [comment]
> Microsoft.ML.OnnxRuntime.OnnxRuntimeException ... dml_provider_factory.cc(124)\onnxruntime.DLL
> it runs Windows Server Essentials as operating system.

Based on the [line number 124](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/dml/dml_provider_factory.cc#L124)...

```
ORT_THROW_HR_IF(E_INVALIDARG, IsSoftwareAdapter(adapter.Get()));
```

...the device_id you're passing to `AppendExecutionProvider_DML` is a software adapter (just passing 0 I presume?). I'm not familiar with the Server Essentials SKU to know whether the software adapter index comes first (0) which might be deliberate since the screen output wouldn't go anywhere anyway, and whether the integrated one comes second (assuming it's available), but it's definitely possible to check this beforehand using a few calls to DXGI (`EnumAdapters1` and `IDXGIAdapter1::GetDesc1`, like what `IsSoftwareAdapter` is doing).

**Comment by fdwr** [comment]
> Changing the behavior of GetAvailableProviders would be controversial, so I would suggest a GetReadyToRunProviders();

For ORT API changes, I'd see what folks on ORT core think (I just work on the DML EP) like @Pranavsharma or @skottmckay. Pranav/Skott, the user request is an API that checks whether the given EP is runnable on the machine without error. This could apply to {DML, CUDA, OpenVino...} where ORT may have been *built* with selected EPs, but the machine being run on might not be able to *run* that EP (e.g. no capable GPU, or missing dependencies like the CUDA libraries).

What is ORT's current advice is for cases like this? For C++, you just check the OrtStatusPtr for success. For C#, it's evidently a bit noisier in throwing exceptions that would need to be caught. Another possibility (in lieu of an ORT "precheck" function) is for the app to check before trying to add an EP (e.g. a DXGI call to check adapter support before trying to use the DML EP, or some equivalent CUDA API's before trying to use the CUDA EP), and these calls are trivial in C++ but more awkward in C#. I generally think "precheck" functions are brittle, trying to keep code paths in sync of the actual initialization logic with logic that tries to predict whether initialization may or may not succeed, and it may ultimately give a false sense of comfort anyway because some failures can still occur later even if the precheck function expects it *should* succeed. It could still be useful though.

**Comment by pranavsharma** [comment]
Currently, the onus of adding the appropriate EP lies on the ORT user. The Append* functions don't really do much; they merely append factory functions to session options. Later when the session is created, the CreateProvider method is invoked on these factories to create the relevant providers and then added to the session. If CreateProvider throws an exception, we abort everything and return an error. It appears that we [don't](https://github.com/microsoft/onnxruntime/blob/5dae0c477d6c70d91952fb2c11fad37301cde7ae/onnxruntime/core/session/onnxruntime_c_api.cc#L687-L692) even check if the provider ptr returned is NULL.

This is not just about fallback to CPU. More generally should we continue with creating and adding other provider instances if an exception is thrown by one of the providers is a policy decision. Since we rely on users to attach the appropriate EP based on their hardware, it becomes important for us to notify them if this EP wasn't successfully added to the session. We could potentially add a flag to session options that says ignore failed EP creation, but it might be confusing if the user is expecting the model to perform well on (say) DML but it didn't since DML was never added and I doubt any warning log messages will be read. We'll give it some thought.

**Comment by vpenades** [comment]
> Since we rely on users to attach the appropriate EP based on their hardware

That's not exactly true.

I know my hardware, and I know exactly which providers to attach in my machine.

But we're developing a product that's going to be distributed in the wild, so we don't know beforehand which hardware the end users are going to have. We have to _detect it somehow_

Ideally, we would like to use Cuda, if it fails then fallback to DML, if it fails then fallback to CPU.

One decision we took early was to discard Cuda as a valid provider to deliver products in the wild, because it is so much difficult to check whether it's runnable or not in end user's machines.  We did a small trial and we found that 75% of our users were unable to run it because outdated graphics drivers.

**Comment by fdwr** [comment]
> We have to detect it somehow

@vpenades: What will you do in the meantime? Did you end up calling `EnumAdapters1` and `IDXGIAdapter1::GetDesc1`?

**Comment by vpenades** [comment]
> What will you do in the meantime?

@fdwr what I'm doing right now is, when I register the SessionOptions into `SessionOptionsContainer`, I wrap it with a Try-Catch block. If it throws an exception at `AppendExecutionProvider_DML`, the catch block attempts to create a fallback, CPU based SessionOptions object.

It makes the code somewhat verbose, and the try catch block might have undersirable side effects, like leaking some memory of the partially created SessionOptions that threw the exception.

Another problem is that I am only able to find out if a specific SessionOptions configuration is valid when I create the SessionOptions, immediately before creating an Onnx Session. And at this point I've also initialized many other things that I have to roll back.

**Comment by nums11** [comment]
Closing as resolved.
