### ISSUE TITLE
[DirectML] model fails to load on DirectML, but works on CUDA or CPU

### ISSUE THREAD

**Issue by sclavel** [microsoft/onnxruntime#13330]
Hello,

I'm trying to run this model:
https://tinyurl.com/2jpscefu

It loads with onnxruntime with CUDA provider (or CPU), but not with DirectML provider.
(also fails in WinDMLDashboard).

I'm using onnxruntime 1.12.1 and DirectML 1.9

Is there a way to know which node is not compatible yet with DirectML, so we can modify our model accordingly?

the log looks like this:
(Node placements)
(SaveMLValueNameIndexMapping)
(Done saving OrtValue mappings)
(Saving initialized tensors)
(Done saving initialized tensors)
DirectML.dll/TensorValidator.h(439) Exception "The parameter is incorrect.".
from: DirectML.dll/DmlDevice.cpp(192)
from: onnxruntime.dll/DmlOperator.cpp(43)
from: onnxruntime.dll/MLOperatorAuthorHelper.h(751)
from: onnxruntime.dll/DmlOperatorInstanceNormalization.cpp(65)
from: onnxruntime.dll/MLOperatorAuthorHelper.h(867)
from: onnxruntime.dll/AbiCustomRegistry.cpp(507)

([EDITED] original message was edited, to add that we also tested with latest 1.12.1/1.9 for DirectML, not only the standard WinML shipping with Windows)

**Comment by fdwr** [comment]
🤔 Initial investigation shows it's working locally with recent master bits (2022-10-09). You want to try with 1.13 prerelease? https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime.DirectML/overview/1.13.0-dev-20221019-1249-565da7127

```
onnxruntime_perf_test.exe -I -r 1 o:\temp\notworking.onnx
Session creation time cost: 6.3549 s
Total inference time cost: 0.821539 s
Total inference requests: 1
Average inference time cost: 821.539 ms
Total inference run time: 0.821779 s
Number of inferences per second: 1.21687
Avg CPU usage: 48 %
Peak working set size: 720023552 bytes
Avg CPU usage:48
Peak working set size:720023552
Runs:1
Min Latency: 0.821539 s
Max Latency: 0.821539 s
P50 Latency: 0.821539 s
P90 Latency: 0.821539 s
P95 Latency: 0.821539 s
P99 Latency: 0.821539 s
P999 Latency: 0.821539 s
```

To debug deeper, you can enable the debug layer (which is probably already installed you have Visual Studio installed, but otherwise: https://learn.microsoft.com/en-us/windows/ai/directml/dml-debug-layer).

Start / Run / dxcpl.exe
Add your process path to the list.
Then Force debug messages on.

![image](https://user-images.githubusercontent.com/1809166/196840782-a29a057a-4757-4635-999c-15614f2a156e.png)

**Comment by sclavel** [comment]
yes, working with latest nightly build. all good. thanks.
