### ISSUE TITLE
Support for AMX instruction

### ISSUE THREAD

**Issue by mengniwang95** [microsoft/onnxruntime#13586]
### Describe the issue

Hi, I am curious about the status of AMX support. Does mlas support int8 optimization for AMX instruction? If not, do you have some roadmap about it?

### To reproduce

No

### Platform

Linux

### OS Version

No

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.12.0

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU

**Comment by yufenglee** [comment]
We are working on adding AMX support. Basic support will be available in next release (1.14).

**Comment by mengniwang95** [comment]
Could you provide me a rough date of 1.14 release?

**Comment by chenfucn** [comment]
@mengniwang95 We are working with Intel folks on supporting AMX.  When it comes to int8 matrix multiplication, the accumulators need to be offset by proper scaled column and row sums.  These operations must be done with AVX512 instructions. And since there is no way for AMX tile to interact with AVX512 registers, we need to use a memory buffer in between. Turns out this is a really big performance drain. Since you are from Intel, do you have suggestions about how this problem should be addressed?

**Comment by chenfucn** [comment]
AMX int8 GEMM kernel has been merged into ORT.

https://github.com/microsoft/onnxruntime/pull/14042

**Comment by nguyenvietyen** [comment]
Very cool. I checked out the PR and if my understanding is correct it only supports AMX-INT8. Is there support planned for AMX-BF16?
