### ISSUE TITLE
Concat - CPU Fallback

### ISSUE THREAD

**Issue by iiSeymour** [microsoft/onnxruntime#1368]
**Describe the bug**

Concat operations fallback to the CPU - 

> [W:onnxruntime:Default, cuda_execution_provider.cc:1086 GetCapability] Fallback to CPU execution provider for Op type: Concat node name:

*Side note: [Node.name()](https://github.com/microsoft/onnxruntime/blob/59de37af1fb74aaa8f78c5a376dfcdb8fe27e064/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L1086) always seems to be an empty string.*

**Urgency**

None.

**To Reproduce**

```python
import io
import torch
import onnxruntime

class ConcatModel(torch.nn.Module):
    def forward(self):
        x = torch.randn(10)
        y = torch.randn(10)
        return torch.cat((x, y))
        
buff = io.BytesIO()
torch.onnx.export(ConcatModel(), (), buff)
session = onnxruntime.InferenceSession(buff.getvalue())
session.run(None, {})
```

**System information**

Running in the [CUDA Docker image](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.cuda).

- Linux Ubuntu 16.04
- ONNX Runtime  6b32c7780:
- Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
- GCC Ubuntu 7.4.0-1ubuntu1~18.04.1
- CUDA/cuDNN version: 10.0/7.0
- GPU model and memory: GV100/32GB

**Expected behavior**

Model runs on the GPU without falling back to the CPU.

**Comment by hariharans29** [comment]
Hi @iiSeymour,

Under some conditions, a fallback to CPU for a very small number of nodes might happen in order to prevent data copies between CPU and GPU (sub-optimal) or if a type is not supported by a GPU kenrel of the op. In your case, it's most likely the first scenario.

As for empty node names, it's the model that is missing the node names. The model should be fixed so as to contain node names for it to appear is the logs.

Thanks

**Comment by iiSeymour** [comment]
Is it possible to trace all the operations like you can with TensorFlow to verify if a fallback is costly or not?

What does it mean for a model to be fixed?

**Comment by hariharans29** [comment]
@HectorSVC can potentially answer your first question.

As for the second question (regarding empty node names which are not really a model execution blocker) - where did you obtain the onnx model from ? was it converted/exported using another framework ? The source should be fixed for the model nodes to contain names (in this case the model node names are empty)

**Comment by iiSeymour** [comment]
The original model is converted from PyTorch using ‘torch.onnx.export’.

**Comment by hariharans29** [comment]
I think it would be best to open up a discussion in the PyTorch repo and check why with them as to why the model's nodes have empty names....

**Comment by HectorSVC** [comment]
Specify some nodes running on GPU or CPU is not supported for now. To analysis the performance running the model on GPU, you can use nvprof (https://docs.nvidia.com/cuda/profiler-users-guide/index.html).
For your case, the Concat node maybe between Shape -> Concat -> Reshape. Force Concat to be running on CPU will avoid the data copy between CPU and GPU, because Shape output always on CPU, and Reshape (shape) input always on CPU. If place this Concat on GPU, there will be a data copy from CPU to GPU between Shape -> Concat, and a data copy from GPU back to CPU between Concat -> Reshape. It is very costly.

**Comment by iiSeymour** [comment]
Thanks @HectorSVC I no longer get the warnings post #1370. 

Looking at the performance with `nvprof` I see that `cudaStreamCreateWithFlags` is dominating the runtime?

![onnx-gpu-profile](https://user-images.githubusercontent.com/4310904/60965108-ec3f0980-a30c-11e9-8141-13b4c11cffb0.png)

This is with the driver in persistence mode.

```bash
$ nvidia-smi -i 0 -q | grep -i Persistence
    Persistence Mode                : Enabled
```

**Comment by HectorSVC** [comment]
you should skip the profiling overhead part

**Comment by iiSeymour** [comment]
FYI it is possible to get a trace output by simply by setting `enable_profiling`.

```python
options = runtime.SessionOptions()
options.enable_profiling = True
session = runtime.InferenceSession(args.model + ".onnx", options)
```

The GPU initialisation cost is very high -

<img width="1405" alt="Screenshot 2019-07-10 at 22 10 40" src="https://user-images.githubusercontent.com/4310904/61005515-3b625a00-a360-11e9-89f1-302299767549.png">

CPU -

<img width="1267" alt="Screenshot 2019-07-10 at 22 16 34" src="https://user-images.githubusercontent.com/4310904/61005607-6a78cb80-a360-11e9-893a-0d191fb173b5.png">
