### ISSUE TITLE
[TypeInferenceError] Attribute expected to have a one-dim tensor

### ISSUE THREAD

**Issue by LJXLJXLJX** [microsoft/onnxruntime#1396]
- OS Platform and Distribution: windows 10 64bit
- ONNX Runtime installed from (source or binary): binary
- Python version: 0.4.0
- Only CPU

I export my model as onnx with pytorch, and try to load it with onnxruntime, but I get errors as follow:

> RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from model/crnn.onnx failed:[TypeInferenceError] Attribute expected to have a one-dim tensor

Here is my model definition code and the onnx file. 

https://1drv.ms/f/s!AsUq39SrlQ1g5HF99mxPJR9CFu7U

**Comment by linkerzhang** [comment]
This is a failure from ConstantOfShape op's shape inference. ConstantOfShape op is expecting a "scaler" attribute "value", so that it's checking the attribute's dim size to ensure dim size is 1.
Unfortunately, I failed to download the attached model, so that can't check the dim size in the model.
@spandantiwari  can you help to double check pytorch exporter please?  1) having pytorch export always set the "value" attribute as a 1-dim tensor; 2) we may think of running ORT after pytorch exporting (not sure how much work it will be though :).

Thank you very much!

**Comment by LJXLJXLJX** [comment]
@linkerzhang  I have uploaded the model to google drive , please try this , thank you.

https://drive.google.com/drive/folders/1NMcSS8K6uOZplQkM4lmEeqQO-q87xpvB?usp=sharing

**Comment by spandantiwari** [comment]
@LJXLJXLJX - PyTorch 0.4.0 is quite old and there have been many updates to the exporter since then. Please install a newer version and see if this issue still persists. If it does, this would be a PyTorch issue, so I would suggest opening an issue in PyTorch GitHub repo, as that will help get any PT issues resolved faster/

**Comment by linkerzhang** [comment]
Thank you! @spandantiwari 

@LJXLJXLJX you may use latest pytorch which should have the export issue fixed.

**Comment by LJXLJXLJX** [comment]
> @LJXLJXLJX - PyTorch 0.4.0 is quite old and there have been many updates to the exporter since then. Please install a newer version and see if this issue still persists. If it does, this would be a PyTorch issue, so I would suggest opening an issue in PyTorch GitHub repo, as that will help get any PT issues resolved faster/

My pytorch version is the newest, 0.4 is the version of onnx-runtime. Thank you anyway !

**Comment by LJXLJXLJX** [comment]
@linkerzhang Hello, I fix this problem now, it seems there were 2 versions of torch exist in my PC. I uninstall them and install the newest torch, and it works.

But I still have a question, can I use I dynamic input (it is supported both by tf and torch) in onnx-runtime?
Such as  
```python
dummy_input = torch.randn(1, 3, 32, None)
onnx._export(net,dummy_input,'./model/crnn.onnx')
```
Thank you!
