### ISSUE TITLE
MIGraphX EP Failures with latest changes [Build] 

### ISSUE THREAD

**Issue by TedThemistokleous** [microsoft/onnxruntime#14126]
### Describe the issue

We're seeing compile time failures on the MIGraphX EP related to changes found  in SHA-1: a81faee41ef2344de448caecb0f42a34fdc9ead7

PR: #13495 

This has apparently broken builds and testing on our end due to the changes directly related to the MIGraphX EP

ROCm EP at this moment is fine and builds without any issue.

Currently the CI environment isn't flagging this as an issue and passes as well when looking at:
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=850247&view=logs&j=d16d5fd4-8d86-5567-da58-c395dcb46727&t=552849c5-fb58-5dc4-02df-aff7894ed6da

### Urgency

Blocking all other builds/testing between MIGraphX and Onnxruntime

### Target platform

Linux

### Build script

building the onnxruntime with the MIGraphX EP

### Error / output

/workspace/onnxruntime/onnxruntime/core/providers/migraphx/migraphx_execution_provider.cc: In lambda function:
/workspace/onnxruntime/onnxruntime/core/providers/migraphx/migraphx_execution_provider.cc:1176:9: error: ‘api’ was not declared in this scope; did you mean ‘migraphx::api’?
 1176 |         api->KernelContext_GetGPUComputeStream(context, &rocm_stream);
      |         ^~~
      |         migraphx::api
In file included from /workspace/onnxruntime/onnxruntime/core/providers/migraphx/migraphx_inc.h:8,
                 from /workspace/onnxruntime/onnxruntime/core/providers/migraphx/migraphx_execution_provider.h:13,
                 from /workspace/onnxruntime/onnxruntime/core/providers/migraphx/migraphx_execution_provider.cc:9:
/opt/rocm-5.3.0/include/migraphx/migraphx.hpp:41:18: note: ‘migraphx::api’ declared here
   41 | inline namespace api { // NOLINT
      |                  ^~~

**Comment by TedThemistokleous** [comment]
Out of curiosity how are you running MIGraphX? It looks like you're using the branch, branch_for_ort. 

If possible can you use the release version of MIGraphX from ROCm 5.4 instead? that should have the latest released changes for you to test with.

**Comment by cloudhan** [comment]
@souptc Mind take a look? Is it possible to opt out of multi-stream?

**Comment by PeixuanZuo** [comment]
Hi @TedThemistokleous, Could you please tell us how you test MIGraphX and onnxruntime on your side? I check the branch branch_for_ort and this branch was maintained by someone but stopped updating since Apr 12, 2022. Do you know why you provide this branch for ort before? Is there any special changes for ORT? I think the first PR is https://github.com/microsoft/onnxruntime/pull/2929/files#diff-2461bc0718da8a72e86fbe9f8023ec0f8eae563bebf8e44fef223e39c3bd96e0R30. Thanks.

**Comment by TedThemistokleous** [comment]
> Hi @TedThemistokleous, Could you please tell us how you test MIGraphX and ORT on your side?

@PeixuanZuo, so typically we build from the top of the ORT mainline tree for new additions and features, as were the changes created and tested with PR #12899 (Stream sync changes). There were a few other changes floating around which would run an entire test run with both MIGraphX and ORT to run some models.

During testing I had a few models we tested with using some of the bench marking scripts in the ORT repo. 

We have some additional scripts which do a performance run using ORT+MIGraphx that's run monthly internally for our own metrics. That's what triggered me digging into this build failure and uncovering things.

We have CI (Jenkins+github actions) automation setup  which does a test build with ORT for every one of our pull requests targeting a SHA-1 from ORT mainline.

As I've began looking into this, we're using an older SHA-1 (Back from 2021) to test all our builds in CI , which I'm currently fixing. I'm rolling back from ORT main, until I find a working SHA-1 which  I shall fix any MIGraphX issues on our side sync with ORT mainline: https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1504. 

Please let me know if there's a preferred set of git tags or release branches instead we should just be building and testing against, instead of using main.

In our case we want to get our Docker to be a working out of the box solution which gives a tested and working version of ORT and MIGraphx to the user as well so they can build the MIGraphX EP via the build_and_test_onnxrt.sh found in our repo.


> I check the branch migraphx_for_ort and this branch was maintained by someone but stopped updating since Apr 12, 2022. Do you know why MIGraphX provide this branch for ORT before? Is there any special changes for ORT? I think the first PR which specified branch migraphx_for_ort is https://github.com/microsoft/onnxruntime/pull/2929/files#diff-2461bc0718da8a72e86fbe9f8023ec0f8eae563bebf8e44fef223e39c3bd96e0R30. Thanks.

So there's some history here. The developer who maintained this branch moved on and why its been without a maintainer. We were pushing performance updates to this branch as a way to get changes into your CI process with the latest MIGraphX changes, but these changes would later be integrated into MIGraphX's mainline and releases. 

Currently the latest and greatest should be added via ROCm releases at this point as we're run all our CI and QA checks through these changes.

**Comment by PeixuanZuo** [comment]
@TedThemistokleous, thanks for your information.
`Please let me know if there's a preferred set of git tags or release branches instead we should just be building and testing against, instead of using main.`
If ORT release tags meet your requirement, release tags may better than a specified commit. ORT will release 1.14 and it will includes your PR https://github.com/microsoft/onnxruntime/pull/12899 (Stream sync changes). 
`We were pushing performance updates to this branch as a way to get changes into your CI process with the latest MIGraphX changes, but these changes would later be integrated into MIGraphX's mainline and releases.`
For MIGraphX, the main difference between migraphx_for_ort branch and dev branch is this commit https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/commit/2e43e30b01e5e6158a3407a5cf7f1a6f4d1c164d, it adds two cast(named `convert` in MIGraphX) ops before and after LRN op and make sure the input and output of LRN are both float type, ORT can support LRN with half type input and output, so I'am not sure what this modification is for. 
If this commit is not necessary, we can update MIGraphX to tag rocm5.4.0 now and update it to the corresponding ROCm release version we used in the future. cc @ytaous

**Comment by TedThemistokleous** [comment]
That commit, is something we'll need to optimize for in another part and can be removed. If you target things to ROCm5.4 you'll get the latest changes to test your CI against.

**Comment by PeixuanZuo** [comment]
Fix this issue in PR(https://github.com/microsoft/onnxruntime/pull/14141) and update MIGraphX branch used in ORT to rocm-5.4.0 in PR(https://github.com/microsoft/onnxruntime/pull/14184). @TedThemistokleous please use the latest ORT main branch to  verify the fix.

**Comment by PeixuanZuo** [comment]
@TedThemistokleous Can you close this issue if it's fixed?

**Comment by TedThemistokleous** [comment]
Verified. Builds are working again after the fix.
