### ISSUE TITLE
[Build] met build error when building for arm

### ISSUE THREAD

**Issue by chxfly** [microsoft/onnxruntime#14190]
### Describe the issue

met build error when building for arm 

### Urgency

High

### Target platform

arm

### Build script

git clone [https://github.com/microsoft/onnxruntime.git](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fonnxruntime.git&data=05%7C01%7Cxcuh%40microsoft.com%7C96856ae5dff649c23edf08daf261bea0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638088798874640111%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VfzLgq27S4xjT4ADBhZCFqmFWRIkV52un4YILErRhCg%3D&reserved=0)

cd onnxruntime

git checkout v1.13.1

git submodule update --init --recursive

build.bat --config=Release --cmake_generator="Visual Studio 17 2022" --arm --build_shared_lib

### Error / output

C:\Users\xxxx\onnxruntime\onnxruntime\core\mlas\lib\mlasi.h(1803): fatal  error C1017: invalid integer constant
 expression [C:\Users\xxxx\onnxruntime\build\Windows\Release\onnxruntime_mlas.vcxproj]
cl : command line  error D8040: error creating or communicating with child process [C:\Users\xxxx\onnxruntime\b
uild\Windows\Release\onnxruntime_mlas.vcxproj]

### Visual Studio Version

17.4.3

**Comment by mszhanyi** [comment]
@zhanghuanrong 
This fatal error `error C1017: invalid integer constantexpression ` in onnxruntime_mlas
could be removed by comment out one line in test_exp.cpp https://github.com/microsoft/onnxruntime/blob/d3785ef8f623d06ee110a7457b925156bd551be6/onnxruntime/test/mlas/unittest/test_exp.cpp#L28.

From my gut feeling, it's a regression in VC toolset, because there's no problem with VS2019. 
Could you provide a minimal, self contained repro to the Visual C++ team?
It's required in the ticket of  https://developercommunity.visualstudio.com/t/Compilation-Error-with-VS2022-ARM/10285309.

CC @faxu @snnn

**Comment by mszhanyi** [comment]
I've created a minimal, self contained repro. 
[arm.zip](https://github.com/microsoft/onnxruntime/files/10862300/arm.zip)

The repro steps are:
Unzip the attached.

1. Open …\arm\vmax\vmax.sln with VS2022
2. Change Configuration -> RelWithDebInfo, Platform -> ARM
3. Start Build, there's error
![image](https://user-images.githubusercontent.com/16190118/222176965-603de228-2e53-4829-b1cc-a62f3945395d.png)
4. change Project Properties->General->Platform Toolset to Visual Studio 2019(v142)
     or open the solution vmax_2019.sln.
     Build will succeed.

@zhanghuanrong @yufenglee @snnn

**Comment by mszhanyi** [comment]
Visual studio 2022 17.7 is released.
The issue can be closed.
