### ISSUE TITLE
Creating an inference session takes longer when there are many sessions already created

### ISSUE THREAD

**Issue by Kobzol** [microsoft/onnxruntime#14260]
### Describe the issue

I'm trying to create a large number (~10 thousand) of ONNX sessions in a single process. Since the model is very small, when I create a single session, it is usually very fast to load (sub millisecond). However, when I load a large number of models, some of the sessions being created take an enormous amount of time (seconds). Initially I thought that there might be some quadratic behaviour, but when I plot the times it doesn't seem quadratic, rather there are some really large outliers:

(x axis = loading of n-th model copy, y axis = time in seconds)
![image](https://user-images.githubusercontent.com/4539057/212021774-efa5db87-8b0e-4e08-af6d-382c7da13da1.png)

When I simply create the sessions and immediately free them, this doesn't happen and everything is fast. So it seems like it might be caused by some perf. hit when ONNX accesses some shared data structues when there are already a lot of sessions loaded in memory, for example false sharing or other multithreading issue. The chart above is for 8 threads (the default that `onnxruntime` uses on my system). When I force a single thread, everything is mostly fast as expected:

![image](https://user-images.githubusercontent.com/4539057/212023685-8d0aa2c5-f807-4912-a5e5-db3182754d20.png)

I experimented with `SessionOptions` a bit and the slowdown happens when I set `opts.intra_op_num_threads` to a value larger than one (the higher the value, the slower it is).

### To reproduce

```python
import sys
import time

import onnxruntime as ort
import seaborn as sns
import matplotlib.pyplot as plt

opts = ort.SessionOptions()
# This causes it to be slow
opts.intra_op_num_threads = 8

count = 1000
models = []

times = []
for _ in range(count):
    start = time.time()
    # executing just `ort.InferenceSession(...)` without storing the returned object also removes the bottleneck
    models.append(ort.InferenceSession("_model_1.onnx", sess_options=opts))
    duration = time.time() - start
    times.append(duration)

sns.lineplot(x=list(range(len(times))), y=times)
plt.show()

print("load", duration, (duration / count))
sys.stdout.flush()
```

### Platform

Linux

### OS Version

22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Model File

[model.zip](https://github.com/microsoft/onnxruntime/files/10399937/model.zip)

### Is this a quantized model?

No

**Comment by xadupre** [comment]
Every time a model is loaded, onnxruntime performs optimizations. You can disable them with `opts.graph_optimization_level = GraphOptimizationLevel.ORT_DISABLE_ALL`. You can also save the optimized model `opts.optimized_model_filepath = "to_save_the_optimized_onnx_file.onnx"` and use this one for the next InferenceSession.

**Comment by Kobzol** [comment]
The problem is not that it is slow to load/optimize any individual model, rather that there is probably some multithreading perf. issue when a large number of models is loaded and paralellism is used for model loading/optimization.

This problem persists even if I load an optimized model or if I disable optimizations.

**Comment by skottmckay** [comment]
Why are you creating that many sessions? A session supports concurrent requests to run the model.

Each session has its own threadpools and memory arena, so by creating a massive number of sessions you're really just increasing resource contention unnecessarily vs. the expected usage of making concurrent calls to InferenceSession::Run using a single session.

**Comment by Kobzol** [comment]
I know that it's far from ideal. I just have 10k (different) models that I want to use in a single process (don't ask me why :D ). This is probably a niche use-case, but still it might be interesting to investigate.

**Comment by pranavsharma** [comment]
Each session creates its own allocator and threadpool. A couple of things to try:

1. Limit the # of threads per session to 1 by configuring intra_op_num_threads. But with 10k models (sessions) you'll get 10k threads. Not surprisingly this will cause oversubscription.
2. Instead of #1 you can use a global env with a global threadpool. This allows the sessions to share a common set of threads. However, now you'll have 10k models competing to run on N threads.
3. Use and register a common allocator to be shared across sessions by using this API: CreateAndRegisterAllocator. This will help with reducing the memory usage due to the memory arena (created inside the allocator) significantly. However, it'll create contention when memory is requested due to the usage of a lock inside the Allocate function.
4. If #3 is bad, turn off the arena altogether. However, this might cause a lot of memory fragmentation.

No matter how you slide and dice it you'll run into some serious system resource related issues. Creating 10k sessions in a single process is a recipe for a lot of heartache. The simple solution is to not do it. This might be a good opportunity to go back to the drawing board and examine your use case with a fine toothed comb.

**Comment by Kobzol** [comment]
I know that the use case is bad (it's not my idea, I'm just supposed to make it run fast :) ).

Just to be clear, I'm not worried about inference time, but rather about the loading time. It seems that there is some false sharing or similar bottleneck going on when so many models are loaded using multiple threads. I thought that maybe this could be interesting to examine, as possibly finding out and optimizing what causes it could also speed-up more common code.

But it's true that most users probably won't ever hit this. And if they do, this issue and your answer might help them find a potential solution. Thanks!
