### ISSUE TITLE
[Feature Request] Expose GetAvailableProviders  in c# bindings

### ISSUE THREAD

**Issue by valeriob** [microsoft/onnxruntime#14378]
### Describe the feature request

It's usefull to diagnose if the providers are configured as expectred

### Describe scenario use case

I'm trying to run the DML provider without success, but i expected it be present given i referenced the related nuget package

**Comment by yuslepukhin** [comment]
I will look into the feature request. However, just because you reference the package in your VS Solution, the provider would not be active. You would need to add it to the providers argument when instantiating the session. That would cause the appropriate libraries loaded. There is not a build time linking to it. All dynamic.

**Comment by vborioni-onit** [comment]
Thank you @yuslepukhin 
you are correct, i'm initializing the SessionOptions with AppendExecutionProvider_DML, that's the method that give exception : 
What am i missing ?

![image](https://user-images.githubusercontent.com/42647445/214547243-2469c986-4447-4d16-b898-cacec890e35e.png)

Thanks

**Comment by yuslepukhin** [comment]
Do you have `Microsoft.AI.DirectML` and `Microsoft.ML.Onnxruntime.DirectML` packages installed?
Please, be sure to check https://github.com/microsoft/onnxruntime/issues/13429

**Comment by valeriob** [comment]
And you are right :D that was the issue, thanks !

**Comment by yuslepukhin** [comment]
I am seeing `GetAvaiableProviders()` implemented [here](https://github.com/microsoft/onnxruntime/blob/main/csharp/src/Microsoft.ML.OnnxRuntime/OnnxRuntime.shared.cs#L127)
