### ISSUE TITLE
[Web] wasm not support int32 and webgl not support int64

### ISSUE THREAD

**Issue by jkla139** [microsoft/onnxruntime#14589]
### Describe the issue

This incompatibility leads to switch model frequently when testing.

wasm:
![image](https://user-images.githubusercontent.com/44624598/216827271-2ced4fcc-e792-4d20-8beb-7c6c8af8c4b2.png)
Maybe only some ops like Tile not support int32 ?

webgl:
![image](https://user-images.githubusercontent.com/44624598/216827449-a1641257-4394-4d05-989d-cc0e5d298dde.png)

### To reproduce

...

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### Execution Provider

Other / Unknown

**Comment by guschmue** [comment]
for wasm / tile - this seems to be working for me as expected:
![image](https://user-images.githubusercontent.com/22941064/217084236-c7ffc504-d25f-4513-8909-2653494bdc57.png)

If the 2nd input would be int32 it would fail because the onnx spec doesn't allow this:
https://github.com/onnx/onnx/blob/main/docs/Operators.md#tile

**Comment by jkla139** [comment]
Oh, maybe it's the second situation.
