### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by jatinsingh-nykaa** [microsoft/onnxruntime#15007]
### Describe the issue

XGBClassifier with **squaredlogerror** objective not getting converted to ONNX.
It gives error: RuntimeError: Unexpected objective: reg:squaredlogerror

### Urgency

I need to use to to make the above conversion

### Target platform

NA

### Build script

NA

### Error / output

RuntimeError: Unexpected objective: reg:squaredlogerror

**Comment by skottmckay** [comment]
Sounds like a converter issue rather than an onnxruntime issue and guessing that may involve sklearn-onnx. 

Can you please provide more information about what exactly you're attempting to do?

Is this documentatation of any help? https://onnx.ai/sklearn-onnx/auto_tutorial/plot_gexternal_xgboost.html

**Comment by jatinsingh-nykaa** [comment]
I am trying something like this
model = XGBClassifier(objective='reg:squaredlogerror')
model.fit(X_train, y_train)

initial_types = [('float_input', FloatTensorType([None, X_train.shape[1]]))]
onnx_model = onnxmltools.convert_xgboost(model, initial_types = initial_types)

it gives RuntimeError: Unexpected objective: reg:squaredlogerror
---------------
It works fine if using some other objective like logistic

**Comment by skottmckay** [comment]
Closing. https://github.com/onnx/onnxmltools/issues/613 is a better location for the issue.
