### ISSUE TITLE
`convert_float_to_float16` calls `onnx.shape_inference.infer_shapes` that raises `onnx.ModelProto exceeds maximum protobuf size of 2GB` for large models

### ISSUE THREAD

**Issue by fxmarty** [microsoft/onnxruntime#15063]
### Describe the issue

Hi,

For large ONNX with external data as a single file, `convert_float_to_float16` raises `onnx.ModelProto exceeds maximum protobuf size of 2GB: 24208534956` with the traceback:

```
  File "/home/user/scripts/optimum/optimum/onnxruntime/optimization.py", line 200, in optimize
    optimizer.convert_float_to_float16(
  File "/home/user/miniconda3/lib/python3.10/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 633, in convert_float_to_float16
    fp16_model = convert_float_to_float16(model, **parameters)
  File "/home/user/miniconda3/lib/python3.10/site-packages/onnxruntime/transformers/models/gpt2/../../float16.py", line 203, in convert_float_to_float16
    model = func_infer_shape(model)
  File "/home/user/miniconda3/lib/python3.10/site-packages/onnx/shape_inference.py", line 39, in infer_shapes
    model_str = model if isinstance(model, bytes) else model.SerializeToString()
```

I see a fix for this issue has been implemented for quantization, but it does not seem for optimization, see https://github.com/microsoft/onnxruntime/pull/11106 from @yufenglee

I found this related answer https://github.com/onnx/onnx/issues/3588#issuecomment-881501923, but I am not sure whether it is up to date.

Is passing `disable_shape_infer=True` to `convert_float_to_float16` the only possibility? Meaning that shape inference needs to be done ahead of time? https://github.com/microsoft/onnxruntime/blob/32533dd1c290aa6025c584a705d3fa00fde1cd0a/onnxruntime/python/tools/transformers/float16.py#L177

### To reproduce

Will provide if needed.

### Urgency

medium

### Platform

Linux

### OS Version

Linux 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, CUDA

**Comment by fxmarty** [comment]
Shouldn't it be here https://github.com/microsoft/onnxruntime/blob/32533dd1c290aa6025c584a705d3fa00fde1cd0a/onnxruntime/python/tools/transformers/onnx_model.py#L621

rather

```python
parameters = {"disable_shape_infer": not use_symbolic_shape_infer}
```

?

cc @tianleiwu @yufenglee

**Comment by tianleiwu** [comment]
@fxmarty, fp16 conversion need data type information, which can be provided by either onnx shape inference if model is not optimized, or symbolic shape inference after model is optimized. The logic `{"disable_shape_infer": use_symbolic_shape_infer}` is good, which means we can disable onnx shape inference since OnnxModel has done symbolic shape inference at that time.

Possible changes to handle this:
(1) change https://github.com/microsoft/onnxruntime/blob/32533dd1c290aa6025c584a705d3fa00fde1cd0a/onnxruntime/python/tools/transformers/float16.py#L212 to call onnx.shape_inference.infer_shapes_path
(2) add another option to let use provide an example input for type inference: use ORT to run inference then record the data type of intermediate outputs.

**Comment by fxmarty** [comment]
Thank you @tianleiwu for your quick answer and fix, I see you've went for option 1 as in https://github.com/microsoft/onnxruntime/pull/11106.

For option 2, what would it look like, or do you have an example? Is shape inference done automatically during inference by ORT or would you need manual hack (like outputting all intermediate results and recording shapes?)?

**Comment by tianleiwu** [comment]
@fxmarty, I recommend optimum using the default symbolic_shape_infer=True in https://github.com/microsoft/onnxruntime/blob/32533dd1c290aa6025c584a705d3fa00fde1cd0a/onnxruntime/python/tools/transformers/onnx_model.py#L586 since it is better to use symbolic shape inference instead of onnx shape inference for optimized model. 

The pull request of 15067 is intended for non-optimized model (like CNN model where optimizations is optional).

**Comment by tianleiwu** [comment]
I could add an option to use ORT to run inference then record data type later. That could avoid shape inference in fp16 conversion.
