### ISSUE TITLE
CoreML connector cannot handle add_broadcast operations

### ISSUE THREAD

**Issue by j-baker** [microsoft/onnxruntime#15110]
### Describe the issue

I'm presently trying to get an ML model running against the Apple Neural Engine by using the Onnx CoreML EP.

In the model's ONNX graph, there's an add between data of dimensions `[2, 3, 80, 144, 1]` and `[2, 1, 80, 144, 1]`. I assume that because these are images, the 3 relates to the colour channel, and the onnx semantics are that it should be added to each of the colour channels, but I couldn't tell you for sure - SWE not AI person.

When this happens, CoreML explodes. The error provided to the user is:

`Error computing NN outputs -1`.

In the unified logger with private logging turned on, Espresso reports `'Invalid blob shape', 'Cannot broadcast [2, 3, 80, 144, 1] and [2, 1, 80, 144, 1] outputs`.

By modifying `binary_op_builder.cc` to override `IsOpSupportedImpl` as follows:

```c++
bool BinaryOpBuilder::IsOpSupportedImpl(const Node& node, const OpBuilderInputParams& /* input_params */,
                                        const logging::Logger& logger) const {
  const auto& input_defs = node.InputDefs();
  if (input_defs.size() != 2) {
    return false;
  }
  std::vector<int64_t> left, right;
  if (!GetShape(*input_defs[0], left, logger) || !GetShape(*input_defs[1], right, logger)) {
    return false;
  }
  return left == right;
}
```

I aimed to catch this case, and force execution on the CPU provider. This worked and the model executed. This change is almost certainly overkill - I don't understand the details of the guarantees that Onnx is supposed to provide, but I think hopefully demonstrates the bug.

I believe I'm demonstrating that CoreML has different semantics to what Onnx expects for ADD operators.

### To reproduce

Run a broadcast style add operator using the CoreML execution provider and watch it fail.

### Platform

Mac

### OS Version

Ventura

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

CoreML

**Comment by skottmckay** [comment]
I think the issue might be that it's creating a basic Add instead of a broadcastable one.

The code currently calls `mutable_add`

https://github.com/microsoft/onnxruntime/blob/e42f7487dfe5b986a5a945a99ce0da99404e370c/onnxruntime/core/providers/coreml/builders/impl/binary_op_builder.cc#L39

Which creates an instance of this 

https://github.com/microsoft/onnxruntime/blob/e42f7487dfe5b986a5a945a99ce0da99404e370c/onnxruntime/core/providers/coreml/mlmodel_format/NeuralNetwork.proto#L501

but might need to be this to support broadcasting

https://github.com/microsoft/onnxruntime/blob/e42f7487dfe5b986a5a945a99ce0da99404e370c/onnxruntime/core/providers/coreml/mlmodel_format/NeuralNetwork.proto#L594
