### ISSUE TITLE
[Mobile] Support/Handle NhwcConv on Android runtime.

### ISSUE THREAD

**Issue by cherrerajobs** [microsoft/onnxruntime#15129]
### Describe the issue

The stable diffusion model generated by the new optimizer code uses a NhwcConv node to layout the data in a way that makes it faster to run inference on GPUs. Modern qualcomm chipsets support NHWC layout on the GPU so if it can take advantage of it it should.

### To reproduce

Load up optimized stable diffusion model on onnx runtime 1.14.0 in android, then run the model. Gets error:
`ai.onnxruntime.OrtException: Error code - ORT_NOT_IMPLEMENTED - message: Failed to find kernel for NhwcConv(1) (node NhwcConv_0-/conv_in/Conv). Kernel not found`

### Urgency

Stable Diffusion Inference runs slow on android systems. I'm trying to optimize the models with the available tools in order to speed up inference and reduce heat generated on Android. I manually downloaded the android runtime generated here:
https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=924634&view=results

But it looks like there's no support for the node in that version.

Discussion here:
https://github.com/microsoft/onnxruntime/discussions/15115

### Platform

Android

### OS Version

Android 12 API 32

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

1.14.0

### ONNX Runtime API

Java/Kotlin

### Architecture

ARM64

### Execution Provider

Default CPU, NNAPI

### Execution Provider Library Version

NNAPI/XNNPACK

**Comment by skottmckay** [comment]
I'm not familiar with the new optimizer code. Maybe @tianleiwu can comment on that. Looks like that was added with the intention of usage on GPU only so there's no CPU kernel.

When running on Android the NNAPI or XNNPACK EP will do a runtime conversion from the default ONNX NCHW layout to NHWC for the nodes that EP will take. If there was a normal Conv it would be able to take it. It's not aware of or looking for any custom ops, so it wouldn't know how to run an NhwcConv. Due to that we probably do not want to be inserting NhwcConv nodes if the model is intended for usage on Android.

**Comment by tianleiwu** [comment]
NhwcConv is intended for CUDA/ROCM EP, and there is no implementation on other EP.
