### ISSUE TITLE
Error when loading with C#: An unhandled exception of type 'System.AccessViolationException' occurred in Microsoft.ML.OnnxRuntime.dll

### ISSUE THREAD

**Issue by jannavarro** [microsoft/onnxruntime#1538]
I have a .Net Core API that is able to evaluate locally. However, when deployed to Azure an error occurs when instantiating an `InferenceSession`.

I have a client application that sends a file name and `byte[]` content of the ONNX file to the Azure app service - .Net Core API. The service internally writes the ONNX model supplied to Azure local app data using the code below which works without errors.

```
public string Write(string name, byte[] model)
        {
            var localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);

            var infEnginePath = Path.Combine(localAppData, "InferenceEngine", "Models");

            Directory.CreateDirectory(infEnginePath);

            var modelPath = Path.Combine(infEnginePath, $"{name}.onnx");
            File.WriteAllBytes(modelPath, model);

            return modelPath;
        }
```

Using the `modelPath` returned in the method above the code below throws an error:

`var session = new InferenceSession(modelPath);`

An error occurs:

```
Exception thrown: 'System.AccessViolationException' in Microsoft.ML.OnnxRuntime.dll
An unhandled exception of type 'System.AccessViolationException' occurred in Microsoft.ML.OnnxRuntime.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

System information

**OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Azure App Service (latest Windows server OS perhaps).
**ONNX Runtime installed from (source or binary)**:binary - Nuget
**ONNX Runtime version**:0.4.0
Visual Studio version (if applicable): N/A
-.NET Core 2.2

**Comment by jignparm** [comment]
This issue is similar to the one here https://github.com/dotnet/machinelearning-samples/issues/448. Since the issue cannot be reproduced locally, the Azure App service is likely to be causing this error (or at least partially). 

Can you rule out permission and/or issues when writing the byte[] to file and reading it back in?

**Comment by jannavarro** [comment]
@jignparm Thanks for the response. I was able to write successfully so write access should not be the problem. I also tried to write to %TEMP% and was able to do so however I encountered the same error when instantiating `InferenceSession`. The [documentation](https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system) of Azure says those file systems should be accessible.

This might be same with #1174 where error occurs on `GetInputName` but I'm not entirely sure. Is there a code in there that might cause this?

Another side question, is there any plan to create an `InferenceSession` from a `Stream`? This can solve issues accessing the file system.

**Comment by jignparm** [comment]
> This might be same with #1174 w

The solution mentioned in #1174 was to use  the x64 configuration (instead of AnyCPU) because he was using .Net Framework 4.6.1. Is case the Azure App service is also using .Net Framework (and not .Net Core) , can you see if  x64 solves the error?

> Another side question, is there any plan to instantiate an `InferenceSession` from a `Stream`?

The native C-API already supports loading models from arrays. There should be an equivalent C# API coming soon. Would that be sufficient? It's not the same as a  stream, but at least you don't have to write the model out to disk.

https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L192

**Comment by faxu** [comment]
@jannavarro do you still need assistance on this?

**Comment by faxu** [comment]
please reopen if addl help is needed.
