### ISSUE TITLE
[Build] make ios dylib erro

### ISSUE THREAD

**Issue by MarsMeng1994** [microsoft/onnxruntime#15536]
### Describe the issue

follow the docs build iOS, but error with
FileNotFoundError: [Errno 2] No such file or directory: 'nuget'
![Uploading image.png…]()

### Target platform

iOS

### Build script

./build.sh --config Release --use_xcode --ios --ios_sysroot iphoneos --osx_arch arm64

### Error / output

FileNotFoundError: [Errno 2] No such file or directory: 'nuget'

**Comment by edgchen1** [comment]
Recently a dependency on nuget was introduced in order to download the protobuf compiler.
https://github.com/microsoft/onnxruntime/commit/df11c8595529c4518e6127696664a0a203a55974
You can either install nuget (https://learn.microsoft.com/en-us/nuget/install-nuget-client-tools) or use your own copy of protoc and provide its path to `--path_to_protoc_exe`.

@snnn Should we document this somewhere?
