### ISSUE TITLE
[Mobile] How Android uses NNAPI to run Stable diffusion

### ISSUE THREAD

**Issue by ZTMIDGO** [microsoft/onnxruntime#15629]
### Describe the issue

Unfortunately, the SD model running on the onnxruntime-android does not support NNAPI

This is my project https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX

The model used https://huggingface.co/TIEMING/Chilloutmix/tree/main

### To reproduce

OrtSession.SessionOptions options = new OrtSession.SessionOptions();
options.addConfigEntry("session.load_model_format", "ORT");
options.addNnapi(EnumSet.of(NNAPIFlags.CPU_DISABLED));
OrtSession session = OrtEnvironment.getEnvironment().createSession(PathManager.getModelPath(context) +"/" +model, options);

The model used https://huggingface.co/TIEMING/Chilloutmix/tree/main

### Platform

Android

### OS Version

android 12

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

v1.14.0

### ONNX Runtime API

Java/Kotlin

### Architecture

ARM64

### Execution Provider

NNAPI

**Comment by wejoncy** [comment]
Hi 
Would you mind pasting the error msg here?

**Comment by wejoncy** [comment]
I guess the error comes from `options.addNnapi(EnumSet.of(NNAPIFlags.CPU_DISABLED));`. If no

**Comment by tianleiwu** [comment]
I think NNAPI EP cannot run stable diffusion. For example, instance normalization is not supported in NNAPI EP according to the document. See operators supported:
https://onnxruntime.ai/docs/execution-providers/NNAPI-ExecutionProvider.html#supported-ops

**Comment by cherrerajobs** [comment]
I would like to mention the following paper from Google regarding stable diffusion on Android devices:
https://arxiv.org/abs/2304.11267

They claim being able to achieve 20 steps of a non 8bit quantized 512x512 generation in about 12 seconds on GPU equipped mobile phones. Android is just about ready to handle some of these bigger models but we need better GPU support. This is serious as I get the feeling other implementations are racing to implement SD support on mobile and I really enjoy the ONNX ecosystem and it's professionalism.

**Comment by tianleiwu** [comment]
To support SD in NNAPI EP, it need add implementation for many operators like LayerNormalization, GroupNorm, Gelu, MultiHeadAttention (with flash attention) etc. 

Contributions are welcome!

@guschmue

**Comment by guschmue** [comment]
@skottmckay must have looked at this.

**Comment by blueokanna** [comment]
It looks good on me, if there support another useful model and replace it it might good. In another way, I still find a way that use GPU to support it and let it run faster than CPU generation.

**Comment by ZTMIDGO** [comment]
> It looks good on me, if there support another useful model and replace it it might good. In another way, I still find a way that use GPU to support it and let it run faster than CPU generation.

The ONNX model can be quantified using code
https://github.com/LowinLi/stable-diffusion-streamlit/blob/main/src/stable-diffusion-streamlit/pages/model/quantization.py

ONNX model
https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/onnx

ORT model format
https://onnxruntime.ai/docs/performance/model-optimizations/ort-format-models.html

**Comment by skottmckay** [comment]
A few notes.

We're limited by 2 things. First, by what NNAPI supports (reference is [here](https://developer.android.com/ndk/reference/group/neural-networks)), and second by which ONNX operators we have implemented conversion to the NNAPI equivalent for in the ORT NNAPI Execution Provider. 

We can add conversion logic for gaps, but we can't change what NNAPI supports.

For a dynamically quantized model, AFAIK there's no NNAPI equivalent to DynamicQuantizeLinear and MatMulInteger. We could possibly implement DynamicQuantizeLinear using lower level ops, but the lack of MatMulInteger would be a blocker. And if you can't quantize the model, would mobile devices be able to load and execute the model due to its size?

As @tianleiwu mentioned there are other important operators required as well. Any gap in operator coverage results in a transition between NNAPI and the CPU EP when executing the model, and those transitions come with a significant performance hit.
