### ISSUE TITLE
[Web]   Uncaught (in promise) TypeError: i2 is null     loadFromOrtFormat model.ts:50

### ISSUE THREAD

**Issue by ghsanti** [microsoft/onnxruntime#15792]
### Describe the issue

The program should run loadFromOnnxFormat but it is running loadFromOrtFormat. You can see what it tries to load and errors here:

```
Uncaught (in promise) TypeError: i2 is null
    loadFromOrtFormat model.ts:50
```

### To reproduce

Code is too long, but I am running this (pseudocode):

``
loadOnnxFile()
session.run(...)
```

This code would run just fine for `"wasm"` and `"cpu"` which I am not sure whether they are different or just aliases for the same thing.

However if I use ["webgl"] I get this random error:



### Urgency

Very urgent

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

    "onnxruntime-web": "^1.14.0"

### Execution Provider

WebGL

**Comment by fs-eire** [comment]
It tries to initialize the model as .onnx format, and if it failed it will try to initialize as .ort format. could you share your model so that I can take a look?

**Comment by mahnehsilla** [comment]
Hi, thanks for the reply. Been trying hard to fix this.

Correct. I tried to convert the model to ORT as well, does it fine but it does not load anyways, because of "integet64 not supported". A shame because the model is quite accurate. 

If what you are planning to check is the support for the operators, I converted the model from here (i think it is the best way to check): https://github.com/Megvii-BaseDetection/YOLOX they provide the pytorch weights in the readme. That should be uploadable to **netron**.

I can share the exact **model.onnx** files or pictures (from Netron) to you but not publicly because it is a private project.

Please, let me know.

**Comment by fs-eire** [comment]
I understand your concern as this is for a private project. the most important thing that helps me to debug the issue is the model structure, which include the input/output datatype, the information about which operators are inside and how they are organized.

So is the model referenced here has the same issue? If so please let me know so I can take investigation. https://github.com/Megvii-BaseDetection/YOLOX/tree/main/demo/ONNXRuntime

**Comment by mahnehsilla** [comment]
> So is the model referenced here has the same issue? If so please let me know so I can take investigation. https://github.com/Megvii-BaseDetection/YOLOX/tree/main/demo/ONNXRuntime

It this neural network that I am only fine tuning, the specific type is the `yolox_s`.
