### ISSUE TITLE
[Web] A tensor's dims must be a number array

### ISSUE THREAD

**Issue by bhomaidan1990** [microsoft/onnxruntime#15987]
### Describe the issue

I get this error when I try to do inference using MNIST:
```js
const imgData = this.ctx.getImageData(0, 0, this.CANVAS_SIZE, this.CANVAS_SIZE);
let img_arr= new Float32Array(imgData.data); //560 x 560 = 313600
const dims = [1, 1, 560, 560];
const input = new ort.Tensor(img_arr, "float32", dims);
```
#### Error:
```
A tensor's dims must be a number array
```

### To reproduce

I have created [this repository](https://github.com/bhomaidan1990/onnx_vue) to reproduce this problem.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14

### Execution Provider

'webgl' (WebGL)

**Comment by bhomaidan1990** [comment]
It seems that the order of the parameters has been changed in the new API:
```js
let img_arr = new Float32Array(imgData.data); //560 x 560 = 313600
const dims = [1, 1, 560, 560];
const input_tensor = new ort.Tensor("float32", img_arr, dims);
```

**Comment by fs-eire** [comment]
according to [`Tensor`'s constructor](https://onnxruntime.ai/docs/api/js/interfaces/TensorConstructor.html#constructor.new_TensorConstructor-2), your code passes the arguments incorrectly.

```
const input = new ort.Tensor(img_arr, "float32", dims);
```
should be 
```
const input = new ort.Tensor("float32", img_arr, dims);
```

you may think the error message is confusing... It's because the constructor also supports:
```
// no need to specify 'type', as it is inferred to 'float32' because img_arr is Float32Array
const input = new ort.Tensor(img_arr, dims);
```

so if the arg[0] is not Float32Array, the constructor will assume arg[1] is dims, this is why the error message occurs.
