### ISSUE TITLE
what's the status of dev/opencl branch? will it be release in the any future release?

### ISSUE THREAD

**Issue by ldfandian** [microsoft/onnxruntime#16312]
### Describe the issue

what's the status of dev/opencl branch? will it be release in the any future release? @cloudhan 

currently, for android onnx runtime, only nnapi is supported but it is kinda slow and has random performance on different android device.
it looks like dev/opencl would be a very good one-for-all solution for android phone's gpu inference.

### To reproduce

n/a

### Urgency

n/a

### Platform

Android

### OS Version

13

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

n/a

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Other / Unknown

### Execution Provider Library Version

dev/opencl branch

**Comment by cloudhan** [comment]
Due to lacking of internal 1P customer, the effort of opencl support is paused for a long time, and will continue to be so in the foreseeable future.

**Comment by ldfandian** [comment]
> Due to lacking of internal 1P customer, the effort of opencl support is paused for a long time, and will continue to be so in the foreseeable future.

Thanks for the quick response.

It looks like the only Android mobile GPU accelerator that msft/onnxruntime supports is NNAPI... it is pretty useless from the Android point of the view...

Maybe vulkan support is a better choise actually, given that almost every Android machine support vulkan.

**Comment by skottmckay** [comment]
Unfortunately with limited resources we have to prioritize development on things with the best cost/benefit. Adding a new execution provider has a very high cost in terms of development and maintenance. Having concrete production use cases is one part of the benefit, as is the number of scenarios that would be supported. An execution provider that would only be the preferred option on Android devices limits the benefit. Additionally, executing a model using only GPU on a mobile device can negatively impact device responsiveness, which also reduces the number of scenarios where it's the preferred option.

Totally agree that NNAPI is inconsistent in terms of performance due to the lower layer of that being implemented by hardware vendors. However, I'd expect that to improve over time with newer devices having better implementations, and if that happens NNAPI would gradually become the preferred option given it can use GPU as well as NPU.

We do listen to feedback and are happy to consider expanding the opencl execution provider or adding a Vulkan based one if a case can be made to justify the development and maintenance cost of doing so.
