### ISSUE TITLE
Segmentation fault when I import onnxruntime berofe torch

### ISSUE THREAD

**Issue by sesevasa64** [microsoft/onnxruntime#16388]
### Describe the issue

I try to compare EfficientNet inference speed on pytorch and onnx. When I do forward pass of torch model on cuda, I get segmentaion fault. If I first import torch or torchvision, all works normally. It also works fine, if I change device to cpu.

Link to simple reproduction on Colab: https://colab.research.google.com/drive/1LHYKY930ghBPMZ3-t9QY9ivziPFAc1Fr?usp=sharing

### To reproduce

Try to run efficientnet_b3 on cuda when onnxruntime imported before torch:
```python
import onnxruntime as ort
import torch
import torchvision
from torchvision.models import efficientnet_b3, EfficientNet_B3_Weights

model = efficientnet_b3(weights=EfficientNet_B3_Weights.IMAGENET1K_V1)
model = model.to("cuda")

model(torch.randn((1, 3, 224, 224), device="cuda"))
```
Get segmentation fault

### Platform

Linux

### OS Version

Ubuntu 20.04.6 LTS

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.0

**Comment by sesevasa64** [comment]
> The prebuilt onnx runtime packages do not support CUDA 12.0. You will need to build it from source. We can only support one CUDA major version(12.x or 11.x) in the prebuilt packages.

Sorry, this version of CUDA is taken from nvidia-smi, which is wrong I guess
I can reproduce this issue on my local pc in WSL with CUDA 11.8 installed
Google Colab with CUDA 11.8 is also crashing 

`nvcc --version` output on my pc:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by tianleiwu** [comment]
I did some investigation on the colab:

Using a script in https://github.com/microsoft/onnxruntime/issues/11092#issuecomment-1484756347 to run in colab.

When import torch first, cuda and cudnn are loaded from torch package:
```
/usr/local/lib/python3.10/dist-packages/torch/lib/libcublas.so.11
/usr/local/lib/python3.10/dist-packages/torch/lib/libcublasLt.so.11
/usr/local/lib/python3.10/dist-packages/torch/lib/libcudnn.so.8
```

When import ort first, cuda and cudnn are loaded from system like in the colab:
```
/usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.11
/usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.11
/lib/x86_64-linux-gnu/libcudnn.so.8
```
Since the torch installed in the colab is built with CUDA 11.8, let's assume the only difference DLL is cuDNN. 

`torch.backends.cudnn.version()` show `8700` so torch 2.0.1 uses cuDNN 8.7

`pathlib.Path('/lib/x86_64-linux-gnu/libcudnn.so.8').resolve()` shows that `/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0`, so the one used by ORT is cuDNN 8.9.

The solution: try install same cuDNN version used in torch to the system.
