### ISSUE TITLE
pip3 install onnxruntime-directml - Could not find a version that satifies the requirement

### ISSUE THREAD

**Issue by marshalleq** [microsoft/onnxruntime#16442]
### Describe the issue

onnxruntime installs perfectly, however onnxruntime-directml does not.  I have an AMD card so need directml version.
I've tried both Python 3.9 and 3.10, both of which are supposed to be supported.

pip3 install onnxruntime-directml
ERROR: Could not find a version that satisfies the requirement onnxruntime-directml (from versions: none)
ERROR: No matching distribution found for onnxruntime-directml

### To reproduce

Run the following using either python 3.9 or python 3.10:
pip3 install onnxruntime-directml
ERROR: Could not find a version that satisfies the requirement onnxruntime-directml (from versions: none)
ERROR: No matching distribution found for onnxruntime-directml

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, DirectML

### Execution Provider Library Version

5.4.6.50406-148~22.04

**Comment by fdwr** [comment]
> Ubuntu 22.04

Aah, we only publish packages to PIP for ORT+DML with Windows. Is your Ubuntu running as the primary OS or within WSL?

**Comment by marshalleq** [comment]
Ah I had wondered about this, no I am definitely bare metal Ubuntu.  It's quite a problem with AMD cards at present under linux for any ML work, but the price of NVIDIA cards these days as I'm sure you know!

So I've been following the guide at the bottom of this thread: https://github.com/yangxy/GPEN/issues/120

I even made a comment asking if this was for windows, but then _I saw against the package on PyPi that onnxruntime-directml does support Posix Linux_.  So you're saying that it does, but only under WSL?

Is this likely to ever change?  I guess the guide I was following was for windows, or the package mention was a mistake.  I'm leaning toward it was a mistake as I don't think it runs on windows.  Thanks.

**Comment by fdwr** [comment]
> So you're saying that it does, but only under WSL?

For ORT+DML, we only officially support and test on Windows...

| Component | Win | WSL | metal Ubuntu |
|----------------|----|----|----|
| ORT DML EP | ✅ |  ❔ |  ❌  |
| DirectML | ✅ | ✅ |  ❌  |

...but in theory, since ORT builds for Linux, and since DirectML runs on WSL, then it should be possible to build ORT for Linux and use the WSL version of DirectML. So I see no *technical* blockers, but there would be a chunk of build work enabling the DirectML execution provider to build in conjunction with the Windows SDK headers. It's something we've considered before, and although we don't have time right now, if you have the penchant to fork it and attempt, it *should* work 🤞.

**Comment by marshalleq** [comment]
Thanks very much for your detailed reply.  I'm not a developer - can only do basic code compiling, but at least this is some kind of hope!  Will close this now as I guess this has reached it's conclusion.  Thanks again!

**Comment by gboddin** [comment]
It would indeed be respectful to have builds for an OS you're taking advantage in your own instead of a gaslighting consideration :no_mouth:
