### ISSUE TITLE
[Documentation] Missing documentation on CUDA version and CuDNN version on lastest 1.15.x build.

### ISSUE THREAD

**Issue by Shadow-Alex** [microsoft/onnxruntime#16565]
### Describe the documentation issue

Hi, what is the recommended CUDA and cuDNN version for latest 1.15.1 build (win10)? I couldn't find it on the document.
![image](https://github.com/microsoft/onnxruntime/assets/46802674/261cc6d5-33f7-4796-8ede-630fb2168be7)

### Page / URL

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by baijumeswani** [comment]
CUDA version: 11.8 (https://github.com/microsoft/onnxruntime/releases/tag/v1.15.1)
cuDNN version: I think any 8.x should be good. From what I read on https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html#fntarg_4, maybe you can use 8.9.2.

> For best performance, the recommended configuration is cuDNN 8.9.2 on H100 with CUDA 12.0, and cuDNN 8.9.2 on all other GPUs with CUDA 11.8, because this is the configuration that was used for tuning heuristics.


@microsoft/onnxruntime-es would you please share if there is a recommendation on cudnn version?'

**Comment by tianleiwu** [comment]
I recommend cuDNN 8.5~8.7, which shall be compatible with Torch 1.13~2.01. Although ONNX Runtime does not depend on Torch, many users use them together. When you import torch before onnxruntime, you do not need to install cuDNN separately (since PyTorch has it).

If you install cuDNN 8.9, Torch 2.0.1 might crash. See issue https://github.com/microsoft/onnxruntime/issues/16388.

**Comment by snnn** [comment]
The table contains more information than needed. Our prebuilt binaries should work well with any CUDA 11.x version.  The latest is the best. The same for cudnn.

**Comment by natke** [comment]
The document was updated by #17081
