### ISSUE TITLE
[Web] Preserve session in localStorage

### ISSUE THREAD

**Issue by nezaBacar** [microsoft/onnxruntime#16848]
### Describe the issue

Hi, I am building a web app with model inference in browser. Is there a way to preserve an inference session even when the browser window is refreshed? The user experience would be much better if the model only loaded the first time the site was opened and then the session would be stored in local store. 
I tried to save the session into a variable but i realised that the object is not the same as it was before the window reload. If I am not able to store the session is there any way that I created the session faster with the data stored in the object?
Object right after session is created:
![Screenshot 2023-07-25 at 16 35 49](https://github.com/microsoft/onnxruntime/assets/44346767/d2b04a70-5283-4acf-bb8e-565d8d4ec449)
Object after window is reloaded:
![Screenshot 2023-07-25 at 16 35 16](https://github.com/microsoft/onnxruntime/assets/44346767/1986d7bf-80ee-4710-8c73-1f178b11667d)

### To reproduce

/

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

/

### Execution Provider

'webgl' (WebGL), 'wasm'/'cpu' (WebAssembly CPU), 'xnnpack' (WebAssembly XNNPACK), 'webgpu' (WebGPU)

**Comment by fs-eire** [comment]
sessionStorage and localStorage can only use up to 5MB of the space limit, which is unlikely to save all the data required for an inference session.

(FYI, an inference session uses a stateful web assembly program with its dedicated memory, and any GPU resources that available if using WebGL/WebGPU backend)

however, the web assembly files and model files can be stored in IndexDB so that next time the initialization can be accelerated.
