### ISSUE TITLE
[Training] pip onnxruntime-training=1.15.1 should install onnx=1.14.1

### ISSUE THREAD

**Issue by wschin** [microsoft/onnxruntime#17064]
### Describe the issue

I run `pip install onnxruntime-training=1.15.1` in one of PyTorch's CI and my `onnx-weekly` seems replaced by `onnx=1.14`. However, the latest onnx release is 1.14.1 and `pip onnxruntime` doesn't have this problem.

### To reproduce

pip install onnxruntime-training=1.15.1 with a clean environment. Then you will see onnx=1.14 is installed.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### PyTorch Version

Not related

### Execution Provider

Other / Unknown

**Comment by snnn** [comment]
The release is not out yet? https://github.com/onnx/onnx/releases

**Comment by snnn** [comment]
We cannot require our users to install a non-exist version.

**Comment by baijumeswani** [comment]
The difference comes because `onnxruntime-training` takes a dependency on `onnx`: https://github.com/microsoft/onnxruntime/blob/6e6f582e0875f15837b338c402b065fd95e0dd46/requirements-training.txt#L5

Where as `onnxruntime` has no such dependency: https://github.com/microsoft/onnxruntime/blob/main/requirements.txt.in

Since `onnxruntime-training` does not pin the version of onnx, it will pick the latest available on PyPI (not sure why it uninstalled your installation though).
