### ISSUE TITLE
Model inference consumes too much memory

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1725]
**Describe the bug**
Running the model on ONNX Runtime consumes too much memory. During inference, it consumes 10 ~ 20 GB. If deployed on CPU, the inference failed due to `std::bad_alloc`. And similarly for GPU deployment, it failed on `cudaMalloc`.

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.5.0
- Python version: 4.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: TITAN V 12036 Mib

**To Reproduce**
- Run in docker image built from [Dockerfile.source](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.source) or  [Dockerfile.cuda](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.cuda) for GPU in proper release version branch
- After unzipping the file from link in "additional context", run `ensemble_encdec_native_onnx_runtime.py` script in clients folder. You will need to modify the path variable in the script accordingly.

**Expected behavior**
The inference should be able to finish without OOM

**Additional context**
https://drive.google.com/file/d/1dSaB-PjmIuugPaln5cpSqwfNz8re_Nex/view?usp=sharing

**Comment by snnn** [comment]
Would you disable memory pattern and try it again?
https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L223

**Comment by GuanLuo** [comment]
I tried it with the Python binding by specifying session option when loading the model, but the same error occurred when I ran the model.
```Python
session_option = onnxruntime.SessionOptions()
session_option.enable_mem_pattern = False
decoder = onnxruntime.InferenceSession(decoder_path, session_option)
```

**Comment by faxu** [comment]
@guanluo is this still an issue with the latest 1.0 release?

**Comment by GuanLuo** [comment]
I will verify it as soon as possible.

**Comment by Saj1234** [comment]
> @GuanLuo is this still an issue with the latest 1.0 release?

I am running into the same issue with ARM32.  onnxruntime is running on  on raspberry pi edge device module container following this example. 
[YOLOv3 Object Detection on RPi 3 with Azure IoT Edge](https://github.com/microsoft/azure-iot-edge-cv-model-samples/tree/master/IoT/Rpi3-objectdetection)
Opened an  [issue](https://github.com/microsoft/azure-iot-edge-cv-model-samples/issues) in there.
 
I was thinking that this is  due to ARM32  setup and the device maybe under powered. But looks like its actually within onnxruntime regardless the arm architecture.

**Comment by GuanLuo** [comment]
@faxu unfortunately the OOM is still happening in 1.0.0 release

**Comment by yuslepukhin** [comment]
@GuanLuo I assume you are using sequential executor?

**Comment by GuanLuo** [comment]
@yuslepukhin I believe so since the two models are encoder and decoder

**Comment by skottmckay** [comment]
Can you also try disabling the memory arena by calling OrtApi::DisableCpuMemArena? If that and memory pattern are disabled ORT will just call malloc/free for each individual request instead of maintaining it's own buffers/cache in an attempt to minimize allocations. If it still runs out of memory with that setup the model requires more memory than you have available, and the next question would be whether particular operator implementations could be more efficient. 

Note: There's currently no way to disable arena usage on GPU, so please test this on CPU only.

**Comment by hariharans29** [comment]
Hi @GuonLuo,

Does this issue still persist ? If so is the model shareable ? I think this maybe a bad model conversion if it is requesting so much memory - something along the lines of what was happening here - https://github.com/microsoft/onnxruntime/issues/2699

**Comment by GuanLuo** [comment]
Yes the issue still exists... You can obtain the models here: https://drive.google.com/file/d/1dSaB-PjmIuugPaln5cpSqwfNz8re_Nex/view?usp=sharing
