### ISSUE TITLE
AZure VM with ubuntu does not have DLLs in _ld_preload.py

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#17477]
### Describe the issue

https://github.com/microsoft/onnxruntime/blob/29a818caa09ad377d6cc019e11f90630e1eaaf66/setup.py#L115

The Azure VM with Ubuntu does not have "AUDITWHEEL_PLAT" environment variable so is_manylinux=False. Then it will not write the ld_preload according to https://github.com/microsoft/onnxruntime/blob/29a818caa09ad377d6cc019e11f90630e1eaaf66/setup.py#L182-L228.

Is there benefit to have preload? Can we enable it in ubuntu VM as well?

### To reproduce

Install onnxruntime-gpu in an Azure VM with Ubuntu OS, and check onnxruntime/capi/_ld_preload.py in the installed package. The content of the file has only some comments there.

### Platform

Linux

### OS Version

20.04.1-Ubuntu (5.15.0-1042-azure, x86_64 GNU/Linux)

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by snnn** [comment]
Yes, you can. 
You can build the wheels on Ubuntu. You can manually set the missing env. However, first we need to understand why do you need this? The auditwheel tool is for generating a redistributable manylinux wheel file for many different Linux distros. If your purpose is to setup a new build pipeline, I discourage using Ubuntu in our packaging pipelines. Or if your purpose is to generate a wheel file that just is just for this machine or just for Ubuntu and you do not have an interest to publish the wheel file to pypi, you do not need to run this auditwheel tool.

Even in CentOS the AUDITWHEEL_PLAT was manually set in Dockerfiles. The tool treats CentOS and Ubuntu the same. Who run the tool or who build the docker image needs to set up the env. 



Also please be aware that the tool is for generating a redistributable wheel file for many different Linux distros, but the tool itself is not designed to run on many different Linux distros. Only the wheels files it generates are.  In the past the tool only supports CentOS. Recently it added Ubuntu support so you can use it on Ubuntu.

**Comment by snnn** [comment]
> Is there benefit to have preload?

The reason we have this "preload" thing was because we need to a way to bypass manylinux's shared library check. In order to be compliant with manylinux standard, we need to pack all the dependent shared libs (that are not listed in https://github.com/pypa/auditwheel/blob/main/src/auditwheel/policy/manylinux-policy.json) in the wheel file. It means we should pack CUDA and CUDNN libs in our wheel file. However, it will make our wheel file super huge and oversize.  You know how big CUDA and CUDNN are. So, we chose a workaround. We used patchelf tool to modify the onnxruntime_pybind11_state.so file (and other shared libs we generate) so that the so file doesn't claim it depends on CUDA libs. It means when Linux loads the so file, Linux won't auto load cuda libs. Therefore we need to manually load CUDA libs before we load the so file. The loading is done in the _ld_preload.py you mentioned above.  All these tricks were just for making onnxruntime_gpu wheel file passing `auditwheel` tool's check. There is no performance benefit, and it has extra side effects.  So in a recent PR #17365 I removed the tricks. From now on the preload script will only be empty.

**Comment by tianleiwu** [comment]
@snnn, thanks for the information.

I asked this since optimum uses the file to check whether onnxruntime-gpu is installed in Linux. See https://github.com/huggingface/optimum/pull/771.
The check of _ld_preload.py in optimum shall be removed.
