### ISSUE TITLE
floating point exception

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1767]
I am try to inference maskrcnn onnx model using onnxruntime, but we got something wrong:

```
floating point exception
```
The model comes from onnx model zoo, I want to know, does this a bug or anything wrong, codes reproduce:

```
"""

Try inference on MaskRCNN using onnx

"""
import os
import sys
import numpy as np
from PIL import Image
import math
from alfred.utils.log import logger as logging
import onnxruntime as rt


def preprocess(image):
    # Resize
    ratio = 800.0 / min(image.size[0], image.size[1])
    image = image.resize((int(ratio * image.size[0]), int(ratio * image.size[1])), Image.BILINEAR)
    # Convert to BGR
    image = np.array(image)[:, :, [2, 1, 0]].astype('float32')
    # HWC -> CHW
    image = np.transpose(image, [2, 0, 1])
    # Normalize
    mean_vec = np.array([102.9801, 115.9465, 122.7717])
    for i in range(image.shape[0]):
        image[i, :, :] = image[i, :, :] - mean_vec[i]
    # Pad to be divisible of 32
    padded_h = int(math.ceil(image.shape[1] / 32) * 32)
    padded_w = int(math.ceil(image.shape[2] / 32) * 32)
    padded_image = np.zeros((3, padded_h, padded_w), dtype=np.float32)
    padded_image[:, :image.shape[1], :image.shape[2]] = image
    image = padded_image
    return image


img_f = 'images/horses.jpg'
if len(sys.argv) > 1:
    img_f = sys.argv[1]
    print('predicting image: {}'.format(sys.argv[1]))
img = Image.open(img_f)
img_data = preprocess(img)
print(img_data)

sess = rt.InferenceSession("models/mask_rcnn_R_50_FPN_1x.onnx")
input_name = sess.get_inputs()[0].name
logging.info(input_name)
out = sess.run(None, {input_name: img_data})
logging.info('out: {}'.format(out))
```

**Comment by jinfagang** [comment]
```
INFO 09-06 15:25:46 demo_onnxrt_maskrcnn.py:46 - image
[1]    26685 floating point exception  python3 demo_onnxrt_maskrcnn.py

```

**Comment by skottmckay** [comment]
I tried using this python code with an arbitrary image from the coco1200 set and the model from the model zoo and it ran successfully. Can you provide details on how ORT was built and maybe the image you're attempting to use?

**Comment by nieyan** [comment]
I got the same error using onnxruntime, model was mobilenetv2 which came from onnx model zoo. It seems because of my enviroment, but I can't find out.

### System information

OS Platform and Distribution :Linux Ubuntu 18.04(virtual machine)
ONNX Runtime installed from :binary(pip install onnxruntime)
ONNX Runtime version:0.5
onnx version:  1.6.0                
Python version:3.7.3
Visual Studio version (if applicable):no
GCC/Compiler version (if compiling from source):7.4.0
CUDA/cuDNN version: just CPU
GPU model and memory:just CPU

### Code for test:

import onnxruntime
import numpy as np
ort_session = onnxruntime.InferenceSession('mobilenetv2-1.0.onnx')
X = np.random.random((1, 3, 224, 224)).astype(np.float32)
ort_inputs = {ort_session.get_inputs()[0].name: X}
ort_outs = ort_session.run(None, ort_inputs)

### Error message:
[1]    5400 floating point exception (core dumped)

**Comment by nieyan** [comment]
> I got the same error using onnxruntime, model was mobilenetv2 which came from onnx model zoo. It seems because of my enviroment, but I can't find out.
> 
> ### System information
> OS Platform and Distribution :Linux Ubuntu 18.04(virtual machine)
> ONNX Runtime installed from :binary(pip install onnxruntime)
> ONNX Runtime version: 0.5.0
> onnx version: 1.6.0
> Python version:3.7.3
> Visual Studio version (if applicable):no
> GCC/Compiler version (if compiling from source):7.4.0
> CUDA/cuDNN version: just CPU
> GPU model and memory:just CPU
> 
> ### Code for test:
> import onnxruntime
> import numpy as np
> ort_session = onnxruntime.InferenceSession('mobilenetv2-1.0.onnx')
> X = np.random.random((1, 3, 224, 224)).astype(np.float32)
> ort_inputs = {ort_session.get_inputs()[0].name: X}
> ort_outs = ort_session.run(None, ort_inputs)
> 
> ### Error message:
> [1] 5400 floating point exception (core dumped)

Found virtual machine bring that error.
