### ISSUE TITLE
[Build] Building --config Debug on Windows with TensorRT fails

### ISSUE THREAD

**Issue by BengtGustafsson** [microsoft/onnxruntime#18029]
### Describe the issue

When building the Debug configuration of onnxruntime using VS2022 there seems to be an issue with the set include paths:
I get an error:

C:\gl\thirdpartylibs\onnxruntime\build\WindowsD\Debug\_deps\onnx_tensorrt-src\ImporterContext.hpp(10,10): fatal  error C1083: Cannot open include file: 'onnx/common/stl_backports.h': No such file or directory (compiling source file C:\gl\thirdpartylibs\onnxruntime\build\WindowsD\Debug\_deps\onnx_tensorrt-src\builtin_op_importers.cpp) [C:\gl\thirdpartylibs\onnxruntime\build\WindowsD\Debug\_deps\onnx_tensorrt-build\nvonnxparser_static.vcxproj]

I have found said header file in: C:\gl\thirdpartylibs\onnxruntime\cmake\external\onnx\onnx\common which leads me to believe that an appropriate include path is missing.

Note that with --config Release this works.

My guess is that this has to do with the patch introduced for some other VS/Debug issue (https://github.com/microsoft/onnxruntime/issues/16273)  that causes the printout:

-- [Note] There is an issue when running "Debug build" TRT EP with "Release build" TRT built-in parser on Windows. This build will use tensorrt oss parser instead.

not being appropriately accompanied with its required include path changes.

### Target platform

Windows 64 bits

### Build script

c:\gl\thirdpartylibs\onnxruntime>build.bat --config Debug --parallel 4 --build_shared_lib --build_dir build/WindowsD --skip_tests --use_tensorrt --use_dml --cuda_version=11.6 --cuda_home "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA" --cudnn_home "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA" --tensorrt_home "C:/Program Files/NVIDIA GPU Computing Toolkit/TensorRT-8.6.1.6"

### Error / output

Several lines like:

C:\gl\thirdpartylibs\onnxruntime\build\WindowsD\Debug\_deps\onnx_tensorrt-src\ImporterContext.hpp(10,10): fatal  error C1083: Cannot open include file: 'onnx/common/stl_backports.h': No such file or directory (compiling source file C:\gl\thirdpartylibs\onnxruntime\build\WindowsD\Debug\_deps\onnx_tensorrt-src\builtin_op_importers.cpp) [C:\gl\thirdpartylibs\onnxruntime\build\WindowsD\Debug\_deps\onnx_tensorrt-build\nvonnxparser_static.vcxproj]

### Visual Studio Version

VS2022

**Comment by chilo-ms** [comment]
The compile error `"Cannot open include file: 'onnx/common/stl_backports.h': No such file or directory"` is because ONNX [removed](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fonnx%2Fonnx%2Fpull%2F5370&data=05%7C01%7CChi.Lo%40microsoft.com%7Cb6faf713feef4199ba4708dbc5c287ba%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638321211530547390%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zxlAusesDhKqKEKNoqUddurssC2a6Di%2BmK7YBVAIYT0%3D&reserved=0) stl_backports.h months ago but the [onnx-tensorrt parser](https://github.com/onnx/onnx-tensorrt) ORT uses is still the older version.
So, two suggestions here:

- Please modify the [deps.txt](https://github.com/microsoft/onnxruntime/blob/main/cmake/deps.txt) to make it uses older onnx version. (Following is ORT 1.16.0 which uses ONNX commit e2525550194ce3d8a2c4a3af451c9d9b3ae6650e)
    


      -onnx;https://github.com/onnx/onnx/archive/14303de049144035dfd94ace5f7a3b44773b1aad.zip;250eab9690392b248d75b56e605fb49eca373442
      +onnx;https://github.com/onnx/onnx/archive/e2525550194ce3d8a2c4a3af451c9d9b3ae6650e.zip;782f23d788185887f520a90535513e244218e928

- Or please modify the line onnx_tensorrt in deps.txt to make it use the latest onnx-tensorrt commit. We will update this soon.
(Note: The xxx.zip is the commit value and the last random number is the SHA1 of that zip file)

As for why this issue only shows up in "Debug" mode not "Release" mode. It's because we implicit builds onnx-tensorrt parser along with ORT when in "Debug" mode due to known issue. However, in "Release" mode, we don't build the parser but instead link ORT against the built-in parser that comes with TRT libraries.

**Comment by chilo-ms** [comment]
https://github.com/microsoft/onnxruntime/pull/18067
The main branch now uses the latest onnx-tensorrt repos.
