### ISSUE TITLE
[LayerNormalization Operator] Why LayerNormalization do not support weight and bias auto broadcast.

### ISSUE THREAD

**Issue by triple-Mu** [microsoft/onnxruntime#18184]
### Describe the issue

Input is [1, 16, 256, 256]
I want to do layernorm in axes 1 and the weight and bias shape is [1, 16, 1, 1].
It will broadcast to [1, 16, 256, 256].
But the error is:
``` text
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running LayerNormalization node. Name:'/LayerNormalization' Status Message: Size of X.shape()[axis:] == 1048576. Size of scale and bias (if provided) must match this. Got scale size of 16 and bias size of 16
```
So what can i do?

### To reproduce

![2023-10-31_13-45](https://github.com/microsoft/onnxruntime/assets/92794867/7fab943d-2846-40ef-8425-c7ca60a49bef)

### Platform

Linux

### OS Version

ubuntu 20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

cpu

### Is this a quantized model?

No

**Comment by tianleiwu** [comment]
It's valid case according to onnx spec `This operator supports unidirectional broadcasting (tensors Scale and B should be unidirectional broadcastable to tensor X)`.

ORT does not support it yet since the original implementation for ms domain (before the operator added to onnx domain) does not support broadcasting.
