### ISSUE TITLE
Expand fails with -1 in the size

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#1840]
**Describe the bug**

When there is -1 in expand the axis is not inferred and instead is used as -1

> RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:332 void onnxruntime::BroadcastIterator::Append(int64_t, int64_t) axis == 1 \|\| axis == largest was false. Attempting t o broadcast an axis by a dimension other than 1. -1 by 6

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 0.4/0.5
- Python version: 3.5

**To Reproduce**
```python
a = x.expand([-1, 2, -1])
```

**Expected behavior**
Treat -1 correctly in [expand](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.expand):
> Passing -1 as the size for a dimension means not changing the size of that dimension.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by hariharans29** [comment]
Hi @dashesy,

This maybe a useful enhancement but this issue is for the ONNX repo and for the ONNX community to accept it and if accepted this op can be enhanced in its next version.

AFAIK, the current 'Expand' implementation in ORT adheres to spec in not allowing negative values as the op spec states that it is similar to `numpy.broadcast_to()` (with the minor exception which is documented). numpy.broadcast_to does not accept `-1` in its shape. Also the op states that the functionality of the op is `numpy.array(input) * numpy.ones(shape)` and we can't feed in negative values for the shape in this case either. 

So, this seems specific to Torch and this one should be raised in ONNX and if accepted - ORT can support it.

Thanks

**Comment by hariharans29** [comment]
Please re-open if you need further clarifications.

**Comment by leimao** [comment]
I got `expand` in the PyTorch code. Sounds like this is the source of the error.
