### ISSUE TITLE
[DmlEP] BeamSearch node is not supported for DmlEP?

### ISSUE THREAD

**Issue by trajepl** [microsoft/onnxruntime#18805]
### Describe the issue

![image](https://github.com/microsoft/onnxruntime/assets/13343117/2c8f791a-c8a7-4e00-8af6-d7e543b4fece)
 Could not find an implementation for BeamSearch node even if I enable onnxruntime extensions for Dml EP.

### To reproduce

Install DmlEP, run whisper example https://github.com/microsoft/Olive/tree/main/examples/whisper.

Remembered to change the ep to 
![image](https://github.com/microsoft/onnxruntime/assets/13343117/43e94ef1-d2f8-4ec4-bd85-4de45bd54064)

### Platform

Windows

### OS Version

Win11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

DirectML

**Comment by fdwr** [comment]
[com.microsoft.BeamSearch](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.BeamSearch) isn't supported by the DML Execution Provider (see the [DML EP kernel list](https://github.com/microsoft/onnxruntime/blob/main/docs/OperatorKernels.md#dmlexecutionprovider)), but you *should* still get fallback to the CPU for this operator though. So why that's not happening is the question. I suspect @PatriceVignola would be more familiar with this area (noting you're using Whisper and Olive), since he's been trying a number of transformer models lately.

**Comment by trajepl** [comment]
Thanks for your answer. So sounds like it is hard to [1]**run generation task in DmL-gpu** if we want to insert beam search node into onnx graph. The expected behavior should fallback to CPU but the performance will be impacted. 

I am the Olive contributor actually. Just want to double check if [1] is supported in Dml EP as current example in Olive for Eml use optimum for generation tasks.

**Comment by trajepl** [comment]
As for the failure of fallback, I doubt it is my local env issue. Switched to another linux machine, it worked.  So I will close this issue.
Thanks! fdwr

**Comment by fdwr** [comment]
> if we want to insert beam search node into onnx graph

Reading [com.microsoft.BeamSearch](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.BeamSearch), it doesn't sound like a very GPU-amenable operator, with subgraphs and variable size ngrams and tokens. Hopefully it's an operator than just occurs once or a few times in the graph.

> As for the failure of fallback ... Switched to another linux machine, it worked. 

🤔 DML doesn't run on raw Linux. Did you mean using the DML EP atop WSL?

> Just want to double check if [1] is supported in Dml EP as current example in Olive 

Sounds like the current answer is no 😉, not until the bug is figured out.

**Comment by trajepl** [comment]
Thanks! 👍 Yes it seems the graph transformer issue and I will reach our Pat for help if needed. 

> 🤔 DML doesn't run on raw Linux. Did you mean using the DML EP atop WSL?

Oh, I mean the fallback logics not limited to the EP.
