### ISSUE TITLE
[Web] [WebGPU] Non-zero status code returned while running Clip node

### ISSUE THREAD

**Issue by nagadomi** [microsoft/onnxruntime#19402]
### Describe the issue

I tried `webgpu` EP with the latest release 1.17.0 and got the following error:
```
2024-02-03 22:27:17.382700 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Clip node. Name:'/Clip_1' Status Message: Failed to run JSEP kernel
j @ 6865e4a4-e2f8-4435-a1a3-cddbd51b6520:8
test.html:22 

Uncaught (in promise) Error: [WebGPU] Kernel "[Clip] /Clip_1" failed. Error: Failed to generate kernel's output[0] with dims [1,440,440,3]. If you are running with pre-allocated output, please make sure the output type/dims are correct. Error: 18162040
    at Object._OrtRun (6865e4a4-e2f8-4435-a1a3-cddbd51b6520:6:1567)
    at async Tu (6865e4a4-e2f8-4435-a1a3-cddbd51b6520:2107:27147)
```

### To reproduce

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <script src="//cdn.jsdelivr.net/npm/onnxruntime-web@1.17.0/dist/ort.webgpu.min.js"></script>
    <script>
     const BACKEND = "webgpu"; // works in `wasm`
     async function test()
     {
       const ses = await ort.InferenceSession.create(
         "cunet_art_noise3_scale2x.onnx",
         { executionProviders: [BACKEND] });
       const x = new ort.Tensor('float32', new Float32Array(3 * 256 * 256), [1, 3, 256, 256]);
       var out = await ses.run({"x": x})
       console.log(out.y.dims);
     }
     document.addEventListener("DOMContentLoaded", async function(event) { 
       console.log("load");
       ort.env.wasm.proxy = true;
       ort.env.wasm.simd = true;
       ort.env.wasm.numThreads = 1;
       await test();
     });
    </script>
  </head>
  <body>
  </body>
</html>
```
[cunet_art_noise3_scale2x.zip](https://github.com/microsoft/onnxruntime/files/14151559/cunet_art_noise3_scale2x.zip)

- The model works with `wasm`, but has never worked with `webgpu` before
- The model is a super-resolution model for BCHW input/output
- The model uses negative values as `Pad` arguments

The error message seems to assume that the output shape is `[1,440,440,3]`(BHWC), but the correct shape is `[1,3,440,440]`(BCHW).

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.0

### Execution Provider

'webgpu' (WebGPU)

**Comment by fs-eire** [comment]
I can reproduce this issue. This may be a problem of the NHWC transform optimizer. I will take a further look.

**Comment by fs-eire** [comment]
Update: After some debugging, I found that the problem is the original model is invalid.

![image](https://github.com/microsoft/onnxruntime/assets/7679871/b5f0c0b5-33ce-4307-b502-589f17137820)

The model defines its input `x` as shape [batch_size, 3, height, width] and output `y` as shape [batch_size, clipy_dim_1, height, width]. However the actual input shape is [1, 3, 256, 256] and output shape is [1, 3, 440, 440]. This confused ONNX Runtime NHWC transformer because `height` and `width` cannot be 256 and 440 at the same time during one inference run call. Somehow the error message is a little bit confusing.

The solution is to re-export the model, with different names for output shape placeholders, like `height_out` and `width_out`. They need to be different to the input names so they can have different value.

**Comment by fs-eire** [comment]
The reason why you see shape [1, 440, 440, 3] is because when you use WebGPU, it requests the NCHW transformer to transform the graph to use channel last instead of channel first. A "Transpose" will be added to the begin and end of the original graph so the E2E shape/data is equivalent. This is a little bit confusing but not the cause of the issue.

**Comment by nagadomi** [comment]
Thanks for the debugging.
I will try to fix the export code.

I thought there was nothing wrong with the model since it has been working fine with python onnx(CUDA and CPU EP) and wasm EP and onnx.checker.check_model() doesn't report any problems.
