### ISSUE TITLE
[Mobile] [Python][MacOS] Why outputs so different between android and python, even if inputs and the model.onnx are the exactly same?

### ISSUE THREAD

**Issue by thelou1s** [microsoft/onnxruntime#19449]
### Describe the issue

Hi, 
Why outputs so different between android and python, even if inputs and the model.onnx are the exactly same?
I checked python onnx runtime version 1.16.3, checked android onnx runtime version 1.16.3. But got so diff outputs on same inputs. please help, thank you.

![image](https://github.com/microsoft/onnxruntime/assets/5654770/9dc02be9-b779-4d7a-a912-abf9e96c7da0)

![image](https://github.com/microsoft/onnxruntime/assets/5654770/6d35329d-d8e5-4e40-9798-935b1b05fa39)

![image](https://github.com/microsoft/onnxruntime/assets/5654770/1f09cab9-5922-4d22-8203-4d53231bcc79)

### To reproduce

1.run python to predict a wav file
2.run android app to predict the same wav file
3.get so diff outputs

### Platform

Android

### OS Version

Android 10

### ONNX Runtime Installation

Released Package

### Compiler Version (if 'Built from Source')

1.16.3

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

C++/C

### Architecture

ARM64

### Execution Provider

Other / Unknown

**Comment by skottmckay** [comment]
Different numbers are expected especially if the model involves lots of floating point operations (e.g. look for MatMul/Gemm/Conv operations in the model)

The order of the individual operations will affect the exact value produced by each node. There are [many additions and multiplications](https://en.wikipedia.org/wiki/Matrix_multiplication) in a single MatMul and MatMul is used in Gemm and Conv and other operations. The order of each set of multiplications matter. The order those are added together matter. But there's no rule about the order. i.e. mathematically a x b x c == c x b x a, but you'll get two different results due to how floating-point numbers work.

The low-level instructions used to execute the operations differ by platform/architecture (e.g. various AVX instruction sets on intel/amd, NEON on arm, etc.). These differences accumulate with each node and are magnified by nodes that do a lot of calculation (e.g. MatMul/Conv/Gemm).

All these things contribute to differences when the same model is run with the same input on different platforms or with different execution providers on the same platform.

Are the predictions after converting the raw float outputs into something meaningful different?
