### ISSUE TITLE
Missing MacOS arm64 and x86_64 wheels for v1.17.0 in PyPi

### ISSUE THREAD

**Issue by dmitry-danilov** [microsoft/onnxruntime#19555]
### Describe the issue

MacOS arm64 and x86_64 wheels are missing for v1.17.0 in PyPi - only universal2 are present. This causes `pip install onnxruntime==1.17.0` to fail on MacOS with the error below:

`ERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.0 (from versions: 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.17.0
`

Python v3.11
pip v24.0

### To reproduce

run `pip install onnxruntime==1.17.0` on MacOS

### Platform

Mac

### OS Version

Sonoma 14.0

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by dmitry-danilov** [comment]
Happy to confirm `SYSTEM_VERSION_COMPAT=0 pip install onnxruntime==1.17.0` fixed the issue for me.
Many thanks!

**Comment by ckot** [comment]
I tried `SYSTEM_VERSION_COMPAT=0 pip install onnxruntime==1.17.0` but I still get 

ERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.17.0

is this due to macOS 10.15.7 (Catalina) being too ancient for this trick?
