### ISSUE TITLE
[Training] Convert to onnx with opset 16 but cannot find an implementation for operator Cos with opset 7.

### ISSUE THREAD

**Issue by SunHaoOne** [microsoft/onnxruntime#19710]
### Describe the issue

I have convert the onnx with opset 16, but cannot run it with ort. It said `onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Cos(7) node with name '/encoder/Cos'`
I have provided more details in this issue. Could you please give me some ideas?

### To reproduce

#19414

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### PyTorch Version

2.1.1+cu118

### Execution Provider

Default CPU

### Execution Provider Library Version

cu118

**Comment by baijumeswani** [comment]
Are you able to share the onnx model?

**Comment by SunHaoOne** [comment]
> Are you able to share the onnx model? Or if you're able to share the all the steps such that I can reproduce this on my end, I can take a deeper look.

Thanks for your reply, I update the `onnx` file here. By the way, the model can be successfully run by tensorRT.
[model.zip](https://github.com/microsoft/onnxruntime/files/14455269/model.zip)

**Comment by baijumeswani** [comment]
I think the problem seems to be that the model is using `Cos` for inputs with types `float64`:

![image](https://github.com/microsoft/onnxruntime/assets/12852605/39a85853-04f2-466c-bc0e-8021da3a743d)


The problem is that onnxruntime has not defined a kernel for Cos that takes in tensors of type double. See [here](https://github.com/microsoft/onnxruntime/blob/2a857d9a86ca3049829256df3347521069ccd6b4/onnxruntime/core/providers/cpu/math/element_wise_ops.cc#L1362-L1366).

Are you able to change your model to use float 32 inputs?
