### ISSUE TITLE
@parcel/resolver-default: Could not load './dist/ort-web.min.js' from module 'onnxruntime-web' found in package.json#browser

### ISSUE THREAD

**Issue by abhijithbabu** [microsoft/onnxruntime#19915]
### Describe the issue

When you using parcel and latest version of onnxruntime-web (1.17.1), I am getting following error 

@parcel/resolver-default: Could not load './dist/ort-web.min.js' from module 'onnxruntime-web' found in package.json#browser 

seems like package.json has "browser": "dist/ort-web.min.js", which doesn't exist.

Thanks

### To reproduce

Use latest version of onnxruntime-web (1.17.1)
and import as below
import {env, InferenceSession, Tensor} from 'onnxruntime-web';

When using parcel to start dev, the error is observed

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### Execution Provider

Other / Unknown

**Comment by paramonych** [comment]
I have exactly the same issue.

After installing the package [as described here](https://onnxruntime.ai/docs/get-started/with-javascript/web.html#install) (tried both ways) :
```
# install latest release version
npm install onnxruntime-web

# install nightly build dev version
npm install onnxruntime-web@dev
```
The following error occurs when trying to build the project with parcel, because apparently the required _**ort-web.min.js**_ is not anywhere near (please find two attached screenshots below).

Please advice!

![Screenshot from 2024-03-25 10-50-32](https://github.com/microsoft/onnxruntime/assets/2950010/439551e8-1bf2-4eef-844e-053bf425c4a1)

![photo_2024-03-25_10-55-28](https://github.com/microsoft/onnxruntime/assets/2950010/c6db9e4d-e489-4c7e-9ae5-ba5481767199)

**Comment by paramonych** [comment]
I have exactly the same issue.

After installing the package [as described here](https://onnxruntime.ai/docs/get-started/with-javascript/web.html#install) (tried both ways) :
```
# install latest release version
npm install onnxruntime-web

# install nightly build dev version
npm install onnxruntime-web@dev
```
The following error occurs when trying to build the project with parcel, because apparently the required _**ort-web.min.js**_ is not anywhere near (please find two attached screenshots below).

Please advice!

![photo_2024-03-25_11-04-17](https://github.com/microsoft/onnxruntime/assets/2950010/f778d575-f6f0-4ce0-b8fd-77fb24a5a721)

![photo_2024-03-25_10-55-28](https://github.com/microsoft/onnxruntime/assets/2950010/c6db9e4d-e489-4c7e-9ae5-ba5481767199)

**Comment by fs-eire** [comment]
@paramonych thanks for your feedback. Could you try if [this](https://parceljs.org/blog/v2-9-0/#new-resolver) fixes the problem?

**Comment by ex3ndr** [comment]
I have the same problem in React Native project, everything works fine for native apps, but for web it can't resolve modules. Also enabling new exports support is not possible in my project (it breaks a lot of other dependencies)
