### ISSUE TITLE
[Documentation] What's the relation ship between NHWC and amd64, NHWC and arm64, NCHWc and amd64, QDQIsInt8Allowed and arm

### ISSUE THREAD

**Issue by deahhh** [microsoft/onnxruntime#20218]
### Describe the documentation issue

I am puzzled by the help of parameter `target_plantform` for `onnxruntime.tools.convert_onnx_models_to_ort`
is it true that NCHWc format onnx model cannot be converted to ort?

**Comment by skottmckay** [comment]
ORT format is an alternative version of the ONNX model that is required to use onnxruntime when you do a minimal build to reduce binary size. This is generally only applicable in some mobile/edge scenarios. i.e. don't use it unless you require an ORT binary to be as small as possible.

All ONNX format models are NCHW.  The ONNX spec only supports this layout.

Different platforms have different preferences. 
NCHWc is a format that can be used on amd64 devices. ORT has internal operators that use this format. 
NHWC is the preferred layout on ARM devices. ORT has internal operators that use this format.

In typical usage we apply platform specific optimizations like converting parts of the model to NCHWc or NHWC at runtime so we know the current platform and what works best.

The ORT format model is created offline, so may be used on a different platform. In order to make sure we don't use the incorrect optimizations for the target platform, the user can specify that when converting an ONNX model to ORT format.

**Comment by deahhh** [comment]
@skottmckay,
Thank you so much. After reading your explanation, it was instantly clear to me. No more struggling to convert ONNX models from NCHW format to NHWC format.
However, you guys are so awesome that you can do this format conversion at runtime. I tried to convert before and found it difficult to do it for specific models.
Thanks again!

**Comment by Rohanjames1997** [comment]
@skottmckay thanks for this answer! I had a follow-up question:

>NHWC is the preferred layout on ARM devices. ORT has internal operators that use this format.
In typical usage we apply platform specific optimizations like converting parts of the model to NCHWc or NHWC at runtime so we know the current platform and what works best.

Could you, or someone else, point me to where the ARM-specific conversion to NHWC occurs? 
I'm trying to avoid this conversion, as I'm implementing NCHWc Conv on ARM as well. 

Thanks!
