### ISSUE TITLE
[Performance]  inference is too slow

### ISSUE THREAD

**Issue by feff2** [microsoft/onnxruntime#20241]
### Describe the issue

I tested the mobile vit and vit tiny. Mobile vit has only 1,935,169 parameters, while ViT tiny has 5,527,701. At the same time, ViT tiny works faster on a mobile device than Mobile ViT without using NNAPI. Mobile ViT gets ahead a bit, with the using NNAPI. I added custom layter from onnxruntime-extensions to both models.

Here is the time of the working for pipeline:
mobile: 6 221,75 ms
tiny: 4 832,15 ms 
mobile with nnapi: 4 216,05 ms

### To reproduce

I tried to convert Mobile ViT to .ort format, but but the inference has become even slower

### Platform

Android

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.0.

### ONNX Runtime API

Python

### Architecture

Other / Unknown

### Execution Provider

NNAPI

### Is this a quantized model?

No

**Comment by skottmckay** [comment]
ORT format has the same info as the ONNX model, but you might lose some runtime optimizations when you use it. ORT format is about reducing the binary size rather than improving performance. Use ONNX format unless you have to use a minimal build due to a hard constraint on binary size.

Performance depends on the nodes in the model. One model could have more parameters but less layers and be faster. You'd have to look at the difference between the two models using something like Netron to get an idea of why a model with a lot more parameters runs faster. 

FWIW NNAPI performance differs massively by device. If you're trying to get a general idea about the performance of two models compare using the CPU EP. Using NNAPI would be a later choice that you make by perf testing with and without the NNAPI EP enabled on each specific device.

**Comment by feff2** [comment]
Thanks!
