### ISSUE TITLE
Ensures <li> elements are used semantically (li:nth-child(3)): A11y_WCP URLs - ONNX Runtime_AI4W

### ISSUE THREAD

**Issue by aniketr99** [microsoft/onnxruntime#20261]
## GitHub Tags: 
#A11ySev2; #A11yTCS; #DesktopWeb; #SH_ONNX Runtime & Ecosystem_Web_Mar2024; #ONNX Runtime & Ecosystem; #WCP; #Win11; #FTP; #P3_WCP; #ONNX Runtime; #ChromiumEdge; #A11yMAS; #WCAG1.3.1; #A11yAuto; #Info and relationships; #Accessibility; #listitem; 

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".** 

## Environment Details: 
Application Name: WCP URLs - ONNX Runtime 
URL: https://onnxruntime.ai/training
Edge version: 124.0.0.0 (Official build) (64-bit) 
OS: Windows 11 version 23H2

## Issue: 
Ensures < li> elements are used semantically (listitem - https://accessibilityinsights.io/info-examples/web/listitem)

## Target application: 
ONNX Runtime | Training - https://onnxruntime.ai/training

## Element path: 
div[data-svelte-h="svelte-1fow8f8"] > li:nth-child(3)

## Snippet: 
< li>Image / Audio classification</li>

### Fix any of the following:
  List item does not have a < ul>, < ol> parent element

## Environment: 
Microsoft Edge version 124.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.41.0 (axe-core 4.7.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

## Attachment:
![image](https://github.com/microsoft/onnxruntime/assets/100269580/3d804d26-0077-4ffe-a7eb-ec0c547e3d9b)

**Comment by PadminiGariki** [comment]
Verified the issue in below environment.
Application Name: WCP URLs - ONNX Runtime
URL: https://onnxruntime.ai/training
Edge version:125.0.2535.92 (Official build) (64-bit)
OS: Windows 11 version 23H2

Issue is fixed. Hence the bug is closed.
For reference attachment is added.

#Regressed:06-13-24; #Closed;

Attachment:

![Screenshot 2024-06-13 121038](https://github.com/microsoft/onnxruntime/assets/142479541/bc7b629d-1894-4731-81b4-3c3e7a10b5b3)
