### ISSUE TITLE
[BUG] Incorrect Output Generated by ONNX Runtime with ORT_ENABLE_ALL Optimization

### ISSUE THREAD

**Issue by SuhwanSong** [microsoft/onnxruntime#20321]
### Describe the issue

When using the "ORT_ENABLE_ALL" optimization flag in onnxruntime, the generated output differs from the expected output (i.e., ORT_DISABLE_ALL). This discrepancy indicates a potential issue with the optimization process in onnxruntime.

### To reproduce

[poc.zip](https://github.com/microsoft/onnxruntime/files/14986397/poc.zip)

1. Download and unzip "poc.zip" to obtain the ONNX model file and input numpy file.
2. Run the following Python code.
```python
import onnxruntime
import numpy as np

if __name__ == "__main__" :
    
    onnx_model_path = 'poc.onnx'
    np_path = 'poc.npy'
    
    rt_option_list = [onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL, 
                        onnxruntime.GraphOptimizationLevel.ORT_ENABLE_BASIC,
                        onnxruntime.GraphOptimizationLevel.ORT_ENABLE_EXTENDED,
                        onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL]
    
    rt_sess_option_list = []
    
    for level in rt_option_list:
        sess_options = onnxruntime.SessionOptions()
        sess_options.graph_optimization_level = level
        rt_sess_option_list.append(sess_options)
    
    input_np = np.load(np_path)
    input = {'x' : input_np}

    outputs = []
    for sess_options in rt_sess_option_list:
        try:
            ort_session = onnxruntime.InferenceSession(onnx_model_path, sess_options)
            ort_output  = ort_session.run(None, input)
            outputs.append(ort_output)
        except Exception as e:
            print (e)
            
    for i in range(1, len(outputs)):
        assert np.allclose(outputs[0], outputs[i], rtol=1e-03, atol=1e-05), \
        f"outputs are not the same, {rt_sess_option_list[i].graph_optimization_level}"

```

### Platform

Linux

### OS Version

6.2.0-35-generic

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
Floating point inaccuracies accumulate with more floating point operations. The model has a lot of Conv nodes which do matrix multiplication, which involves a lot of floating point operations.

The NCHWc optimization results in different assembly instructions being used. That changes the order of operations. They're mathematically equivalent, but due to how floating point numbers work result in differences.

If you change to atol=1e-04 there's no error. The 'correct' rtol/atol is subjective, and AFAIK depends on how many floating point operations are involved.

Do the predictions change when NCHWc is used?

**Comment by SuhwanSong** [comment]
> Do the predictions change when NCHWc is used?

I did not test this model with other NCHWCs. I used ''CPUExecutionProvider".

### Description:
When utilizing the "ORT_ENABLE_ALL" optimization flag in ONNX Runtime, the inference results diverge from the expected outcome achieved with "ORT_DISABLE_ALL".

### Steps to Reproduce:

1. Download and use the provided ONNX model (poc.onnx) and the accompanying Python script (test_script.py).
2. Execute the Python script with the ONNX model using different optimization levels (ORT_DISABLE_ALL and ORT_ENABLE_ALL).
3. Observe the outputs and compare results.

[New poc.zip](https://github.com/microsoft/onnxruntime/files/15156600/poc.zip)

Could you please test this onnx model with the following python script?

```python
import onnxruntime
import numpy as np

if __name__ == "__main__" :

    onnx_model_path = 'poc.onnx'
    
    rt_option_list = [onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL, 
                      onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL
                      ]

    rt_sess_option_list = []
    
    for level in rt_option_list:
        sess_options = onnxruntime.SessionOptions()
        sess_options.graph_optimization_level = level
        rt_sess_option_list.append(sess_options)


    ort_sessions = []
    for sess_options in rt_sess_option_list:
        try:
            ort_session = onnxruntime.InferenceSession(onnx_model_path, sess_options)
            ort_sessions.append(ort_session)
        except Exception as e:
            print (e)

    num_of_error = 0
    for _ in range(100):
        input_np = np.random.randn(1, 3, 224, 224).astype('f')
        input_ = {'data_0': input_np}

        outputs = []
        for ort_session in ort_sessions:
            try:
                ort_output  = ort_session.run(None, input_)
                outputs.append(np.array(ort_output))
            except Exception as e:
                print (e)
    
        if outputs[0].argmax() != outputs[1].argmax():
            print (f'output {outputs[0].argmax()} != {outputs[1].argmax()}')
            num_of_error += 1

    print (f'Errors: {num_of_error} / 100')

```

### Screenshot

![image](https://github.com/microsoft/onnxruntime/assets/41769825/39a426b3-74ad-43e4-9b45-015a24baabe8)
![poc onnx](https://github.com/microsoft/onnxruntime/assets/41769825/4aaf4d8a-9b04-4e4f-bb2e-80fa354eb1c5)

**Comment by skottmckay** [comment]
Comparing using argmax doesn't really make sense. Any two or more values in a set of output could have similar values. 

Contrived examples for softmax output with 3 probabilities. The 2 small values differ slightly on each run due to floating point variances, resulting in an argmax diff. However the model prediction is unchanged as the small values that differ slightly are ~0.5% probabilities.

```
a = np.array([ .99, .00500001, .00499999 ]).astype(np.float32)
b = np.array([ .99, .00499999, .00500001 ]).astype(np.float32)
np.allclose(a, b)
True
```

In your example there are 1000 values in the output, but with the random input you're generating the model is essentially predicting that none of those 1000 possibilities are a good match, as the min and max values for the entire 1000 output values are extremely close to each other. That leads to there being _lots_ of values that are nearly identical numerically so even small floating point differences are highly likely to change the value returned by argmax.

![image](https://github.com/microsoft/onnxruntime/assets/979079/b39bb60c-2aec-40ed-9f25-f08c6d8225dd)

Using numpy.allclose returns no errors for me with the default atol/rtol.
```
        if not np.allclose(outputs[0], outputs[1]):
            num_of_error += 1

    print(f'Errors: {num_of_error} / 100')
```

> Errors: 0 / 100

Given all that, I don't see an issue here.
