### ISSUE TITLE
NNAPI doesn't work on google-edgetpu [Mobile] 

### ISSUE THREAD

**Issue by nonetrix** [microsoft/onnxruntime#20782]
### Describe the issue

I am trying to run Stable Diffusion locally on my Pixel 6a with the help of [SDAI](https://github.com/ShiftHackZ/Stable-Diffusion-Android) on Android, it uses this library under the hood to implement Stable Diffusion. However, for some reason my device doesn't work. Related issues here https://github.com/ShiftHackZ/Stable-Diffusion-Android/issues/82 and https://github.com/ShiftHackZ/Stable-Diffusion-Android/issues/160
![Screenshot_20240523-023248](https://github.com/microsoft/onnxruntime/assets/45698918/25ba89c8-53d9-45da-9d6d-bf9ec603b12c)
This seems to be related to onnxruntime rather than the app

### To reproduce

1. Download SDAI or probably just try to do anything with onnxruntime on Pixel device (confirmed devices to have this issue are Pixel 6a and Pixel 8 Pro)

### Urgency

medium to minor, Pixel devices are somewhat common now so this should be fixed imo

### Platform

Android

### OS Version

14

### ONNX Runtime Installation

Other / Unknown

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

Java/Kotlin

### Architecture

ARM64

### Execution Provider

NNAPI

**Comment by skottmckay** [comment]
Most likely the root cause is either 
- a model with dynamic input shapes (NNAPI doesn't support this), or 
- the model is using one or more ONNX operators that the NNAPI Execution Provider doesn't convert to the equivalent NNAPI operator, or
- the model is using an NNAPI operator that the device does not have a non-CPU implementation for, and execution by NNAPI using CPU is disabled

I couldn't see the actual models anywhere on the repo for that app, so it's hard to say without being able to look at those directly.
