### ISSUE TITLE
indices element out of data bounds

### ISSUE THREAD

**Issue by sandeepnmenon** [microsoft/onnxruntime#2080]
**Bug Description**
We have a query annotation model written in pytorch and deployed as the onnx model. In our telemetry logs, we are seeing the following error come up.
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : indices element out of data bounds, idx=6157 data_dim=6148

**System information**
- OS Platform and Distribution: Linux (ubuntu 18.04)

- ONNX Runtime version: '0.4.0'

- Python version: Python 3.7.3

- GCC/Compiler version (if compiling from source): GCC 7.3.0

- CUDA/cuDNN version: 10.1

- GPU model and memory:  NVIDIA Tesla V100, 224 GiB

**Model used**
```
LSTMClassifier(
  (encoder): Embedding(8952, 400, padding_idx=1)
  (rnn0): LSTM(400, 1150)
  (rnn1): LSTM(1150, 1150)
  (rnn2): LSTM(1150, 400)
  (clas_layers): Sequential(
    (0): BatchNorm1d(800, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): Linear(in_features=800, out_features=50, bias=True)
    (2): ReLU(inplace=True)
    (3): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (4): Linear(in_features=50, out_features=2, bias=True)
  )
)
```

**Comment by hariharans29** [comment]
As the error message indicates, the model (which has  a Gather operator) is seemingly trying to access an index 6157 when the size of the data dimensions is only 6148 (index out of bounds). Since I don't see a gather op in the code above, this must have been added by the PyTorch exporter while converting to ONNX. Hence, this might be a converter issue.

Did this (converted ONNX) model work in OnnxRuntime previously ?

**Comment by sandeepnmenon** [comment]
Yes it works in OnnxRuntime. We are seeing only a small percentage of failures in the telemetry. Unfortunately, since the query strings are customer data, we are not able to access it

**Comment by hariharans29** [comment]
Is it failing only for some query strings ?

**Comment by sandeepnmenon** [comment]
yes, only for some query strings.

**Comment by hariharans29** [comment]
Hi Sandeep,

I am convinced that in the preprocessing step, there should be a step to pad short strings so that the expected size of the input string matches the input tensor shape requirement. The error message (and especially the fact that it only repros for certain strings) is symptomatic of this problem - 

" indices element out of data bounds, idx=6157 data_dim=6148 "

 Please check the necessary input string length requirement (long strings may have to be truncated and short string may have to be padded). 

If after this investigation and fix, it still continues to fail, please re-open the issue with the ONNX model and a sample failure string (if you are unable to share customer query string, please share a dummy string with the same length) and I think that should help us debug.

Closing this out for now.  Thanks!

**Comment by KokinSok** [comment]
Same issue here:

> [ErrorCode:InvalidArgument] Non-zero status code returned while running Gather node. Name:'/roberta/embeddings/position_embeddings/Gather' Status Message: indices element out of data bounds, idx=514 must be within the inclusive range [-514,513]


different input strings also, some work, some dont.

**Comment by linglongxian** [comment]
@KokinSok hi, did you have solve this problem? i meet similar problem, can you share your solution for reference? Thanks.

**Comment by Sunk011** [comment]
@linglongxian hi, did you have solve this problem? i meet similar problem, can you share your solution for reference? Thanks.
