### ISSUE TITLE
[Build]  ERROR: *.whl is not a valid wheel filename & ImportError: DLL load failed while importing onnxruntime_pybind11_state

### ISSUE THREAD

**Issue by srijanie03** [microsoft/onnxruntime#21102]
### Describe the issue

I am trying the Build for on-device training.  I was following the instructions here:
https://onnxruntime.ai/docs/build/training.html#build-instructions-for-the-training-phase

It seems to complete the build fine; however, no wheel file is generated. 
Unable to import onnxruntime.training

### Urgency

Very urgent. Unable to move forward without resolution.

### Target platform

Windows 11 x64

### Build script

.\build.bat --config RelWithDebInfo --cmake_generator "Visual Studio 17 2022" --build_shared_lib --parallel --enable_training --build_wheel --cmake_path "C:\Program Files\CMake\bin\cmake.exe" --ctest_path "C:\Program Files\CMake\bin\ctest.exe" 

I exclusively had to specify the cmake and ctest paths otherwise it was throwing error as mentioned in:
https://github.com/microsoft/onnxruntime/issues/7168

### Error / output

ImportError: DLL load failed while importing onnxruntime_pybind11_state: A dynamic link library (DLL) initialization routine failed.

![image](https://github.com/microsoft/onnxruntime/assets/34174706/5d1929f8-246b-4e1c-856e-e323127a1a1c)

No dist folder is created and no whl file either:
![image](https://github.com/microsoft/onnxruntime/assets/34174706/0a72a728-cb73-4b9a-8add-85d762795be7)

![image](https://github.com/microsoft/onnxruntime/assets/34174706/645e39b1-e2c2-4ed2-bb18-681d71d34e6f)

### Visual Studio Version

17.10.3 2022

**Comment by snnn** [comment]
Likely it is because recently you upgrade your Visual Studio to 17.10. 

Please tell us if you were using conda. If yes, you need to check if you have installed the "vs2015_runtime" package. If still yes, you need to use the following command to get a newer version from conda-forge.
```
 conda install conda-forge::vs2015_runtime
```
CPython(from python.org) does not have this issue.

You also need to install the latest VC++ runtime from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170. The latest version was released a few weeks ago. If you didn't reinstall it recently, please do so.

**Comment by snnn** [comment]
If a C/C++ program was built by Visual Studio version X, then at runtime it will require VC++ Runtime version >=X, otherwise it may result undefined behavior. Recently Visual Studio introduced an ABI change for std::mutex in the latest 17.10 release, therefore if you run the new binary with old VC runtime it will crash. 

VC runtime is a collection of DLLs.  Mainly, it has three pieces:

1. Universal CRT, which is a part of Windows 10. Before that, users need to manually install it. It is no longer a concern because most Windows users have upgraded to Windows 10 or 11. 
2. vcruntime[version].dll, which is the basic Runtime Library for C native code.
3. msvcp[version].dll, which is the C++ Standard Library for C++ native code.

In order to get a simple C++ hello world program to run, you need all the three pieces.  A C program only needs the top two.  For example, python.exe itself is written in C. It doesn't contain any C++ code. So, in order to run python.exe, you need the Universal CRT and vcruntime[version].dll.  So, if you open the folder where your python.exe lives, you will find a "vcruntime140.dll" there. The DLL was installed there when installing the python. The DLL is certainly old.  Even if you have installed the latest VC Runtime, the old DLL will still get used since it has higher preference(because it is in the same dir as the executable: python.exe).  However, it won't cause issue here. You will not find a msvcp140.dll there, since python.exe doesn't depend on that. And the C++ std::mutex change we are talking about is in msvcp140.dll, which is not part of python. 
 
However, if your python is Conda and the python version is bigger than 3.8, I believe you will find msvcp140.dll in your conda's installation dir. I think it is brought by the "vs2015_runtime" package. And you can update the package by running:

```
 conda install conda-forge::vs2015_runtime
```

Not only python, JDKs usually also have this problem.

**Comment by snnn** [comment]
To verify if the error("A dynamic link library (DLL) initialization routine failed.") you saw was caused by VC runtime version mismatch, you should check which msvcp140.dll was loaded.  As you already have Visual Studio, you can get the information by debugging it there.  In Visual Studio, you can open python.exe as a project. 

![image](https://github.com/microsoft/onnxruntime/assets/856316/b409d542-4424-49b3-ad4e-30851420b2e1)

Then right click the project, setup properties.

![image](https://github.com/microsoft/onnxruntime/assets/856316/4edb8e95-952f-4211-b3ec-7a210f03cc31)

In the new Windows you can should set "arguments" to the full path of your python script , which should be as simple as just one line: "import onnxruntime".
Then you press "F5" to debug it.
In the debug windows you should be able to see the full path of  msvcp140.dll . The log should contain things like:

```
'python.exe' (Win32): Loaded 'C:\hostedtoolcache\windows\Python\3.12.4\x64\Lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state.pyd'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. 
```

Then you find the DLL in File Explorer. Right click it, check its properties. 


![image](https://github.com/microsoft/onnxruntime/assets/856316/80a5a869-3df3-4b18-88e9-eab5040da8b8)

If the version number begins with 14.40, it's good.  Otherwise, delete the DLL if it is not in system32 folder.

**Comment by srijanie03** [comment]
Thank you for the detailed comments.

1. Yes, I was using conda. I have updated the "vs2015_runtime" package.

2. It seems like I have the latest release of vc++. I tried to re-install it and this is what I get :
![Screenshot 2024-06-19 163153](https://github.com/microsoft/onnxruntime/assets/34174706/baff58a4-0d86-4456-8952-40d87056ba2f)

3. I checked the msvcp140.dll file and seems like I have the correct one.
![Screenshot 2024-06-19 160613](https://github.com/microsoft/onnxruntime/assets/34174706/7df23d98-d74b-46e1-86fc-1bb04da2caf4)

I ran the build again and this time it didn't give me the error as it did before.  It says 'build complete' but I still don't see the wheel file. What am I missing?

![image](https://github.com/microsoft/onnxruntime/assets/34174706/1a13d905-cba5-4316-9d0b-bbd012f2daa9)

**Comment by snnn** [comment]
You need to add one more "\RelWithDebInfo" in the path.  Like `D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\dist`

**Comment by srijanie03** [comment]
I can see the wheel file now. But still unable to install it using : 
python -m pip install build/Windows/RelWithDebInfo/RelWithDebInfo/dist/*.whl

![Screenshot 2024-06-19 181050](https://github.com/microsoft/onnxruntime/assets/34174706/605e3196-facf-4022-b140-4251d5b7dacd)

**Comment by srijanie03** [comment]
I was able to install the wheel file by specifying the file name exclusively.  Looks like it was installed successfully.
![image](https://github.com/microsoft/onnxruntime/assets/34174706/4c813bec-5420-4f0b-ad7f-5959d54baa10)

But it is installed within the dist directory, I am unable to import onnxruntime.training outside it. I am hoping changing the target path would work.

**Comment by azamet90** [comment]
PS D:\yapay zeka\stable-diffusion-webui-amdgpu> pip install onnxruntime
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: onnxruntime in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (1.15.0)
Requirement already satisfied: coloredlogs in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (from onnxruntime) (15.0.1)
Requirement already satisfied: flatbuffers in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (from onnxruntime) (24.3.25)
Requirement already satisfied: numpy>=1.21.6 in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (from onnxruntime) (1.26.4)
Requirement already satisfied: packaging in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (from onnxruntime) (24.1)
Requirement already satisfied: protobuf in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (from onnxruntime) (5.27.1)
Requirement already satisfied: sympy in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (from onnxruntime) (1.12.1)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (from coloredlogs->onnxruntime) (10.0)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (from sympy->onnxruntime) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\users\cilginflix\appdata\roaming\python\python310\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime) (3.4.1)





is it same on me? what do i have to do?

**Comment by snnn** [comment]
Very likely. Please see the solution above.  You can use Visual Studio debugger to confirm that. 

First please install the latest Visual Studio C++ Runtime from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
Then, if you use conda, please also run 
```
 conda install conda-forge::vs2015_runtime
```
