### ISSUE TITLE
CUDA 12 and session.get_providers() not showing CUDAExecutionProvider

### ISSUE THREAD

**Issue by RomRoc** [microsoft/onnxruntime#21354]
### Describe the documentation issue

I installed onnxruntime in Colab having T4 gpu and Cuda 12, using the commands the guide:
`pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
`

When I run command:
`onnxruntime.get_device()`
I get GPU

But when I run command:
`session = onnxruntime.InferenceSession(model_path, providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
session.get_providers()`
I get CPUExecutionProvider

In fact inference doesn't use GPU memory. Why? Should I ran any other steps?
Thanks

### Page / URL

https://onnxruntime.ai/docs/install/#install-onnx-runtime-gpu-cuda-12x

**Comment by snnn** [comment]
The installation command looks wrong.  Please uninstall the package then use the following commands:
```
pip install -r https://raw.githubusercontent.com/microsoft/onnxruntime/main/requirements.txt
pip install onnxruntime-gpu --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ 
```
Should be "--index-url" instead of "--extra-index-url".

We will update the doc shortly.

**Comment by tianleiwu** [comment]
Currently colab uses torch 2.3.0+cu121 by default, which requires nvidia-cudnn-cu12==8.9.2.26 while onnxruntime-gpu 1.18.1 for cuda 12 requires **cudnn 8**. 

You can setup colab like the following:

Choice 1: torch nightly 2.5.0 for cuda12.4 and ORT-gpu 1.18.1 for cuda 12
```
!pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124 --force-reinstall
!pip install -r https://raw.githubusercontent.com/microsoft/onnxruntime/main/requirements.txt
!pip install onnxruntime-gpu --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ 
```
See [example colab job](https://colab.research.google.com/drive/12pIlpPx8Vrzebfd8s7IOWf0BWKEc_F7P?usp=sharing) for this combination.

Choice 2: torch 2.3.0+cu121 and ORT-gpu 1.18.0 for cuda 8.
```
!pip install torch torchvision torchaudio
!pip install -r https://raw.githubusercontent.com/microsoft/onnxruntime/main/requirements.txt
!pip install onnxruntime-gpu==1.18.0 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ 
```

**Comment by huzaifahshamim** [comment]
> The installation command looks wrong. Please uninstall the package then use the following commands:
> 
> ```
> pip install -r https://raw.githubusercontent.com/microsoft/onnxruntime/main/requirements.txt
> pip install onnxruntime-gpu --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ 
> ```
> 
> Should be "--index-url" instead of "--extra-index-url".
> 
> We will update the doc shortly.

Hi @snnn , I am attempting to do the following commands via a Dockerfile on a Jetson Xavier Orin. However, I run into the error: "no matching distribution found for onnxruntime-gpu". If you have any advice for me, I would greatly appreciate it.

**Comment by tianleiwu** [comment]
> >  I am attempting to do the following commands via a Dockerfile on a Jetson Xavier Orin. However, I run into the error: "no matching distribution found for onnxruntime-gpu". If you have any advice for me, I would greatly appreciate it.

@huzaifahshamim, for Jetson, you can download onnxruntim-gpu wheel in https://elinux.org/Jetson_Zoo for JetPack 6.0 (CUDA 12 and cuDNN 8.9).

**Comment by tianleiwu** [comment]
I also added two notebooks that use onnxruntime-gpu without importing pytorch:

CUDA 11:
https://colab.research.google.com/drive/1iDLX2g1di3FYRO2oKmdOPUuO378O0ITW?usp=sharing

CUDA 12:
https://colab.research.google.com/drive/1OcHA3ie57KD5fIJ9sFhrLR53lr0-6qNQ?usp=sharing

Installation:
```
pip install onnxruntime-gpu==1.18.1 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ 
pip install nvidia-cudnn-cu12==9.2.1.18 nvidia-cuda-runtime-cu12==12.5.82 nvidia-cufft-cu12==11.2.3.61
```

Then you can run inference like:
```
from ctypes import *
cudnn_libc = cdll.LoadLibrary("/usr/local/lib/python3.10/dist-packages/nvidia/cudnn/lib/libcudnn.so.9")
cublas_libc = cdll.LoadLibrary("/usr/local/lib/python3.10/dist-packages/nvidia/cublas/lib/libcublas.so.12")
cublaslt_libc = cdll.LoadLibrary("/usr/local/lib/python3.10/dist-packages/nvidia/cublas/lib/libcublasLt.so.12")
cudart_libc = cdll.LoadLibrary("/usr/local/lib/python3.10/dist-packages/nvidia/cuda_runtime/lib/libcudart.so.12")
cufft_libc = cdll.LoadLibrary("/usr/local/lib/python3.10/dist-packages/nvidia/cufft/lib/libcufft.so.11")

import onnxruntime
ort_session = onnxruntime.InferenceSession("model.onnx", providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
print(ort_session.get_providers())
```
The key here is to preload nvidia DLLs from python package (so that you need not depend on cuda or cudnn installed in system.)

**Comment by huzaifahshamim** [comment]
> > > I am attempting to do the following commands via a Dockerfile on a Jetson Xavier Orin. However, I run into the error: "no matching distribution found for onnxruntime-gpu". If you have any advice for me, I would greatly appreciate it.
> 
> @huzaifahshamim, for Jetson, you can download onnxruntim-gpu wheel in https://elinux.org/Jetson_Zoo for JetPack 6.0 (CUDA 12 and cuDNN 8.9).

Hi @tianleiwu, thank you for your reply. So that is how I was initially attempting to download it onto my Docker container on Orin. I tried both onnxruntime 1.17 and 1.18 with python 3.10 but was running into errors that there was no .11.so for cublassLt and other CUDA libraries. Which wheel should I use?

**Comment by RomRoc** [comment]
In my opinion it should be easier to use the most popular inference library (onnxruntime) in the most popular dev tool (Colab).
Maybe you can upgrade the library to be compliant to Colab? 
In this way it will be easier even to deploy to VMs. In my case I can't use Cuda even in my T4 Azure instance.
Thanks

**Comment by tianleiwu** [comment]
See https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements for cuda 12 requirement. 
The root cause of this issue is PyTorch 2.3 use cuDNN 8.x, while onnxruntime-gpu 1.18.1 for cuda 12 requires cuDNN 9. 

Note that the coming PyTorch 2.4 will support cuDNN 9.x, so that will help.

Example colab notebooks ([ORT 1.18.1 +Torch 2.4](https://colab.research.google.com/drive/1bMnZifft3PPnTufjAlJZR_-a8Q4Nchkt?usp=sharing), [ORT 1.18.1 only](https://colab.research.google.com/drive/1OcHA3ie57KD5fIJ9sFhrLR53lr0-6qNQ?usp=sharing)) are provided. This issue is closed. 

Feel free to create new issue if it is not related to colab.

**Comment by RomRoc** [comment]
I confirm that upgrading to Pytorch 2.4, it uses Cuda inference.
Thanks
