### ISSUE TITLE
Error "Name:'bn_data' Status Message: Invalid input scale: NumDimensions() != 3"

### ISSUE THREAD

**Issue by luan1412167** [microsoft/onnxruntime#2175]
**Describe the bug**
Hi all,
I'm using onnx runtime from source (latest version support spatial BN = 0 ). my model [here](https://drive.google.com/file/d/1aZBakhRE9dIhiGf8WI-hpS6nenuYcZm9/view?usp=sharing)

`Non-zero status code returned while running BatchNormalization node. Name:'bn_data' Status Message: Invalid input scale: NumDimensions() != 3`
![Screenshot from 2019-10-18 14-58-20](https://user-images.githubusercontent.com/37315746/67081720-dff70200-f1c1-11e9-84b6-0af901fab937.png)

Thanks so much for your help

**Urgency**
 I must to implement retinaface and arcface on C++ for my thesis at my university.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source 
- ONNX Runtime version: latest
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 3.15
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by hariharans29** [comment]
Hi Luan,

Did you convert this model from MxNet by any chance ? It has the same issue as the ArcFace model where the BN nodes are stamped with spatial == 0 and the inputs (scale, B, mean, var) do not conform to ONNX spec - 

![image](https://user-images.githubusercontent.com/9969784/67127575-82a58580-f1ae-11e9-82e0-0d99761ed912.png)

The input shape [3] is acceptable only when spatial == 1. As it is, this is an invalid ONNX model. Please try using the script I shared in the ArcFace model issue to correct this model and try again.

Closing this, because it is an invalid ONNX opset-8 model.

**Comment by chinmayjog13** [comment]
@hariharans29 can you please share a link to issue? I am unable to find it in arcface model issues
