### ISSUE TITLE
Context leak detected with CoreMLExecutionProvider

### ISSUE THREAD

**Issue by ankane** [microsoft/onnxruntime#22007]
### Describe the issue

Running a number of different models from Hugging Face Hub with the `CoreMLExecutionProvider` on Mac arm64 outputs multiple instances of:

```text
Context leak detected, msgtracer returned -1
```

### To reproduce

Models

- [Supabase/gte-small](https://huggingface.co/Supabase/gte-small/blob/main/onnx/model.onnx)
- [mixedbread-ai/mxbai-embed-large-v1](https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1/blob/main/onnx/model.onnx)
- [Snowflake/snowflake-arctic-embed-m-v1.5](https://huggingface.co/Snowflake/snowflake-arctic-embed-m-v1.5/blob/main/onnx/model.onnx) (comment out `token_type_ids` input for this one)

Code

```python
import onnxruntime

session = onnxruntime.InferenceSession('model.onnx', providers=['CoreMLExecutionProvider'])
inputs = {
    'input_ids': [[101,2008,2003,1037,2200,3407,2711,102]],
    'attention_mask': [[1,1,1,1,1,1,1,1]],
    'token_type_ids': [[0,0,0,0,0,0,0,0]]
}
session.run(None, inputs)
```

### Platform

Mac

### OS Version

14.6.1

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19.2

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

CoreML

**Comment by yuygfgg** [comment]
I'm have the same issue. But what's strange for me is that it occurs more often when GPU is running heavy OpenCL load.

**Comment by jason-ni** [comment]
Hi @ankane, has this issue been fixed? I'm using 1.22.0 and still having this error.

**Comment by fhrzn** [comment]
still got the same issue via Qdrant's FastEmbed

**Comment by altunenes** [comment]
Same problem :/ CoreML is really annoying :-D

**Comment by blureonlabs** [comment]
have any of you guys got it fixed? running dinov2 via onnx and hitting qdrant. latency is higher than cpu. running on m4 pro

**Comment by altunenes** [comment]
> have any of you guys got it fixed? running dinov2 via onnx and hitting qdrant. latency is higher than cpu. running on m4 pro

it is likely caused by excessive graph partitioning. I experience this with almost every new models.

I think it's a common issue where ONNX models split into hundreds of tiny subgraphs if CoreML doesn't support specific operators in your DINOv2 graph similar with other models. 

for example:
https://github.com/microsoft/onnxruntime/issues/26355

I saw this same behavior with a Parakeet TDT model that fragmented into 341 partitions, accompanied by recurring Context leak detected, CoreAnalytics returned false warnings—a symptom of the system struggling with these rapid memory handovers. Also you can check my extensive logs to see what's happening during those states:

https://github.com/altunenes/parakeet-rs/pull/51#issuecomment-3669655608
https://github.com/altunenes/parakeet-rs/issues/3

To fix this, we could try exporting models with static shapes to encourage node fusion and reduce partitioning, or switch to the CPUExecutionProvider entirely to bypass the data transfer overhead until the model is more CoreML friendly. But it also contains its own problems so its not an effective way to solve this.

This problem is also happening for LLMs, especially the vision ones.  I tried many with the ONNX form, but nope...  even llms that created by apple lol
https://github.com/apple/ml-fastvlm/issues/50
