### ISSUE TITLE
[Web] warning about the use of eval in Vite

### ISSUE THREAD

**Issue by jclaessens97** [microsoft/onnxruntime#22156]
### Describe the issue

Whenever I build with Vite I get the following warning message:

<img width="862" alt="image" src="https://github.com/user-attachments/assets/1492ef57-6d09-4e18-81cf-57113799cebe">

### To reproduce

1. Install onnxruntime-web
2. Build application with Vite

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19.2

### Execution Provider

'webgl' (WebGL)

**Comment by fs-eire** [comment]
The only `eval` is introduced by dependency protobufjs:

**Comment by fs-eire** [comment]
We still need protobufjs if using WebGL.

If using CPU only, you can import `onnxruntime-web/wasm`
If using WebGPU, you can import `onnxruntime-web/webgpu`

They both do not depend on protobufjs and there should be no `eval()` in the corresponding bundles.

**Comment by jclaessens97** [comment]
I tried using wasm import before, but then I get [a related issue](https://github.com/microsoft/onnxruntime/issues/22010).

**Comment by jclaessens97** [comment]
Any update?

**Comment by fs-eire** [comment]
The "use of eval" warning will exist for a while until WebGL backend is eventually go out of lifetime and be replaced by WebGPU.

The specific code that uses "eval" is from protobuf.js to ensure the call to `require()` is not preprocessed by bundlers. Technically it does not get called in a web environment so it should be pretty much fine.

I will close this issue because there is no further action item. Will revisit the other issue when I get some time.

**Comment by michaelmunie** [comment]
If people are having problems importing /webgpu or /wasm in a chrome plugin, it can be solved with webpack.  Please see my solution in [this related issue](https://github.com/microsoft/onnxruntime/issues/22010).
