### ISSUE TITLE
[Web] When the "node" condition path in exports is null vite (+svelte) build will wrongly throw a "No known conditions for" error 

### ISSUE THREAD

**Issue by bn-l** [microsoft/onnxruntime#22361]
### Describe the issue

I am trying to build a project with this line. I've used webgl here but this applies to any import path (/wasm, /all, /webgpu, etc). Just importing "onnxruntime-web" without a path works though.

```javascript
import * as ort from "onnxruntime-web/webgl";
```

when I run vite build I get this error:

```shell
error during build:
[commonjs--resolver] No known conditions for "./webl" specifier in "onnxruntime-web" package
```

-------------
The issue is with the exports of this particular package.json (excerpt from [original](https://github.com/microsoft/onnxruntime/blob/5c74539ab70e953e952fd2e4a8cc29daaf3455d5/js/web/package.json)).

**!!!  Note that the node condition for webgl is null:  !!!**

```JS
{
  "exports": {
      ".": {
        "node": {
          "import": "./dist/ort.node.min.mjs",
          "require": "./dist/ort.node.min.js"
        },
      "./webgl": {
        "node": null,
        "import": "./dist/ort.webgl.min.mjs",
        "require": "./dist/ort.webgl.min.js",
        "types": "./types.d.ts"
      }
}
```

Vite will error if  `node:`'s value is `null`. If I change it to any working path (e.g. `"/types.d.ts"`) then it won't blow up and will correctly resolve to `"import": "./dist/ort.webgl.min.mjs",`. So this does work:

```JS
{
  "exports": {
      ".": {
        "node": {
          "import": "./dist/ort.node.min.mjs",
          "require": "./dist/ort.node.min.js"
        },
      "./webgl": {
        "node": "./types.d.ts",  <----| Changed to any valid path!
        "import": "./dist/ort.webgl.min.mjs",
        "require": "./dist/ort.webgl.min.js",
        "types": "./types.d.ts"
      }
}
```

Also **swapping the order** works also (no build error). Note that `"import": "./dist/ort.webgl.min.mjs",` is now before `"node": null`:

```JS
{
  "exports": {
      ".": {
        "node": {
          "import": "./dist/ort.node.min.mjs",
          "require": "./dist/ort.node.min.js"
        },
      "./webgl": {
        "import": "./dist/ort.webgl.min.mjs",  <-----|  Swapped!
        "node": null,                          <-----|
        "require": "./dist/ort.webgl.min.js",
        "types": "./types.d.ts"
      }
}
``` 

### Further info

From here: https://nodejs.org/api/packages.html#package-entry-points, it can be seen that null should not be used like this.

### System Info

```shell
System:
    OS: Windows 10 
  Binaries:
    Node: 22.7.0
```

### To reproduce

Create a new vite project
`npm create vite@latest`

Add the package:
`npm add -D onnxruntime-web`

In index.ts:
`import * as ort from "onnxruntime-web/webgl";`

Then run the default build script from vite.

### Urgency

I have a script that corrects this package.json so not urgent.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19.2

### Execution Provider

'webgl' (WebGL), 'wasm'/'cpu' (WebAssembly CPU), 'xnnpack' (WebAssembly XNNPACK), 'webgpu' (WebGPU), Other / Unknown

**Comment by bn-l** [comment]
From: https://github.com/vitejs/vite/issues/18015 (posted issue with vite initially--this was a mistake):

> Indeed, for web app, I don't think Vite would use `node` condition. I couldn't repro from the template and both dev / build seems fine. https://stackblitz.com/edit/vitejs-vite-usxpr5?file=main.js
> 
> ```shell
> > vite build
> 
> vite v5.4.8 building for production...
> node_modules/onnxruntime-web/dist/ort.webgl.min.mjs (6:94998): Use of eval in "node_modules/onnxruntime-web/dist/ort.webgl.min.mjs" is strongly discouraged as it poses security risks and may cause issues with minification.
> ✓ 4 modules transformed.
> dist/index.html                  0.32 kB │ gzip:  0.24 kB
> dist/assets/index-wx6rlKjT.js  418.37 kB │ gzip: 93.44 kB
> ✓ built in 1.54s
> ```
> 
> @bn-l Can you provide reproductions?

@hi-ogawa Couldn't reproduce using plain vite because I am using sveltekit on top of vite which builds the server side rendering part no matter what (see here: https://github.com/sveltejs/kit/issues/2937). So even though I don't use the package in a node environment and have SSR disabled, it's still trying to build for node. 

This is a sveltekit issue so I will close this. Sorry to bother you unnecessarily.

**Comment by ollema** [comment]
@fs-eire I wonder if this can be reopened and there to be a different solution to this problem?

I have also run into this, and for SvelteKit there is simply no workaround at the moment and in the near future as far as I can tell.

even when you disable server side rendering (SSR) in SvelteKit, all files are still analyzed on the server during build time, for example to look for the `export const ssr = flag` to disable SSR. see https://github.com/sveltejs/kit/issues/12580 for more details

I understand that this should not work on node, and that is a very valid stance, but maybe restricting it so that it's not even possible to import is a bit too strict?

it would be very helpful if it was at least possible to import this on the server without getting the `No known conditions` error - even if you have no intentions to ever run it on the server, just because how SSR meta frameworks like SvelteKit works.

eventually I hope that SvelteKit will allow for disabling of the SSR analyze/build step for client side only apps. but even then it might be a problem for hybrid apps? not sure.

would love to hear your thoughts on this!
