### ISSUE TITLE
[cuda] [npm/nodejs] Failed to download the binaries: 404 Not Found

### ISSUE THREAD

**Issue by lucyknada** [microsoft/onnxruntime#22877]
the readme tells you to use

```
npm install onnxruntime-node --onnxruntime-node-install-cuda=v12
```

to pull in the cuda binaries for linux x64; it tries to download:

```
https://github.com/microsoft/onnxruntime/releases/download/v1.20.0/onnxruntime-linux-x64-gpu-cuda12-1.20.0.tgz
```

which indeed does not exist, what does exist is:

```
 onnxruntime-linux-x64-gpu-1.20.0.tgz 
```

but there is no way to pass an empty string to `--onnxruntime-node-install` so that it assembles the right URL.

**Comment by lucyknada** [comment]
after looking at the code `--onnxruntime-node-install-cuda` just as is will make this work; however maybe the docs/readme should be updated?

**Comment by skottmckay** [comment]
Which docs specifically?

**Comment by skottmckay** [comment]
@fs-eire should we update the install script if we're not producing CUDA 11 and 12 packages to remove the option to choose?

**Comment by fs-eire** [comment]
**Background:** There is a max size limit for NPM package, so it is impossible to include CUDA binaries inside `onnxruntime-node`. I made this install script for onnxruntime-node to allow users to download the CUDA binaries from github.

Before 1.18.x, there are both [onnxruntime-win-x64-gpu-1.18.0.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.18.0/onnxruntime-win-x64-gpu-1.18.0.zip) and [onnxruntime-win-x64-gpu-cuda12-1.18.0.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.18.0/onnxruntime-win-x64-gpu-cuda12-1.18.0.zip) in the github release assets, containing the CUDA v11 bits and CUDA v12 bits. 

- `--onnxruntime-node-install-cuda[=v11]` will download file `https://github.com/microsoft/onnxruntime/releases/download/v{VERSION}/onnxruntime-win-x64-gpu-{VERSION}.zip`
- `--onnxruntime-node-install-cuda=v12` will download file `https://github.com/microsoft/onnxruntime/releases/download/v{VERSION}/onnxruntime-win-x64-gpu-cuda12-{VERSION}.zip`

Since 1.19.x, CUDA v12 became default and the `onnxruntime-win-x64-gpu-cuda12-{VERSION}.zip` is no longer provided in Github release assets.

I can make a change in the installation script to fix it for CUDA v12. However, it may be difficult for CUDA v11 since there is no public assets.

**Comment by fs-eire** [comment]
I will make a change to fix the installation script for cuda v12.
