### ISSUE TITLE
what is a scoring engine in short? differ from a score function?

### ISSUE THREAD

**Issue by zzz6519003** [microsoft/onnxruntime#2418]

**Comment by zzz6519003** [comment]
@faxu thx for labeling

**Comment by hariharans29** [comment]
Don't know if this is the textbook definition, but here is my take - 

Scoring function - A scoring function f, is an abstraction for anything that maps a collection of independent variables (e.g. features) to a dependent variable (e.g. class probabilities): y =f(x). Any machine learning/deep learning model is essentially a scoring function because it takes in some "features" and produces something that the next layer can consume or if it is the final layer, it produces the final results (i.e.) "scores". 

Scoring engine - Any abstraction/library/software that can help run a scoring function (model).

**Comment by zzz6519003** [comment]
so they are all abstraction, but engine is even cooler XD
