### ISSUE TITLE
Do you have any documents about C++ interface loading model?

### ISSUE THREAD

**Issue by huang229** [microsoft/onnxruntime#2657]
This is really a great job, cross deep learning framework, cross deployment platform.
I converted the pytorch model to onnx format. I want to load the converted model with C++ code in vs.
Do you have any documents about C++ interface loading model?

**Comment by skottmckay** [comment]
https://github.com/microsoft/onnxruntime/tree/master/samples#CC

**Comment by huang229** [comment]
It's really great. thanks very much.

**Comment by faxu** [comment]
If this resolves your question, please close the issue. Thanks!

**Comment by hoaquocphan** [comment]
Hi @skottmckay  
the sample in Your link is very simple such as:
in the sample there is only 1 input model. but, when I port the multi input model, it doesn't have the example.

**Comment by skottmckay** [comment]
Can you provide some example code, ideally the model if possible, and the exact error message?

**Comment by hoaquocphan** [comment]
Hi @skottmckay 

>> Can you provide some example code, ideally the model if possible, and the exact error message?
Sorry, this comment because of I didn't understand about it, Yesterday, I create the code as follow and it run.

Now, I have some concern need the support from you as below:
1/ Please help me to feedback my last comment in https://github.com/microsoft/onnxruntime/issues/3170

Thank you.
