### ISSUE TITLE
Howto: Support of CUDA/CPU using one DLL

### ISSUE THREAD

**Issue by kzuiderveld** [microsoft/onnxruntime#2787]
We'd like to use Onnx runtime using one DLL that can adapt to the available hardware resources on the platform. I believe this was also the intention of the onnxruntime designers because of the "provider" support. 
The specific use-case we're interested in: do inference using Cuda when appropriate hardware is available on the system, otherwise fall back on CPU inference. 

I compiled the 1.1 release using VS2019 (Windows 10) twice - the CPU version and the CUDA version (so two different dlls). 

On my system (which has CUDA hardware), I can run models on CUDA when adding a CUDA provider; it uses the CPU when I don't do that. That is great, that's the behavior we were after. 

However, we can't run that dll on systems without CUDA hardware; our application will not start because the CUDA-enabled dll looks for the NVIDIA libraries during loading - and croaks when it doesn't find them. onnxruntime.dll simply doesn't load and brings our application down with it. 

Is this behavior intentional? I'd like a CUDA-enabled dll that basically disables CUDA in case it can't find the NVIDIA dlls (so the CPU path will still work) rather than the current behavior (dll unable to load). 

Cheers, Karel

**Comment by snnn** [comment]
> Is this behavior intentional? 
No.

**Comment by nietras** [comment]
I have observed the same issue. We would very much like to be able to run with whatever execution provider that might be available. This relates a bit to my comment in https://github.com/microsoft/onnxruntime/issues/2742#issuecomment-571570024 a "plugin" based model would be preferable.

**Comment by snnn** [comment]
Sorry I need to revisit my previous answer.  There are two ways of supporting this feature:

1. Delay-loading, which is Windows-only, and didn't work as we expected. When you delay-load a DLL, you have less control when the DLL will be unloaded. In our case, it may result crashes when the process is ending.  So we gave it up. 

2. [Explicit Linking](https://docs.microsoft.com/en-us/cpp/build/linking-an-executable-to-a-dll?view=vs-2019).  It should work fine, but it need significant work. 

So, if you ask me again, "Is this behavior intentional?"

I have to say: Yes, for now.
