### ISSUE TITLE
MLAS rewrite (#2844) causes performance issues on CPUs with high core count

### ISSUE THREAD

**Issue by kzuiderveld** [microsoft/onnxruntime#2885]
This patch increases execution time on my 2x18-core Xeon machine (CPU inferencing) from 56.4 seconds to 123.8 seconds. I perform sequential execution of the ONNX model in an OpenMP parallel region. 

I used VTune Amplifier 2020 to identify the issue. After the #2844 fix, the overhead of MlasReorderInput is dominant; the total CPU time is 6738 seconds with #2844 as opposed to 3305 seconds in the prior version. I suspect that the additional memory traffic caused by the change introduces memory bandwidth issues. 

**System information**
Windows 10, Visual Studio 2019
Comparing Onnx runtimes compiled from source (ID 927b6bb2 1/15/2020 has the issue, ID 56030f8d 1/14/2020 doesn't). 

![image](https://user-images.githubusercontent.com/28074679/72853407-885bad00-3c6e-11ea-9e17-380dbf371328.png)
![image](https://user-images.githubusercontent.com/28074679/72853428-9a3d5000-3c6e-11ea-97d7-947e22c4ced6.png)

**Comment by tracysh** [comment]
@kzuiderveld, #2844 was primarily changes for quantized or int8 GEMMs. The hotspot you list is for MlasReorderInput which is a single threaded function used to reorder buffers for the optimized float32 convolution. It's not clear from this why the performance would have changed.

What optimization level is used for SetSessionGraphOptimizationLevel? If ORT_ENABLE_EXTENDED is used instead of ORT_ENABLE_ALL, what performance do you observe?

Can I get a copy of the model to reproduce the slowdown locally?

**Comment by kzuiderveld** [comment]
Reordering buffers implies copying of data. The MlasReorderInput might be single-threaded, but is used within an OpenMP region so there are 72 threads calling it and each memory operation adds overhead. 

I'll get back to you wrt ORT_ENABLE_EXTENDED. You can have a copy of the model as long it is considered covered on an NDA.

**Comment by snnn** [comment]
But we found perf regression on another commit just after Tracy's change. Commit 724ff0753bc3c7a1931e58ccb092df41b262d61f .

**Comment by kzuiderveld** [comment]
I benchmarked a dozen or so commits to find the one that caused the slowdown I observed. 56030f8d is OK, didn't test 5db85430 as it is documentation only, next one was Tracy's and it has the issue.

**Comment by kzuiderveld** [comment]
sssn, you're absolutely right. I screwed up. The main degradation was indeed caused by 724ff07, although Tracy is not totally out of the woods (but apologies Tracy, you're not the main culprit). 

My results:
Version 56030f8d (1/14): 57.3 seconds (3352 seconds). Life is good. 
![image](https://user-images.githubusercontent.com/28074679/72857673-919f4680-3c7b-11ea-92ec-fa21c4dff1ec.png)

Version 928b6bb2 (1/16, Tracy's): 68.3 seconds (3943 seconds). Performance degradation. 
![image](https://user-images.githubusercontent.com/28074679/72857758-d62ae200-3c7b-11ea-9e08-80c511f91229.png)
(memcpy now #1 function, suggesting memory bandwidth issues)

Version 724ff075 (1/16, Scott's): 121.3 seconds (6915 seconds). Huge performance degradation with ORT_ENABLE_ALL. 
![image](https://user-images.githubusercontent.com/28074679/72857834-0d998e80-3c7c-11ea-9c6f-7dc7a732f230.png)

724ff075 with ORT_ENABLE_EXTENDED behaves a bit better, but still has issues (108.8 seconds, 5187 CPU seconds). 
![image](https://user-images.githubusercontent.com/28074679/72857924-53eeed80-3c7c-11ea-8a32-5c18bb8fb360.png)

So 1/15 and 1/16 were not good days for performance, both commits seem to have introduced issues.

**Comment by tracysh** [comment]
The samples for 56030f8 are referencing the older convolution algorithm (MlasConvIm2Col). This is odd because the default optimization level was bumped up to ORT_ENABLE_ALL in change 7c6242b (1/13). I wonder if that build failed to fully rebuild everything that used these values and the test continued to use the older algorithm.

Regarding the model, it would be useful for me to get a copy for internal performance testing only. Barring that, the model consists of Conv + Upsample nodes? What parameters are used for the upsamples? The NCHWc path (via ORT_ENABLE_ALL) should ultimately be faster than the old code path, but some level of support for Upsample needs to be added as well to avoid the reorders.

**Comment by kzuiderveld** [comment]
I would have to verify that the "fast" benchmark was indeed made with 56030f8 - jumping between all the branches, rebuilding the libs, relinking with my app and benchmarking and then keeping track of everything is asking for trouble. It was a long day yesterday. 

Yup, you can get my model (it's an unet). Let me know where to e-mail it (it's about 7MB).

**Comment by tracysh** [comment]
Thanks, I can be reached at tracysh@microsoft.com.

**Comment by skottmckay** [comment]
a92e924ab29ed71f2176bb04fd9ec3c117c0de5b reverted the change from 724ff0753bc3c7a1931e58ccb092df41b262d61f

**Comment by kzuiderveld** [comment]
![image](https://user-images.githubusercontent.com/28074679/75307961-56f47500-580a-11ea-9355-3957d684e99e.png)

I pulled down the latest version of ONNX runtime and redid my benchmarks. The latest version is a tad faster compared to the version I was using, so whatever caused the performance degradation, it is fixed now and this issue can be considered as resolved. 

Note: in my case, inference becomes completely memory bandwidth limited around 30 threads. If onnx runtime uses intermediate buffers, please make sure they fit into L1/L2 cache...
