### ISSUE TITLE
Fail to run onnxruntime-gpu ImportError #2861

### ISSUE THREAD

**Issue by YZhao33** [microsoft/onnxruntime#2894]
Reopen issue #2861. 
I installd cuda 10.0, but the issue remains.

**Comment by snnn** [comment]
We need the FULL error messages to help you. 
Did you see something like: "UserWarning: Cannot load onnxruntime.capi. Error: 'DLL load failed: The specified module could not be found." ?

**Comment by YZhao33** [comment]
I do not see this. the error message is as follows: 

Traceback (most recent call last):
  File "xx\run_sid_eval.py", line 23, in <module>
    import onnxruntime as rt
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnxruntime\__init__.py", line 12, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode
ImportError: cannot import name 'get_all_providers' from 'onnxruntime.capi._pybind_state' (C:\ProgramData\Anaconda3\lib\site-packages\onnxruntime\capi\_pybind_state.py)

**Comment by jywu-msft** [comment]
That error message is a bit misleading, it's caused by missing dll dependency.
in this case since it's gpu python build, it's probably due to missing cuda libraries (or missing python lib). can you confirm that 
cuda 10 libraries are in your PATH? e.g. C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin

additionally, you can confirm what dependencies are required for the python-gpu package.
Use the Visual Studio developer command prompt and run the dumpbin tool.
(something like C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\dumpbin.exe)

e.g. run dumpbin in the build directory on onnxruntime_pybind11_state.pyd

"dumpbin /dependents onnxruntime\capi\onnxruntime_pybind11_state.pyd"

it will show the dll dependencies.

Dump of file onnxruntime\capi\onnxruntime_pybind11_state.pyd

File Type: DLL

  Image has the following dependencies:

    python35.dll
    cublas64_100.dll
    cudnn64_7.dll
    SHLWAPI.dll
...

please ensure all the dependencies are present and available in the path.

**Comment by snnn** [comment]
Is there anything before the "Traceback (most recent call last):" message ?

**Comment by tianleiwu** [comment]
I encountered similar error. The solution is to install CUDA 10.0, and CuDNN 7.3 (on Windows) or 7.6 (on Linux). 
Here is an example to run in Windows:
(1) Make sure those DLLs can be found in path, like in Windows command line:
   set Path=%Path%;<path to Cuda Bin directory>; <path to CuDNN bin directory>
(2) After that, you can run python script in the same command window.

**Comment by jywu-msft** [comment]
> Is there anything before the "Traceback (most recent call last):" message ?

@YZhao33 can you comment on @snnn 's question? there may be a message prior which will indicate the missing dll.

**Comment by YZhao33** [comment]
Thank you! the issue is solved. I forgot to put cudnn into path.
