### ISSUE TITLE
JNI version seems too high for Android

### ISSUE THREAD

**Issue by daquexian** [microsoft/onnxruntime#2925]
**Describe the bug**

@Craigacp Thanks for your great work on Java API!

When compiling Java API for Android (with some necessary modifications), the compilation fails because `JNI_VERSION_1_8` [here](https://github.com/microsoft/onnxruntime/blob/master/java/src/main/native/OrtJniUtil.c#L13) doesn't exist in `jni.h` of Android NDK. The highest jni version Android NDK has is `JNI_VERSION_1_6`.

Could the jni version be downgraded to 1.6 safely? Thanks! @Craigacp 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- ONNX Runtime installed from (source or binary): source
- GCC/Compiler version (if compiling from source): latest Android NDK

**Comment by Craigacp** [comment]
I set it to 1.8 as the Java code requires Java 8, but I'm not entirely sure what JNI changes are exposed by requesting 1.8 instead of 1.6. I'll ask around and see if I can determine what the difference is.

**Comment by Craigacp** [comment]
The 1.8 level is necessary to call a default method on an interface from JNI. I don't think we do this anywhere in the codebase, so it should be ok to export the lower version until we do do that (and I'll have to document that somewhere as otherwise it will be very mysterious). Any idea why the Android NDK exports the lower version when it supports Java 8?

**Comment by daquexian** [comment]
@Craigacp Thanks!

> Any idea why the Android NDK exports the lower version when it supports Java 8?

sorry I have no idea either ;)
