### ISSUE TITLE
Does CAST node support INT64 to FLOAT16?

### ISSUE THREAD

**Issue by crvkumar** [microsoft/onnxruntime#2974]
For a model converted from Float32 to Float16, an error is thrown while trying to load the inference session at the CAST node stating that the expected output type is tensor(float) rather than the actual tensor(float16).

**Comment by hariharans29** [comment]
It seems like there is a problem with the conversion. Just to be sure, can you share the model please ?

**Comment by crvkumar** [comment]
The model works fine using ML.NET 1.4.0. 
Sorry about the rather large model file. It is a transfer learnt VGG16 model.

[https://drive.google.com/open?id=15gw1bfgBLLcXLrM5LxA2408_60tm5Hi4](url)

**Comment by konabuta** [comment]
@hariharans29  Could you check this ?

**Comment by hariharans29** [comment]
Hi,

Sorry I was busy with other stuff and I lost track of this.

I took a look and it seems like the model has an issue - 


![image](https://user-images.githubusercontent.com/9969784/76997015-c9d7a400-690f-11ea-891a-122ba6575065.png)

The output edge is marked to be of float16 type (which seems to be expected as the node consuming this edge seems to require float16 too). But the 'to' attribute has a value '1' which according to Cast's [spec](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Cast), actually corresponds to converting it to [float](https://github.com/onnx/onnx/blob/master/onnx/onnx.proto#L453). When ORT runs type inferencing statically (at model load time), it notices that the request is to convert it to "float" but the edge is bound to "float16" and hence it throws.

ORT does support [converting to float16](https://github.com/microsoft/onnxruntime/blob/c24d7a8a0a95002cfde70db8ffdac1a1d95b3ca7/onnxruntime/core/providers/cpu/tensor/cast_op.cc#L54). So, once this issue is fixed, provided there are no other conversion issues, the model should run fine.

**Comment by hariharans29** [comment]
Here is a way to fix this issue. 

Install onnx via pip  and then run this script - 

```
import onnx

model =onnx.load('cast_model.onnx')
graph = model.graph
for node in graph.node:
	if node.name == "TFNodes_flatten_1_Shape__7":
		for attr in node.attribute:
			attr.i = 10
	
onnx.save(model, 'cast_model_fixed.onnx')
```

The fixed model loaded fine for me but you must try making sample inference runs and make sure the output is right because there could be more conversion issues/ runtime issues.

Closing this out for now. Please re-ope if you encounter further issues. Thanks.
