### ISSUE TITLE
No Op registered for Shape with domain_version of 12

### ISSUE THREAD

**Issue by sdpython** [microsoft/onnxruntime#2982]
**Describe the bug**

Operators not modified in onnx 12 are not supported if the onnx graph is created with opset 12.

```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:kgpd_Shape : No Op registered for Shape with domain_version of 12
```

**Urgency**
Probably worht investigating.

**System information**
- Debian
- ONNX Runtime installed from gihub
- ONNX Runtime version: master branch (onnx from master branch too)
- Python version: 3.7

**To Reproduce**

Run python unit tests of onnxruntime.

**Expected behavior**

**Screenshots**

```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:kgpd_Shape : No Op registered for Shape with domain_version of 12
```

**Comment by snnn** [comment]
We would think that's a converter bug. Please use the correct opset.

**Comment by snnn** [comment]
Please see the discussion below.

<hr/>

From: Wenbing Li 
Sent: Friday, November 8, 2019

Most of converters always stamps the model with max since version from all op appeared, instead of target opset number specified by the user.
Then, If the model generated by the converter was stamped with opset 12, it really means it contains at least one op which spec is changed beyond opset 11 , and there is no way to let the released ORT support it, so the runtime has to raise an exception for it.

<hr/>

**Comment by GuanLuo** [comment]
Sorry for reviving the thread, is this restriction newly introduced in v1.2.0? If so, is there an estimate on when opset 12 will be supported?

I am trying to use latest ONNXRuntime version (v1.2.0), and hitting this issue in our tests. Apparently the models we used are generated with opset 12, but the older version (v1.1.1) we used will load the models without throwing this exception.
