### ISSUE TITLE
Error using output of one model as input for another

### ISSUE THREAD

**Issue by erikbrntsn** [microsoft/onnxruntime#2983]
I have two nested/sequential models i.e. I want to call model2.Run(model1.Run(data))
With the call to model2.Run I get "Arithmetic operation resulted in an overflow". I dont believe it is really related to #713 as the output of model1 is a 1x64x56x64 float tensor which should not give any memory problems.

The overflow happens here
```
return new MemoryHandle((void*)((int)_dataBufferPointer + elementIndex * _elementWidth)); //could not use Unsafe.Add
```
with _dataBufferPointer=0x000002c542065060, elementIndex=0

The output dimensions of model1 are the same as the input dimensions for model2.

I am using onnxruntime in a c# application through the nuget package (version 1.1.1).

I am missing something?
If this is intentionally not supported, would it be possible to output a more user friendly error message?

**Comment by hariharans29** [comment]
Can you share the model please ?

**Comment by hariharans29** [comment]
Also, are you able to run both the models individually ?

**Comment by erikbrntsn** [comment]
I just tried a few things and doing the following works:

```
model2.Run(Fix(model1.Run(data)))

private static List<NamedOnnxValue> Fix(IDisposableReadOnlyCollection<DisposableNamedOnnxValue> t, InferenceSession model)
{
    var q = t.First().AsTensor<float>();
    var dims = q.Dimensions;
    var data = q.ToArray();
    var tensor = new DenseTensor<float>(data, dims);
    var name = model.InputMetadata.Keys.First();
    return new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor(name, tensor) };
}
```
So yes, both models works individually.

**Comment by erikbrntsn** [comment]
I have created a minimal model that reproduces the problem:

[Uploading models.zip…]()

Run the following in a c# application:
```
head.Run(base.Run(data))
```

The two models are implemented in PyTorch like this:

```
class BaseModel(nn.Module):
    def __init__(self):
        super(BaseModel, self).__init__()
        self.conv = torch.nn.Conv2d(1, 64, kernel_size=3, stride=1, padding=1)

    def forward(self, x):
        return self.conv(x)


class Head(nn.Module):
    def __init__(self):
        super(Head, self).__init__()
        self.conv = torch.nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1)

    def forward(self, x):
        return self.conv(x)
```

**Comment by hariharans29** [comment]
Hi,

I finally got around to investigating this. I used your sample models (thanks) and there are several takeaways:

1) The output (tensor) of Run() is of type `DisposableNamedOnnxValue` and the input tensor of Run() is of type `NamedOnnxValue`. `DisposableNamedOnnxValue` is a derived class of `NamedOnnxValue` and hence Run() accepts the output of another Run(). Unfortunately, there is logic in the Run() to pin managed memory buffer in the `NamedOnnxValue` which doesn't play well with `DisposableNamedOnnxValue` since `DisposableNamedOnnxValue` is maintains a wrapper over the native memory containing the output of Run(). 

2) We could support an input to Run() containing `DisposableNamedOnnxValue`  by adding some gaurd logic to prevent pinning in that case and directly re-using the native memory but chances of that being useful are very low because both `NamedonnxValue` and `DisposableNamedOnnxValue` are bound to "feed names" and hence validation of the input will eventually fail unless we run into the very rare chance that the output name of one model exactly matches the input name of the next model. Even in your toy example, even though the shapes match the names are different. 

3) As it stands, you can get it to work with something like this - 
                var container1 = new List<NamedOnnxValue>();
                var tensorIn = new DenseTensor<float>(....);
                var nov1 = NamedOnnxValue.CreateFromTensor("input", tensorIn);
                container1.Add(nov);

                var res1 = session1.Run(container);
                // This is not disposed

                var container2 = new List<NamedOnnxValue>();
                var nov2 = NamedOnnxValue.CreateFromTensor("input", res1.First().AsTensor<float>().ToDenseTensor()); // .ToDenseTensor() copies contents over
                container2.Add(nov2 );
                var res2 = session.Run(container2);

4) The above will work but is not optimal -
     i) It will create another managed buffer and copy over the contents of the results of the first run
    ii) It will create another OrtValue instance (for the new input) before calling into native code. Ideally we should be able to re-use the OrtValue instance created from the output of the first Run()

5) There is a PR by @fs-eire (https://github.com/microsoft/onnxruntime/pull/3171) that will eventually solve it. It introduces a new class `PinnedOnnxValue` that can help re-use the underlying OrtValue value instances and there are several Run() overloads that will take in PinnedOnnxValues. You can use PinnedOnnxValue for the output of the first Run() and use the same for the input of the next Run() and that will solve the problem.

**Comment by hariharans29** [comment]
Synced offline with @fs-eire. After discussing, we felt DisposableNamedOnnxValue inputs in Run() should be accommodated as DisposableNamedOnnxValue is NamedOnnxValue (it is a derived class). Adjusted the PR contents accordingly.

**Comment by erikbrntsn** [comment]
Thank you guys!
