### ISSUE TITLE
Question about adding new optimization 

### ISSUE THREAD

**Issue by engdorm** [microsoft/onnxruntime#3042]
I want to add new optimization, 
In this optimization, some nodes will be added pads to their inputs,
The question is there a way to update all of the shapes of the tensors in the graph 
I changed only the node Inputs and output Defs of the specific Node 
but is there a way to do ShapeInfernce with the same graph 
Or some help function in the graph_utils that I can use?

Thanks

**Comment by skottmckay** [comment]
The optimizers and graph_utils aren't really setup for changing shapes of everything downstream in the graph, so there's no utility for doing that (I'd expect it would be non-trivial as well). 

FWIW, after an optimizer modifies the graph it will get resolved again, which will run the type/shape inferencing, however there's a good chance that will fail due to a mismatch between the expected and inferred shapes. 

Possibly this sort of change is better done prior to model loading as often individual nodes don't have shapes, and the shape inferencing will fill that info in when the model is loaded so you get propagation of the values for free.
