### ISSUE TITLE
inference 4096 Images, GPU, small modell

### ISSUE THREAD

**Issue by Armin234** [microsoft/onnxruntime#3190]
Hi,

using the gpu provider (Cuda), I noticed that increasing the batch from 1 to 128 will speedup the inference near 10x, but increasing the batch size more will slow down the inference.
The workload of the GPU is less then 10%

What can I do to speedup the inference ?

Win10
C-Api
Cuda-Provider
GPU RTX 2070 Super

[Batch_1.zip.001.zip](https://github.com/microsoft/onnxruntime/files/4323780/Batch_1.zip.001.zip)
[Batch_1.zip.004.zip](https://github.com/microsoft/onnxruntime/files/4323783/Batch_1.zip.004.zip)
[Batch_1.zip.002.zip](https://github.com/microsoft/onnxruntime/files/4323784/Batch_1.zip.002.zip)
[Batch_1.zip.003.zip](https://github.com/microsoft/onnxruntime/files/4323785/Batch_1.zip.003.zip)

**Comment by skottmckay** [comment]
Hard to say without seeing the model. 

One thing to note is that ORT does not split up a batch internally, so you may get better performance by doing that yourself and making concurrent requests to Run, if that is possible with your model. By 'split up' I mean that if ORT received a batch of 4 items, it doesn't take each item (or say 2 items at a time) and run it separately through the graph in parallel.   

e.g. say you have 4 cores. you could send in 4 concurrent requests to Run, each with a batch size of 128. you may also want to set intra-op threadpool size to 1 so that the concurrent requests aren't attempting to use more threads than there are cores (only necessary if some of the nodes are assigned to CPU though).
