### ISSUE TITLE
Error when quantizing Squeezenet

### ISSUE THREAD

**Issue by marph91** [microsoft/onnxruntime#3220]
**Describe the bug**
Quantization of Squeezenet with the script [quantize.py](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/quantize.py) fails in mode `QuantizationMode.QLinearOps`.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Opensuse 15.1
- ONNX Runtime installed from (source or binary): binary (pip)
- ONNX Runtime version: 1.1.1
- ONNX version: 1.6.0
- Python version: 3.6.10
- Visual Studio version (if applicable): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**To Reproduce**
- Download the newest Squeezenet from https://github.com/onnx/models.
- Execute the code (adapted from the tutorial):
```
import numpy as np
import onnx
from quantize import quantize, QuantizationMode

# Load the onnx model
model = onnx.load('squeezenet1.1.onnx')
# Quantize
quantized_model = quantize(model, quantization_mode=QuantizationMode.QLinearOps,
                               static=False,
                               quantization_params={'squeezenet0_flatten0_reshape0': [np.uint8(128), np.float32(0.0)]})
# Save the quantized model
onnx.save(quantized_model, 'squeezenet1.1_quantized.onnx')
```
- The following error appears:
```
Warning: The original model opset version is 7, which does not support quantized operators.
            The opset version of quantized model will be set to 10. Use onnx model checker to verify model after quantization.
Traceback (most recent call last):
  File "quantize_model.py", line 66, in <module>
    main()
  File "quantize_model.py", line 62, in main
    parse_param("/home/martin/Downloads/onnx_models/squeezenet1.1.onnx")
  File "quantize_model.py", line 27, in parse_param
    quantization_params={'squeezenet0_flatten0_reshape0': [np.uint8(128), np.float32(0.0)]})
  File "/home/workspace/picocnn/code/python_tools/cnn_onnx/quantize.py", line 1486, in quantize
    quantizer.quantize_model()
  File "/home/workspace/picocnn/code/python_tools/cnn_onnx/quantize.py", line 312, in quantize_model
    new_list += self._quantize_convolution(node, new_list)
  File "/home/workspace/picocnn/code/python_tools/cnn_onnx/quantize.py", line 1359, in _quantize_convolution
    return self._quantize_convolution_qlinear_ops(node, new_nodes_list)
  File "/home/workspace/picocnn/code/python_tools/cnn_onnx/quantize.py", line 1257, in _quantize_convolution_qlinear_ops
    assert (data_found)
AssertionError
```

**Expected behavior**
Successful quantization.

**Additional context**
Trying to quantize Modelnet yielded the same result.

**Comment by pranav-prakash** [comment]
I believe this is because even in `dynamic` quantization mode you must specify the output scale for all the quantized operators (only the input scales are dynamically computed). You can use the `calibrate.py` script to do this.

Perhaps to make this more clear, instead of the `assert` an exception could be thrown (e.g "Output quantization parameters not specified for node {}")

**Comment by marph91** [comment]
Thanks for the clarification. After reading it again I'm understanding more. However, it's not working yet. My use case is:
- specifying the scales and zero points manually (because they are restricted to 2^x, respectively 0)
- using `quantize.py` with static quantization to convert all `Conv` layers to `QuantizeLinear -> QLinearConv -> DequantizeLinear`

Is this possible at all? Is there any example of using `quantize.py` with static quantization on a real model?

The corresponding code is:
```python
import numpy as np
import onnx

from quantize import quantize, QuantizationMode


def calibrate_custom(model):
    quant_dict = {}
    for node in model.graph.node:
        if node.op_type == "Conv":
            quant_dict[node.input[0]] = [np.uint8(128), np.float32(0.0)]
            quant_dict[node.output[0]] = [np.uint8(128), np.float32(0.0)]
    return quant_dict


def main():
    filename = "squeezenet1.1.onnx"
    filename_q = "squeezenet1.1_quantized.onnx"

    model = onnx.load(filename)

    param_q = calibrate_custom(model)

    quantized_model = quantize(model, quantization_mode=QuantizationMode.QLinearOps,
                               static=True,
                               quantization_params=param_q)

    onnx.save(quantized_model, filename_q)


if __name__ == "__main__":
    main()
```

```
> python3 calibrate.py 
Warning: The original model opset version is 7, which does not support quantized operators.
            The opset version of quantized model will be set to 10. Use onnx model checker to verify model after quantization.
Traceback (most recent call last):
  File "calibrate.py", line 32, in <module>
    main()
  File "calibrate.py", line 26, in main
    quantization_params=param_q)
  File "/home/workspace/pocket-cnn/code/python_tools/cnn_onnx/quantize.py", line 1486, in quantize
    quantizer.quantize_model()
  File "/home/workspace/pocket-cnn/code/python_tools/cnn_onnx/quantize.py", line 312, in quantize_model
    new_list += self._quantize_convolution(node, new_list)
  File "/home/workspace/pocket-cnn/code/python_tools/cnn_onnx/quantize.py", line 1359, in _quantize_convolution
    return self._quantize_convolution_qlinear_ops(node, new_nodes_list)
  File "/home/workspace/pocket-cnn/code/python_tools/cnn_onnx/quantize.py", line 1252, in _quantize_convolution_qlinear_ops
    quantized_bias_name = self._quantize_bias(node, nodes)
  File "/home/workspace/pocket-cnn/code/python_tools/cnn_onnx/quantize.py", line 904, in _quantize_bias
    node.input[0]].scale_name
KeyError: 'data'
```

`data` is the input of the whole model. It isn't found in the dict `self.quantized_value_map`. But I think it is correct. `data` isn't in this dict, because it didn't get quantized.

**Comment by pranav-prakash** [comment]
Yes this is possible, although the version of `calibrate.py` upstream doesn't properly implement static quantization. Take a look at my [fork](https://github.com/pranav-prakash/onnxruntime-riscv/tree/systolic/systolic_runner/quantization) which extends their scripts to handle full-static quantization.

Take note that my use case is `int8` quantization, so you'll have to comment out the set of lines in [calibrate.py:222](https://github.com/pranav-prakash/onnxruntime-riscv/blob/systolic/systolic_runner/quantization/calibrate.py#L222) and uncomment the following set. 

You'll also have to change back [quantize.py:1458](https://github.com/pranav-prakash/onnxruntime-riscv/blob/systolic/systolic_runner/quantization/quantize.py#L1458) to `symmetric_activation=False` and `symmetric_activation=False`.

You can invoke the entire thing by running
```
python3 calibrate.py --model_path $MODEL/model.onnx --dataset_path $MODEL --output_model_path $MODEL/model_quantized.onnx --data_preprocess=None --static=True
```
as noted in the quickstart readme, where $MODEL points to the folder containing the model+test data downloaded from the model zoo (the folder should contain the .onnx proto along with various files like `test_data_set_0`). This will calculate calibration parameters aggregated across all available test cases, then run the quantizer with those parameters.

I've successfully tested this on various models including squeezenet and googlenet. Let me know if anything doesn't work though, since I've only really been focusing on our specific use case.

If there's interest I'd be happy to work on upstreaming this, since the changes made were pretty minimal and mostly limited to the calibration script.

**Comment by marph91** [comment]
Thanks for your help! The script is now working and I can test a little bit around. If there is enough time, I will try to use the calibration script for the use case, too. In general it would be good to have the fix in `_quantize_bias` upstream, to prevent others to have this issue.

About the parameters, you are right. Somehow the chosen values in the tutorial, led me to the wrong assumption that scale is the first parameter.
