### ISSUE TITLE
Long load time when using Grouped convolutions

### ISSUE THREAD

**Issue by d-colwell** [microsoft/onnxruntime#3361]
I am using a Depthwise/Pointwise op in my network, and i notice that when loading a network that contains depthwise (grouped) convolutions, it takes a *lot* longer to load. 

Secondary issue, there seems to be a lot of idle time on either side of the network executing.
I've included sample networks that just use stacked conv/bn/activation layers, as well as the associated performance log files from Onnxruntime.

- GPU: Nvidia Titan RTX
- Onnxruntime: Trunk build, running Python inference, Cuda and TensorRT enabled (Cuda exec provider used)
- Python version 3.7.5
- CUDA: 10.1
- CUDNN: 7.5.3
[ONNX files and perf logs](https://github.com/microsoft/onnxruntime/files/4400412/NeuralNetworks.zip)

**Comment by skottmckay** [comment]
Slow loading is possibly due to the model being optimized at load time. If you disable optimizations (set the graph_optimization_level to 0. see [here](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Perf_Tuning.md)) for more info) what is the load time like? If that's the cause it's possible to save the optimized model so loading is faster in the future.

Do the inputs/outputs need to be copied between CPU and GPU? That could explain the delay between the executor starting and ending.

**Comment by d-colwell** [comment]
I will do some benchmarks with pre-loading the inputs to the GPU. Its less worrying than the initial load. Taking 10 seconds to load a tiny network the first time is pretty slow
