### ISSUE TITLE
Memory use with GPU in C++ API

### ISSUE THREAD

**Issue by danperazzo** [microsoft/onnxruntime#3427]
**Describe the bug**
I have been tring to use GPU support to my ONNX model (ported from Tensorflow) using the C++ API. However, I noticed that the program now consumes much more memory compared with the original Python implementation (about 25% more memory). And, because of the memory usage, I cannot access the GPU (too much memory). Are there any commands I can use to optimize memory usage? Again, thanks for the help!
**Urgency**
1 week

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): Binary from Nuget package
- ONNX Runtime version: 1.2.0
- Python version: ---
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.1/cudnn 7.6
- GPU model and memory: GEFORCE GTX1050ti/4Gb memory

**Comment by faxu** [comment]
@danperazzo sorry for the delay. is this issue still relevant? If so, could you repro with the latest release version (1.3) and share your model and the performance #s? Also, since you're on Windows, have you tried the [DirectML EP](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.directml)? (More info on DML - https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/DirectML-ExecutionProvider.md)
