### ISSUE TITLE
C++cuda api

### ISSUE THREAD

**Issue by huang229** [microsoft/onnxruntime#3592]
I will refer to the application examples you have given.
CUDA 10.0 I used. But it doesn't work.

An exception is thrown at the following code.
CUDAExecutionProvider::PerThreadContext::~PerThreadContext() {
  CUBLAS_CALL_THROW(cublasDestroy(cublas_handle_));
  CUDNN_CALL_THROW(cudnnDestroy(cudnn_handle_));
}
The exception information is as follows:
Detected memory leaks!
Dumping objects ->
{118736} normal block at 0x0000028107AF88C0, 8 bytes long.
I've been thinking about it for a long time, but I still don't know what's wrong. I hope I can get help. Thank you.
In addition, I did not see that the example you provided also contains the header file using CUDA API.
https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/fns_candy_style_transfer/fns_candy_style_transfer.c

**Comment by huang229** [comment]
I also tested the example you provided. The CPU is faster than GPU, and I don't know why. I refer to the examples and steps provided by you. The examples are as follows:
https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/fns_candy_style_transfer/fns_candy_style_transfer.c

**Comment by huang229** [comment]
@jdhuntington

**Comment by skottmckay** [comment]
Can you please fill out the issue template to provide a bit more context?

**Describe the bug**
A clear and concise description of what the bug is.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by huang229** [comment]
@skottmckay  Thank you very much for your reply. I'm sorry, because I'm busy in the near future and I can't give you feedback in time.
The two problems I encountered above are essentially the same. Now let's just talk about the second one, because this is an example you provide, which is convenient to explain.
Let me repeat the question:
I also tested the example you provided. The CPU is faster than GPU, and I don't know why. I refer to the examples and steps provided by you. The examples are as follows:
https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/fns_candy_style_transfer/fns_candy_style_transfer.c

System information
OS Platform and Distribution (e.g., win10):
ONNX Runtime installed from (source):
ONNX Runtime version: 1.1.0
Python version:  python3.6.7
Visual Studio version (if applicable):  vs2017
GCC/Compiler version (if compiling from source):  vs compiler
CUDA/cuDNN version: cuda10.0 /cudnn7.5.1
GPU model and memory:  8G
Compile the executable completely according to the links and instructions you provided.
In the code, only the print model forwarding time is added here.
clock_t start,ends;
start=clock();
  ORT_ABORT_ON_ERROR(
      g_ort->Run(session, NULL, input_names, (const OrtValue* const*)&input_tensor, 1, output_names, 1, &output_tensor));
ends=clock();
cout<<ends-start<<endl;

Then, prepare an image:
PNG format
Dimension of 720x720
Run
Command to run the application:
fns_candy_style_transfer.exe <model_path> <input_image_path> <output_image_path> [cpu|cuda|dml]

**Comment by skottmckay** [comment]
IIRC the exception can happen if the per thread context was not freed prior to the application shutting down as the cuda library may have been unloaded before PerThreadContext::~PerThreadContext runs. There's at least a catch for the exception in the latest code and I think the issue was resolved so things are freed correctly.

Regarding the speed it may simply be that to run the model on GPU the inputs and outputs need to be copied between CPU and GPU. You could enable profiling by calling g_ort->EnableProfiling(...) to see. Note that this adds overhead so it will just give a better idea of how long executing the model takes with the device copy excluded by looking at the time taken by the sequential executor. See [here](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Perf_Tuning.md#profiling-and-performance-report) for some more details on viewing the profiling output.

**Comment by huang229** [comment]
I'm very sorry. I found the reason. It's a very low-level error. CUDA will initialize many things from CPU to GPU in the first pass, so it's wrong to test a pass.
