### ISSUE TITLE
Loop outputs are incorrect when TRIP_COUNT is the input for the subgraph

### ISSUE THREAD

**Issue by kevinch-nv** [microsoft/onnxruntime#3794]
**Describe the bug**
Loop calculations using `TRIP_COUNT` as an input seems to be incorrect.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): Binary
- ONNX Runtime version: 1.6.0
- Python version: 3.6.9
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a
 
**To Reproduce**
Run ONNXRT inference on the model provided.

**Expected behavior**
Model can be summarized to: `LOOP(trip_count (5), <none>, input) -> ADD(input, trip_count)`

Since the addition is using trip_count as an input, the corresponding loop should be:
`for (i = 0; i < trip_count; i++) input = input + trip_count;`

Instead, the loop is calculating:
`for (i = 0; i < trip_count; i++) input = input + i;`

**Screenshots**
n/a

**Additional context**
Graph can be found here: https://drive.google.com/file/d/1Ms7HQXqMTOwg0wEUKjKX3GHPpw-hNUJe/view?usp=sharing

**Comment by jywu-msft** [comment]
@skottmckay , can you verify this bug?

**Comment by skottmckay** [comment]
The trip count is only used in the Loop implementation to determine how many times to call the subgraph. As per the spec the subgraph is called with the iteration number as the first input. See the description of the 'body' attribute [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-37)

It is possible to add the trip_count to the input by referencing it as an outer scope variable. If you wish to do that the input to the Add node in the subgraph should be '2' (the constant in the main graph with the trip count) instead of 'i.1' (the current iteration passed as the first input to the subgraph.

**Comment by kevinch-nv** [comment]
Thanks @skottmckay for the clarification. Closing.
