### ISSUE TITLE
Inference session output with null _nativeMemoryManager (C#)

### ISSUE THREAD

**Issue by nathanlamplough-MeVitae** [microsoft/onnxruntime#3822]
**Describe the bug**
The output probabilities resulting from calling .Run on my onnx inference session have a null _nativeMemoryManager value, so when I try to obtain the probability values by calling .AsTensor\<float> or .AsDictionary<long,float> null is returned.

**System information**
- OS Platform and Distribution : Windows 10
- ONNX Runtime installed from (source or binary): Nuget
- ONNX Runtime version: Microsoft.ML.OnnxRuntime 1.2.0
- Python version: 3.7.3
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
C# Code:
```
using (var session = new InferenceSession(StaticFields.MULTINOMIALNBONNXMODEL))
            {
                var inputMeta = session.InputMetadata;
                var container = new List<NamedOnnxValue>();

                var tensor = new DenseTensor<string>(new string[] { "Test string" }, inputMeta.Values.First().Dimensions);
                container.Add(NamedOnnxValue.CreateFromTensor<string>("input", tensor));

                // Run the inference
                using (var results = session.Run(container))
                {
                    var labelOutput = results.First().AsTensor<long>().GetValue(0);
//this gives null output
                    var probabilitiesOutput = results.Last().AsTensor<float>();
                }
            }
```
Python Model Creation:

```
from skl2onnx import convert_sklearn
from sklearn.pipeline import Pipeline
from skl2onnx.common.data_types import StringTensorType
from sklearn.feature_extraction.text import TfidfVectorizer
from onnxmltools import save_model

text_clf = Pipeline([
     ('tfidf', TfidfVectorizer()),
     ('clf', MultinomialNB()),
])
text_clf.fit(X_train, y_train)
model_onnx = convert_sklearn(text_clf,
                            name= 'NB_Predictor',
                             initial_types=[("input", StringTensorType([1, 1]))])
save_model(model_onnx, "NB_Predictor.onnx")
```

**Expected behavior**
I expect to be able to convert the probability values to a tensor

**Screenshots**
Showing null value with output probabilities
![onnx-c#-screenshot](https://user-images.githubusercontent.com/53299652/81080446-a03b0200-8ee8-11ea-9b4d-b917dac64afc.PNG)

**MODEL**
[NB_Predictor.zip](https://github.com/microsoft/onnxruntime/files/4581504/NB_Predictor.zip)

**Comment by hariharans29** [comment]
Hi,

I investigated this. Your second output is actually a sequence of maps. You would have to do this to parse the results (I verified the output) - 

```
var seq = results.Last().AsEnumerable<NamedOnnxValue>();
var map = seq.First().AsDictionary<Int64, float>();
```

Please check out this example - https://github.com/microsoft/onnxruntime/blob/22a711457f369cef32b3d00881e9ed7da44a826e/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L1321

_nativeMemoryManager being null is a red herring. It will be null for non-tensor types (i.e.) maps and sequences or sequence of maps because the output of the native Run() is converted to a managed object in these cases (as opposed to tensors where we only maintain a handle to the native OrtValue and hence it would be non-null), but this is an implementation detail.

Hope this helps.

**Comment by nathanlamplough-MeVitae** [comment]
Amazing, thank you!
