### ISSUE TITLE
onnxrt fails at no-op squeeze

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/onnxruntime#3922]
I was exporting a squeeze call of non-single dimension in PyTorch (should have no-op effect). OnnxRuntime fails when executing such a trace. I'm not sure if onnxrt or PyTorch is being at fault.

Full repro and description: https://github.com/pytorch/pytorch/issues/36796

**Comment by hariharans29** [comment]
Hi,

I read through your description and investigated both the provided models. Actually, the statement - "Squeeze of dimension 1 is a no-op, since it's not squeezable" is not true per ONNX spec. Please see https://github.com/onnx/onnx/blob/master/docs/Operators.md#Squeeze, where it says "If an axis is selected with shape entry not equal to one, an error is raised". This means that for the input of shape [16, 8000], if the axes contains [1] for the Squeeze node, then an error will have been raised in ORT - https://github.com/microsoft/onnxruntime/blob/e86214e5c00ffbb95b85478c111c8eb21de94fe9/onnxruntime/core/providers/cpu/tensor/squeeze.h#L46. 

This specific model fails at loading stage - to be precise when it runs shape inference. This is because, in the shape inference logic for Squeeze - https://github.com/onnx/onnx/blob/6801d7e46f4768ae2a304615edb69ff1a388c624/onnx/defs/tensor/old.cc#L1196, since the dimensions are symbolic in the graph ["B", "T"], it can't check if the dim value is 1 and raise an error there, hence it proceeds to "squeeze" out the dim which then fails in the Slice node because the Slice node now has an input data rank of 1 and the axes seems to have a value {1} which is outside the range of accepted values and hence shape inference throws here - https://github.com/onnx/onnx/blob/6801d7e46f4768ae2a304615edb69ff1a388c624/onnx/defs/tensor/old.cc#L865.

Technically, this is not an ORT issue and hence I am closing it out. Please re-open if you have more questions.

**Comment by vadimkantorov** [comment]
@hariharans29 Thanks for explanation! I'll update the PyTorch issue accordingly!
