### ISSUE TITLE
CUDA error executing cudaMemcpy for large batch size

### ISSUE THREAD

**Issue by lifuhuang** [microsoft/onnxruntime#4008]
**Describe the bug**

Fail: [ONNXRuntimeError] : 1 : FAIL : CUDA error executing cudaMemcpy(dst_data, src_data, bytes, cudaMemcpyDeviceToHost)

**Urgency**
ASAP

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows Server 2019
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: Latest
- Python version: 3.7.5
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28614
- CUDA/cuDNN version: 
CUDA:7.6.5.32
cuDNN: 10.2
TensorRT: 7.0.0.11

- GPU model and memory: Tesla V100

**To Reproduce**
1. Built ONNX Runtime with TensorRT
2. Run the BERT-SQuAD model (the one in ONNX model zoo after shape inferrence) using different providers
3. Both CPU and Tensor RT seems to work for all different batch sizes (1, 2, 4, 8, 16, 32, 64)
    But CUDA starts failing with batch_size greater than 29 (e.g. batch size 28 works fine)

**Expected behavior**
Since the same model / batch size works for Tensor RT and CPU, I expect it should also work for CUDA.

**Comment by skottmckay** [comment]
Is there a call stack from the error? It's strange it's in cudaMemcpy (vs memory allocation), so would need to know what it was trying to copy at the time.

I don't have the same hardware so not sure I can repro. When you say 'starts failing' are you using the same InferenceSession for all the requests and changing provider and/or increasing batch size each time?

**Comment by lifuhuang** [comment]
Thank you Scott for looking into the issue!

I tried again today using a different hardware (both V100 and M60 GPU) and even different model (a similar BERT model from our partner team), the same issue seems to repro in all the cases. 

I couldn't seem to find and call stack in the error message and the issue happens regardless if I using the same InferenceSession for all requests and change provider and/or starting a new InferenceSession with a large batch size.

Please feel free to let me know if there is any extra information that I can provide.

**Comment by skottmckay** [comment]
So there are a lot of things interacting here. I boils down to an out of memory error from the arena that tries to allocate a large block for the whole run to use. It hits an edge case where it doesn't throw when it can't do the allocation, a nullptr is returned but that isn't checked for, and the nullptr gets stuffed in another stucture that we use when we need some memory for an Node. When we go to use that memory we get the nullptr (but assume it's a valid pointer to an offset within a large block) and that is passed to the cudaMemcpy as the destination address. In my testing where I saw an allocation failure instead of cudaMemcpy error it didn't hit this edge case - so it's actually the same root cause just with different error messages.

This happens on the second run as on the first one the arena doesn't know how large a block size to use so we allocate smaller blocks as we go along (if you run onnx_test_runner with '-v' you'll see output from BFCArena where these blocks are allocated). On the second run we go to allocate the large block, but we don't currently have a way to cleanup the smaller blocks from the first run which we're not going to use, leading to the out of memory error as now you essentially need 2x the memory (left over blocks from the first run and the single large block of the same total size for the second run). This is why TensorRT works with the batch size as it's not using this arena.

Additionally onnx_test_runner is reporting success for multiple runs even though only the first one is passing, which is why it's harder to notice the error when using that. 

Short term I'll see if we can handle the large block allocation failure better. Performance won't be totally optimal but it should still be able to use the smaller blocks from the first run so it shouldn't be too bad. There may be some other options but I'll need to test those out better and they may take a lot longer to validate and implement.
