### ISSUE TITLE
Improve C++ API with support for modern C++ standards

### ISSUE THREAD

**Issue by jgbradley1** [microsoft/onnxruntime#4094]
Is there interest in updating the C++ API to use modern C++ best practices? From what I can tell, the C++ API is just a simple wrapper around the C API. It could in theory be more supportive of modern C++ standards and handle the necessary conversions to the C API.

For example, support for `std::string` over `const char *` would improve the ability to integrate with other frameworks/libraries instead of forcing C++ devs to drop down to C-style syntax.

For example
```
// works only because of implicit conversion
size_t num_nodes = session.GetInputCount();
std::vector<std::string> input_node_names;
for (int i=0; i<num_nodes; i++) {
    input_node_names.push_back( session.GetInputName(i, allocator) );
}

size_t num_nodes = session.GetOutputCount();
std::vector<std::string> output_node_names;
for (int i=0; i<num_nodes; i++) {
    output_node_names.push_back( session.GetOututName(i, allocator) );
}
```

But when trying to run inferrence:
```
// will not work
std::vector<Ort::Value> output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names.data(), input_tensors.data(), input_tensors.size(), output_node_names.data(), output_node_names.size());
```

because `input_node_names` and `output_node_names` are strings.

**Describe the solution you'd like**
Add support for the string type in the public API functions. This could also lead to simplifying the `Run()` call to something like:

```cpp
std::vector<Ort::Value> output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names, input_tensors.data(), input_tensors.size(), output_node_names);
```

**Additional context**
In general, I would appreciate more modern C++ standards supported by the C++ API with direct support for STL containers (i.e. std::vector) and the string type. Perhaps the C++ API could make better use of function templates to allow this - but starting by adding support for the `string` type would be a first step.

**Comment by pranavsharma** [comment]
We welcome external contributions. Would you like to create a PR for this? Thx.
cc @RyanUnderhill

**Comment by RyanUnderhill** [comment]
@jgbradley1 I agree! One of the goals of the C++ wrapper was to have zero performance cost to using it, which of course wasn't possible for std::string due to the cost of creating them.

But, if this is something every user is going to need to do anyways, it's probably a good idea to have it for convenience. As long as there is a way to let the user know that there is an extra cost for that one.

**Comment by KevinHake** [comment]
I'd use std::vector inputs instead of 'buffer, buffersize' inputs for Ort::Session::Run and other calls with buffers if it were available. Don't need to get rid of the old interface, it can be overloaded.

Also, imho "Ort::RunOptions{nullptr}" is not an improvement over "NULL" in the C interface. In places it is common to leave an option empty, we could use default arguments to avoid the clutter.

I'm confused why I have to ask the session for input name with Ort::Session::GetInputName and then provide it back to the same session object when I call Ort::Session::Run... but maybe that's a general API thing, and not a C++ improvement (and perhaps my limited understanding of the ONNX architecture).
Speaking of names, with both input and output node names, I am not sure why those wouldn't be set as part of Session setup, and not be arguments to the Run method. Unless I'm confused (well I am) I think unless you modify the session, you would want to use the same names every time you call Run?

**Comment by KevinHake** [comment]
along the same lines as for input and output node names, for input_node_dims I'm not clear why if the Session (in a roundabout way) knows what they are, why it is an input to Ort::Session::Run

**Comment by KevinHake** [comment]
For Ort::Session::Run, for me it's a common (i.e. the only) case that both my input and output node counts are 1. It would be cool if the APIs were overloaded so in this simplified case I didn't have to provide arrays (or vectors) of length 1 as input or receive my output as an array (or vector) of length 1.

**Comment by jgbradley1** [comment]
Agree with @KevinHake . My suggestion then would be to leave the current interface alone for backwards compatibility and add new overloaded functions (starting with Ort::Session::Run).

A few implementation choices include
1. Allow Run() to accept std::vector<string> as input for some arguments.
2. Run() could also be generalized further with templates to allow for any container by passing in begin/end iterators. This would make the arguments list to Run() more verbose initially but simpler (less verbose) overloaded versions of the function could be written afterwards (for example, removing the need to pass in buffersize).

I would also propose that these changes (if accepted) be placed under an experimental namespace (Ort::session::experimental) to give the community time to test and refine them.

**Comment by Craigacp** [comment]
You could want different outputs from a given model based on the inputs, which is why it's controllable to choose what outputs are returned. I agree in practice it's not that likely to be useful, but it could be. For the input names there are situations where it would be useful to only compute part of a graph, by providing some of the inputs and requesting some of the outputs, but at the moment the runtime doesn't support providing a subset of the inputs, see https://github.com/microsoft/onnxruntime/issues/3128.

**Comment by KevinHake** [comment]
@Craigacp thanks for the info! So sounds like definitely it's viable to have an overloaded Run that takes in only an input tensor, the rest of the boilerplate goes away for that common case.

I'm also curious - isn't it also a common case that the session knows ahead of time the dimensions the input tensor should be? I'm thinking it could be useful if Run supported a simple vector input, and internally it could create a proper tensor object if needed, instead of constructing one manually with Ort::Value::Tensor before calling Run.

And in the partial input case, if I'm understanding correctly, we could add a method to the session object to create a properly dimensioned tensor given the input name, instead of using the input name to get dimensions, creating a tensor with those, then calling Run with the name and tensor. Or again, just have a regular vector input along with input name to ascertain dimensions (I prefer this to needing to call Ort::Value::CreateTensor). Personally, my philosophy is never to implement a public interface for functionality that doesn't exist yet, so probably that should be part of #3128/#2878.

**Comment by Craigacp** [comment]
A lot of onnx models have an unbound first dimension in their input tensor so they accept arbitrary size batches, so the reshape logic would be a little more complex as it would have to check the input is a multiple of the bound dimensions. At that point it's probably better to have the user make the tensor themselves rather than have more magic.

**Comment by jgbradley1** [comment]
@KevinHake one red flag I believe we should keep in mind is overloaded functions that don't match the API in other languages. For example, I like how OpenCV has designed their API so that the Python and C++ implementation are nearly the same. It becomes second nature then to port code over from other languages (i.e. moving code from research to production).

I'm beginning to think that parts of the current C+++ API might be too low-level for the general intended purpose (to run inference on onnx models). This proposal for overloaded functions could lead to a new _enhanced_ C++ API (which would come at a small memory cost due to decisions like using strings), that simplifies away most of the mundane argument passing that doesn't make sense.

For a majority of computer vision models, only one input and one output is desired and most of the arguments passed to `Run()` become unnecessarily tedious to state. Perhaps defining default arguments that automatically assume all input nodes will be used and all output nodes will be used makes the most sense. A lot of other frameworks make this assumption implicitly already.

**Comment by KevinHake** [comment]
@jgbradley1 agreed. Some of my comments above might better be addressed in the architecture as a whole (i.e. all the apis), not just C++, like being able to ask the session for a tensor based on input name instead of asking for dimensions, or allowing a regular array to be input to Run and having the API just use the session info to do its thing. I suppose you're right, those structural changes that could be done in all the APIs don't really belong in a PR that's more about taking advantage of C++-specific features.

So primarily I would say adding a default arg for null arguments and allowing vector inputs for buffers would be a good clear PR.

Improvements more general to all languages we can open separate issues/PRs for

**Comment by CJCombrink** [comment]
Although I support this, I think there is a missed opportunity here.

From my perspective, I would much rather prefer an C++ API that resembles the Windows ML API more closely. 
When I started looking at ONNX Runtime, I started with the Windows ML C++/WinRT API due to its availability in my project.
Now I am porting my existing code to the C++ API (evaluation for cross platform future), but was disappointed with the C-ness of the API, and the vastly different approaches. 

The Windows ML API is very modern C++ OO oriented, and I think this ONNX Runtime C++ API can benefit a lot from being common. Naturally without the C++/WinRT aspects, but only pure C++, and I think there is a good mapping from the C++/WinRT API to pure C++.

**Comment by patrikhuber** [comment]
I would say this is far from resolved. I just looked at some options of running onnx models in C++, had a look at the onnxruntime "C++" API (I put that in quotes deliberately), and I'll be staying away from it if I can. Modern C++ APIs can be simple, beautiful and easy to use, and there's really no reason anymore in 2023 that it has to be so hard and ugly. It's possible to write a modern C++ API in such a way that it's not more difficult to use than it would be in Python.

To be honest, I don't find the Windows ML C++/WinRT API much better and I'd apply the same comment to it - but then again it looks like I might be spoiled by true modern C++ APIs. I hope someone comes up with an ONNX runtime at some point in the future using true modern C++ that makes ONNX models as easy to use in C++ as it is in Python.

**Comment by RyanUnderhill** [comment]
@patrikhuber It's good to hear your feedback on this, I have been experimenting with a new simpler C++ API, here's a PR of it so far:

https://github.com/microsoft/onnxruntime/pull/13725

It describes the goals in it, but if you have any feedback please let me know.
