### ISSUE TITLE
x86 onnxruntime_perf_text.exe fails to load vgg16 with bad allocation

### ISSUE THREAD

**Issue by martinb35** [microsoft/onnxruntime#4136]
looks like vgg makes the process run out of memory on x86. 

**To Reproduce**
onnx model is from the model zoo here: https://github.com/onnx/models/blob/master/vision/classification/vgg/model/vgg16-7.onnx 

run onnxruntime_perf_test.exe with this model and it fails. 

PS B:\tmp\bin> .\onnxruntime_perf_test.exe -m duration -I -t 5 -e cpu C:\users\brianma\Downloads\vgg16-7.onnx .\results.log
2020-06-04 15:31:44.5250099 [E:onnxruntime:, inference_session.cc:925 onnxruntime::InferenceSession::Initialize] Exception during initialization: bad allocation
Exception during initialization: bad allocation

**Expected behavior**
This used to work on previous onnxruntime versions.

**Comment by snnn** [comment]
Right, the file is about 548 MB, and protobuf need 2x to 3x memory to load a file, so you'll need about 1.5GB memory in a 32 bits process. Due to memory fragment/address space reserved by hardware,  it's hard to get it. But, please don't put blame on protobuf. ONNX had a bad design at the beginning, protobuf isn't designed for large messages.  ONNX should only use protobuf to keep the metadata(without tensor weights) or divide the whole data into smaller pieces(like 2MB for each).  Protobuf is a message format, not a file format. ONNX should have another layer on top of it.

**Comment by WenyuZhu** [comment]
@snnn Hi, I'm facing the same issue here. I'm loading an exported ONNX file to my x86 UWP app using 'onnxruntime.inferencesession()', it's has a size of 537MB. How may I possibly solve this issue?

**Comment by snnn** [comment]
Probably this could help: https://github.com/onnx/onnx/blob/ea8e57a71e01d1e70b188465c028eb3c6c6cc118/docs/ExternalData.md
