### ISSUE TITLE
Locking seems to be taking the share of the time

### ISSUE THREAD

**Issue by migueldeicaza** [microsoft/onnxruntime#4251]
**Describe the bug**

I was trying to profile my code on a Mac, and found that too much of the time is lost into thread synchronization.   This is on a 16 CPU machine

**System information**
- macOS Catalina
- Source, compiled with ./build.sh --cmake_generator Ninja --enable_pybind --enable_training
- ONNX Runtime version: git checkout on June 15th, e0334f177cb3cc5dc7aeabe8a5ef4773cd9ea902
- Python version: 3.7.6
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.3 (clang-1103.0.32.62)
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**

Run the:
```
./build/Linux/Debug/onnxruntime_training_mnist --model_name mnist_gemm
```

This is the heaviest stack trace as identified by Instruments:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/36863/84811709-3fb8dd80-afdb-11ea-9e72-81ebae1bcac3.png">

About 45% of the time is spent here, zooming into a single thread, the heaviest stack trace is the thread synchronization:

<img width="1848" alt="image" src="https://user-images.githubusercontent.com/36863/84811626-257eff80-afdb-11ea-8963-9cfbfd4c9492.png">

**Comment by mrry** [comment]
I think this is a known issue with the Eigen threadpool implementation used in ORT: it wastes a lot of cycles attempting to steal work items from other threads when there's no work to do.

@tlh20 has PR #4236 in flight, with several improvements to the threadpool implementation. One of its aims is to waste less time in synchronization, so I'd expect it to have a noticeable improvement for small models like the one in this experiment.

One caveat though: Tim's optimizations have been primarily focused on improving end-to-end inference latency and bringing it to parity with an OpenMP-based implementation. Part of that involves more aggressive spinning instead of blocking on the per-thread condvar, so it won't always reduce user-mode time.

**Comment by snnn** [comment]
@mrry Would it be better if user disable the spinning in the threadpool?

**Comment by migueldeicaza** [comment]
If there is too much contention in the work stealing something is probably wrong somewhere else, as the main benefit is precisely to remove the centralized locking.

Joe Duffy covered some details about the .net implementation here: http://joeduffyblog.com/2008/08/11/building-a-custom-thread-pool-series-part-2-a-work-stealing-queue/

**Comment by mrry** [comment]
(Caveat: Tim knows this area much better than me, and he's been deep in the implementation recently, so his opinion should carry more weight.)

If I'm reading the profiler stack trace correctly, it's showing time spent in one of the atomic loads here, on a victim per-thread queue, rather than a centralized lock:

https://github.com/microsoft/onnxruntime/blob/12367a6b11e96e70112026cb7975f7035c7ad0ed/include/onnxruntime/core/platform/EigenNonBlockingThreadPool.h#L400-L404

To Changming's point, it probably make sense to disable spinning in the threadpool if ORT is sharing the core with other runnable processes. The original Eigen threadpool implementation was not optimized for shared settings, so it spins instead of blocking on a condition variable. The spinning duration is arbitrary, as this comment from the original authors admits:

https://github.com/microsoft/onnxruntime/blob/edd5855fb7b7ed9e66c48d6fb2816ea7b4b8e068/include/onnxruntime/core/platform/EigenNonBlockingThreadPool.h#L688-L692

To disable spinning, you'd have to create a `SessionOptions` object, set `intra_op_param.allow_spinning` to false, and pass the `SessionOptions` to the `TrainingRunner` constructor. However, I'd expect this to increase the end-to-end walltime for training, due to the extra syscalls. Depending on the size of the operations in that training graph, it might make sense to set the intra-op pool size to 1 (i.e. disable intra-op parallelism altogether).

**Comment by tlh20** [comment]
It would be good to re-run the profiling once we've merged https://github.com/microsoft/onnxruntime/pull/4236.  That changes much of the synchronization around work distribution, and if we still see issues here we should dig into them further.

Right now, there are two reasons why profiles show a lot of time in the work queue functions:

- Threads are very quick to block, and this interacts poorly when a workload runs a series of short-duration parallel loops.  If the sequential sections are only a few microseconds long, then this is sufficient for most of the worker threads to decide to block.  By the time the threads are woken again, the short loop is already complete.  That leaves the profile showing a lot of work in the threadpool, and not so much productive work in the operators.

- Threads block/unblock using a LIFO stack hanging off an EventCount object https://github.com/microsoft/onnxruntime/blob/edd5855fb7b7ed9e66c48d6fb2816ea7b4b8e068/include/onnxruntime/core/platform/EigenNonBlockingThreadPool.h#L194.  This stack is great for keeping a small number of threads active when the entire pool is not needed (if a workload only creates work for 2 threads, then it's the same 2 blocking and unblocking all the time).  However, it interacts poorly with the way we distribute work to a random thread in some code paths -- we distribute the work, then unblock a thread, and then the thread has to go and hunt across the pool.

The PR makes the synchronization patterns more like those in OpenMP runtime systems, with work being pushed to a specific thread, and that thread woken (if needed).  Work stealing is still used to re-balance work.  That is important when multiple concurrent operators push work into the thread pool, or if a worker thread is pre-empted.

The question of whether or not to spin is interesting.  With OpenMP, I have seen implementations where OMP_WAIT_POLICY=ACTIVE will cause all of the worker threads to always spin waiting for work.  We avoid doing that in ORT, both today and with the PR, and have threads spin for a configurable duration prior to blocking on a condition variable.  The aim is for that duration to be long enough to keep threads active over any short gaps between parallel sections, while yielding the CPU when there is less work available.  The CPU load can show as higher with spinning because it enables more threads to contribute to running the parallel sections, as opposed to the actual CPU consumption by the spinning itself.

[There are some older papers with mathematical analysis of how long this duration should be by framing it as a competition between a fixed algorithm in the scheduler and an "adversary" trying to be cunning in distributing work at the worse possible moment for the algorithm to be effective -- let me know if you're interested in reading more.]

**Comment by tlh20** [comment]
> The original Eigen threadpool implementation was not optimized for shared settings, so it spins instead of blocking on a condition variable

BTW, if I'm reading the code here correctly, the configuration is unusual.  It controls only the behavior of a single thread, as opposed to a spin-then-wait policy across the pool.  Effectively the last thread to block decides, instead, to spin for a short duration.  It makes the pool more responsive to new work when going from completely-idle to 1-task.
