### ISSUE TITLE
TVM HOME?

### ISSUE THREAD

**Issue by mei-ye** [microsoft/onnxruntime#4264]
**Is your feature request related to a problem? Please describe.**

**System information**
- ONNX Runtime version (you are using):

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
It looks like Microsoft maintains own TVM gtihub and it is quite out of date.  Is there a plan to keep the source in-sync or have a separated TVM build?

**Comment by KeDengMS** [comment]
May I understand more about the requirements of TVM? The current TVM repo is forked for building Nuphar execution provider. Since Nuphar EP is not being actively worked on, there's no plan to upgrade at the moment.

That said, Nuphar and onnxruntime-tvm are both open source and we welcome external contributions to it.
