### ISSUE TITLE
Includes of onnxruntime_c_api.h don't have path starting with onnxruntime

### ISSUE THREAD

**Issue by monamimani** [microsoft/onnxruntime#4359]
**Describe the bug**
In my project I use a fully qualified path to include the header for example it looks like this #include "onnxruntime/core/session/onnxruntime_cxx_api.h" I prevent allowing this #include "onnxruntime_cxx_api.h" because for commonly named files like environment.h or status.h you don't know which one you'll get. At the moment the providers (onnxruntime/core/providers) but lots of the public headers just include the file without qualifying it from the "root", onnxruntime.

This can cause issues with compilation when the wrong file is found first by the compiler or makes it hard to find the right file to include using smart ide that suggests paths because the include search path is just bloated.

**Comment by pranavsharma** [comment]
Is this affecting your usage of onnxruntime? Are you using onnxruntime as a DLL or statically linking to it? If you're using it as a DLL, all you need is onnxruntime_c_api.h.

**Comment by matt-deboer** [comment]
I just ran into this when attempting to use the shared library (from linux) in a c++ program; as @monamimani mentioned, adding 
`#include <onnxruntime/core/session/onnxruntime_cxx_api.h>` 
works initially, but when I have to bring in other includes (for example, using CUDA inference provider) 
`#include <onnxruntime/core/providers/cuda/cuda_provider_factory.h>`
the includes fail since there are includes within that file (chain) like `#include <onnxruntime_cxx_api.h>` which cannot be resolved.

**Comment by govindamagrawal** [comment]
Hi @pranavsharma , @monamimani  @matt-deboer I am trying to run the code using cuda, https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp.
I am new to c++ and facing problems while compiling and running the code. Can you write the commands to compile and run the onnx model?

**Comment by monamimani** [comment]
> Is this affecting your usage of onnxruntime? Are you using onnxruntime as a DLL or statically linking to it? If you're using it as a DLL, all you need is onnxruntime_c_api.h.

The issue is more that it is a pain to add all those include search path instead of just the include folder. 

The solution would be to have all the #include relative to that include folder.
