### ISSUE TITLE
[Advice] GPU memory transfer optimizations

### ISSUE THREAD

**Issue by katrasnikj** [microsoft/onnxruntime#4390]
I have a question about optimization of data transfers to and from the GPU. I have 4 sessions with different models running simultaneously on the GPU. I call the Run method on those sessions from 4 different threads. Is there a way to batch the input data going to those sessions in order to reduce the GPU memory transfer overhead?

Are there any other device to host memory transfer optimizations that might be worth trying? When I profile my application 74 % of the CPU Time is spent in the `cuMemcpyDtoH_v2` function. I'd like to reduce this time as much as possible.

I'm using the CUDA execution provider with the Nvidia GeForce RTX 2080 Ti Graphics Card.

**Comment by skottmckay** [comment]
Each session is a standalone entity so there's not much you can do inter-session.

On a per-session level you should be able to use the new IOBinding feature to provide the inputs on GPU and potentially keep the outputs on GPU post-execution. Keeping the outputs on GPU requires you to know the size of each output in order to pre-allocate a buffer on GPU with the correct size/shape. 

We're working on making this simpler as currently pytorch is required to do the allocation on GPU. That change should be available in the next couple of weeks and will remove the pytorch dependency. We will also be adding a mechanism to keep an output on GPU even if you don't know the size prior to model execution. 

https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/python/onnxruntime_test_python_iobinding.py has some example IOBinding usage, but possibly isn't clear enough about allocating memory on GPU. 

Here is a minimal example of how you'd currently allocate an output on GPU and bind that to the output 'output_name' from graph execution. When ORT executes the model it will write the output directly to this buffer with no copy to CPU. Similar approach for inputs. 

In this example the model takes an input X with shape {1, 2} and produces an two outputs, Y (shape {1, 1}) and Z. For the sake of the example we provide the input on CPU, and ask for the Y output to be written to a pre-allocated buffer on GPU, and the Z output to be returned on CPU. Note that if you're using IOBinding you must bind all inputs and outputs. 

```
import numpy as np
import torch
import onnxruntime as ort

sess = ort.InferenceSession("model.onnx")
io_binding = sess.io_binding()

# create input 'X' with shape [1,2]. bind the input to the cpu object. ORT will handle any copy to GPU if needed
x = np.array([1., 2.], np.float32).reshape(1, 2)
io_binding.bind_cpu_input("X", x)
# the bind_cpu_input call is roughly equivalent to 
# io_binding.bind_input("X", 'cpu', 0, np.float32, list([1, 2]), x.__array_interface__['data'][0])

# create buffer for output 'Y' on cuda. 
d = torch.device("cuda", 0)
torch_tensor = torch.zeros([1, 1], device=d, dtype=torch.float32)
io_binding.bind_output("Y", torch_tensor.device.type, torch_tensor.device.index, np.float32, [1,1], torch_tensor.data_ptr())

# receive output Z on CPU (no preallocated buffer)
io_binding.bind_output("Z")

sess.run_with_iobinding(io_binding)
```

Output from `help(io_binding)`

> class IOBinding(builtins.object)
 |  IOBinding(session)
 |  
 |  This class provides API to bind input/output to a specified device, e.g. GPU.
 |  
 |  Methods defined here:
 |  
 |  __init__(self, session)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  bind_cpu_input(self, name, arr_on_cpu)
 |      bind an input to array on CPU
 |      :param name: input name
 |      :param arr_on_cpu: input values as a python array on CPU
 |  
 |  bind_input(self, name, device_type, device_id, element_type, shape, buffer_ptr)
 |      :param name: input name
 |      :param device_type: e.g. CPU, CUDA
 |      :param device_id: device id, e.g. 0
 |      :param element_type: input element type
 |      :param shape: input shape
 |      :param buffer_ptr: memory pointer to input data
 |  
 |  bind_output(self, name, device_type='cpu', device_id=0, element_type=None, shape=None, buffer_ptr=None)
 |      :param name: output name
 |      :param device_type: e.g. CPU, CUDA, CPU by default
 |      :param device_id: device id, e.g. 0
 |      :param element_type: output element type
 |      :param shape: output shape
 |      :param buffer_ptr: memory pointer to output data
 |  
 |  clear_binding_inputs(self)
 |  
 |  clear_binding_outputs(self)
 |  
 |  get_outputs(self)
 |      Obtain outputs.

As the IOBinding feature is fairly new you may need to build ORT yourself or use a nightly package with GPU support.
`pip install -U -i https://test.pypi.org/simple/ ort-nightly_gpu`

**Comment by matt-deboer** [comment]
Could you provide an example of how to accomplish this w/ the C or C++ api?

**Comment by skottmckay** [comment]
> Could you provide an example of how to accomplish this w/ the C or C++ api?

We're currently adding IOBinding support to the C, C++ and C# APIs so that should be available in the next few weeks.

**Comment by ShaohongBai** [comment]
> I have a question about optimization of data transfers to and from the GPU. I have 4 sessions with different models running simultaneously on the GPU. I call the Run method on those sessions from 4 different threads. Is there a way to batch the input data going to those sessions in order to reduce the GPU memory transfer overhead?
> 
> Are there any other device to host memory transfer optimizations that might be worth trying? When I profile my application 74 % of the CPU Time is spent in the `cuMemcpyDtoH_v2` function. I'd like to reduce this time as much as possible.
> 
> I'm using the CUDA execution provider with the Nvidia GeForce RTX 2080 Ti Graphics Card.

Maybe relevant, do you try to have a cluster GPU of 4 nodes, each of them have separate CPUs, to do the same, whether it will balance memory overhead? Not sure whether it will be fast or slower.

**Comment by AnthonyMeehan** [comment]
How would this work for autoregressive models? 
I.e. the model outputs some value, and a state that is slightly bigger than the input state.  You want to feed the state back in without leaving the GPU, but you want to bring the value back to the CPU for processing.
