### ISSUE TITLE
ONNXRuntime C++ Documentation

### ISSUE THREAD

**Issue by TratsiakY** [microsoft/onnxruntime#4491]
Could anybody add documentation for onnxruntime for C++? I believe that this will make use of the onnxruntime in C++ more user friendly.

Existing examples must be simplified!

**Comment by pranavsharma** [comment]
We've [some samples](https://github.com/microsoft/onnxruntime/tree/master/samples#CC). What's missing?

**Comment by jgbradley1** [comment]
@TratsiakY Agreed. As an outside contributor, I created the [same issue](https://github.com/microsoft/onnxruntime/issues/3879) a while back. After some head-banging, I ended up adding a couple [C++ examples](https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx/model-explorer) myself to the repo that I thought were much easier to follow than the other examples.

In the master branch, I've updated several aspects of the C++ API since the last release (including the addition of a new Experimental API that allows for more modern C++ code) that should make life easier (see the model-explorer example). You will need to download and build from source in order to take advantage of the latest additions.

There is still a lot of room for improvement on the C++ documentation front. My best suggestion is review the python documentation [here](https://microsoft.github.io/onnxruntime/python/api_summary.html) to understand the nomenclature of the API and then read the header file directly. Most of the public-facing API calls are not documented at this point however the function names resemble the python docs close enough that it's reasonable to refer to the python docs for guidance.

**Comment by TratsiakY** [comment]
> We've [some samples](https://github.com/microsoft/onnxruntime/tree/master/samples#CC). What's missing?

First of all I should to note that examples are not documentation. Seems, that onnxruntime proposes powerful possibilities, but the absence of the clear documentation that describe classes, their parameters,  structures for input and output data, makes it not user friendly. If developers want to build the strong community around the project, the excellent and clear documentation should be written at first.

Absence of the documentation results to spend a lot of time (time is money, as you know) on reading source code and examples decomposition. Especially for humans like me, who haven't strong skills in cpp, but who is going to transfer their models from python to c++. Thus, comprehensive  and clear documentation is a way to strong community and satisfied users. I hope on understanding.


@jgbradley1 thank you for reply

**Comment by xmba15** [comment]
I have created some examples here
 https://github.com/xmba15/onnx_runtime_cpp
Would it be fine if I contribute with mask-rcnn model?

**Comment by XiaoXiao-Woo** [comment]
> I have created some examples here
> https://github.com/xmba15/onnx_runtime_cpp
> Would it be fine if I contribute with mask-rcnn model and try with a PR?

Thanks your contribution ! that's great! It's been bothering me for a long time about Type uint64_t on MaskRCNN outputs
