### ISSUE TITLE
How can I get a reference to an already running environment on the same thread?

### ISSUE THREAD

**Issue by brnd42** [microsoft/onnxruntime#4492]
I am writing a plugin that uses ONNX Runtime for neural network inference. This plugin is a dynamic library on MacOs or Windows and it can be opened on the same thread with other plugins using ONNX Runtime. To run our inference I need to create an environment when the plugin is opened. If two plugins are opened the second one will throw an exception, since there can only be one environment on one thread at a time.
What is the best way to solve this? Do I need shared memory between the plugins to hold a pointer to an environment or should I call another dynamic library that holds the environment? Is there maybe some ONNX Runtime API call to get a pointer to existing environments on a thread?

I do not have any control over the threading by the plugin host and I cannot exchange information over the host.

I am using the c++ api

**Comment by pranavsharma** [comment]
CreateEnv will always return the same environment instance on every invocation since only one env can be created in a process. This way you can get hold of an existing env ptr. The creation of the env is guarded by a mutex as seen [here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/session/ort_env.cc#L39), so calling it from multiple threads should be thread-safe.

**Comment by mayeut** [comment]
If I'm not mistaken, CreateEnv will return an error on the second call because of this [line](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/common/logging/logging.cc#L105) which will be called whether an environment already exists or doesn't. This exception is thrown when creating a logging manager from [here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/session/ort_env.cc#L42-L56) which is not in the block checking that an environment already exists.

Moving the creation of the logging manager seems like a bad idea (since the user could decide to pass different options and not know they've been ignored the second time around).

If you have a layout like the one described in the issue (I guess) with both plug-in A & B depending on onnxruntime:
PlugInA.dll
PluginB.dll
onnxruntime.dll

Then, managing to get only one environment created for the whole process is a bit challenging.
Of course, one could decide to build a static version of the library (if at all possible) but would lead in unnecessary growth of the binaries.
One easy option I'm seeing is to create an intermediate onnxruntime_env.dll that creates the environment upon loading & destroys it when unloading and acts as a kind of proxy with an accessor to get this singleton environment. It doesn't fit all scenarios though since all plug-ins in this case would need to use this onnxruntime_env.dll rather than depending only on onnxruntime.dll & create their own environment thinking they're the only ones using onnxruntime. This proxy could use the static library of onnxruntime and reexpose the same API in order to prevent this latter scenario.

IMHO, the "correct" way to fix this issue would be not to rely on a single global environment in onnxruntime but rather only rely on the ones provided by the user (& there can be multiple ones). I think this would a topic for another discussion if being considered.

**Comment by pranavsharma** [comment]
> If I'm not mistaken, CreateEnv will return an error on the second call because of this [line](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/common/logging/logging.cc#L105) which will be called whether an environment already exists or doesn't. This exception is thrown when creating a logging manager from [here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/session/ort_env.cc#L42-L56) which is not in the block checking that an environment already exists.

We'll fix this. Also fyi the env returned is refcounted, so calling CreateEnv again will simply increase the refcount and return the same instance.

> Moving the creation of the logging manager seems like a bad idea (since the user could decide to pass different options and not know they've been ignored the second time around).
> IMHO, the "correct" way to fix this issue would be not to rely on a single global environment in onnxruntime but rather only rely on the ones provided by the user (& there can be multiple ones). I think this would a topic for another discussion if being considered.

Fair points. Marking this as an enhancement for now; we'll consider it.

**Comment by brnd42** [comment]
Thank you very much for the insight. We are using the C API CreateEnv for now and then construct a smart pointer on an Ort::Env from the returned OrtEnv from CreateEnv. The logger exception is only thrown when using the Ort::Env default constructor.
