### ISSUE TITLE
Worse performance of onnxruntime v-1.4.0 compared to v-1.2.0 on armv8 (aarch64) device

### ISSUE THREAD

**Issue by omasaht** [microsoft/onnxruntime#4621]
**Describe the bug**
I have a simple multiscale semantic segmentation model that has worse inference compute time on version-1.4.0 than on version-1.2.0. Inference time is ~48ms on version-1.2.0 and ~92ms on version-1.4.0, I didn't do any testing on version-1.3.0 due to my project time constraints. I am currently running inference on Python. I built both libraries using same flags with no ACL or any custom providers natively on my ARM device:

`./build.sh --config MinSizeRel --enable_pybind --build_wheel --skip_tests`

**Urgency**
None.

**System information**
- Device: Odroid N2
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.4.0 and 1.2.0
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: Not applicable
- GPU model and memory: Mali-G52 GPU, 4GB DDR4

**Example Code**
```python
import time
import cv2
import numpy as np
import onnxruntime

ort_session = onnxruntime.InferenceSession('mymodel.onnx')

img = cv2.imread("img.jpg")

img = cv2.resize(img,(320,240))

img_gs = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
img_gs = img_gs/255
img_gs = img_gs.astype(np.float32)

img_gs = img_gs[np.newaxis,np.newaxis,:,:]

iters = 100
for i in range(0,iters):
    t = time.time()
    ort_inputs = {ort_session.get_inputs()[0].name: img_gs}
    ort_outs = ort_session.run(None,ort_inputs)[0].squeeze()
    print(time.time() - t)
```

**To Reproduce**
- By running the example code provided on both versions on ARMv8 device, issue can be reproduced
- ONNX model file is attached

**Expected behavior**
Inference timing should be same or better in latest release (v.1.4.0) compared to earlier release (v.1.2.0)

[mymodel.zip](https://github.com/microsoft/onnxruntime/files/4976387/mymodel.zip)

**Additional context**
I also tested prebuilt binaries (pip install onnxruntime)  of both versions on my Ubuntu Computer (x86_x64), and there was no difference in inference time. I believe the problem is associated with ARM device and building from source.

**Comment by tracysh** [comment]
Hello, @omasaht, 

I'm able to repro the same type of behavior on a Surface X, which also has a mix of big/little cores like your device. 

This appears to be a regression from the updated thread pool used in the 1.4.0 release. The new thread pool implements an "active" mode thread wait policy similar to OMP_WAIT_POLICY=ACTIVE. We need to investigate why that spinning is having such a negative impact on this architecture.

In the mean time, if you build with --use_openmp, then I was seeing the model time return to normal. This is assuming that OMP_WAIT_POLICY=PASSIVE by default on your platform. Alternatively, I was seeing better performance with intra_op_num_threads set to the number of big cores.

**Comment by omasaht** [comment]
Here is my follow up upon @tracysh advice,

My system has A73 (4-big cores) + A53 (2-small cores)

**Version 1.4.0** 

intra_op_num_threads=4 
Latency: 47ms
CPU Usage: 100% 4 big cores,
	
intra_op_num_threads=0 
Latency: 92ms 
CPU Usage: 100% 2 small cores, ~40-50% 1 big core, <10% remaining big cores


**Version 1.2.0*** 

intra_op_num_threads=4 
Latency: 50ms 
CPU Usage: 70-80% 4 big cores, ~50-60% 1 small core

intra_op_num_threads=0 
Latency: 48ms 
CPU Usage: 100% 4 big cores

So by using intra_op_num_threads=4 in 1.4.0, I was able to reach somewhat better performance compared to 1.2.0 with similar CPU Usage. It seems that intra_op_num_threads behavior is different in both releases.

Then I built version 1.4.0 with --use_openmp flag and my findings were:-

**Version 1.4.0**

intra_op_num_threads=0/4
Latency: 52ms 
CPU Usage: 70-90% 4 big cores and 2 small cores (all cores used)

So --use_openmp didn't help in my case.

**Comment by tlh20** [comment]
Hi @omasaht, I think I can see what is happening here.  I don't have the exact same system as you, but was able to reproduce the behavior on another big.little system running Windows 10 and WSL with Ubuntu 18.04.

I am getting good results on all of the "passive like" configurations.  This includes 1.2.0 with the default build, and 1.4.0 with --use_openmp and OMP_WAIT_POLICY=PASSIVE.  I also got good results with 1.4.0 and the default thread pool with allow_spinning set to false (https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/platform/EigenNonBlockingThreadPool.h#L403).  I am getting the degraded results with all of the "active like" configurations.  This includes 1.4.0 with the default build, and 1.4.0 with --use_openmp and OMP_WAIT_POLICY=ACTIVE.

In the passive builds, I am seeing the overall CPU load remain around 50%.  Although the ORT default is to create one thread per core (#big+#little), the CPU scheduler is effective in keeping those threads on the big cores given the low load.

In the active builds, I am seeing a much higher CPU load (as in the measurements you added above), and the threads are getting split over the big cores and the little cores.  At least in my case, this is causing some load imbalance which the CPU scheduler cannot resolve because, to it, all of the threads look busy in the active workloads.  In addition, I think I am seeing the main thread getting migrated by the OS to run on a little core.

I will investigate if we can make better use of the little cores, but for the moment Tracy's suggestion of setting intra_op_num_threads to #big sounds like the best approach.
