### ISSUE TITLE
Nuget package including 253mb libonnxruntime.dylib file on OSX64

### ISSUE THREAD

**Issue by ispysoftware** [microsoft/onnxruntime#4662]
**Describe the bug**
Referencing the 1.4.0 package from a netcore 3.1 app and deploying for OSX results in a 253mb version of the dylib file in the output directory instead of the 10MB version. It's deploying the correct version for windows/ linux.

253mb version is in:
.nuget\packages\microsoft.ml.onnxruntime\1.4.0\runtimes\osx-x64\native\libonnxruntime.dylib.dSYM\Contents\Resources\DWARF

10mb version is in
.nuget\packages\microsoft.ml.onnxruntime\1.4.0\runtimes\osx-x64\native\

**Urgency**
Can't deploy our application so ASAP.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Building on windows targeting OSX
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Install the Microsoft.ML.OnnxRuntime package from nuget v1.4.0 in visual studio, target OSX with msbuild and deploy

**Expected behavior**
Should result in a 10mb libonnxruntime.dylib file in the output directory, not the 253mb version.

**Comment by pranavsharma** [comment]
The 253mb version is the binary with symbols which are useful for debugging. The other one is stripped of all symbols. See [this](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/copy_strip_binary.sh#L27-L29).

**Comment by ispysoftware** [comment]
well it's including the debug library in the release build then

**Comment by skottmckay** [comment]
Given both the full and the stripped library are available in the nuget package, it sounds like the issue is that the build is picking the libonnxruntime.dylib you don't expect. Not sure that we control what is chosen though.

**Comment by ispysoftware** [comment]
why is the 253mb version included in the package?

it's not included in the other OS directories

linux-x64/native  just has the (small) libonnxruntime.so file in it
win-x64/native and win-x86/native have the dll and a pdb (the pdb is stripped on release build)

should remove the 253mb version from the nuget package if it can't be ignored in release build - nobody wants to distribute a 253mb object file with their projects.

**Comment by skottmckay** [comment]
Out of interest what forces you to distribute the 253MB version? If you link against the the 10MB version does something require the 253MB version to be present?

**Comment by ispysoftware** [comment]
How do you link against the 10mb version? All I'm doing is referencing the nuget package in visual studio. When I publish the app targeting release for OSX the 253mb debug version gets copied to the output directory automatically which shouldn't be happening. I've added a post-build step to delete it and replace it with the 10mb version.

**Comment by skottmckay** [comment]
I don't know if there's a good way to tell VS which dylib to prefer. Looks like it automatically generates a reference to both in the <project>.deps.json file even though one is inside a dSYM bundle.

It may be that a better setup would be to have a nuget symbol package for the symbols instead of including both in the main nuget package. Looks like the nuget package for all platforms could benefit from this as the Windows x64 package has 147MB in the pdb. We can look into that, but it probably won't be the highest priority. 

Symbol package info: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

CI build file that creates the OS X nuget package is triggered from here: https://github.com/microsoft/onnxruntime/blob/e70e9e2f6751e3ce14e7aeca1e21af46e5ad6350/tools/ci_build/github/azure-pipelines/nuget/templates/cpu.yml#L128-L148

**Comment by ispysoftware** [comment]
I think cutting out over half a gigabyte of download per nuget package download is worthy of high priority

**Comment by snnn** [comment]
I believe it has been solved in my PR #6480.

**Comment by snnn** [comment]
And I think snupkg is for Windows PDB files only. It doesn't support Linux or Mac binaries
