### ISSUE TITLE
Document what are the defaults

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#4770]
**Describe the bug**
Reading [this](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Graph_Optimizations.md#graph-optimization-levels) document I am not still sure what is the default value of `GraphOptimizationLevel`.
If I create `InferenceSession` without passing any `SessionOptions`, what will be the default?
If I create `SessionOptions` instance without passing anything for `GraphOptimizationLevel` what is the default?

**Urgency**
Need to understand this to debug perf issue

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): nuget
- ONNX Runtime version: 1.4
- Visual Studio version (if applicable): 2019

**Expected behavior**
Document to mention defaults clearly

**Additional context**
Why is `ORT_ENABLE_ALL` not the default, if it is not.

**Comment by hariharans29** [comment]
It does say - "All optimizations are enabled by default." which is `ORT_ENABLE_ALL`

**Comment by dashesy** [comment]
Thanks! I read that but it was not clear to me.

**Comment by hariharans29** [comment]
Not sure the time frame of these issues, I think there was a time when the default was just BASIC (I think!) and perhaps then users might have been instructed to run with ALL to exercise all optimizations (and get perf gains).

But it has been ALL for some time now and if anything, it is the other way around - when users encounter a graph related exception or when users notice a diff in expected results, they are first instructed to run with NO optimizations to first establish if the issue is because of any of the graph optimizations.

**Comment by askhade** [comment]
That is right... initially the default was set to BASIC and therefore the suggestion used to be to enable all to get perf gains.
