### ISSUE TITLE
Different inference results between 1.4.0 and 1.0.0

### ISSUE THREAD

**Issue by kevinch-nv** [microsoft/onnxruntime#5242]
**Describe the bug**
Upgrading ONNXRT-CPU 1.0.0 -> 1.4.0 gives different inferences results.

**Urgency**
n/a
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): pypi binary
- ONNX Runtime version: 1.0.0 / 1.4.0
- Python version: 3.5 
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
* Run attached script
* Will DM the model to you

**Expected behavior**
Same results for ONNXRT 1.4.0 and 1.0.0

**Screenshots**
n/a

**Additional context**
Attached python script:

```
import numpy as np
import onnxruntime as rt
sess = rt.InferenceSession("model.onnx")
arr1 = np.array([[1, 1, 0, 0]]).astype(np.int64)
arr2 = np.array([[1, 1, 1, 1]]).astype(np.int64)
arr3 = np.array([[1, 0, 0, 1]]).astype(np.int64)
input_dict = {
    sess.get_inputs()[0].name : arr1,
    sess.get_inputs()[1].name : arr2,
    sess.get_inputs()[2].name : arr3
}
pred_onx = sess.run(None, input_dict)
if rt.__version__ == "1.4.0":
    for i,x in enumerate(pred_onx):
        np.save("output_14_"+str(i), x)
# pip uninstall onnxruntime; pip install onnxruntime==1.0.0
else:
    for i,x in enumerate(pred_onx):
        arr = np.load("output_14_"+str(i)+".npy")
        result = np.isclose(arr, x, rtol=1e-4, atol=1e-4)
        if (np.all(result)):
            print ("Output " + str(i) + " matches!")
        else:
            print ("Output " + str(i) + " doesn't match!")

```

**Comment by jywu-msft** [comment]
This may be due to bug fixed by https://github.com/microsoft/onnxruntime/pull/4889
I reproduced issue on ORT 1.5 but with ORT master, the script passes. 

C:\Users\jywu\Downloads>pip install onnxruntime==1.0
Collecting onnxruntime==1.0
  Using cached https://files.pythonhosted.org/packages/45/c6/a018a83ab005244a36ac815e6e704c2fbc99a645106fec973e7d6fc48c93/onnxruntime-1.0.0-cp37-cp37m-win_amd64.whl
Installing collected packages: onnxruntime
Successfully installed onnxruntime-1.0.0

C:\Users\jywu\Downloads>python repro.py
Output 0 matches!
Output 1 matches!
Output 2 matches!
Output 3 matches!
Output 4 matches!
Output 5 matches!
Output 6 matches!
Output 7 matches!
Output 8 matches!
Output 9 matches!
Output 10 matches!
Output 11 matches!
Output 12 matches!

**Comment by kevinch-nv** [comment]
Thanks @jywu-msft. Verified that it's fixed with the latest nightly build.
