### ISSUE TITLE
Unable to load DLL 'onnxruntime'

### ISSUE THREAD

**Issue by devnet123** [microsoft/onnxruntime#5284]
**Description**
I'm trying to go through this tutorial [object-detection-onnx](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx) by using ML.NET and the NuGet packages:

Microsoft.ML 1.5.2,
Microsoft.ML.OnnxRuntime 1.4.0 ,
Microsoft.ML.OnnxRuntime.Managed 1.4.0.
Microsoft.ML.OnnxTransformer 1.5.0

but I always get the exception 

**System.TypeInitializationException: 'The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.'
 Unable to load DLL 'onnxruntime': The specified module could not be found. (Exception from HRESULT: 0x8007007E) at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetApiBase() at Microsoft.ML.OnnxRuntime.NativeMethods..cctor() '**

**Urgency**
I'm Stuck on reproducing the tutorial or better say using OnnxRuntime.

**System information**

- OS :  Windows 7- x64 (also tested on Windows 10 - x64)
- Visual Studio version (if applicable): 2019
- Framework :  C# and .NET Framework 4.7.2
 - Build target: x64

**Additional context**
To further investigate the problem, I created a sample Console Application to test OrtGetApiBase method in onnxruntime.dll,

```
[DllImport("onnxruntime", CharSet = CharSet.Ansi)]
public static extern ref OrtApiBase OrtGetApiBase();

static void Main(string[] args)
{
  OrtGetApiBase();
}

```
but the problem still remains and exception occurs at OrtGetApiBase. I checked the  bin/Debug directory and found  onnxruntime.dll, but I' wondering why the module cannot be found.

![image](https://user-images.githubusercontent.com/71753724/94159265-35d33000-fe90-11ea-8fb4-7bd663a145fe.png)

Any suggestion?

**Comment by yuslepukhin** [comment]
make sure that onnxruntime.dll and its dependents can be found. Place it alongside your executable. From a command line you can simply type: `where onnxruntime.dll` and see if it can be found.
I don't think you need anything else for CPU package.

**Comment by SGStino** [comment]
@snnn, we're seeing a similar issue here.

`dotnet publish -r win-x64`

ran the executable, and it worked

we then copied it over to a windows server 2016, run the same executable and it doesn't work.

It seems that on the local system, onnxruntime.dll is available also in C:\Windows\System32\, and not on the server where it's only available in the bin folder next to the exe.

Does the onnx runtime need to be installed on the system via installer by any chance?

**Comment by wangkaichuang** [comment]
I have the same problem now,do you know how to solve it?

**Comment by snnn** [comment]
onnxruntime.dll is available also in C:\Windows\System32, but please don't use it.  In you case you should use the one that fetched from nuget.org.  Otherwise you'll get the wrong version of onnx runtime. 

Then please read: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

In short:
1. Put onnxruntime.dll in the same dir of your main exe when possible 
2. Alternatively, in the cases that onnxruntime.dll is dynamically loaded by LoadLibrary function call(like dotnet/python/java applications), please make sure you always use  LOAD_WITH_ALTERED_SEARCH_PATH flag. For example, if you main.exe loads main.dll, then main.dll loads onnxruntime.dll. By default main.dll will try to locate onnxruntime.dll in C:\windows\system32 unless main.dll was loaded with "LOAD_WITH_ALTERED_SEARCH_PATH".  For example, [this](https://github.com/python/cpython/blob/3.6/Python/dynload_win.c#L219)  is how python handle it. This is a legacy solution, but it is the most commonly known one. 

Sorry I don't know much about dotnet.  Years ago all the DLLs were loaded with LOAD_WITH_ALTERED_SEARCH_PATH.  I don't know the current status.

**Comment by snnn** [comment]
@devnet123 Looks the samples was written by @luisquintanilla . You may ask him for help.  On the bottom of [the page](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-onnx), you can find a button of "Submit and view feedback for this page". Please click it and report the problem there.  If I knew .NET better I would love to help.
