### ISSUE TITLE
Is there a problem with the python onnxruntime-gpu installation package?

### ISSUE THREAD

**Issue by cuixing158** [microsoft/onnxruntime#5532]
When I use the python package installation instruction `pip install onnxruntime-gpu`, the package is imported successfully, but its attribute value is not recognized. See the figure below. Why?
![onnxruntime_insall](https://user-images.githubusercontent.com/22857777/96393706-8705e380-11f2-11eb-966a-e193807d95a2.jpg)
![onnxruntime-gpu](https://user-images.githubusercontent.com/22857777/96393707-8705e380-11f2-11eb-9831-e110676de826.jpg)

**Comment by tianleiwu** [comment]
It does not reproduce in my machine:
```
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
>>> onnxruntime.__version__
'1.5.1'
>>> onnxruntime.get_device()
'GPU'
```

I think the cause is the dependent DLLs cannot be found in PATH.

The solution for Windows is like following:
(1) Install latest VC 2019 Runtime from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
(2) Install corresponding versions of CUDA and cuDNN
     1.4.0 need CUDA 10.1.243, CUDNN 7.6.5.32
     1.5.* need CUDA 10.2  and cuDNN 8.0
(3) Add path to CUDA and CuDNN bin directories. 

For 1.5.*, the following dependent DLLs shall be in path after the above 3 steps:
```
cublas64_10.dll
cublasLt64_10.dll
cudart64_102.dll
cudnn64_8.dll
cufft64_10.dll
curand64_10.dll
msvcp140.dll
vcruntime140.dll
vcruntime140_1.dll
```

For 1.4, you can find the full list of DLLs in https://github.com/microsoft/onnxruntime/issues/4009

Note that, if you installed the onnxruntime package at the same time, you might keep only one package like:
```
 pip uninstall -y onnxruntime onnxruntime-gpu
 pip install onnxruntime-gpu
```

**Comment by cuixing158** [comment]
thanks very much!

**Comment by rose-jinyang** [comment]
Hi @cuixing158 
I have an issue when using onnxruntime-gpu in python on Windows.
I installed the latest version of onnxruntime-gpu but it does NOT work when forwarding.
Did u have the same issue?

**Comment by MaxReutter** [comment]
I didn't understand the first part, but
` pip uninstall -y onnxruntime onnxruntime-gpu
 pip install onnxruntime-gpu`
repaired the issue. I had installed onnxruntime and onnxruntime-gpu afterwards. After deleting onnxruntime, it stopped working for some weird typical linux reason. But thanks for the fix.
