### ISSUE TITLE
Unsupported Squeeze node

### ISSUE THREAD

**Issue by RaisingSun** [microsoft/onnxruntime#5539]
I used torch.onnx.export to convert a pytorch model to onnx. The conversion is successful, but could not be run by onnxtime. 

Traceback (most recent call last):
  File ".\test_example2.py", line 69, in <module>
    outputs = sess.run(None, inputs)
  File "C:\Users\kewtang\AppData\Local\Continuum\anaconda3\envs\nar_gpu_v2\lib\site-packages\onnxruntime\capi\session.py", line 123, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Squeeze node. Name:'Squeeze_1247' Status Message: D:\7\s\onnxruntime\core/providers/cpu/tensor/squeeze.h:47 onnxruntime::SqueezeBase::ComputeOutputShape input_shape[i] == 1 was false. Dimension of input 1 must be 1 instead of 2. shape={16,2}

Could anyone help me about this?

**Comment by hariharans29** [comment]
The model has a squeeze node that specifies an axis to be squeezed from an input shape out that is not 1. From the error message, it looks like the input shape is {16, 2} and axis = 1, the axis can't be squeezed out since it is not equal to 1.

https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Squeeze-11 - "If an axis is selected with shape entry not equal to one, an error is raised."

Can you please share the model ?

**Comment by RaisingSun** [comment]
> The model has a squeeze node that specifies an axis to be squeezed from an input shape out that is not 1. From the error message, it looks like the input shape is {16, 2} and axis = 1, the axis can't be squeezed out since it is not equal to 1.
> 
> https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Squeeze-11 - "If an axis is selected with shape entry not equal to one, an error is raised."
> 
> Can you please share the model ?

Sure. Sent to your gmail. Thanks.

**Comment by hariharans29** [comment]
I took a look at the model you sent me and I don't find the node: `squeeze_1247` in it. There are only 2 squeeze nodes and they are both named:

![image](https://user-images.githubusercontent.com/9969784/97216768-8c7ba480-1783-11eb-98df-f2b55ed45a7e.png)


Is the model you shared with me different from the original model that hit this ?

**Comment by ismailousa** [comment]
@RaisingSun Have you been able to resolve the issue? I am facing the exact same error with one of my models 

RUNTIME_EXCEPTION : Non-zero status code returned while running Squeeze node. Name:'Squeeze_1878' Status Message: /data/shared/packages/onnxruntime/onnxruntime/core/providers/cpu/tensor/squeeze.h:50 static std::vector<long int> onnxruntime::SqueezeBase::ComputeOutputShape(const onnxruntime::TensorShape&, const std::vector<long int>&) input_shape[i] == 1 was false. Dimension of input 1 must be 1 instead of 2. shape={6,2}
