### ISSUE TITLE
onnxruntime inference quantized-onnx model is very slow?

### ISSUE THREAD

**Issue by cuixing158** [microsoft/onnxruntime#5708]
**Performance bug**
Why do I refer to the given [example](https://github.com/microsoft/onnxruntime/tree/v1.5.1/onnxruntime/python/tools/quantization), the quantified resnet50 model is slower than the original model? There is still no inference speed improvement in version v1.5.1 so far?
Same similar problem：[ #1543](https://github.com/microsoft/onnxruntime/issues/1543)
[#3987](https://github.com/microsoft/onnxruntime/issues/3987)

**Urgency**
none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu18.04 and win10
- ONNX Runtime installed from (source or binary): pip install onnxruntime-gpu
- ONNX Runtime version: v1.5.1
- Python version: 3.7
- Visual Studio version (if applicable): 
- GCC/Compiler version (if compiling from source): ubuntu18.04 paltform is gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0 and win10 paltform is VS2019
- CUDA/cuDNN version: 10.2
- GPU model and memory:  ubuntu18.04 paltform is jetson nano and win 10 paltform is 4G-GTX1050ti

**To Reproduce**
I ran this [routine](https://github.com/microsoft/onnxruntime/blob/v1.5.1/onnxruntime/python/tools/quantization/E2E_example_model/e2e_user_example.py) and successfully quantified resnet50. I can also use onnxruntime for reasoning. The reasoning results are consistent with the original model, but the reasoning speed is reduced a lot. Why, the latest version does not seem to solve the problem?
paltform | origin-model | quantize-model |
-|-|-|
jetson | 135ms | 1000ms
win10 | 14ms | 50ms

**Expected behavior**
quantize-model is more fast than origin-model

**Screenshots**
none

**Comment by yufenglee** [comment]
ORT is working on supporting quantization on GPU, i.e., your quantization model is running on CPU instead of GPU. Note that even after GPU quantization is implemented, you still need GPU with arch >= Turing to get better performance. GTX1050i is definitely too old and won't get benefit.

BTW, as mentioned in the other thread, performance improvement with quantization needs hardware support, and is model dependent. On CPU with AVX2, AVX512 extension, you can get good performance improvement for a I/O bound model, but not compute bound model. You need CPU with VNNI (AVX512 VNNI or AVXVNNI) to get better performance for a compute bound model.

**Comment by jay-karan** [comment]
Hi @yufenglee, How do we differentiate I/O bound models and Compute models. Further more, I tried the similar thing on RTX 2080, quantized models were still performing slower compared to non-quantized models. How do I overcome this?
