### ISSUE TITLE
Moving from v1.5.1-cuda10.2-cudnn8 to v1.5.2-cuda10.2-cudnn8 downgrades Python and removes nvcc

### ISSUE THREAD

**Issue by RaphiePS** [microsoft/onnxruntime#6016]
**Describe the bug**
The image tagged `v1.5.1-cuda10.2-cudnn8` reports Python 3.7.0 and has NVCC in the PATH. However, upgrading to `v1.5.2-cuda10.2-cudnn8` downgrades Python to 3.6.9 and removes nvcc.

**Urgency**
This breaks my previously-building container, and might break others'. Not an enormous issue, but worth looking into.

**System information**
- Building Docker image on Amazon Linux
- Using `mcr.microsoft.com/azureml/onnxruntime` container registry

**To Reproduce**
```bash
# v1.5.1: Python 3.7.0
docker run -it mcr.microsoft.com/azureml/onnxruntime:v1.5.1-cuda10.2-cudnn8 python3 --version

# v1.5.2: Python 3.6.9
docker run -it mcr.microsoft.com/azureml/onnxruntime:v1.5.2-cuda10.2-cudnn8 python3 --version

# v1.5.1: Release 10.2
docker run -it mcr.microsoft.com/azureml/onnxruntime:v1.5.1-cuda10.2-cudnn8 nvcc --version

# v1.5.2: Executable file not found
docker run -it mcr.microsoft.com/azureml/onnxruntime:v1.5.2-cuda10.2-cudnn8 nvcc --version
```

**Expected behavior**
Python version and nvcc presence remain consistent through patch releases.

**Comment by snnn** [comment]
Sorry, I did it.

First, we plan to only maintain and have one of these two images. Because we don't have many people working on that.  Whenever we do a patch release of onnxruntime, we'll directly update the previous docker image instead of create a new one, or we'll just delete the previous image.

Second, we decide to keep our image small, to not include anything unnecessary. nvcc is not needed for running ONNX models, so I removed it. Also, nvcc is not a Microsoft product, it is a proprietary software owned by Nvidia. If a user need it, we suggest the user directly consult Nvidia. 

About the python: we used to have conda in our images, it makes license issues more complicated.  So I removed it. I replaced it with the python binary from Ubuntu official repo.  The license is covered by https://github.com/microsoft/containerregistry/blob/master/legal/Container-Images-Legal-Notice.md .

Please also note these images are made solely for Azure customers. https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/LICENSE-IMAGE.txt.  They must be used on Microsoft Azure Services only. However, you're free to get our source code and docker files to build them by your own, then you don't need to insert such license notices and you get can nvcc back by changing the line:
https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.cuda#L17
To
```
FROM nvidia/cuda:10.2-cudnn8-devel
```

**Comment by RaphiePS** [comment]
Hey @snnn, thanks for such a prompt and detailed reply.

All of your changes make a lot of sense - removing proprietary code is always a great move. Reading the docs, no version of Python is specified, nor is NVCC mentioned, so it was improper of me to rely upon them. I apologize if I came off as frustrated, and I appreciate your work here.

And finally, thanks for the heads up on the License Agreement! I'll rebuild from Open Source.
