### ISSUE TITLE
[ONNXRuntimeError] : 9 : NOT_IMPLEMENTED error on OneHot op

### ISSUE THREAD

**Issue by Nedae** [microsoft/onnxruntime#6116]
Hello,

 I have a detection model, with NonMaxSuppression node added to that, and then a OneHot node which gets its input indices from NMS. When visualizing the graph, the nodes seems to attach correctly! At runtime however, I get 

```onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node OneHot(11)```
I did some research and noticed that it is the opset version not being supported. But could not resolve the issue! 

Any help would be appreciated!

My onnxruntime version is 1.5.2, and onnx version is 1.7.0.
Without the OneHot op, and only with NMS added I do not get such an error, while the NMS op version is 11 as well!

**Comment by snnn** [comment]
We have onehot11. The current implementation is at: 
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/onehot.cc#L59

But we didn't implement it for all the possible input types, because there are too many.

So, I think you need to tell us the input types of the onehot op in your model.  And please feel free to modify the file I show you, to add the new types there.

**Comment by Nedae** [comment]
Got it, that is correct, the input shapes I provided were not supported, I changed those to `INT64` and it works. Thanks for the help!
