### ISSUE TITLE
Cuda availibility checker

### ISSUE THREAD

**Issue by EJShim** [microsoft/onnxruntime#6206]
**Is your feature request related to a problem? Please describe.**
Is there a way I can check cuda is available in current device?

**System information**
- ONNX Runtime version (you are using): 1.6.0

**Describe the solution you'd like**
Hope there is cuda availability checker like ```(torch::hasCUDA()``` in libtorch

**Comment by yuslepukhin** [comment]
Currently, there is not a way you can check the availability of CUDA on the machine using onnxruntime.
The current package structure (CPU vs GPU) requires you to know ahead of time your deployment target and then deploy your software. Although CPU package would work on all hardware, GPU package requires CUDA present otherwise the product would not launch due to cuda libraries absent.
There are other ways to find out but all of them require some additional investment on your part.
This feature is in our backlog.

**Comment by AlexKay28** [comment]
@yuslepukhin , has this feature been added already?

**Comment by yuslepukhin** [comment]
> @yuslepukhin , has this feature been added already?

I don't believe so.
