### ISSUE TITLE
Which correct version of CUDA and cuDNN?

### ISSUE THREAD

**Issue by disktnk** [Microsoft/onnxruntime#660]
**Describe the bug**
Document says "*Requires CUDA 9.1 and cuDNN 7.3*" when install binary via PyPI
https://github.com/Microsoft/onnxruntime#apis-and-official-builds

However, cuDNN 7.3.0 or 7.3.1 for CUDA 9.1 is not distributed on nvidia's archive site.
https://developer.nvidia.com/rdp/cudnn-archive (need to login)

I'd like to know proper version of CUDA and cuDNN, please.

**System information**
- OS Platform and Distribution: Ubuntu 16.04 / 18.04
- ONNX Runtime installed: Try via PyPI
- ONNX Runtime version: 0.2.1
- Python version: 3.5.6 / 3.6.8
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by raymondxyang** [comment]
docker image: nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04
com.nvidia.cuda.version: 9.1.85
I got my on my linux box from: https://developer.nvidia.com/cuda-91-download-archive?target_os=Linux

**Comment by disktnk** [comment]
Thank you for your polite reply.

Docker image `nvidia/cuda:9.1-cudnn7-devel-ubuntu16.04` seems to include cuDNN **7.1**, ref https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.1/devel/cudnn7/Dockerfile#L5

Could you tell me how to upgrade cuDNN version to 7.3/7.4, because cuDNN 7.3/7.4 **for CUDA9.1** looks not found on official nvidia site, as I wrote.

Regard,

**Comment by raymondxyang** [comment]
@disktnk actually its a very good point. 
Yes the docker image has cudnn 7.1, which we actually support. Previously list 7.3 is just one of our deploy environment, and putting it there seems to be not accurate. Ill update the README accordingly. 

Again thanks for pointing out this 😃

**Comment by disktnk** [comment]
I got it, thanks!

**Comment by codeling** [comment]
Seems the CUDA/CuDNN version information was removed from the README? Was it moved to some other documentation?
Otherwise, if it wouldn't be too much trouble, it would be really great to have the compatible versions of CUDA and CuDNN documented [with the release notes](https://github.com/microsoft/onnxruntime/releases)!

**Comment by faxu** [comment]
@codeling 
- The 1.8.0 release notes mention that CUDA 11.1 will be available in the NEXT release (1.9). 1.8.0 inferencing package uses 11.0.3 (side note: after evaluation, we've revised the v1.9 release plan to use 11.4 instead of 11.1)
- The 1.8.1 release notes are referring to the onnxruntime-training package, which uses different versions of CUDA as it needs to match PyTorch.
