### ISSUE TITLE
Optimal CPU Configuration

### ISSUE THREAD

**Issue by yaysummeriscoming** [microsoft/onnxruntime#6639]
**Describe the bug**
This is a configuration question. I couldn't find a general support forum, apologies if I'm posting this in the wrong place.

I'm serving a transformer model with the ONNXRuntime backend. I process long inputs by splitting into chunks and then passing sequentially through the model. For a single core machine, this is fine. But for multicore machines, I don't see much uplift in performance - 8 cores reduces runtime only 50%.

I've tried adjusting inter_op_num_threads and intra_op_num_threads to no avail.

I've tested batching the chunks together, however I don't see an uplift in performance (to be expected for CPU). Would I be better off creating multiple inference workers? Or are there any other knobs/levers I should be adjusting?

**Urgency**
Low

**System information**
- OS Platform and Distribution: Ubuntu 20.04
- ONNX Runtime installed from: binary
- ONNX Runtime version: 1.6.0 
- Python version: 3.8

**Comment by tianleiwu** [comment]
You might try our benchmark tools, and choose a pretrained model name and class that most close to your scenario:
```
pip install onnxruntime_tools==1.6.0
python -m onnxruntime_tools.transformers.benchmark --help
```

Example of bert base model:
```
python -m onnxruntime_tools.transformers.benchmark -m bert-base-cased --model_class AutoModel -e onnxruntime -p fp32 -o -i 3 -t 100 -b 1 -s 128 -n 1 2 4 8 16
```

In my machine, the output indicates that CPU cores help reduce BERT model latency:

{'engine': 'onnxruntime', 'version': '1.6.0', 'device': 'cpu', 'optimizer': True, 'precision': <Precision.FLOAT32: 'fp32'>, 'io_binding': True, 'model_name': 'bert-base-cased', 'inputs': 3, 'threads': 1, 'batch_size': 1, 'sequence_length': 128, 'datetime': '2021-02-12 04:29:48.103946', 'test_times': 100, 'latency_variance': '0.10', 'latency_90_percentile': '266.13', 'latency_95_percentile': '278.26', 'latency_99_percentile': '294.58', 'average_latency_ms': '256.46', 'QPS': '3.90'}

{'engine': 'onnxruntime', 'version': '1.6.0', 'device': 'cpu', 'optimizer': True, 'precision': <Precision.FLOAT32: 'fp32'>, 'io_binding': True, 'model_name': 'bert-base-cased', 'inputs': 3, 'threads': 2, 'batch_size': 1, 'sequence_length': 128, 'datetime': '2021-02-12 04:30:18.030037', 'test_times': 100, 'latency_variance': '0.11', 'latency_90_percentile': '148.54', 'latency_95_percentile': '160.92', 'latency_99_percentile': '212.09', 'average_latency_ms': '145.59', 'QPS': '6.87'}

{'engine': 'onnxruntime', 'version': '1.6.0', 'device': 'cpu', 'optimizer': True, 'precision': <Precision.FLOAT32: 'fp32'>, 'io_binding': True, 'model_name': 'bert-base-cased', 'inputs': 3, 'threads': 4, 'batch_size': 1, 'sequence_length': 128, 'datetime': '2021-02-12 04:30:36.609157', 'test_times': 100, 'latency_variance': '0.03', 'latency_90_percentile': '74.57', 'latency_95_percentile': '79.95', 'latency_99_percentile': '102.84', 'average_latency_ms': '75.20', 'QPS': '13.30'}

{'engine': 'onnxruntime', 'version': '1.6.0', 'device': 'cpu', 'optimizer': True, 'precision': <Precision.FLOAT32: 'fp32'>, 'io_binding': True, 'model_name': 'bert-base-cased', 'inputs': 3, 'threads': 8, 'batch_size': 1, 'sequence_length': 128, 'datetime': '2021-02-12 04:30:48.198231', 'test_times': 100, 'latency_variance': '0.06', 'latency_90_percentile': '48.53', 'latency_95_percentile': '55.64', 'latency_99_percentile': '81.33', 'average_latency_ms': '46.06', 'QPS': '21.71'}

{'engine': 'onnxruntime', 'version': '1.6.0', 'device': 'cpu', 'optimizer': True, 'precision': <Precision.FLOAT32: 'fp32'>, 'io_binding': True, 'model_name': 'bert-base-cased', 'inputs': 3, 'threads': 16, 'batch_size': 1, 'sequence_length': 128, 'datetime': '2021-02-12 04:30:56.924427', 'test_times': 100, 'latency_variance': '0.00', 'latency_90_percentile': '30.65', 'latency_95_percentile': '33.99', 'latency_99_percentile': '36.40', 'average_latency_ms': '28.97', 'QPS': '34.52'}

Of course, behavior for different model might be different. For GPT-2 model with past state, the bottle neck is IO (since past state tensor is large) instead of compute.

**Comment by yaysummeriscoming** [comment]
@tianleiwu thanks thats very helpful!

**Comment by yaysummeriscoming** [comment]
So I did some more testing, and it seems that starting multiple single thread ORT sessions is much faster than 1 session utilising all CPU cores:

```
import multiprocessing
import os
import sys
import time

iters = 1000
threads = os.cpu_count()
array = ['%s -m onnxruntime_tools.transformers.benchmark -m bert-base-uncased -e onnxruntime -p fp32 -o -i 3 -t %d -b 1 -s 128 -n 1' % (sys.executable, iters)] * threads

stt = time.time()
with multiprocessing.Pool(threads) as pool:
    pool.map(os.system, array)

total_examples = iters * threads
total_time = time.time() - stt
print('Processing %d examples took %0.2f seconds, or %0.2f examples/sec' % (total_examples, total_time, total_examples / total_time))
```

Gives:
Processing 16000 examples took 466.07 seconds, or 34.33 examples/sec

Whilst running:
`python -m onnxruntime_tools.transformers.benchmark -m bert-base-uncased -e onnxruntime -p fp32 -o -i 3 -t 16000 -b 1 -s 128`
Gives 26.05 examples/sec

Is it possible to configure this behaviour inside a single ORT session, or with ORT server?
