### ISSUE TITLE
1 : FAIL : Type Error: Type parameter (T) bound to different types (tensor(double) and tensor(float) in node (MatMul).

### ISSUE THREAD

**Issue by dalavayi** [microsoft/onnxruntime#6782]
I am trying to run an SGD_classifier with image inputs in form  of nd.arrays, i keep getting this error when trying to initialise the session.

**Comment by faxu** [comment]
Can you share your model and inputs?

**Comment by dalavayi** [comment]
@faxu  Thanks for responding, the trained onnx_model and the notebook to recreate the error along with the pickled inputs are attached.
[animal_classification.zip](https://github.com/microsoft/onnxruntime/files/6034171/animal_classification.zip)
Please let me know if you are able to access the files

**Comment by hariharans29** [comment]
The input X of the MatMul node is marked as float64, yet the second input to the MatMul node is an initializer of type float32. This makes the model invalid because the input types to the MatMul op need to be homogeneous per the ONNX spec.  Please report this issue to the project that helped you get the ONNX model.

![image](https://user-images.githubusercontent.com/9969784/108981935-1a886e80-7642-11eb-8b5a-b4abd99b4d51.png)
