### ISSUE TITLE
same structure with different parameters run at very different speeds

### ISSUE THREAD

**Issue by chenbohua3** [microsoft/onnxruntime#6865]
**Describe the bug**
  I have a ssd-vgg style PyTorch model and export it to ONNXs through `torch.onnx.export`. Two onnx models are exported and the difference between them are only the parameters. 
  
  One of the models, whose scales and variances of the BN layers are initialized to 1, and means and bias are initialized to 0, runs about **3ms** in my pc. And the other, whose parameters are resumed from a pre-trained model runs about **15ms** in my pc.
  
So I wonder why there is a large performance gap between these two models. I think this may caused by the parameters of bn layer, because if I change parameters of some BN layers of the pre-trained model to 1 and 0, the model becomes faster.
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.6.0 cpu
- Python version: 3.7.10
- CPU: Intel i5-6500 with AVX2 and **OMP_NUM_THREADS** is set to 1
- models: [models.zip](https://github.com/microsoft/onnxruntime/files/6068460/models.zip)

**To Reproduce**
```
def run_benchmark_onnx(model_file):
    elapsed = 0
    dummy_data = torch.randn(1, 3, 300, 300).cpu().numpy()
    ort_session = onnxruntime.InferenceSession(model_file)
    ort_inputs = {ort_session.get_inputs()[0].name: dummy_data}
    with torch.no_grad():
        for i in range(200):
            start = time.time()
            onnx_outs = ort_session.run(None, ort_inputs)
            end = time.time()
            elapsed = elapsed + (end-start)
    print('Elapsed time: %3.5f ms' % (elapsed/200.0*1000))
run_benchmark_onnx("slow.onnx")
run_benchmark_onnx("fast.onnx")
```

**Expected behavior**
These two models should  have the same speed performance.

**Comment by tracysh** [comment]
Hello, @chenbohua3, the problem is caused by the fused weights (fusing Conv+BN) getting too small: this results in the CPU doing denormal multiplies and the processor takes several clocks longer to complete math involving denormals. You can search the issues for "denormal" and find other instances of this.

The runtime does support enabling a "flush denormals to zero mode". After changing the above code to do the below, I then see the same time from fast.onnx/slow.onnx. This is the ORT version of calling torch.set_flush_denormal.

    ort_session_options = onnxruntime.SessionOptions()
    ort_session_options.add_session_config_entry("session.set_denormal_as_zero", "1")
    ort_session = onnxruntime.InferenceSession(model_file, ort_session_options)

The other option that has been used in the past is to edit the model's weights to clip anything below some threshold to zero. I don't have any pointers to scripts that do this though.

**Comment by chenbohua3** [comment]
@tracysh thanks so much. Directly apply your changes leads to about 4ms gain. And after clip small values to zero in pytorch, the fast.onnx and slow.onnx run at the same speed.
