### ISSUE TITLE
celu get wrong result when alpha is negtive

### ISSUE THREAD

**Issue by zjusaga** [microsoft/onnxruntime#6906]
**Describe the bug**
celu get wrong result when alpha is negtive

**System information**
- OS Platform and Distribution (Linux Ubuntu 16.04):
- ONNX Runtime installed from (binary):
- ONNX Runtime version: 1.5.2
- Python version:python: 3.7.5

**To Reproduce**
when alpha=-0.5, x = -0.49682534, celu got -0.49682534, but according to the formula， the result should be -0.850585938

**Comment by hariharans29** [comment]
Which EP are you using ?

**Comment by zjusaga** [comment]
sorry, what did you mean by "EP" ?

**Comment by fdwr** [comment]
EP = Execution Provider

For comparison:
CPU EP: -0.496825
DirectML EP: -0.850539
My calculator: Max(0,-0.49682534) + Min(0, -0.5*(Exp(-0.49682534 / -0.5)-1)) = -0.850538632

**Comment by hariharans29** [comment]
Hmm - looks like we don't have a CPU kernel fort Celu in the CPU EP. Celu is function based in the ONNX spec and so it is constructing a subgraph in its place and using that for compute in ORT. Quite possibly, the issue is in the composed subgraph. In any case, we should have a kernel for Celu in our default provider atleast.
