### ISSUE TITLE
Support basic array output types

### ISSUE THREAD

**Issue by dashesy** [Microsoft/onnxruntime#693]
**Is your feature request related to a problem? Please describe.**
Currently the output is `IDisposableReadOnlyCollection<DisposableNamedOnnxValue>` and `NamedOnnxValue` provides:

```C#
        public IEnumerable<T> AsEnumerable<T>();
        public Tensor<T> AsTensor<T>();
```

In order to get a `float[]` result I can do either:

```C#
            using (var results = _session.Run(inputs))
            {
                return results.First().AsTensor<float>().ToDenseTensor().Buffer.ToArray();
            }
```

or use more `Linq` like

```C#
            using (var results = _session.Run(inputs))
            {
                return results.First().AsEnumerable<float>().ToArray();
            }
```

The latter is faster! 

**System information**
- ONNX Runtime version (you are using): 0.3.0

**Describe the solution you'd like**

Provide 

```C#
        public T[] AsArray<T>();
```

To directly get the array, I know my network outputs a contiguous array.

**Describe alternatives you've considered**

Alternative [Tensor types](https://github.com/Microsoft/onnxruntime/issues/540) that may have easier way to get array.

**Additional context**
[This issue](https://github.com/Microsoft/onnxruntime/issues/673) is related.

**Comment by jignparm** [comment]
@dashesy -- Most models are Tensor models, hence the **AsTensor()** support. The **AsEnumerable()** is primarily to support models that produce sequences of maps().

The C# API is tied closely to the native C-API, which works with Tensors primarily, and in some cases sequences and maps. 

Supporting **AsArray()** would not fully capture the metadata (e.g. shape of Tensor) that is often needed by users, and therefore be confusing.

It should be easy to get an array from a Tensor(). Please re-open this if this is a blocker for some reason. Otherwise the preference is to keep the API() simple, and reflect the C API as much as possible.

**Comment by solarflarefx** [comment]
@dashesy What approach did you ultimately use for your conversion to Array?  Using the latest version of the ONNX Runtime C# API it seems that of your two options, I only have your first option.  Since I do inferencing on a set of data in a for loop, the conversion using results.First().AsTensor<float>().ToDenseTensor().Buffer.ToArray(); is taking quite a bit of time.

**Comment by dashesy** [comment]
If using an older C# version 

```C#
                return results.ToDictionary(
                    val => val.Name, 
                    val => new TensorArray<float>(val.AsEnumerable<float>().ToArray(), val.AsTensor<float>().Dimensions.ToArray())
                );
```

If it is CoreApp, I'd keep it as `ReadOnlySpan<float>` and do not convert to List. It can be used just like a list of floats, but is more efficient.
