### ISSUE TITLE
customer op with cuda provider compute is error

### ISSUE THREAD

**Issue by KnightYao** [microsoft/onnxruntime#6952]
I have defined some customer op, and some op just run on cpu,In my customer op i use default stream for cuda kernel,
In onnxruntime-1.5.1, it work well, I can get  correct result, but when i run with onnxruntime-1.7.0, the result was error.
But when I set 'export CUDA_LAUNCH_BLOCKING=1' ， it will get correct result. so i want to know in onnxruntime-1.7.0 what should I do for customer op, and it will get correct result.
@hariharans29

**System information**
- OS Platform and Distribution (e.g., Linux Center OS):
- ONNX Runtime installed from (source):
- ONNX Runtime version: 1.7.0
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda-10.1 cudnn-7.6.5
- GPU model and memory:

**Comment by hariharans29** [comment]
Can you share a minimal reproable cuda cusotm op implementation that worked with 1.5.0 and not with 1.7.0? 

Are you using cuBlas/cuDNN in your custom op ?

Did you try this with 1.6 ? If so, what was the outcome?

**Comment by hariharans29** [comment]
With this PR ((https://github.com/microsoft/onnxruntime/pull/3723), ORT’s hand-crafted CUDA kernels, CuDNN, and CuBlas ALL use the same compute stream – either uses the compute stream provided by a user via SessionOptions on a per-session basis or if the user doesn’t provide a compute stream, ORT creates a stream and uses that and this stream doesn’t synchronize with the default legacy stream – hence custom ops launched in the default legacy stream will have to be:

1)	Manually synchronized (OR)
2)	We need to expose something for custom op users to get access to the ORT created default compute stream (OR)
3)	Custom op users can pass in a created compute stream for ORT to use (via session options) and use the same compute stream for their custom ops

Since we don't have (2) right now, please try creating your own compute stream and pass it via session options for ORT to use and use that compute stream to launch your custom op CUDA kernels. This should ensure that ORT's kernels and your custom kernels are synchronized.

**Comment by KnightYao** [comment]
Thanks！！！

**Comment by KnightYao** [comment]
@hariharans29 Thanks!

**Comment by hariharans29** [comment]
Closing this for now as it answers your question.

We have backlog items to expose ORT's CUDA compute stream (this way users are not forced to pass a stream at session creation) and we will get to it when we can.
