### ISSUE TITLE
Feature Request: enable cmake install target

### ISSUE THREAD

**Issue by boxerab** [microsoft/onnxruntime#7041]
I am using ONNX runtime in another c++ project. Currently each build has to configure the ONNX runtime library location,
as there is not C++ install target for ONNX. If there was one, I could use cmake to find the ONNX package, and it would greatly
simplify the build process.

**Comment by snnn** [comment]
I'm afraid we can't use ONNX from somewhere else.  Because,

1. One onnxruntime version is only compatible with one ONNX commit, and usually the ONNX commit is not a release version.
2. ONNX has many build options. For example, you can even customize its namespace. We can't support them all. 
3. If you build ONNX as a shared library, I'm sure it will cause problems. But if you have built it as static library, how would you keep the build flags consistent across ONNX and ONNX Runtime? I think there is no easy way. Also what's the benefit of building ONNX on your own?

**Comment by boxerab** [comment]
Thanks, @snnn 

> 1. One onnxruntime version is only compatible with one ONNX commit, and usually the ONNX commit is not a release version.
It is up to the user to decide which onnx runtime version they would like to use. But

> 2. ONNX has many build options. For example, you can even customize its namespace. We can't support them all.
> 3. If you build ONNX as a shared library, I'm sure it will cause problems. But if you have built it as static library, how would you keep the build flags consistent across ONNX and ONNX Runtime? I think there is no easy way. Also what's the benefit of building ONNX on your own?

**Comment by boxerab** [comment]
Thanks for your comments, @snnn 

> 1. One onnxruntime version is only compatible with one ONNX commit, and usually the ONNX commit is not a release version.
> 2. ONNX has many build options. For example, you can even customize its namespace. We can't support them all.
> 3. If you build ONNX as a shared library, I'm sure it will cause problems. But if you have built it as static library, how would you keep the build flags consistent across ONNX and ONNX Runtime? I think there is no easy way. 

This is how most libraries work: they have periodic releases, these releases can be built and installed in a standard location, and other libraries can link either statically or dynamically to the artifacts.

> Also what's the benefit of building ONNX on your own?

I am working on another C++ project that can use ONNX to run the models. There is no other way of linking to ONNX C++ API other than building on my own.

**Comment by snnn** [comment]
> other libraries can link either statically or dynamically to the artifacts.

No. For example, glibc and google protobuf are not. 

When you change a static library to dynamic, the change may extend some variables' visibility and lifetime. For example, ONNX is an open standard and open source library for machine learning interoperability built upon libprotobuf. ONNX was designed to be sharable and reusable among machine learning frameworks. And libprotobuf has a functionality which allows you create a message based on its name(we call reflection), so protobuf requires you have a centralized way to managed all the protobuf definitions (*.proto files) to avoid name conflicts. But commonly it's not a real conflict, it's just two pieces of code want to use the same protobuf definition. Like if you have two ML frameworks in python package form that both dynamically link to libprotobuf, then they must dynamically link to ONNX too, so that the protobuf messages defined in ONNX will only have one copy per process and will only be registered once to libprobuf's central database. Also none of the frameworks can extend or reuse the message definition in a different way. If a framework wants to define a protobuf message that contains an ONNX TensorProto message inside, it can not directly include ONNX's existing *.proto file.

**Comment by boxerab** [comment]
Yes, there are exceptions, but as I said, most libraries work this way. 
I am using ONNX right now in this fashion, except I have to manually configure my own project to search
the ONNX build in the source directory for the .so and headers. 
My request is simply to allow users to install .so and headers in standard location, for example `/usr/local`
on linux.

**Comment by boxerab** [comment]
funny, it turns out this already exists. Just use the `onnxruntime/cmake` directory as source directory, and configure a new
cmake variable `onnxruntime_CUDNN_HOME` and it just works.

**Comment by boxerab** [comment]
If I build from cmake directly, then I can install the headers to /usr/local/include, but the binaries are not installed.

**Comment by boxerab** [comment]
So, it looks like the only issue preventing a proper install is that the binary files are not installed in the standard `bin` directory in the cmake output directory.  Is there a reason why a non-standard location is used to put the binaries? The standard location is '$CMAKE_BINARY_DIR/bin', but '$CMAKE_BINARY_DIR' is used instead.

**Comment by boxerab** [comment]
closing this as there is a pending PR to implement this.
