### ISSUE TITLE
AsTensor is slower than AsEnumerable.ToArray

### ISSUE THREAD

**Issue by dashesy** [Microsoft/onnxruntime#706]
**Describe the bug**
To get the results I have tried these two:

```C#
using(var results = _session.Run(inputs))
{
    return results.First().AsEnumerable<float>().ToArray();
}
```

```C#
using(var results = _session.Run(inputs))
{
    return results.First().AsTensor<float>().ToDenseTensor();
}
```

I noticed that the latter is slower than the former, even though there seems to be a copy involved in both (?).

I first thought it is `ToDenseTensor` that has some copying overhead, but used 

```
using (var pin = (tensor as DenseTensor<float>).Buffer.Pin())
```

and still it was 60ms slower! which makes sense because `ToTensor` is already dense so `ToDenseTensor` according to documentation does not copy.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): nuget
- ONNX Runtime version: 0.3.0

**To Reproduce**
Install 0.3.0 and try consuming the results using `AsTensor` vs `AsEnumerable`

**Expected behavior**
Should be about the same runtime, unless Tensor object creation is heavy

**Additional context**
The final results size is 1000000 which is why copy matters at all

**Comment by pranavsharma** [comment]
@shahasad @jignparm can one of you take a look? thanks.

**Comment by dashesy** [comment]
According to a colleage who is an expert, this has something to do with C# ToArray optimized for ToArray because ICollection is implemented, whereas ToTensor is different.

**Comment by jignparm** [comment]
@dashesy - as for being 60ms slower, what percentage slower is it (i.e. what it the total running time)? Are you comparing Debug build or Release build? Most performance comparisons should be on release build, with optimizations enabled.

**Comment by dashesy** [comment]
It is 190ms vs 130ms, both release build. To try to see the difference make sure the tensor size is 1000,000 floats.

**Comment by jignparm** [comment]
In terms of fastest way to iterate over tensor data, below are the results for some basic trials. Between the 5 different options below, options **1 and 2**  had similar latency of ~**150ms**. Option **3** took **~5200 ms**  while option **4** was  **~6300ms**, and option **5** around  **~5600 ms**. 

Options **1 and 2** seem to be the best choices at this time. 

Not sure why options **3 and 4** differ in performance, if the returned object is already a DenseTensor and the extra cast should not result in a copy (from what you mentioned above), so we should expect these two options to have similar performance. 

Option **5**, using the pin() method + unsafe pointer operations after casting to DenseTensor was slightly better than option **4**, but worse than option **3**.  One explanation could be that the the cast to DenseTensor **does** involve some overhead, but then the pointer arithmetic is faster than iterating/indexing over Tensor objects, which would explain why this faster than **4**, but slower than **3**.

            unsafe
            {
              var res1 = resnov.ToArray()[0].AsTensor<float>().ToArray<float>();
              var res2 = resnov.ToArray()[0].AsEnumerable<float>().ToArray();
              var res3 = resnov.ToArray()[0].AsTensor<float>();
              var res4 = resnov.ToArray()[0].AsTensor<float>().ToDenseTensor();
              var res5 = (float*)resnov.ToArray()[0].AsTensor<float>().ToDenseTensor().Buffer.Pin().Pointer

              // start timer
              // res below is substituted with res1 through res5 above
              foreach (var r in res)  
              {
                  // do something simple
              }
              // stop timer
            }

In terms of performance enhancement, the **System.Numerics.Tensor** class is a fundamental type in the OnnxRuntime C# library, so it  cannot be removed easily. The fastest way to access  data seems to be via the AsArray() methods at this time.

Regarding the other related issue #713, not being able to access large tensor output (>2G), I was able to construct an model output tensor of 1 Billion floats (size=4G ), and access the values via options **1 and 2** above in about **2817 ms**. Option **5** + unsafe pointer operations, also worked successfully, but took  longer at around **52290 ms**.  It seems like the cast  to DenseTensor is taking cycles , but there was no exception processing a large output tensor.

For the exception for large output tensor, please attach/forward a minimal example to reproduce the crash, since it cannot be reproduced using the test mentioned above.

**Comment by jignparm** [comment]
Adding to the options list above, option **6** below only takes **67 ms**, which should be close the fastest possible. This avoids any data copies, and directly accesses the underlying pinned native memory, which you were initially trying to do. 

    var res6 = (resnov.ToArray()[0].AsTensor<float>() as DenseTensor<float>).Buffer.Span; 

The **ToDenseTensor()** method in the options below is creating a copy (is not a cast), which explains why it's slow. https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Tensors/src/System/Numerics/Tensors/Tensor.cs#L1179

Please reopen for other concerns.
