### ISSUE TITLE
Pytorch squeeze after pad function cause CPU Fallback warning at runtime.

### ISSUE THREAD

**Issue by II245** [microsoft/onnxruntime#7096]
**Describe the bug**
When I export a model from Pytorch (1.8.0) to onnx I get warnings at runtime. (Please, see below)
I only have troubles with fallback_cpu_capability warnings. Value error was somehow raised at runtime and not present in my main code. 

```
1.8.0
torch.Size([1, 10])
{'o': tensor([[0.0000, 0.7245, 0.8421, 0.7092, 0.6501, 0.6383, 0.4523, 0.5001, 0.9790,
         0.5590, 0.3269, 0.0000]], device='cuda:0')}
2021-03-22 15:08:07.537204469 [W:onnxruntime:Default, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: Gather_17
2021-03-22 15:08:07.537347425 [W:onnxruntime:Default, fallback_cpu_capability.h:140 GetCpuPreferedNodes] Force fallback to CPU execution for node: Equal_19
Traceback (most recent call last):
  File "fp32_squeeze_repro.py", line 33, in <module>
    print(runtime.run(None, dict(x=x.cpu().numpy())))
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 120, in run
    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
ValueError: Model requires 3 inputs. Input Feed contains 1
```

**Urgency**
none.

**System information**
 - OS Platform and Distribution: Linux Ubuntu 18.04: Linux x86_64
 - ONNX Runtime installed from (source or binary): binary
 - ONNX Runtime version: onnxruntime-1.6.0
 - Python version: Python 3.8.5
 - Pytorch version: 1.8.0
 - CUDA/cuDNN version: CUDA Version: 10.2
 - GPU model and memory: Tesla V100 (32G)

**To Reproduce**
```python
import onnxruntime
from torch import nn
import torch
import torch.nn.functional as F

print(torch.__version__)


class Model(nn.Module):
	def forward(self, x):
		p = F.pad(x, (1, 1), mode='constant').squeeze(1)
		return dict(o=p)


model = Model()
model.to(device='cuda')
x = torch.rand(1, 10).to(device='cuda')
print(x.shape)
print(model(x))

torch.onnx.export(
		model, (x,),
		'fp32_squeeze_repro.onnx',
		verbose=False,
		opset_version=12,
		export_params=None,
		do_constant_folding=True,
		input_names=['x'],
		output_names = ['o']
)

runtime = onnxruntime.InferenceSession('fp32_squeeze_repro.onnx')
print(runtime.run(None, dict(x=x.cpu().numpy())))
```

**Expected behavior**
Inference without warnings.

[fp32_squeeze_repro_onnx.zip](https://github.com/microsoft/onnxruntime/files/6185527/fp32_squeeze_repro_onnx.zip)

**Comment by hariharans29** [comment]
1) The "force fallback to cpu" is actually an optimization wherein ORT dynamically decides that performing certain operations on CPU is more optimal than incurring the overhead of scheduling CUDA kernels and waiting for the operation to finish. Usually they are tiny "shape" related subgraphs whose result is ultimately needed on CPU (because shapes don't hold very large number of elements requiring GPUs to process them) . In your case:

![image](https://user-images.githubusercontent.com/9969784/112949791-771df400-90ee-11eb-97cb-af8acc467ee2.png)

The Shape output feeds through a simple `Gather` and `Equal` which forms the `condition` to the downstream `If` node (and the condition needs to be on CPU even if the `If` node itself is placed on CUDA) and hence ORT made the decision that processing a few shape dim values (Gather + Equal) on CPU is better than launching 2 CUDA kernels + waiting for it to finish + getting it back to CPU to ultimately feed into the `If` node. 

This is an optimization which is just getting logged. 

2) The runtime error is simple - your onnx model requires 3 inputs and you are feeding it just 1. Hence, the complaint from ORT.

Hope this answers your questions.

**Comment by vadimkantorov** [comment]
@hariharans29 `export_params=None` is wrong, but the model does not contain any parameters in fact. Why would it require 3 inputs?

**Comment by hariharans29** [comment]
![image](https://user-images.githubusercontent.com/9969784/113292658-a75dc200-92a9-11eb-9fa6-9cfb94d41321.png)

**Comment by vadimkantorov** [comment]
very interesting, seems a PyTorch bug. I'll report it there

**Comment by roshan-gopalakrishnan** [comment]
I am also getting the same issue. Is there any solution ?
