### ISSUE TITLE
Issue pinning large memory in C# (crash)

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#713]
**Describe the bug**

```
Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.op_Explicit(IntPtr value)
   at Microsoft.ML.OnnxRuntime.NativeOnnxTensorMemory`1.Pin(Int32 elementIndex)
   at System.Memory`1.Pin()
```

In [this line](https://github.com/Microsoft/onnxruntime/blob/1288a8caed7f473d42a3b2cc6f9d2c31011d328d/csharp/src/Microsoft.ML.OnnxRuntime/NativeOnnxTensorMemory.cs#L200) the cast to (int) fails  if allocated on a high-address range (to see the issue use a large buffer to increase the chance).

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): nuget
- ONNX Runtime version: 0.3.0

**To Reproduce**
Pin the output tensor with large size (>2GB)

**Expected behavior**
No crash

**Additional context**
A colleague found the root cause in the process of trying to understand [this issue](https://github.com/Microsoft/onnxruntime/issues/706). 
We need to `pin` because there is no fast way to index the buffer of tensor to get one value out.

**Comment by jignparm** [comment]
The **Pin(Int32 elementIndex)** method is inherited from **MemoryManager<T>** class below, which is why it's only able to take an Int32 (most likely for x86 support).

BTW, do you have a workaround (besides the performance you mentioned)? It seems like you're trying to pin beyond 2G explicitly. If you use AsTensor() to retrieve the tensor object, are you able to process the data successfully?

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Buffers/MemoryManager.cs#L28

**Comment by dashesy** [comment]
See the crash when doing `.Pin()` on `results.First().AsTensor<float>().ToDenseTensor().Buffer`, so this is `AsTensor()` to retrieve the tensor object, then `ToDenseTensor` to be able to use `Buffer`.
There is no specific try to pin beyond 2G, it is just Pin

I want to get `tensor[index]` but Tensor object cannot be index so the need to `Pin` first

**Comment by jignparm** [comment]
Below are some different methods for retrieving output values (see similar response in issue #706).

            unsafe
            {
              var res1 = resnov.ToArray()[0].AsTensor<float>().ToArray<float>();
              var res2 = resnov.ToArray()[0].AsEnumerable<float>().ToArray();
              var res3 = resnov.ToArray()[0].AsTensor<float>();
              var res4 = resnov.ToArray()[0].AsTensor<float>().ToDenseTensor();
              var res5 = (float*)resnov.ToArray()[0].AsTensor<float>().ToDenseTensor().Buffer.Pin().Pointer

              // start timer
              // res below is substituted with res1 through res5 above
              foreach (var r in res)  
              {
                  // do something simple
              }
              // stop timer
            }

Regarding  not being able to access large tensor output (>2G), I was able to construct an model output tensor of 1 Billion floats (size=4G ), and access the values via options **1 and 2** above in about **2817 ms**. Option **5** + unsafe pointer operations, also worked successfully, but took  longer at around **52290 ms**.  It seems like the cast  to DenseTensor is taking cycles , but there was no exception processing a large output tensor.

For the exception for large output tensor, please attach/forward a minimal example to reproduce the crash, since it cannot be reproduced using the test mentioned above.

**Comment by jignparm** [comment]
Looks like limitation is on the number of number of elements (not the amount of RAM). This is coming from the Tensor implementation, which can only take **size** of type **int32** as a parameter.

https://github.com/dotnet/corefx/blob/master/src/System.Numerics.Tensors/src/System/Numerics/Tensors/Tensor.cs#L269

Created an issue for System.Numerics.Tensor here: https://github.com/dotnet/coreclr/issues/23754

We need to be able to handle more than 2G elements in C# API, since the native C++ API already supports large tensors.

**Comment by faxu** [comment]
https://github.com/dotnet/coreclr/issues/23132

**Comment by faxu** [comment]
dotnet/coreclr#23132

**Comment by faxu** [comment]
#dotnet/coreclr#23132

**Comment by faxu** [comment]
@fs-eire can you take a look at this and if it's related to other work you're doing here?

**Comment by fs-eire** [comment]
> @fs-eire can you take a look at this and if it's related to other work you're doing here?

This is not related to my recent work. As explained by @jignparm this is depending on core CLR array length limit.
