### ISSUE TITLE
Install onnxruntime==1.7.0 on CentOS 6

### ISSUE THREAD

**Issue by yaoyuannnn** [microsoft/onnxruntime#7130]
**Describe the bug**
When I try to install onnxruntime 1.7.0 on our CentOS server, I get this error:

```console
$ pip install onnxruntime==1.7.0
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.7.0
ERROR: No matching distribution found for onnxruntime==1.7.0
```
If I use `pip install onnxruntime`, onnxruntime 1.4.0 will be installed. 

I also tried installing from a .whl file, which gave the following error:

```console
$ pip install onnxruntime-1.7.0-cp36-cp36m-manylinux2014_x86_64.whl
ERROR: onnxruntime-1.7.0-cp36-cp36m-manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

We need a higher ORT version for newer opsets.

**System information**
- OS Platform and Distribution: CentOS 6.8
- ONNX Runtime version: 1.7.0
- Python version: 3.6.2
- Pip version: 21.0.1

**Comment by snnn** [comment]
Sorry, we stopped support CentOS6.

**Comment by yaoyuannnn** [comment]
What CentOS version does onnxruntime support?

**Comment by snnn** [comment]
7 and above.

**Comment by yufenglee** [comment]
I hit the exactly same issue on ubuntu 18.04. We stopped supporting CentOS6 since 1.7, but @yaoyuannnn can only see ORT 1.4.

**Comment by yufenglee** [comment]
I can install 1.7 successfully with conda environment.

**Comment by yaoyuannnn** [comment]
> I can install 1.7 successfully under conda environment with the same python version (3.6).

Thanks for reopening this! Did you install it on CentOS 6? What was the command you used?

**Comment by yufenglee** [comment]
I tried on ubuntu 18.04, not on CentOS 6. You can try installing conda and then pip install install onnxruntime in conda env.

**Comment by yaoyuannnn** [comment]
> I tried on ubuntu 18.04, not on CentOS 6. You can try installing conda and then pip install install onnxruntime in conda env.

I was actually using conda. I was only able to see ORT 1.4 as the newest version though.

**Comment by snnn** [comment]
You can find all the tech details at https://www.python.org/dev/peps/pep-0599/. 

For example, "The wheel may only contain binary executables and shared objects compiled for one of the following architectures supported by CentOS 7, or a CentOS 7 compatible base image ". It means, CentOS 7 is the minimum requirement.  Ubuntu 16 and 18 are supported too because their glibc versions are newer. 

onnxruntime python package conforms to manylinux2014, which requires pip >= 19.3. If you are using CentOS 7 rh-python38, CentOS 8 python38, Fedora 32+, Mageia 8+, Photon OS 4.0+ (3.0+ with updates) or Ubuntu 20.04+, then by default the pip program is new enough. Otherwise, please update it before installing onnxruntime.

**Comment by snnn** [comment]
I removed the release:1.7 tag because it is not a 1.7 release issue.
