### ISSUE TITLE
Memory leak of using dynamic shapes with Openvino

### ISSUE THREAD

**Issue by ledaiduongvnth** [microsoft/onnxruntime#7271]
**Describe the bug**
Run model Inference with Openvino supported causes memory leak. The issue occurs only with dynamic input shape, which is [2, 3](height, width) in my case.

**System information**
- OS Platform and Distribution: Ubuntu18.04
- ONNX Runtime installed from source with Openvino(2021.2.200) supported
- ONNX Runtime version: 1.7.1

**To Reproduce**
The following code works fine without Openvino
```
#include <opencv2/imgcodecs.hpp>
#include <chrono>
#include <string>
#include <vector>
#include <onnxruntime_cxx_api.h>
#include <opencv2/dnn.hpp>

int main(int argc, char* argv[]){
    std::string modelFilepath{"/mnt/hdd/PycharmProjects/Pytorch_Retinaface/FaceDetector.onnx"};
    Ort::Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING);
    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(1);
    OrtOpenVINOProviderOptions options;
    options.device_type = "CPU_FP32";
    options.num_of_threads = 1;
//    sessionOptions.AppendExecutionProvider_OpenVINO(options);
    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_DISABLE_ALL);
    Ort::Session session(env, modelFilepath.c_str(), sessionOptions);

    std::vector<const char*> inputNames{"input"};
    std::vector<const char*> outputNames{"output", "outputt", "outputtt"};
    Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);

    while  (true){
        // Create random number between 640 and 2500
        int range = 2500 - 640 + 1;
        int num = rand() % range + 640;
        
        std::vector<int64_t> inputDims {1, 3, num, num};
        cv::Mat img(num, num, CV_32FC3, cv::Scalar(113, 113, 113));
        cv::dnn::blobFromImage(img, img);
        Ort::Value inputTensors = Ort::Value::CreateTensor<float>(memoryInfo, (float*)img.data, num*num*3, inputDims.data(), 4);
        std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();
        // Run inference
        std::vector<Ort::Value> ort_outputs = session.Run(Ort::RunOptions{nullptr}, inputNames.data(), &inputTensors, 1, outputNames.data(), 3);
    }
}
```
The following code causes memory leak and warning while using with Openvino:

```
[WARN] 2021-04-07T07:23:07z ngraph/frontend/onnx_import/src/core/graph.cpp 98	Could not create an nGraph Constant for initializer '678'. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_68227 () -> (f32{})' with friendly_name 'Constant_68227':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).
```

```
#include <opencv2/imgcodecs.hpp>
#include <chrono>
#include <string>
#include <vector>
#include <onnxruntime_cxx_api.h>
#include <opencv2/dnn.hpp>

int main(int argc, char* argv[]){
    std::string modelFilepath{"/mnt/hdd/PycharmProjects/Pytorch_Retinaface/FaceDetector.onnx"};
    Ort::Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING);
    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(1);
    OrtOpenVINOProviderOptions options;
    options.device_type = "CPU_FP32";
    options.num_of_threads = 1;
    sessionOptions.AppendExecutionProvider_OpenVINO(options);
    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_DISABLE_ALL);
    Ort::Session session(env, modelFilepath.c_str(), sessionOptions);

    std::vector<const char*> inputNames{"input"};
    std::vector<const char*> outputNames{"output", "outputt", "outputtt"};
    Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);

    while  (true){
        // Create random number between 640 and 2500
        int range = 2500 - 640 + 1;
        int num = rand() % range + 640;

        std::vector<int64_t> inputDims {1, 3, num, num};
        cv::Mat img(num, num, CV_32FC3, cv::Scalar(113, 113, 113));
        cv::dnn::blobFromImage(img, img);
        Ort::Value inputTensors = Ort::Value::CreateTensor<float>(memoryInfo, (float*)img.data, num*num*3, inputDims.data(), 4);
        std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();
        // Run inference
        std::vector<Ort::Value> ort_outputs = session.Run(Ort::RunOptions{nullptr}, inputNames.data(), &inputTensors, 1, outputNames.data(), 3);
    }
}
```
Model: https://drive.google.com/file/d/1WShOvxZ7gTgZ64KSOcJ5bz9RsMaJL6Wj/view?usp=sharing

**Comment by jywu-msft** [comment]
@MaajidKhan can you take a look? thanks.

**Comment by MaajidKhan** [comment]
@ledaiduongvnth Hello. 
so, I was able to compile your cpp code with OpenVINO and I was able to successfully do the inferencing on CPU.

If my understanding is correct, you were also able to successfully do the inferencing using OpenVINO but you had 2 concerns.

**1. warning with openvino.**
This warning actually comes from ngraph component of the openvino which is actually used to parse the onnx model, create a readable network before sending it to OpenVINO backend. This warning can be ignored. we will work with the OpenVINO team to suppress or fix this warning in the future releases.

**2.Memory Leak**
I would actually request you more information on how would I reproduce this memory leak from my end.

can you give me information on.
-> How did you detect this memory leak
-> can you provide me additional screenshots, stack traces or pointers.
-> Do you use any third party software like valgrind to detect these memory leaks

Any other information and detailed steps, so that I reproduce the memory leak at my end.

**Comment by ledaiduongvnth** [comment]
@MaajidKhan from my end, it is very easy to reproduce the problem. 
On 16 GB of Ram Machine, the program consumes most of the memory just after about` ~ 30 seconds( ~ 100 times of inference)` and outputs the following log continuously.
```
[WARN] 2021-04-12T02:42:00z ngraph/frontend/onnx_import/src/core/graph.cpp 98	Could not create an nGraph Constant for initializer '678'. Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at ngraph/core/include/ngraph/op/constant.hpp:69:
While validating node 'v0::Constant Constant_87663 () -> (f32{})' with friendly_name 'Constant_87663':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).
```
 I also notice that huge memory consumption comes from model Inference(I am not hands-on memory leak debug technics, so sorry). Note that the same program works fine on the same machine without Openvino support.
 
![Screenshot from 2021-04-12 09-42-11](https://user-images.githubusercontent.com/28498007/114334694-538a8d00-9b75-11eb-823a-e885ea564f74.png)

**Comment by ledaiduongvnth** [comment]
@MaajidKhan could you reproduce the issue? please let me know!

**Comment by MaajidKhan** [comment]
Hi @ledaiduongvnth . I was able to reproduce this issue with your model and the code. I will try to debug further and get more details on this and post it here.

**Comment by MaajidKhan** [comment]
@ledaiduongvnth 

Just wanted to confirm that this isn't a memory leak with OpenVINO. Memory leak is when there is improper usage of dynamic memory that is been getting allocated in the heap or the excess and unused memory is not getting freed before the application is getting terminated.

I will now try to explain, what is happening, with this specific sample when you are trying to run with OpenVINO Execution Provider with the help of a small code snippet as below. Also note that this issue was only seen with dynamic models with OpenVINO.

**while  (true){
        // Create random number between 640 and 2500
        int range = 2500 - 640 + 1;
        int num = rand() % range + 640;
        std::vector<int64_t> inputDims {1, 3, num, num};
}**

so, what is happening is, for every iteration, you are trying to pass some random input shape to this dynamic model which doesn't happen in any practical scenario or there's no such use case.

usually, though we have a dynamic model, we restrict the data that's coming in to one particular input shape or say a combination of some different input dimensions depending on the use case.

But here, with every iteration, it's a different input dimension and every time a new blob is created w.r.t hardware and gets stored as cache and today OpenVINO-EP has no limit for the number of cache blobs that could be available. There can be any number of cache blobs be created.

so if you observe, as the inference is happening, with time, the cpu memory usage keeps going up as with every iteration a cache blob is getting added up w.r.t new input_shape for the model per iteration.

And this is the reason, why the CPU memory section is shooting up with time.

In future, we would like to limit the number of cache blobs that we would like to have at one point of time. But currently, we don't have this feature because practically such use case doesn't exist.

**Comment by MaajidKhan** [comment]
If you try something like this, the RAM memory won't shoot up just the cpu utilization will go up.
![image](https://user-images.githubusercontent.com/29036417/114707307-addb4780-9d47-11eb-9b9b-395c766342ec.png)

**Comment by ledaiduongvnth** [comment]
@MaajidKhan Thanks for your detailed explanation. Is there any way to walk around the issue? I really want to keep the input as the original size to improve accuracy.

**Comment by MaajidKhan** [comment]
@ledaiduongvnth currently, we don't have this feature to limit the number of cache blobs. so, I am not sure if there's any workaround for this.

so for your dynamic model, you can try pre-processing the input shape of the data to one fixed size and try to compare the accuracy tradeoff between it and when you try to run with different input shape every time.

If you still think, you aren't happy with the accuracy drop, I would suggest you to use default cpu provider for your task or use case.

**Comment by xiechunhong** [comment]
@MaajidKhan
Such use case does exist, for example:
1. dynamic batch size
2. dynamic image width (in my case, an OCR text recognition model, with fixed image height and dynamic image width, as texts have different length)

My workaround for these two use cases:
1. split data into fixed batch-sizes, like [1, 2, 4, 8, 16, 32, 64, 128]. For example, if the input data length is 200, it can be split into 128, 64, 8, so I can get the 200 results by three inferences, it is slower a little bit, but the RAM usage is predictable.
2. similar workaround for dynamic image width. Image height is fixed, with limited number of fixed widths (70, 140, 280, 560, 1120, 2240), for the tradeoff between speed and RAM usage.

ONNXRuntime + CUDA EP has no such issue, so I think it is a good improvement for OpenVINO to consider. With such improvement, we can have identical code for GPU(CUDA) and CPU(OpenVINO).

**Comment by mezotaken** [comment]
Same issue after exporting yolov5 to onnx with dynamic input only. Memory consumption grows infinitely with onnxruntime-openvino, and the use case is exactly the dynamic batch size for me.
