### ISSUE TITLE
Profiling shows that kernel time only takes a very little part of total run time 

### ISSUE THREAD

**Issue by lewisword** [microsoft/onnxruntime#7390]
**Describe the bug**
This is a performance issue. When I run the Conv operator with input size of (32 * 128 * 256 * 256), profiling shows that kernel time only takes a very little part of total run time. I wonder why this phenomenon happens，and what does the cpu do during the run time except kernel time.

**Urgency**
Urgent

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux Release 7.4
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.0
- Python version: 3.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): gcc5.4
- CUDA/cuDNN version: 10.1 cuDNN7.6
- GPU model and memory: Tesla T4 and V100

**To Reproduce**
I run the Conv operator on both Tesla T4 and V100, the profiling has little difference.
![微信截图_20210421093809](https://user-images.githubusercontent.com/31215614/115486155-a5739700-a288-11eb-9b21-8ee0f9473f70.png)

**Screenshots**
Profiling Overview：
![微信截图_20210420203855](https://user-images.githubusercontent.com/31215614/115486190-bc19ee00-a288-11eb-9ddd-b18eea80d8fa.png)

True Kernel time：
![微信截图_20210420203949](https://user-images.githubusercontent.com/31215614/115486195-bfad7500-a288-11eb-97e4-09422cb99cad.png)

**Comment by mrry** [comment]
When you run a model on GPU, this view can be confusing, because the "kernel_time" only covers launching the corresponding kernel asynchronously on the GPU. The kernel itself "completes" and does not wait for the code to actually execute on the GPU. 

However, I would guess that your code is fetching the result of the convolution back to the CPU as one of the `Run()` call arguments. To do this, the CPU must copy the result from GPU to CPU, and that copy cannot start until the producing code (i.e. the CUDA kernel for convolution) finishes on the GPU.

So the "empty" space in the profile under "model_run" is mostly spent waiting on the Conv computation and then the GPU-to-CPU copy to complete. If you visualize the execution with a profiler like [nvvp](https://developer.nvidia.com/nvidia-visual-profiler) you would see extra events corresponding to this work on the GPU's streams. (There is also work underway to integrate this information into the ONNX Runtime profiler view.)

**Comment by mrry** [comment]
I'm going to close this issue, since I think I've answered the question, but please feel free to reopen if it seems to be a different issue!

**Comment by hyt589** [comment]
Is this documented any where?

> When you run a model on GPU, this view can be confusing, because the "kernel_time" only covers launching the corresponding kernel asynchronously on the GPU. The kernel itself "completes" and does not wait for the code to actually execute on the GPU.
> 
> However, I would guess that your code is fetching the result of the convolution back to the CPU as one of the `Run()` call arguments. To do this, the CPU must copy the result from GPU to CPU, and that copy cannot start until the producing code (i.e. the CUDA kernel for convolution) finishes on the GPU.
> 
> So the "empty" space in the profile under "model_run" is mostly spent waiting on the Conv computation and then the GPU-to-CPU copy to complete. If you visualize the execution with a profiler like [nvvp](https://developer.nvidia.com/nvidia-visual-profiler) you would see extra events corresponding to this work on the GPU's streams. (There is also work underway to integrate this information into the ONNX Runtime profiler view.)
