### ISSUE TITLE
[C#] Feed session.Run a 2D Tensor

### ISSUE THREAD

**Issue by ADD-eNavarro** [microsoft/onnxruntime#7395]
In Windows Server 2019 Standard I am using a model I previously transform to onnx format to get the dvector of a voice from the mel spectrogram.
This spectrogram is a list of 160 float arrays of 40 elements, named "audio". I use the next code:

```
List<NamedOnnxValue> container = new List<NamedOnnxContainer>();
container.Add(NamedOnnxValue.CreateFromTensor<float[]>("input", audio.ToArray().ToTensor()));

using (var results = session.Run(container))
[...]
```
The container does contain what expected: a float[160][40]. My model takes as input (1,160,40) as checked in Netron.

But I get this error in the session.Run line:
_Microsoft.ML.OnnxRutime.OnnxRuntimeException: '[ErrorCode:RequirementNotRegistered] BUG Check'_

That tells me nothing, and I haven't been able to find related issues, or 2D Tensor examples online.
Any help?

**Comment by liqunfu** [comment]
I like to leave someone from C# API to answer. But for me it looks like float[] is not a supported data type.

**Comment by yuslepukhin** [comment]
`NamedOnnxContainer` is not familiar to me. However, you need to specify a shape to each Tensor you are feeding. [this](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L336) might be a good example.

FixedBufferOnnxValue is a great way to feed inputs. However, they must be disposed of, just like outputs.

Also, if you model is expecting a 3-D shape, you won't be able to feed a 2-D shape. However, since the leading dimension is 1, you can specify that 3-D shape to your Tensor.

With regards to your bug check. Do you have any other information in that regard such as line number?

**Comment by yuslepukhin** [comment]
Likely coming from https://github.com/microsoft/onnxruntime/blob/8d737f977056444a307f1b7f0bcd402fba62d790/csharp/src/Microsoft.ML.OnnxRuntime/OrtValue.cs#L148

You are not feeding a Tensor of registered type. While we still have work to do to make this API usable, I suggest you follow test code examples.

**Comment by ADD-eNavarro** [comment]
Thank you both, you are absolutelly right: the problem was that float[] is not a registered type. 
So, instead of creating a tensor from float[160][40], I created a tensor<float>(1,160,40) and then passed every element of the 2D array one by one, as in the examples. My bad for assuming at some point that feeding CreateFromTensor a 2D array would create a tensor of dimensions (1, 2Darray_dimension_1, 2D_array_dimension_2). 
By the way, that could be a great improvement in usability to that function, if it could turn an array of arrays into a tensor without having to loop copying every single element by hand.
