### ISSUE TITLE
"Can't reduce on dim with value of 0 if 'keepdims' is false" in Session::Run()

### ISSUE THREAD

**Issue by jf99** [microsoft/onnxruntime#7563]
**Describe the bug**
I have an onnx keypoint detection network, which is expected to estimate keypoints of fish in an image. Sometimes, it does not find any keypoints in an image. Sometimes when it doesn't find any keypoints, OnnxRuntime crashes during inference. More specifically, `Session::Run()` throws an exception and prints the following to the console (which is also the `what()` of the exception):
> [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running ReduceMax node. Name:'' Status Message: /root/build/igd-onnxruntime/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:503 void onnxruntime::CommonReduce(onnxruntime::OpKernelContext*, std::vector<long int>, int64_t, onnxruntime::ResultsNoTransposePrepareForReduce&, bool) [with T = float; AGG = onnxruntime::ReduceAggregatorMax<float, float>; int64_t = long int] keepdims_ was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{0,4}

**Urgency**
no hard deadlines

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04 LTS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.1 (I know there is 1.7.2, but there are no relevant changes in the changelog)
- Python version: -
- Visual Studio version (if applicable): -
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: I only use the CPU
- GPU model and memory: -
- I am using the C++ interface of OnnxRuntime as you might have guessed.

**To Reproduce**
This behavior can best be reproduced by throwing a random image at the net. [Here](https://owncloud.igd-r.fraunhofer.de/s/0G41v3opw5uxreh/download) is such an image in its raw form as it is given to the network (all preprocessing is already done). And here is the [onnx file](https://owncloud.igd-r.fraunhofer.de/s/33XsNKFGann8jV0/download).

**Expected behavior**
Inference completes and just returns no keypoints.

Ask for more information if you need any.

**Comment by ytaous** [comment]
Similar issue: https://github.com/microsoft/onnxruntime/issues/3687 and: https://github.com/microsoft/onnxruntime/issues/1670

@hariharans29 ,  @BowenBao - I can repro the same error with the steps:
1. clone from master 
2. ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --build_wheel --skip_tests
3. install the whl
4. run with sample code like so:
-------------------------------------------------
import numpy as np
import onnxruntime
import timeit

session = onnxruntime.InferenceSession('fish-keypoint-rcnn-resnet.onnx')
input_name = session.get_inputs()[0].name
image = np.random.rand(3, 544, 960).astype(np.float32)

def run():
    session.run([], {input_name: image})

# warmup
for i in range(10):
    run()

print(timeit.timeit(run, number=100))
---------------------------------------------------
Any idea?

**Comment by skottmckay** [comment]
I believe this matches numpy behavior though. The reduction fails if you attempt to reduce an axis with a value of 0 and keepdims of false. 

```
>>> a = np.ndarray(shape=(0,4))
>>> np.maximum.reduce(a, axis=0, keepdims=False).shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: zero-size array to reduction operation maximum which has no identity

>>> np.maximum.reduce(a, axis=1, keepdims=False).shape
(0,)

>>> np.maximum.reduce(a, keepdims=False).shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: zero-size array to reduction operation maximum which has no identity
```

e.g. if I had a shape of {3, 0, 4} and specified reduction on axis 1, the output shape would be {3, 4} (dropping the reduced axis instead of reducing it to 1), which would be invalid as there was no data to start with.

**Comment by ytaous** [comment]
@jf99 - close it for now - please check/adjust your model and see if you can work around it.
Thanks.

![image](https://user-images.githubusercontent.com/4484531/117187875-3ff7ce00-ad91-11eb-980b-66d9200af48e.png)

**Comment by jf99** [comment]
Thank you guys for your quick replies. Inference on this net worked with pytorch. So if you say the error is in the ONNX file, then something went wrong during the ONNX export.

**Comment by skottmckay** [comment]
The metadata for the ONNX model says pytorch version 1.3 was used. May be worth re-exporting the ONNX file with a newer version of pytorch.

**Comment by gyenesvi** [comment]
I am getting the same error on a model I got from a client, so cannot change it. However, I don't understand why this problem arises the way it does. First, why does the validity differ depending on the `keepdims` flag? If it can be computed with one setting, it can be reshaped to the other one, so that should not be a differentiating factor. Second, reducing on an array of 0 length should be well-defined if the operator has an identity value or the reduction is given an explicit initial value. The max of 0 elements can be defined as -inf, and numpy allows setting of the initial value. Numpy only fails if None is given to the initial value and the length is 0, and its behavior does not depend on the `keepdims` flag.

**Comment by skottmckay** [comment]
ORT behavior is not matching numpy currently as it's allowing a reduce on an axis with a value of 0 when keepdims=true. I don't know if that's intentional and there's a historical reason for that being the case, but the potential fix would be to also fail when keepdims=true.

e.g. input shape {3, x, 4} with axis=1 should reduce to {3, 1, 4} with keepdims=true or {3, 4} if keepdims=false. If x == 0 the current implementation will reduce to {3, 0, 4} with keepdims=true or fail with keepdims=false.

One mild difference is that when keepdims=true we have the correct rank and can leave the dimensions that weren't reduced alone as we use 0 for the reduced axis instead of 1. When keepdims=false we need a 0 somewhere in the output shape, so the '3' and/or '4' would have to be changed to 0 if we didn't fail. 

If we disallow a reduced axis from having a value of 0 that would also mean that a reduce operator with default behavior (reduce on all axes) would never support empty input.

**Comment by gyenesvi** [comment]
@skottmckay thanks for the response! I think I am starting to get it; ORT uses two different error mechanisms depending on the value of the attribute `keepdims`; making the output have size 0 essentially means that there is no result, right? I do think however that this is somewhat confusing and failing in both cases, like numpy, would be potentially more consistent. And yes, numpy fails on an empty array with default behavior of reducing all axes, but only if the operator does not have an identity element, such as `np.max`. On the other hand, `np.sum` does not fail on an empty array with default attributes. Does ORT work for summing an empty array, independent of `keepdims`?

**Comment by GilbertPan97** [comment]
Have you solved this problem? I have a similar error with you as follows:
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  Non-zero status code returned while running ReduceMax node. Name:'ReduceMax_1728' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:763 void onnxruntime::ValidateKeepDims(const onnxruntime::TensorShape&, int64_t) keepdims was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{0,4}
```

System information:
* pytorch => 1.11.0
* onnxruntime => linux-x64-1.13.1 (binary)
* platform => ubuntu 20.04
* additional info: CPU, C++

ReduceMax node info:
![1](https://user-images.githubusercontent.com/48231519/210041224-8fd8e151-f6ea-41a3-ab5d-55d739047476.png)

**Comment by Hyunseok-Kim0** [comment]
For anyone suffering from invalid output shape error when `ReduceXX` operators are used, please use onnx_graphsurgeon to modify operators' attributes.
This error happens because `ReduceXX` operators try to reduce all dimension when default attribute `axes` is not given. When the given input is not appropriate, dynamic batch dimension can be 0 sometimes, and that makes crash onnxruntime.

```
import onnx
import onnx_graphsurgeon as gs

onnx_save_path = "sample.onnx"

gs_graph = gs.import_onnx(onnx.load(onnx_save_path))
    for i, node in enumerate(gs_graph.nodes):
        if "Reduce" in gs_graph.nodes[i].op and 'axes' not in node.attrs:
            # reduce all axes except batch axis
            gs_graph.nodes[i].attrs['axes'] = [i for i in range(1, len(gs_graph.nodes[i].inputs[0].shape))]

new_onnx_graph = gs.export_onnx(gs_graph)
onnx.save(new_onnx_graph, 'patched.onnx')
```

Please use sample code above to fix your onnx file.

**Comment by GilbertPan97** [comment]
> For anyone suffering from invalid output shape error when `ReduceXX` operators are used, please use onnx_graphsurgeon to modify operators' attributes. This error happens because `ReduceXX` operators try to reduce all dimension when default attribute `axes` is not given. When the given input is not appropriate, dynamic batch dimension can be 0 sometimes, and that makes crash onnxruntime.
> 
> ```
> import onnx
> import onnx_graphsurgeon as gs
> 
> onnx_save_path = "sample.onnx"
> 
> gs_graph = gs.import_onnx(onnx.load(onnx_save_path))
> for i, node in enumerate(gs_graph.nodes):
>     if "Reduce" in gs_graph.nodes[i].op and 'axes' not in node.attrs:
>         # reduce all axes except batch axis
>         gs_graph.nodes[i].attrs['axes'] = [i for i in range(1, len(gs_graph.nodes[i].inputs[0].shape))]
> 
> new_onnx_graph = gs.export_onnx(gs_graph)
> onnx.save(new_onnx_graph, 'patched.onnx')
> ```
> 
> Please use sample code above to fix your onnx file.

Thanks a lot, it does work for me

**Comment by yang162132** [comment]
> For anyone suffering from invalid output shape error when `ReduceXX` operators are used, please use onnx_graphsurgeon to modify operators' attributes. This error happens because `ReduceXX` operators try to reduce all dimension when default attribute `axes` is not given. When the given input is not appropriate, dynamic batch dimension can be 0 sometimes, and that makes crash onnxruntime.
> 
> ```
> import onnx
> import onnx_graphsurgeon as gs
> 
> onnx_save_path = "sample.onnx"
> 
> gs_graph = gs.import_onnx(onnx.load(onnx_save_path))
> for i, node in enumerate(gs_graph.nodes):
>     if "Reduce" in gs_graph.nodes[i].op and 'axes' not in node.attrs:
>         # reduce all axes except batch axis
>         gs_graph.nodes[i].attrs['axes'] = [i for i in range(1, len(gs_graph.nodes[i].inputs[0].shape))]
> 
> new_onnx_graph = gs.export_onnx(gs_graph)
> onnx.save(new_onnx_graph, 'patched.onnx')
> ```
> 
> Please use sample code above to fix your onnx file.

sorry,It seem useless Do I need to change anything?
```
   gs_graph.nodes[i].attrs['axes'] = [i for i in range(1, len(gs_graph.nodes[i].inputs[0].shape))]
TypeError: object of type 'NoneType' has no len()
```
![image](https://github.com/microsoft/onnxruntime/assets/71556279/a9c011af-c3d5-4d75-a7f7-21ad738b8ee7)

**Comment by ykk648** [comment]
`
   gs_graph.nodes[i].attrs['axes'] = [i for i in range(1, len(gs_graph.nodes[i].inputs[0].shape))]
TypeError: object of type 'NoneType' has no len()
`

Same problem, any updates?
