### ISSUE TITLE
CPU memory leak using Scenario 1 of IOBinding

### ISSUE THREAD

**Issue by ArmenGhambaryan** [microsoft/onnxruntime#7611]
Hi, I am encountering CPU memory leak while binding a piece of memory directly/using numpy arrays.

**System information**
- OS: Linux Ubuntu 18.04
- ONNX Runtime installed from: binary
- ONNX Runtime version: 1.6.0
- Python version: 3.8
- CUDA/cuDNN version: 10.2/8
- GPU model and memory: GeForce GTX 1070 Ti

Memory leak disappears in case of using onnxrtuntime version 1.5.2 or 1.4.0,  also in case of using standard inference without iobinding. The memory leak issue still remains when upgraded to version 1.7.0.

**Comment by ArmenGhambaryan** [comment]
Yes, the Scenario 2 with OrtValue for ```X``` presented in the documentation doesn't have leak issues, which means that the following would work without any problem inside the loop:
```
X_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(X, 'cuda', 0)
io_binding.bind_input(name='input', device_type=X_ortvalue.device_name(), device_id=0, element_type=np.float32, shape=X_ortvalue.shape(), buffer_ptr=X_ortvalue.data_ptr())
io_binding.bind_cpu_input('input', X)
```

**Comment by hariharans29** [comment]
There is no leak that I can detect.

In your scenario 1 snippet pasted above, you are binding the numpy array within the loop each time (this is not needed - you can bind the input just once outside the loop). What happens internally is while binding numpy objects, the internal Ort tensor data structure directly uses the numpy object's memory (thus avoiding a copy). Due to this, we are indirectly taking a dependency on the numpy object and expect that its lifetime be atleast the lifetime of the IOBinding instance. To ensure this, we hold a reference to each bound numpy object within the IOBinding instance here - https://github.com/microsoft/onnxruntime/blob/ab4b5055c7411c4dc835bfd1ffb91190956291d8/onnxruntime/python/onnxruntime_inference_collection.py#L369. When you are binding the same object in the loop, you are growing this list and that is the memory growth you are seeing. If you were to put the bind_cpu_input() call outside the loop (as you did with the bind_output() call), you won't see this growth.

Scenario 2 doesn't deal with numpy objects, it deals with memory buffers directly and we expect that the user manage the life-cycle of the memory buffer properly and hence we don't hold onto any references here.  

Please re-open if you have more comments.
