### ISSUE TITLE
Building with OpenVINO on CentOS (undefined symbol: _ZN6ngraph11onnx_import23get_supported_operatorsElRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE)

### ISSUE THREAD

**Issue by umbrellerde** [microsoft/onnxruntime#7879]
**Describe the bug**
Im trying to build onnxruntime with OpenVino support. The build completes, but the test `onnxruntime_test_all` always fails with the following error:

```
1: [----------] 1 test from ParallelExecutor
1: [ RUN      ] ParallelExecutor.TestStatusPropagation
1: 2021-05-26 15:47:36.991253532 [E:onnxruntime:Default, provider_bridge_ort.cc:952 Get] Failed to load library libonnxruntime_providers_openvino.so with error: /home/user/onnxruntime/build/Linux/Debug/libonnxruntime_providers_openvino.so: undefined symbol: _ZN6ngraph11onnx_import23get_supported_operatorsElRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
1/3 Test #1: onnxruntime_test_all .............***Exception: SegFault 16.07 sec
test 2
```

I have the symbol `_ZN6ngraph11onnx_import23get_supported_operatorsElRKSs` in libngraph.so, but I can't find `_ZN6ngraph11onnx_import23get_supported_operatorsElRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE` anywhere.

To build, I used the commands
`./build.sh --use_openvino CPU_FP32 --build_wheel --parallel --config Release --build_shared_lib` or `./build.sh --use_openvino CPU_FP32 --build_wheel --parallel` with many different combinations of Onnx, GCC and OpenVino, but nothing works.

**Urgency**
Not in production use.

**System information**
- OS Platform and Distribution: CentOS 8.3.2011
- ONNX Runtime installed from: source
- ONNX Runtime version: 1.7.0, 1.7.1, 1.7.2, 1.8.0, latest master
- Python version: 3.6.8
- GCC/Compiler version: 8.3.1 or 9.2.1
- OpenVino: 2020.3, 2021.1, 2021.2, 2021.3
- cmake version: 3.20.3

**To Reproduce**
- Install one of the OpenVino versions
- build onnxruntime from source using `./build.sh --use_openvino CPU_FP32 --build_wheel --parallel --config Release --build_shared_lib` or `./build.sh --use_openvino CPU_FP32 --build_wheel --parallel`

**Expected behavior**
Build without errors

**Additional context**
- I had to install cmake via snap since I couldn't find a current version in the repos

**Comment by codemzs** [comment]
@snnn

**Comment by snnn** [comment]
I only tested it with ubuntu18.04 and ubuntu20.04.

**Comment by jywu-msft** [comment]
+@smkarlap , can you advise as you've been testing on CentOS recently?

**Comment by smkarlap** [comment]
I am able to reproduce this issue within a docker centos:8.3.2011 container. I have installed the **intel-openvino-runtime-centos7-2021.3.394.x86_64** 

The **libonnx_importer.so** library that's included in OpenVINO installation contains the symbol `_ZN6ngraph11onnx_import23get_supported_operatorsElRKSs`.
However the **libonnxruntime_providers_openvino.so** library that calls the get_supported_operators() API is compiled to look for the `_ZN6ngraph11onnx_import23get_supported_operatorsElRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE` instead. 

The OpenVINO packages mention in the docs that they only support CentOS 7. My suspicion is that this issue is due to unsupported build toolchain version being used in CentOS 8. 

Would you be able to downgrade the OS to CentOS 7?

**Comment by snnn** [comment]
That's the reason. C++ ABIs between CentOS 7 and 8 are different. If you use the CentOS 7 binaries on Ubuntu, you will see the same error. You can use the _GLIBCXX_USE_CXX11_ABI  macro to fix this. For more information please see: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by umbrellerde** [comment]
Thanks for your help! I guess i will downgrade my CentOs installation.
