### ISSUE TITLE
GCC 4.8.2 support to build ORT?

### ISSUE THREAD

**Issue by KnightYao** [microsoft/onnxruntime#7895]
I use gcc-4.8.2 to compiler ort-1.7.0, but get more error ,so ort build is not support gcc-4.8.2?

**Comment by wnzhyee** [comment]
i meet same error too, cpu version can be successd compiled, but gpu version failed

**Comment by KnightYao** [comment]
help kids，please @snnn

**Comment by codemzs** [comment]
@snnn

**Comment by snnn** [comment]
Why 4.8.2? If you are using CentOS 7, then you can get GCC  4.8.5 from the default yum repo. And it should work well with ONNX Runtime 1.7.x. Sorry 4.8.2 doesn't work.  Compilers often have bugs. It is hard to make our code be compatible with these "bugs".  4.8.5 is just a bug fixes only patch release compared to 4.8.2. So if you can get 4.8.5, I highly suggest you doing so. 

However, the future onnx runtime releases(1.8+) will stop supporting GCC 4.x. If you are using CentOS, you may get a higher version of GCC from Red Hat devtoolset. If you are using Ubuntu, I suggest you upgrading you OS to 18.04+ because 16.x and 14.x are EOL now.
