### ISSUE TITLE
re-download the jni library everytime restart the program

### ISSUE THREAD

**Issue by hongyaohongyao** [microsoft/onnxruntime#8003]
it cause my c disk exhausted fastly. How can i make it to be downloaded to a fixed path

**Comment by Craigacp** [comment]
You can control the native library loading in Java by setting different JVM system properties on the command line (e.g. https://github.com/microsoft/onnxruntime/blob/master/java/src/main/java/ai/onnxruntime/OnnxRuntime.java#L169). The one I linked will allow you to specify the path to the native library if you've extracted it to a specific place.

What OS & JVM are you using where it fails to clean up the temporary files?

**Comment by hongyaohongyao** [comment]
> You can control the native library loading in Java by setting different JVM system properties on the command line (e.g. https://github.com/microsoft/onnxruntime/blob/master/java/src/main/java/ai/onnxruntime/OnnxRuntime.java#L169). The one I linked will allow you to specify the path to the native library if you've extracted it to a specific place.
> 
> What OS & JVM are you using where it fails to clean up the temporary files?

I test it on window. It create a temp dir everytime which start with "onnxruntime-java" and a random number behind

**Comment by Craigacp** [comment]
Yes, that's a known issue with the JVM, based on how `System.loadLibrary` and `file.deleteOnExit` work. Basically we tag the native library with a shutdown hook that should delete it, but at the point where that hook is called the ORT library is still loaded into memory, and Windows won't let you delete files that are still loaded (macOS and Linux will, which is why it's only an issue on Windows). See this very old JVM bug (https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4171239). If this is causing an issue then you should cache the libraries yourself and use the system properties to control library loading.

Depending on which version you are using (either CPU or GPU) and what version of ORT, then you need to supply different system properties. For 1.7.0 & 1.8.0 on CPU, you should use `-Donnxruntime.native.onnxruntime.path=<path-to-onnxruntime.dll> -Donnxruntime.native.onnxruntime4j_jni.path=<path-to-onnxruntime4j_jni.dll>`. If you're using the GPU then you'll need to have similar things for `onnxruntime_providers_shared.dll` and `onnxruntime_providers_cuda.dll`.

**Comment by hongyaohongyao** [comment]
> Yes, that's a known issue with the JVM, based on how `System.loadLibrary` and `file.deleteOnExit` work. Basically we tag the native library with a shutdown hook that should delete it, but at the point where that hook is called the ORT library is still loaded into memory, and Windows won't let you delete files that are still loaded (macOS and Linux will, which is why it's only an issue on Windows). See this very old JVM bug (https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4171239). If this is causing an issue then you should cache the libraries yourself and use the system properties to control library loading.
> 
> Depending on which version you are using (either CPU or GPU) and what version of ORT, then you need to supply different system properties. For 1.7.0 & 1.8.0 on CPU, you should use `-Donnxruntime.native.onnxruntime.path=<path-to-onnxruntime.dll> -Donnxruntime.native.onnxruntime4j_jni.path=<path-to-onnxruntime4j_jni.dll>`. If you're using the GPU then you'll need to have similar things for `onnxruntime_providers_shared.dll` and `onnxruntime_providers_cuda.dll`.

Thanks, I got it. But why not supply a single system property that can control the root of the library😂

**Comment by Craigacp** [comment]
The change to break out CUDA into separate libraries landed in 1.8.0 and I've not had chance to refactor the library loading to make it easier to use. That's work I plan to do over the next few weeks, and adding a root directory override is one of the things on the list to do.
