### ISSUE TITLE
java jni call the interface of onnxruntime  and the program crashes 

### ISSUE THREAD

**Issue by Sammul40619** [microsoft/onnxruntime#8028]
The environment：
       win10，  vs2017， onnxruntime1.7.0
java jni  call  the onnxruntime ，the program crashes
java.lang.UnsatisfiedLinkError: D:\work\code\sdk\paper_test\output\libpapertest-jni-x64.dll: %1 is not a valid Win32 application
and VS2017 can get the program up and running and get the right results
anyone can help?

**Comment by Craigacp** [comment]
Are you using the Java API or calling the JNI or C++ methods directly from another piece of native code which is then wrapped in JNI?

Also are you running on 32-bit Windows? If so, then that's not going to work, the Java API is 64-bit only.

**Comment by Sammul40619** [comment]
> Are you using the Java API or calling the JNI or C++ methods directly from another piece of native code which is then wrapped in JNI?
> 
> Also are you running on 32-bit Windows? If so, then that's not going to work, the Java API is 64-bit only.

for first question，answer is yes.
i am running on 64-bit Windows,  and i try on 6 computers, it works on three computers, but not on the other three.
I suspect there is a problem with the dependent system library。

**Comment by Sammul40619** [comment]
I'm currently printing out all of the dependent libraries for OnNXRuntime to see if the system bits are all 64 bits
![image](https://user-images.githubusercontent.com/35996714/121761673-c14a3980-cb63-11eb-99ae-af8d423b07fc.png)

**Comment by Craigacp** [comment]
I'm not sure what the appropriate set of libraries should be on Windows. What happens if you compile the library from source?

Also, I'm a bit confused as to why `libpapertest-jni-x64.dll` gave an `UnsatisfiedLinkException` in your initial report if you're using the Java API without adding additional JNI. The two libraries that the Java API loads are `onnxruntime.dll` and `onnxruntime4j_jni.dll`.

**Comment by Sammul40619** [comment]
> I'm not sure what the appropriate set of libraries should be on Windows. What happens if you compile the library from source?
> 
> Also, I'm a bit confused as to why `libpapertest-jni-x64.dll` gave an `UnsatisfiedLinkException` in your initial report if you're using the Java API without adding additional JNI. The two libraries that the Java API loads are `onnxruntime.dll` and `onnxruntime4j_jni.dll`.

I found the reason，there is a  the same dynamic library as OnNXRuntime in  Windows system, and the dynamic library is 32-bit

**Comment by Craigacp** [comment]
Ok. That looks a little on the small side for ONNX Runtime, but I think there is some part of it which is packaged in with some Windows APIs. I've no idea how that works though as I think it's only accessible from .net or via the Windows API, neither of which we can get to from the JVM easily.

Did you manage to resolve your issue by changing the library path?

**Comment by Sammul40619** [comment]
> Ok. That looks a little on the small side for ONNX Runtime, but I think there is some part of it which is packaged in with some Windows APIs. I've no idea how that works though as I think it's only accessible from .net or via the Windows API, neither of which we can get to from the JVM easily.
> 
> Did you manage to resolve your issue by changing the library path?

Changing the library path maybe not a good idea. i am about to compile onnx to a different name.

**Comment by Craigacp** [comment]
The Java loader is designed to load it from inside it's jar file, and it directly loads that path rather than using the system library path. If you rename `onnxruntime.dll` when building ORT from source then the Java loader won't be able to find it unless you supply the absolute path as a system property. But you could do that anyway, without renaming it.

I'm a bit confused about what code you are using to load the library.
