### ISSUE TITLE
Cannot run correctly with x86 APP

### ISSUE THREAD

**Issue by znsoftm** [microsoft/onnxruntime#8069]
**Describe the bug**
x64 works fine.
But when I compile my app with x86 and company with the x86 edition of onnxruntime 1.7/1.8 ,  it throws an exception:

`inline void Session::Run(const RunOptions& run_options, const char* const* input_names, const Value* input_values, size_t input_count,
                         const char* const* output_names, Value* output_values, size_t output_count) {
  static_assert(sizeof(Value) == sizeof(OrtValue*), "Value is really just an array of OrtValue* in memory, so we can reinterpret_cast safely");
  auto ort_input_values = reinterpret_cast<const OrtValue**>(const_cast<Value*>(input_values));
  auto ort_output_values = reinterpret_cast<OrtValue**>(output_values);
  ThrowOnError(GetApi().Run(p_, run_options, input_names, ort_input_values, input_count, output_names, output_count, ort_output_values));
}`

on the last line  ThrowOnErro(GetApi()......)

![exception2](https://user-images.githubusercontent.com/15354249/122172274-2fb83000-ceb3-11eb-98e4-691b6dab1dd8.JPG)

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:  1.8/1,.7 x86  (x64 works fine.)
- Python version:
- Visual Studio version (if applicable):  vs2019  x86-release
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by znsoftm** [comment]
I get the reason:


            Ort::RunOptions run_option;
            //run_option.AddConfigEntry(kOrtRunOptionsConfigEnableMemoryArenaShrinkage, "cpu");
            auto outputTensor = m_session->Run(run_option, &szInputName, &inputTensor, 1, &szOutputName, 1);
when I uncomment the above line "run_option.AddConfigEntry(kOrtRunOptionsConfigEnableMemoryArenaShrinkage, "cpu");", it will throw out an exception. But if I comment it, it works fine. 

My goal is shrinking memory occupation after an inference job is done. 
So how should I do so on?

**Comment by hariharans29** [comment]
The CPU allocator maintains a memory arena (pool) only on x64. See how it is turned off for x86 https://github.com/microsoft/onnxruntime/blob/1d8edd0b5bcf3c3172cc10ae60662073e8f8f748/onnxruntime/core/providers/cpu/cpu_execution_provider.h#L40. 

When you try to shrink the arena on x64, it works fine and on x86, there is no arena to shrink - if you check the error message, you will see something similar (something about the CPU allocator being non-arena based and hence it cannot be shrunk).

Since on x86, there is no arena at all, there is no point in trying to shrink it (i.e.) you can skip it as essentially it is a no-op anyway. I will document that the feature is not to be used on x86 for this reason.

By the way, did you use the sample documented here-https://www.onnxruntime.ai/docs/reference/api/c-api.html ?

The correct usage pattern is providing combinations like this: "device_type:device_id", in your use-case, the correct usage pattern would have been "cpu:0". In your case, it works with just "cpu" as it uses the default device id of 0. But it is preferrable if you use the correct pattern.

**Comment by znsoftm** [comment]
I get it from an example code snippet, didn't rember where it  is from LOL.
Thanks for your answer.
