### ISSUE TITLE
ShapeInferenceError during onnxruntime update from 1.7.0 to 1.8.0

### ISSUE THREAD

**Issue by leqiao-1** [microsoft/onnxruntime#8115]
**Describe the bug**
We met a ShapeInferenceError during update. Here is log with ort 1.8.0 and ort 1.7.0.
 
ort 1.8.0:
```
benchmarking model...
Traceback (most recent call last):
  File "perf_test.py", line 39, in <module>
    main()
  File "perf_test.py", line 35, in main
    benchmark(args.model_path)
  File "perf_test.py", line 8, in benchmark
    session = onnxruntime.InferenceSession(model_path)
  File "D:\work\DLISModelOptimization\dlis_model_opt_cpu_py36_tf1_12_onnx\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\work\DLISModelOptimization\dlis_model_opt_cpu_py36_tf1_12_onnx\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from BertForQuestionAnswering_1.onnx failed:Node () Op (Concat) [ShapeInferenceError] All inputs to Concat must have same rank
```
ort 1.7.0:
```
benchmarking model...
2021-06-21 20:31:47.3434794 [W:onnxruntime:, graph.cc:84 onnxruntime::MergeShapeInfo] Error merging shape info for output. 'end' source:{batch_size,10} target:{batch_size,128}. Falling back to lenient merge.
2021-06-21 20:31:47.3438542 [W:onnxruntime:, graph.cc:84 onnxruntime::MergeShapeInfo] Error merging shape info for output. 'start' source:{batch_size,10} target:{batch_size,128}. Falling back to lenient merge.
Avg: 0.45ms
```
**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): pypi
- ONNX Runtime version: 1.7.0 and 1.8.0
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
```
python perf_test.py --model_path BertForQuestionAnswering_1.onnx
```
Model and script are shared. 
[shapeInferenceError.zip](https://github.com/microsoft/onnxruntime/files/6690543/shapeInferenceError.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/61653207/122852625-84402d00-d343-11eb-8793-7952e6c1907a.png)

**Comment by yuslepukhin** [comment]
Cc: @askhade

**Comment by jcwchen** [comment]
Hi @leqiao-1,

After investigation and discussion, we identify it as a mode bug. ONNX has improved [its shape inference](https://github.com/onnx/onnx/pull/3394) in 1.9.0 (which ORT 1.8.0 is using) so this error wasn't caught by ORT 1.7.0 (using ONNX 1.8.0).

In ONNX, [Concat op](https://github.com/onnx/onnx/blob/3c857c57826cf434626cb8c99f0b9517efb62451/onnx/defs/tensor/defs.cc#L448) does not allow inputs have different rank.

![image](https://user-images.githubusercontent.com/14194980/123289222-1d4a8180-d4c5-11eb-9289-b1ea35fd14a8.png)

- ORT 1.8.0 (ONNX 1.9.0): As shown above, the shapes of 274 and 275 are both 1D tensor, but the shapes of 1622 and 1623 are 0D tensor (scalar). Their rank are different: 1 vs 0. This error is expected.
- ORT 1.7.0 (ONNX 1.8.0) : the shapes of 274 and 275 are both 0D tensor and the shapes of 1622 and 1623 are 0D tensor (scalar). Their rank are same: 0 vs 0 so ORT does not catch this error. The reason is the shape op inference does not function correctly, which is not right.

To fix this, please promote the initializers which your model is using for Concat nodes (there are a few of them) from scalar (0D tensor) to 1D tensor. It should help your Concat nodes meet ONNX's requirement and resolve this error. Thank you!

cc @askhade @RandySheriff @gramalingam @EmmaNingMS

**Comment by leqiao-1** [comment]
Thanks for your help. I will have a try.
