### ISSUE TITLE
About batch inference

### ISSUE THREAD

**Issue by znsoftm** [microsoft/onnxruntime#8129]
**Describe the bug**
It's not a bug, I'm asking for an example of batch inference with C++.

I viewed the example in the folder imagenet you guys mentioned, but get nothing, didn't find the correct location.

For batch inference, I guess we need to process the below steps:

1. add batch data into the input tensor then tell onnxruntime the batchsize, it's easy.
2. how we get the output size （same as the input batchsize) ?

if there is a piece of  code snippet, everything is easier. 

Thanks.

**Comment by snnn** [comment]
To this specific example: when I put multiple samples together in a batch, I need to use another data structure to log the image ids(which images are in the batch). Because I know the list of ids, I know how many outputs would be.
see:
https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/imagenet/main.cc#L156

**Comment by snnn** [comment]
For more general cases, you may use the "GetTensorTypeAndShape" function. Once you get the tensor shape, you can extract the batch size from the first dim.

Like:
https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/fns_candy_style_transfer/fns_candy_style_transfer.c#L108

**Comment by znsoftm** [comment]
Thanks a lot for your time.
