### ISSUE TITLE
DML not running on discrete GPU

### ISSUE THREAD

**Issue by amincheloh** [microsoft/onnxruntime#8317]
**Urgency**
low, I can run DML EP on CPU (device id=1) or without DML

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 4993680e567c2ab9147b155854a547aca5c16972
- Python version:
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: RTX 2070 / 8GB

**To Reproduce**
C++
``` C++
    OrtSessionOptionsAppendExecutionProvider_DML(sessionOptions, 1);
    sessionOptions.DisableMemPattern();
```

**Expected behavior**
running on 

**Screenshots**
![image](https://user-images.githubusercontent.com/1217397/124731387-60343c80-df3c-11eb-90f3-7bd21922ade5.png)

**Additional context**
onnx file [dml-no-gpu.zip](https://github.com/microsoft/onnxruntime/files/6776026/dml-no-gpu.zip)

**Comment by fdwr** [comment]
@amincheloh:
> OrtSessionOptionsAppendExecutionProvider_DML(sessionOptions, /*device id*/ 1);

Device id 1 is the GPU 1 (Intel device) based on the Task Manager screenshot. So what happens if you run it on GPU 0 (device_id = 0)? It's an unusual order, as more often the order of DXGI [IDXGIFactory::EnumAdapters](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgifactory-enumadapters) puts device 0 as the Intel integrated and device 1 as the Nvidia card, but maybe they are reordered on your machine based on power settings 🤔.

**Comment by nums11** [comment]
Closing as stale.
