### ISSUE TITLE
ORT_NO_EXCEPTIONS not working on DML provider

### ISSUE THREAD

**Issue by gineshidalgo99** [microsoft/onnxruntime#8464]
**Describe the bug**
Even after setting `ORT_NO_EXCEPTIONS`, compiling ORT from source in a compiler with exceptions disabled results in many compiler errors due to the DML provider still using try/catch/throw commands, as well as DML provider also using Wil's try-catch-throw functionality.

**Urgency**
I'd say high for projects that need to run in compilers with exceptions disabled?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): Tried both, but we care mostly about the source one
- ONNX Runtime version: v1.7.1 and also tested in latest GitHub code
- Python version: None, using C++
- Visual Studio version (if applicable): VS 2019 Professional
- GCC/Compiler version (if compiling from source): VS 2019 Professional
- CUDA/cuDNN version: None (DirectML)
- GPU model and memory: Nvidia 3080

**To Reproduce**
- Describe steps/code to reproduce the behavior.
1. Set ORT_NO_EXCEPTIONS
2. Compile ORT from source with DML enabled in a compiler with exceptions disabled
3. See compiler errors

**Expected behavior**
ORT not using try-catch-throw if `ORT_NO_EXCEPTIONS` is set

**Comment by snnn** [comment]
ORT_NO_EXCEPTIONS was added for non-Windows mobile devices. DML is only available on Windows.  So we didn't try to make it work.  We use C++ exception as much possible. We only disable it when we have to.

**Comment by fdwr** [comment]
@gineshidalgo99 : The DML EP was written with standard C++ in mind from the beginning, which includes exceptions, and converting it from exceptions to return codes would be prohibitive at this point, given I count at least 250 occurrences of `THROW_HR_IF`/`THROW_IF_FAILED` just in the DML EP codebase. I wonder, are you statically linking ORT into a large component? If not, keeping it as a separate DLL/SO and using the C interface would avoid exceptions spanning the module boundary. I also wonder what your desired behavior upon exceptions is, given they can happen for a number of reasons, beyond the very rare case of running out of physical memory. Some laptops with can switch between discrete/on-board GPU's which cause a device removed, and would you want the entire process to `abort` just because of that? 🤔

**Comment by skottmckay** [comment]
@fdwr We converted the ORT codebase to support the mobile build with exceptions disabled by creating a few macros to wrap existing exception handling, so as long as there aren't too many try/catch blocks it's most likely possible to support a build with exceptions disabled mainly by updating your THROW_* macros. FWIW the most significant trick is when the catch block does something meaningful (need to capture that in a lambda so it compiles cleanly in a build with exceptions disabled). See https://github.com/microsoft/onnxruntime/search?q=ORT_HANDLE_EXCEPTION for usage examples.

However, in a scenario where DML is being used I wouldn't expect it to be necessary to disable exceptions in a custom build, as the binary size saving isn't meaningful enough to justify the effort and loss of graceful exception handling by having to use abort. I will close this issue due to those reasons.
