### ISSUE TITLE
ONNX Runtime 1.8.1 Infrence + cpp + windows10+cuda 11.0:  Cant'f find shared library

### ISSUE THREAD

**Issue by jpsalada** [microsoft/onnxruntime#8560]
**Describe the bug**
Cannot run the inference with GPU, with error "Cannot find shared library".

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary (cuda version for windows available in github)
- ONNX Runtime version: 1.8.1
- Visual Studio version (if applicable):16.8.6
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.0/11.3
- GPU model and memory: GeForce RTX 2080

**To Reproduce**
 The following code will fail in the last line with "Cannot find shared library" error message.

```
			Ort::SessionOptions session_options;
			OrtCUDAProviderOptions options;
			options.device_id = 0;
			options.arena_extend_strategy = 0;
			options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::EXHAUSTIVE;
			options.do_copy_in_default_stream = 1;
			session_options.AppendExecutionProvider_CUDA(options);
```

I have both onnxruntime_providers_cuda.dll and onnxruntime_providers_shared.dll in bin folder, and the program can find them. I also ran the Dependencies software with these dlls and it can find all the dependencies.

**Comment by snnn** [comment]
To identify the problem:
1. Install [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
2.  Find the gflags.exe in the windbg install folder and start it, 

3. Select the image file tab
![image](https://user-images.githubusercontent.com/856316/74082914-91d96900-4a13-11ea-95eb-d73db8a5cf13.png)

4. Type your exe name here (instead of "python.exe") then press the "tab" key, check "Show loader snaps" box

![image](https://user-images.githubusercontent.com/856316/74082958-b7667280-4a13-11ea-9eaf-6752695b4904.png)



6.  Start windbg, run your exe

7. in the command windows, type "g", then press the enter key
![image](https://user-images.githubusercontent.com/856316/74083078-d285b200-4a14-11ea-9df4-e86c421c5617.png)

7. You'll see a lot of outputs in the debugging windows.  Please search the lines that have "LdrpProcessWork - ERROR: Unable to load DLL", and put the result here.
e.g.
 "cublas64_100.dll", Parent Module: "C:\intelpython3\lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state.pyd", Status: 0xc0000135

**Comment by jpsalada** [comment]
Hi,

Here is the output:

556c:507c @ 16522781 - LdrpProcessWork - ERROR: Unable to load DLL: "{bin directory}\onnxruntime_providers_shared.dll", Parent Module: "(null)", Status: 0xc0000135
556c:507c @ 16522781 - LdrpLoadDllInternal - RETURN: Status: 0xc0000135
556c:507c @ 16522781 - LdrLoadDll - RETURN: Status: 0xc0000135

**Comment by jpsalada** [comment]
Hi,

My executable configuration was not correct, with all the dependencies when I ran it with windbg. Those dlls were not there. The actual error that I am getting with all the depndencies in the bin directory is this one:

LdrpProcessWork - ERROR: Unable to load DLL: "edgegdi.dll", Parent Module: "(null)", Status: 0xc0000135

**Comment by jpsalada** [comment]
So I have put edgegdi.dll in C:\Windows\System32, as explained [here](https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/edgegdidll-error/f7e6e5f2-f4e0-408f-9b98-59783dc7794a?page=2)

And now the error is the following:
````
(5b64.5b78): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
onnxruntime!OrtSessionOptionsAppendExecutionProvider_CPU+0x28213d:
00007fff`bb3861bd 4183b9e00000000d cmp     dword ptr [r9+0E0h],0Dh ds:00000000`000007e8=????????
````

This is strange because I am calling:  AppendExecutionProvider_CUDA(options);

**Comment by snnn** [comment]
We don't need edgegdi.dll. Please delete it from your "C:\Windows\System32"

Did you see any other error?

**Comment by jpsalada** [comment]
Hi,

there is no other error apart from the one mentioned in the previous comment, even when I remove edgedi.dll.

Any suggestions on some workarounds?

Thank you

**Comment by jpsalada** [comment]
Hi,

I found out an old onnxruntime.dll was being copied, and this was generating the problem. It can now run the line of code:

session_options.AppendExecutionProvider_CUDA(options)
