### ISSUE TITLE
Replace add_dependencies with target_link_libraries in library CMake

### ISSUE THREAD

**Issue by NathanielMcVicar** [microsoft/onnxruntime#8626]
It is not currently possible to build onnxruntime libraries directly from a CMake project using add_subdirectory because add_dependencies doesn't track transitive library dependencies for other targets the way target_link_libraries PUBLIC does. Replacing the add_dependencies in the various onnxruntime_<libname>.cmake files would enable a very powerful use case in the form of add_subdirectory, as everything else seems to work correctly.

ONNX Runtime version: 7b289a79

**Comment by snnn** [comment]
They have totally different semantics. add_dependencies doesn't make the target link to the library.

**Comment by snnn** [comment]
add_dependencies is needed only when some source code of the dependent library is generated during build time, e.g. protobuf uses code gen. Otherwise it is not needed.

**Comment by NathanielMcVicar** [comment]
Reading the guidelines it's not clear to me what the correct way to link against an onnxruntime static library is. In particular, when the project also depends on onnx, there needs to be some way to track that dependency.

**Comment by sstamenova** [comment]
@snnn : We would like to understand what the "correct" way is to link against the onnxruntime static library in the scenario where we include onnxruntime to our cmake project via add_subdirectory. This makes all the targets available to us and we can add a dependency between our executable and onnxruntime, but because the libraries that are required by onnxruntime are not added as public dependencies, that does not currently work.

Is the expectation that any consumer of onnxruntime has to explicitly list all of the libraries that onnxruntime depends on when linking against the target?

**Comment by snnn** [comment]
Can you use the "onnxruntime_EXTERNAL_LIBRARIES" variable? 

The context of the list is not supposed to be transparent to you.  Because very likely you already have some of the libraries installed in your system(e.g. protobuf) or in your current build system. In these case it will not work properly. So you need to very clearly know which lib onnxruntime depends on, You can't treat it as a black box.  And absolutely, you need to add them after onnxruntime_\* libraries, not before.

**Comment by NathanielMcVicar** [comment]
Explicitly listing the libraries (or using onnxruntime_EXTERNAL_LIBRARIES) doesn't work for us because for some reason CMake if very stubborn abouting putting onnxruntime_* libs very late in the link order (after dependencies like onnx and protobuf) causing it to fail to link. The only solution we've found for this is target_link_libraries PUBLIC. To be more explicit, what I believe you are suggesting:
`target_link_libraries(OUR_BIN PUBLIC onnxruntime_lib SomeOtherLibs onnx protobuf ...)`
fails because despite the ordering it puts onnxruntime_lib at the end. On the other hand, using:
`taret_link_libraries(onnxruntime_lib PUBLIC onnx protobuf ...)
target_link_librarires(OUR_BIN PUBLIC onnruntime_lib SomeOtherLibs ...)`
works correctly.

I would appreciate some clarification on the motivation for the guidence to avoid target_link_librarires for static libs. In particular, I think the statement that static libraries aren't linked isn't relevant because target_link_libraries explicitly serves the purpose of establishing dependencies required for libraries linked against a static lib. From the cmake doc: "This also works transitively through a static library. Since a static library does not link, it does not consume the object files from object libraries referenced this way. Instead, the object files become transitive link dependencies of the static library."

**Comment by snnn** [comment]
Let's say, if you have code:
```
target_link_libraries(OUR_BIN PUBLIC onnxruntime_lib SomeOtherLibs onnx protobuf ...)
```
And all these libs are static libs, and none of the static libs has target_link_librarires as I suggested. Then the libraries will show up as the exact order as you specified in the final link command. And if you are not satisfied with the order, you can easily adjust it.  I would suggest to figure out why "despite the ordering it(cmake) puts onnxruntime_lib at the end".  It must because some other code did it. For example, after this line you have another target_link_libraries.
