### ISSUE TITLE
Broken import in TrtTable Dict method

### ISSUE THREAD

**Issue by senysenyseny16** [microsoft/onnxruntime#8920]
# Bug Report

Hi!
When I tried to read `TrtTable` from binary file:
```python
with open(filename, 'rb') as file:
    buf = file.read()
    trt_table = TrtTable.TrtTable.GetRootAsTrtTable(buf, 0)
    for row in range(trt_table.DictLength()):
        key_value = trt_table.Dict(row)  # <- HERE
        ...
```
I got the following error:
```
from CalTableFlatBuffers.KeyValue import KeyValue
ModuleNotFoundError: No module named 'CalTableFlatBuffers'
```
Because `import` on `37` line in `Dict` method of `TrtTable` in `onnxruntime/quantization/CalTableFlatBuffers/TrtTable.py`:
```python
from CalTableFlatBuffers.KeyValue import KeyValue
```
contains error.
When I replaced this `import` to:
```python
from onnxruntime.quantization.CalTableFlatBuffers.KeyValue import KeyValue
```
the method started working as expected, but this file is autogenerated by FlatBuffers, I can't just patch it:
```
# automatically generated by the FlatBuffers compiler, do not modify
```

### System information
- OS Platform and Distribution: Linux Ubuntu 21.04
- ONNX version:  1.10.1
- Python version: 3.8
- Protobuf version: 3.17.3

**Comment by chilo-ms** [comment]
Please use _from onnxruntime.quantization.CalTableFlatBuffers.KeyValue import KeyValue_
You can see [ORT script](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/quant_utils.py#L338) uses this import path as well, because TrtTable.py locates on onnxruntime/quantization/CalTableFlatBuffers. You can double check your onnxruntime python libraries in your system after you pip install onnxruntime or install wheel file

Also, what flatbuffers version are you using? ORT quantization supports flatbuffers v1.12.
It's not compatible with flatbuffers v2.0 yet.

**Comment by senysenyseny16** [comment]
Also, if I turn on validation (`False -> True`):
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/quant_utils.py#L378
I am getting the same error.

**Comment by chilo-ms** [comment]
Yes, you're right. Thanks for finding this issue.

**Comment by chilo-ms** [comment]
PR merged.
https://github.com/microsoft/onnxruntime/pull/8940
