### ISSUE TITLE
Creating custom ONNX operator from model with C++ pytroch extension

### ISSUE THREAD

**Issue by topshik** [microsoft/onnxruntime#9016]
Not a bug.

Hi. Probably, my issue is similar to https://github.com/microsoft/onnxruntime/issues/5113.

My use case is that I have a Huggingface-like Transformer model in which part of the attention layer computations are performed with pytorch c++ extension, following implementation [here](https://github.com/idiap/fast-transformers).

I have successfully trained such model in Pytorch, but now I want to export it to ONNX so that my attention layer will be a single optimized operator. Optimization is crucial for me, so I would like to follow how standard Attention layer is optimized when `onnxruntime_tools.transformers.convert_to_onnx` module is used for, for instance, GPT2LMHead model. 

Can you please help me to understand the whole pipeline to implement this? So far I've been following the pipeline on [this page](https://github.com/onnx/tutorials/blob/master/PyTorchCustomOperator/README.md). I've made two first steps and converted my model to ONNX, however it is now a complex set of operators, but not a single optimized one.

**Comment by garymm** [comment]
Did you try  `onnxruntime.transformers.optimizer` as described [here](https://github.com/microsoft/onnxruntime/tree/615df42b4627be5fb732018c4b93160dc436037e/onnxruntime/python/tools/transformers#model-optimizer)?

**Comment by topshik** [comment]
As far as understand, I was used to do like you suggest for standard GPT2LMHead Huggingface model. However, now I substitute the attention layer with some custom implementation which involves computations on the C++. I’m not sure that the solution that you suggest fits my case, because this optimiser works only with standard attention layer.

**Comment by tianleiwu** [comment]
@hopshik, you can follow our longformer as example for ONNX export (https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/longformer/convert_longformer_to_onnx.py). It uses a torch extension to export the corresponding part to an ONNX operator. In your case, since you have torch extension, it could directly use that to export to a custom operator. For more information, see https://pytorch.org/docs/stable/onnx.html#custom-operators

Once the model is exported to ONNX,  you can easily wrap your C++ pytroch extension code into an ONNX custom op. See https://onnxruntime.ai/docs/how-to/add-custom-op.html for more information.

**Comment by tianleiwu** [comment]
@topskik, your understanding is correct. LongformerAttention is not the whole attention layer because we have other optimization like LayerNormalization and FastGelu could cover the other parts of the layer. That just an example that you can convert one part of the model directly into a contrib/custom operator for OnnxRuntime without using graph fusion.

It is also True for the graph fusion classes. It will automatically detect common parts of transformer and fuse them into existing optimized operators. Note that this could be combined with the previous approach.

The latest doc can be found in https://onnxruntime.ai/docs/reference/operators/add-custom-op.html

**Comment by garymm** [comment]
Doesn't seem like there's anything left to do here, so closing. Feel free to open another issue.
