### ISSUE TITLE
Issue loading model using onnx web 

### ISSUE THREAD

**Issue by EnricoBeltramo** [microsoft/onnxruntime#9322]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

I have a project in react where I use onnx web to load a model.
The code shall be simplified in that way:

const ort = require('onnxruntime-web');

//const session = await ort.InferenceSession.create(modelpath, {executionProviders: ['wasm']});
const session = await ort.InferenceSession.create(modelpath);

but when I load the model (that works correctly in python), I have follow error:
Error: unsupported data type: FLOAT16

Furthermore, when I try to force a different provider, i.e. 'wasm' (see commented line above), I have follow error:
Error: no available backend found. ERR: [wasm] RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0). Build with -s ASSERTIONS=1 for more info..

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.
the load of model in web is the focus of application for our startup project, in this moment any more activity is locked by that

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: "onnxruntime-web": "1.8.0-dev.20210708.0"
- Python version: n.a.
- Visual Studio version (if applicable): vs code
- GCC/Compiler version (if compiling from source): na
- CUDA/cuDNN version: na
- GPU model and memory: na

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by fs-eire** [comment]
@EnricoBeltramo @ManuelGTM could you please share more information, including:
- how do you set up your web app project
   - is it using a well-known framework like react/vuejs?
   - do you have "onnxruntime-web" in your dependencies in package.json?
- how do you deploy your project
   - are you deploying a dev version or a prod version
   - how is your settings in webpack.config.js (or for other bundler)

Also, could you please check the browser's devtool to see what is the URL it requires for the .wasm file.

I will take further investigation based on those information. I think it is a deployment problem, but at least we can improve the documents.

**Comment by ManuelGTM** [comment]
Thank you for your attention.
To make it easy to replicate what I have done is to start a project from scratch, to make it easier to explain all the steps and configurations.

1. I have created a React project using: npx create-react-app my-app
2. I installed the 'onnxruntime-web' package: npm i onnxruntime-web
3. I installed the following packages: npm install react-app-rewired wasm-loader -D and created a config-overrides.js file (so I never modify the default webpack configuration as created with CRA) with the following configuration:

const path = require('path');
module.exports = function override(config, env) {
  const wasmExtensionRegExp = /\.wasm$/;
  config.resolve.extensions.push('.wasm');
  config.module.rules.forEach(rule => {
    (rule.oneOf || []).forEach(oneOf => {
      if (oneOf.loader && oneOf.loader.indexOf('file-loader') >= 0) {
        // make file-loader ignore WASM files
        oneOf.exclude.push(wasmExtensionRegExp);
      }
    });
  });
  // add a dedicated loader for WASM
  config.module.rules.push({
    test: wasmExtensionRegExp,
    include: path.resolve(__dirname, 'src'),
    use: [{ loader: require.resolve('wasm-loader'), options: {} }]
  });
  return config;
};


4. I edited the package.json file, here is the result where you can also see the version of onnxruntime-web installed (1.9.0)

{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.5.0",
    "@emotion/styled": "^11.3.0",
    "@mui/material": "^5.0.6",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "onnxruntime-web": "^1.9.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-app-rewired eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "react-app-rewired": "^2.1.8",
    "wasm-loader": "^1.3.0"
  }
}


5. In the public folder I added an .onnx file downloaded from your repository [https://github.com/microsoft/onnxruntime-inference-examples/blob/main/js/quick-start_onnxruntime-web-bundler/model.onnx] and I prepared a very simple code to load the model.

import Button from '@mui/material/Button';
import { InferenceSession } from "onnxruntime-web";
import './App.css';

function btnAction(){
  console.log('onnxruntime-web')
  const url = "./models/model.onnx";

  // const session = InferenceSession.create(url);
  // const session = InferenceSession.create(url, { executionProviders: ['webgl'] });
  const session = InferenceSession.create(url, {executionProviders: ['wasm']});
  console.log('session.loadModel(url)')
}

function App() {
  return (
    <Button onClick={btnAction}> LOAD MODEL </Button>
  );
}

6. To run it I use either "npm run start" or first "npm run build" and then "serve -s build".

==========

Result:
 + If I use "const session = InferenceSession.create(url, { executionProviders: ['webgl'] });"  loads the model without any problem. 
 + If I use "const session = InferenceSession.create(url);" first generate some warnings, but then load the model, because it uses "webgl"
 + If I force to use "wasm" : const session = InferenceSession.create(url, {executionProviders: ['wasm']}); . It generate this error: https://ibb.co/tCp6Qv1


If I check browser's devtool the URL requeris for the .wasm file is: http://localhost:3000/static/js/ort-wasm-simd.wasm
But that file is not there in that route if I look in the "sourcetree"

The model I have to run if I use "webgl" does not have certain operators, so I needed to use "wasm". What am I doing wrong?
I guess I'm not loading the .wasm files, but I don't know how to fix it.
Thank you very much for your time.

**Comment by 7rains** [comment]
@ManuelGTM I have the same setup as you and had the same issue. If you look at the [webpack config file](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/js/quick-start_onnxruntime-web-bundler/webpack.config.js) for the example project, you'll see they are using the copy webpack plugin. I was able to get the example to work by copying over the wasm files `node_modules/onnxruntime-web/dist/*.wasm` to `public/static/js/`. You can add the copy-wepack-plugin to the override config but make sure the copy-webpack-plugin version works with webpack 4 since you're using react create app.

**Comment by ailen-wrx** [comment]
> @ManuelGTM I have the same setup as you and had the same issue. If you look at the [webpack config file](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/js/quick-start_onnxruntime-web-bundler/webpack.config.js) for the example project, you'll see they are using the copy webpack plugin. I was able to get the example to work by copying over the wasm files `node_modules/onnxruntime-web/dist/*.wasm` to `public/static/js/`. You can add the copy-wepack-plugin to the override config but make sure the copy-webpack-plugin version works with webpack 4 since you're using react create app.

Hi @ManuelGTM, I submitted #11413 because I still cannot successfully deploy a model to wasm in a vue.js project after following the steps in this issue. Could you please have a glance and provide with some suggestions? Thanks :)

**Comment by eisneim** [comment]
i have similar issue but the url is ` http://ort-wasm-simd.wasm` 
i try to edit  "ort.js" but didn't find where is the entry point

**Comment by rvorias** [comment]
just tried @7rains proposal and it works

smh the onnxruntime docs never tell you to setup the webpack config

**Comment by guschmue** [comment]
assume this is no longer an issue.

**Comment by rahulchougule** [comment]
> @ManuelGTM I have the same setup as you and had the same issue. If you look at the [webpack config file](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/js/quick-start_onnxruntime-web-bundler/webpack.config.js) for the example project, you'll see they are using the copy webpack plugin. I was able to get the example to work by copying over the wasm files `node_modules/onnxruntime-web/dist/*.wasm` to `public/static/js/`. You can add the copy-wepack-plugin to the override config but make sure the copy-webpack-plugin version works with webpack 4 since you're using react create app.

In my case, there was no static folder inside public.
