### ISSUE TITLE
ONNXRuntime Python vs C++, different output using same models and inputs

### ISSUE THREAD

**Issue by ibrahimsoliman97** [microsoft/onnxruntime#9472]
We found inference output differences between onnxruntime v1.9 using Python vs C++.  Our experiment includes 4 models, 2 classification models from ONNX Zoo, and 2 classification models exported from PyTorch (torchvision).

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows (C++) and Google Colab (Python) 
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.9.0
- Python version: 3.7
- Visual Studio version (if applicable): v2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
using same input and preprocessing, we sum the last layer outputs (1,1000), then we compare the sum. attached the model and screenshots of our results.

Why are we getting these differences? 

Output Differences :
![image](https://user-images.githubusercontent.com/30038478/138258809-f93ed104-b125-4ad9-aa29-4e68f8a1b6b0.png)

Models:
https://drive.google.com/file/d/14wlYrpWmyXDKsacJcWAQIhQS9nD4GATE/view?usp=sharing

**Comment by skottmckay** [comment]
If you look at the individual input values and the individual output values (i.e. the input to the InferenceSession `run` call and the direct output from that) do they match?

**Comment by skottmckay** [comment]
are you comparing raw values or output from printing the value, where rounding may take place when creating the output?

**Comment by ibrahimsoliman97** [comment]
Now I am controlling the print(cout) precision, for full precision version (2.96934915, 2.96934771).

**Comment by skottmckay** [comment]
You need to compare on the same machine for the comparison to be valid. The instructions used (e.g. what AVX instructions are available) and ordering of the floating point operations will vary across machines and platforms, and differences are expected due to this. 

What matters is whether the differences are significant in those cases, and I don't believe they are. 

I ran an additional test with an image from the ONNX test data for resnet50 and get exactly the same values for python and c++, which is as expected when run on the same machine with the same setttings for ORT.

**Comment by ibrahimsoliman97** [comment]
It took me sometimes to verify this issue on different PCs and OS. 
I managed to get same output from Python and C++ using your code.
Sorry for inconvenience and Thanks for your support.
