### ISSUE TITLE
onnxruntime from source takes long (~O(10 minutes)) to build with CUDA support 

### ISSUE THREAD

**Issue by Debottam** [microsoft/onnxruntime#9627]
**Describe the bug**
We are building onnxruntime with CUDA support from source (e.g. https://onnxruntime.ai/docs/build/eps.html#cuda) for our software framework but it's taking significantly longer than onnxruntime without CUDA support. Currently, we are using ORT v1.5.x; is this issue already identified and resolved in a later version? Please let us know.
**Urgency**
URGENT: We are currently migrating our codes to make them enable to run on dual-platform (CPU/GPU); we will soon be directing our workflow to GPUs
**System information**
- OS Platform and Distribution: Linux : 
- Architecture: x86_64
- Operating System: CentOS 7
- CMake: VERSION 3.18
- ONNX Runtime installed from : source
- ONNX Runtime version: onnxruntime-v1.5.1
- Python version: Python dependency disabled in the build (due to discrepancy in version)
- Visual Studio version (if applicable):N/A
- GCC/Compiler version (if compiling from source):GCC 8, GCC 11
- CUDA/cuDNN version: 11.4/ 8.2.4.15
- GPU model and memory: Currently building using CPU in a single-threaded way

Thanks in advance,
Debo,
ATLAS, CERN

**Comment by krasznaa** [comment]
To give some context: What we see is that the CUDA code compilation is happening in a very single-threaded/process way. I can only imagine that the compilation could be made more parallel by tweaking the CMake configuration of the project "in the right way".

**Comment by skottmckay** [comment]
What if you add the `--parallel` build flag?

**Comment by Debottam** [comment]
Hi @skottmckay ,

Thanks, but where is this flag `--parallel` defined ? I don't see it in https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt. Don't we need it to be in CMakeLists.txt since we are building using CMake?

Thanks,
Debo.

**Comment by krasznaa** [comment]
Hi Scott,

We are not building the project through its build script(s). It's a long story why, but we rather configure the project's CMake build by hand. With this code:

https://gitlab.cern.ch/atlas/atlasexternals/-/blob/master/External/onnxruntime/CMakeLists.txt

How much parallelism we get from the onnxruntime build depends on how much parallelism it can give us in the CMake-generated makefiles. And this is what prompted this ticket.
  - In our current setup, which does not involve building the CUDA code of onnxruntime, the build goes as well as I'd imagine. The onnxruntime project is large, but it builds using all available cores of our build machine in a "reasonable way".
  - When including the build of the CUDA sources with https://gitlab.cern.ch/atlas/atlasexternals/-/merge_requests/871, I see  the build on my system spending ~10 minutes compiling CUDA source files one-by-one. After having built all of the C\+\+ sources already as much as I can tell.

I do not want to start debugging this project's CMake configuration. :frowning: But I'm absolutely sure that this serial build behaviour can not be intentional. It must be due to some mistake/typo in the build configuration somewhere.

Best,
         Attila

**Comment by skottmckay** [comment]
The ORT build script will run cmake using the appropriate arguments for parallelization. e.g. https://github.com/microsoft/onnxruntime/blob/5247247b7fb5f45f589b8e8baf1b7c0011145dd0/tools/ci_build/build.py#L1178-L1189

If you are running cmake directly you most likely need to provide those yourself, either in the same way the ORT build script does, or potentially via the cmake `--parallel` argument.
https://cmake.org/cmake/help/latest/release/3.12.html#command-line

Based on the build script you may also want/need to set the onnxruntime_NVCC_THREADS cmake parameter. 
https://github.com/microsoft/onnxruntime/blob/5247247b7fb5f45f589b8e8baf1b7c0011145dd0/tools/ci_build/build.py#L813

**Comment by krasznaa** [comment]
:confused: I did have a closer look. Though I was hoping that Debo and co would do this instead...

So I was wrong. It's not that building all the many `.cu` files one-by-one would take a long time. The problem is that building https://github.com/microsoft/onnxruntime/blob/v1.5.1/onnxruntime/core/providers/cuda/math/topk_impl.cu takes #@^&%@ forever. :confused:

The reason that I noticed this so clearly is that last week I was building onnxruntime on a fairly fast 64-thread machine. And the slowness of this one file ended up dominating the build as it seems. My educated guess was that it must be the build of multiple files one-by-one that would take minutes on that machine. But as it turns out, it was all just one file. (The confusing thing is that `nvcc` runs multiple downstream processes during the build, so in "top" I would never see any process with a particularly long lifetime.)

I guess this is what you guys introduced `onnxruntime_NVCC_THREADS` for. :stuck_out_tongue: Unfortunately version 1.5.1, which we use, does not have this flag yet.

@Debottam, as I asked in https://gitlab.cern.ch/atlas/atlasexternals/-/merge_requests/871, testing some newer versions of onnxruntime could help.

But for now I'd consider the case closed. Apparently in newer releases `onnxruntime_NVCC_THREADS` can be used to mitigate the issue somewhat. In 1.5.1 we'll just accept that this one source file takes forever to build...
