### ISSUE TITLE
Optimizations fails on a specific graph

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#9671]
**Describe the bug**

The optimization fails on the attached ONNX graph. The node mentioned in the error does not belong to the original graph and it works when optimizations are disabled.

`RuntimeError: Unable to create InferenceSession due to '[ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Transpose(13) node with name 'Transpose_token_1''`

[optimisation_fails.zip](https://github.com/microsoft/onnxruntime/files/7474509/optimisation_fails.zip)

**Urgency**
Before the next release.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): orttraining built from github
- ONNX Runtime version: 0.10.1
- Python version: 3.9
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: none

**To Reproduce**
Create a session with the attached graph.

**Expected behavior**
No failure.

**Comment by TomWildenhain-Microsoft** [comment]
The optimizer is moving the transpose here:

![image](https://user-images.githubusercontent.com/67606533/140419582-990671e7-f662-4430-8071-9e55cdf9aba2.png)

It pushes it below the Squeeze (the Identity nodes don't exist at that point). I don't know why it fails to find an implementation. @skottmckay

**Comment by skottmckay** [comment]
Looks like running the optimizer once is not sufficient. 

```cpp
  // One run should be sufficient. Multiple runs should be ok but are prohibited to prevent any possibility of an
  // infinite loop.
  bool ShouldOnlyApplyOnce() const override { return true; }
```

If I change this line in onnxruntime::TransposeOptimizer to return `false` it works. The reason is that it's the second run that moves the Transpose involving the Squeeze, but this ends up happening after partitioning. That results in a new Transpose node being added with no execution provider being set as there's no mechanism to copy the assigned EP from the existing node. Will look into why all optimizations aren't completed in the first pass . 

We should probably try and preserving any existing EP info as assumably 'moving' the Transpose by creating a new Transpose node should not change the EP that was set for the original Transpose node.

**Comment by skottmckay** [comment]
The current order of optimizers has the Transpose optimizer running after IdentityElimination. That results in the first pass not changing the Transpose -> Squeeze at the end of the graph due to the Squeeze output not having a shape (benefit of -5  for unknown input shape is cancelled out by cost of 5 for unknown output shape).

Following that IdentityElimination runs, which removes the last 2 Identify nodes and makes the Squeeze output 'Y', which has a defined rank as it's a graph output. 

That change means that on the next run of TransposeOptimizer, which happens after partitioning, the Transpose -> Squeeze will be updated due to the cost metric (benefit of -5 is not cancelled due to output rank of 3). 

Doesn't make sense to me that the simplest RewriteRule based optimizations are last in Level 1 so I'll move those to run first on each iteration. Technically that will resolve the issue, however it seems safer to also set ShouldOnlyApplyOnce to `false` to avoid issues due to the ordering of level 1 optimizations in the future.
