### ISSUE TITLE
The input tensor cannot be reshaped to the requested shape. Input shape:{1,0}, requested shape:{-1,0}

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/onnxruntime#9940]
**Describe the bug**
I got an error when I tried to run my model with dynamic axes which is trained using pytorch and converted to onnx format:

Non-zero status code returned while running Reshape node. Name:'Reshape_9' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:37 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape &, std::vector<int64_t> &, bool) size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,0}, requested shape:{-1,0}

The input dimensions of exported model is [-1, -1] and I feed a [1, 0] vector to the model.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.8.1
- Python version:
I'm using C API

**Comment by hanbitmyths** [comment]
Reshape kernel tries to determine an unknown dim, but with a requested shape [-1, 0], the size of known dims is calculated to 0 and can't infer an unknow dim.

**Comment by HaoboGu** [comment]
> Reshape kernel tries to determine an unknown dim, but with a requested shape [-1, 0], the size of known dims is calculated to 0 and can't infer an unknow dim.

So it's a bug or just as designed?
In my model's input, the input shape should be {-1, -1}

**Comment by hanbitmyths** [comment]
It's by design. You can check [ONNX operator schemas](https://github.com/onnx/onnx/blob/master/docs/Operators.md#reshape).

_At most one dimension of the new shape can be -1. In this case, the value is inferred from the size of the tensor and the remaining dimensions. A dimension could also be 0, in which case the actual dimension value is unchanged (i.e. taken from the input tensor)._

Since an input shape is [1, 0], a dim will be inferred as 0 and an unknown dim of new shape can't be calculated.

**Comment by HaoboGu** [comment]
@hanbitmyths thanks for explanation!
