### ISSUE TITLE
Question on DeepCPU

### ISSUE THREAD

**Issue by t13m** [microsoft/onnxruntime#999]
Hi, I read the paper "DeepCPU: Serving RNN-based Deep Learning Models 10x Faster" (published by MSR), and trying to find DeepCPU's implementation. I found there are some "deepcpu_" prefixed file under `onnxruntime/core/providers/cpu/rnn`, like `deep_cpu_lstm.cc`.

Are those codes an implementation of the algorithms described in the paper?

Thanks.

**Comment by samyam** [comment]
The codes implement some of the optimizations described in the paper. It performs fusion of matrix-multiplications, and careful partitioning for parallelization, but it does not do weight centric streamlining. The performance of the code is significantly better than any naïve parallel implementation, but it won't match the performance in the paper.

**Comment by t13m** [comment]
Thank you so much samyam for the detailed answer. It's very useful.
I run through the code and found fused matmul and the time-(in)dependent phases but didn't see the partitionings, are they implemented in sgemm kernels provided by mlas library? Also, is there any plan to add weight centric streamlining to onnxruntime to make it a full-fledged deepcpu implementation?

**Comment by skottmckay** [comment]
The MLAS SGEMM kernels do the partitioning. 

I'm not aware of any plan to add the weight-centric streamlining at this point.

**Comment by t13m** [comment]
ok, thanks a lot :)

**Comment by MlWoo** [comment]
@skottmckay @samyam I am confused about the partition of sgemm. The paper states that finding a  _P_-partioning strategy <X_i, X_j, X_k> to minimize the data movement between L2 and L3 cache is core of `PCP`.  _P_ is the number of cores of CPU and it equals of product of X_i, X_j and X_k. 
I trace the [code](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/rnn/deep_cpu_lstm.cc#L830) and find that it calls [MLAS SGEMM](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/mlas/lib/sgemm.cpp#L1233). Although [MLAS SGEMM](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/mlas/lib/sgemm.cpp#L1233) calls the [MLAS SGEMM kernel (eg.SIMD is AVX)](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/mlas/lib/x86_64/SgemmKernelAvx.S#L402) and the [kernel](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/mlas/lib/x86_64/SgemmKernelAvx.S#L402) applys the partitions to boost computation, the partitions of [kernel](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/mlas/lib/x86_64/SgemmKernelAvx.S#L402) does not have relation with the _P_-partioning strategy. Apparently, the partitions of [kernel](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/mlas/lib/x86_64/SgemmKernelAvx.S#L402) wants to reuse the data in L2 cache in a single core, and  _P_-partioning strategy wants to partition the matrix to different cores in order to minimize the data movement between L2 and L3 cache.  The multi-threads binding to cores just partition the matrix into parts using [`MlasSgemmTryMultithread `](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/mlas/lib/sgemm.cpp#L1060). And [the block of K direction](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/mlas/lib/sgemm.cpp#L1155) will not be partitioned.  So X_k is always 1.   
The part of result C will be not reduced if X_k is 1. and it saves time of hanging in barriers of parallel region. However, it may not the best choice to minimize the data movement between L3 and L2 cache.
 Maybe I have missed something important or misunderstand the code . Could you spare time to 
clear my confusion? Thank you in advance.

**Comment by MlWoo** [comment]
@skottmckay  I noticed that `deep cpu lstm`  is caculated with `mlas` implemented with threading pool and the block of parameters is [binding to cores](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/mlas/lib/sgemm.cpp#L1226) across the sequence. Is it the implementation of the weight-centric streamlining.

**Comment by peterukk** [comment]
Hi I'm new to ONNX. Would it be possible to get a quick example of how to actually use the DeepCPU kernels when running inference in Python with a LSTM-based ONNX model? Do I need to build ONNX again as currently I only have CPUExecutionProvider and CUDAExecutionProvider available?
